### ISSUE TITLE
[Bug] tts-server error with zh-CN/baker/tacotron2-DDC-GST

### ISSUE THREAD

**Issue by akchain** [coqui-ai/TTS#1010]
## 🐛 Description
Hi, I installed the tts via pip and tried to start the server by：
tts-server --port 9300 --model_name tts_models/zh-CN/baker/tacotron2-DDC-GST --vocoder_name vocoder_models/universal/libri-tts/fullband-melgan

![1639387746(1)](https://user-images.githubusercontent.com/71252184/145786586-57a60bde-fc3d-4b5d-85ce-5c136a8e8350.png)

What should be filled the first entry? I tried to leave it blank but cannot generate an audio.

However, I managed to generate an audio via backend commands.
"tts --text "这是个测试" --model_name tts_models/zh-CN/baker/tacotron2-DDC-GST --vocoder_name vocoder_models/universal/libri-tts/fullband-melgan --out_path output.wav"

Thanks for your help.

### Environment

- 🐸TTS Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- Any other relevant information:

**Comment by erogol** [comment]
There shouldn't be an additional input field 

Can you fill out the Environment fields?

**Comment by tomowang** [comment]
This additional input field is controlled by `use_gst`, as in HTML template: https://github.com/coqui-ai/TTS/blob/c63bb481e95bd4a1ff978947d8e3e6c0bfb4177f/TTS/server/templates/index.html#L67-L70

And the config.json of `tts_models--zh-CN--baker--tacotron2-DDC-GST` sets `"use_gst": true`.

Make this input field blank and input "这是个测试", I can generate an audio

![image](https://user-images.githubusercontent.com/3199140/148170532-26b3fe84-5ae6-42fc-835f-09fb3780f6ef.png)

**Comment by erogol** [comment]
the mode uses GST, so I think it is normal to have the input field.

I close this issue then.
