### ISSUE TITLE
[Feature request] graceful handling of dataset issues

### ISSUE THREAD

**Issue by jreus** [coqui-ai/TTS#1042]
Hey all, I'm working on training some multi-speaker models with coqui using the VCTK dataset.

VCTK as downloaded via the included download script has an issue in that there are a number of audio files specified in the metadata that are missing from the dataset. In the case of VCTK, metadata is a set of .txt files each with the spoken text, and whose filenames mirror their corresponding audio files.

The issue I am running into is that coqui happily consumes such an errorful dataset. You won't actually see any issues until training starts, at which point it becomes a bit unclear what the exact issue is (coqui throws `FileNotFoundError` from a location in code well removed from where the dataset files are actually parsed).

My preferred behavior in such cases would be that, during parsing, coqui will do its best to use the dataset as-is, while also providing warnings that some files are missing. This solution addresses two possible situations:

1. You have downloaded/created a dataset where the missing files are not an error, but actually the expected state of the dataset (as is the case with VCTK). In this scenario, the proposed solution would provide the ideal behavior that coqui can handle the missing files gracefully and still parse the remaining dataset.
2. You have downloaded/created a dataset with genuine missing files, perhaps the data was corrupted or didn't download completely. In this scenario, the proposed solution should still provide adequate (i.e. hard to miss) warnings about missing dataset files. 

I've gone ahead and implemented something like this for VCTK in my own local copy. In `TTS/tts/datasets/formatters.py` I've modified the `vctk` function as follows:

```python
def vctk(root_path, meta_files=None, wavs_path="wav48"):
    """homepages.inf.ed.ac.uk/jyamagis/release/VCTK-Corpus.tar.gz"""
    test_speakers = meta_files
    items = []
    meta_files = glob(f"{os.path.join(root_path,'txt')}/**/*.txt", recursive=True)

    for meta_file in meta_files:

        _, speaker_id, txt_file = os.path.relpath(meta_file, root_path).split(os.sep)
        file_id = txt_file.split(".")[0]

        if isinstance(test_speakers, list):  # if is list ignore this speakers ids
            if speaker_id in test_speakers:
                continue

        with open(meta_file, "r", encoding="utf-8") as file_text:
            text = file_text.readlines()[0]

        wav_file = os.path.join(root_path, wavs_path, speaker_id, file_id + ".wav")

        # Test if the wav_file actually exists before adding it to the training files!
        if not os.path.isfile(wav_file):
            print(f"Dataset Warning: File {wav_file} does not exist, skipping!")
        else:
            items.append([text, wav_file, "VCTK_" + speaker_id])

    return items

```

**Comment by erogol** [comment]
We add such warnings by the new PRs
