### ISSUE TITLE
[Bug] ValueError running YourTTS model on tts-server

### ISSUE THREAD

**Issue by VigneshBaskar** [coqui-ai/TTS#1073]
## 🐛 Description
I am trying to run the YourTTS model on the tts-server. I am hitting Internal server error. When I check the log I see `ValueError:  [!] Look like you use a multi-lingual model. You need to define either a language_name or a style_wav to use a multi-lingual model.` 

### To Reproduce
Here is the command: `tts-server --model_name tts_models/multilingual/multi-dataset/your_tts`
 
### Environment
- 🐸TTS Version (e.g., 1.3.0): 0.5.0
- PyTorch Version (e.g., 1.8): 1.10.0
- Python version: 3.7.10
- OS (e.g., Linux): Linux 
- CUDA/cuDNN version: None
- GPU models and configuration: None
- How you installed PyTorch (`conda`, `pip`, source): pip
- Any other relevant information:

### Additional context
Here is the log
```
 " [!] Look like you use a multi-lingual model. "                             
ValueError:  [!] Look like you use a multi-lingual model. You need to define either a language_name or a style_wav to use a multi-lingual model.                                                                          
::1 - - [06/Jan/2022 23:14:17] "GET /api/tts?text=hi&speaker_id=male-pt-3%0A&style_wav= HTTP/1.1" 500 -  
```
 Other models work fine. The problem looks like it is only for YourTTS model

**Comment by erogol** [comment]
I think the error message is clear but if you missed it, you need to define the language and give a reference wav.

run `tts -h` to see the usage.

**Comment by VigneshBaskar** [comment]
> I think the error message is clear but if you missed it, you need to define the language and give a reference wav.

Hi @erogol. Yes sure, the error message is clear. I am sorry. I will check `tts -h`.  Thank you

**Comment by godspirit00** [comment]
I think it is because the `server.py` @ [L176](https://github.com/coqui-ai/TTS/blob/c63bb481e95bd4a1ff978947d8e3e6c0bfb4177f/TTS/server/server.py#L176) does not pass a `language_name` to `synthesizer.tts()` just like `synthesize.py` @ [L287](https://github.com/coqui-ai/TTS/blob/c63bb481e95bd4a1ff978947d8e3e6c0bfb4177f/TTS/bin/synthesize.py#L287).

So to fix this, just pass the `language_name` like `en` to `synthesizer.tts`.  
```
    wavs = synthesizer.tts(text, speaker_name=speaker_idx, language_name="en", style_wav=style_wav)
```

**Comment by VigneshBaskar** [comment]
Thank you :)

**Comment by VigneshBaskar** [comment]
> I think it is because the `server.py` @ [L176](https://github.com/coqui-ai/TTS/blob/c63bb481e95bd4a1ff978947d8e3e6c0bfb4177f/TTS/server/server.py#L176) does not pass a `language_name` to `synthesizer.tts()` just like `synthesize.py` @ [L287](https://github.com/coqui-ai/TTS/blob/c63bb481e95bd4a1ff978947d8e3e6c0bfb4177f/TTS/bin/synthesize.py#L287).
> 
> So to fix this, just pass the `language_name` like `en` to `synthesizer.tts`.
> 
> ```
>     wavs = synthesizer.tts(text, speaker_name=speaker_idx, language_name="en", style_wav=style_wav)
> ```

Thank you :)

**Comment by erogol** [comment]
server.py does not support YourTTS fully yet.
