### ISSUE TITLE
[Question] use of avg_loss_all

### ISSUE THREAD

**Issue by vince62s** [coqui-ai/TTS#1097]
Sorry put this here, but a minor question:

Is this supposed to be used anywhere ?

https://github.com/coqui-ai/TTS/blob/main/TTS/bin/train_encoder.py#L134

**Comment by erogol** [comment]
We used to print that but not anymore I guess. 

Eventually, the speaker encoder will use the Trainer class too. So it can stay as it is for now.

**Comment by erogol** [comment]
I close this but feel free to continue the conversation.
