### ISSUE TITLE
[Bug] Interrogative sentences do not sound like questions

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#1099]
Hi and first of all thanks for this great project!
## 🐛 Description

I tried the Colab notebook "Zero-shot-TTS-Demo" in French and the results were stunning. But I could not hear a difference between "Vous en avez beaucoup!" and "Vous en avez beaucoup?" (note the ! vs ? at the end). I tried with other interrogative sentences and I could not hear a clear question being said. 
So it does not seem that YourTTS handles question marks.

### To Reproduce
Open YourTTS-Zero-shot-TTS-demo notebook in Colab. Run all the cells, upload around 60 seconds of target speaker wav files when prompted, change the "text" variable to "Vous en avez beaucoup? Vous en avez beaucoup! Vous en avez beaucoup.", launch the synthesis and hear the result. All thee sentences sound the same.

### Expected behavior
Input text featuring a question mark should be said like a question.

### Environment
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.9.0+cu102",
        "TTS": "0.2.0",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.12",
        "version": "#1 SMP Tue Dec 7 09:58:10 PST 2021"
    }
}

**Comment by erogol** [comment]
Thanks for your feedback. It is not really a bug but I think it is important to handle such things properly. We'll consider your feedback for the next released model.

**Comment by Ca-ressemble-a-du-fake** [comment]
@erogol Cool! Is there already a way to pronounce a question as it is supposed to sound ? Maybe you are telling this is not possible in this Colab notebook but if I fine tuned the model with a dataset featuring questions, would it work ?

**Comment by skol101** [comment]
Curious, if the model is provided enough interrogative samples , will it learn to proncounce text differently if it ends with a "?"

**Comment by erogol** [comment]
I close this as it does not really a bug but a feature request maybe. But we'll keep this in mind for the next release of the model.
