### ISSUE TITLE
[Bug] Inconsistent items order

### ISSUE THREAD

**Issue by iamanigeeit** [coqui-ai/TTS#1102]
In `tts/datasets/` we have `__init__.py` saying `items` are in `[audio_path, text, speaker_id]` order but the output from `formatters.py` is `[text, audio_path, speaker_name]`. I don't think it affects anything though.

**Comment by erogol** [comment]
Yes the docstring is false. I'll update it thanks.

**Comment by erogol** [comment]
I've updated the docs in the dev branch which will be fixed by the next version.
