### ISSUE TITLE
[Bug] phoneme_to_sequence is actually text_to_phoneme_sequence

### ISSUE THREAD

**Issue by iamanigeeit** [coqui-ai/TTS#1113]
I was a bit confused with this block in `TTS/tts/utils/text/__init__.py`

    def phoneme_to_sequence(
        text: str,
        cleaner_names: List[str],
        language: str,
        enable_eos_bos: bool = False,
        custom_symbols: List[str] = None,
        tp: Dict = None,
        add_blank: bool = False,
        use_espeak_phonemes: bool = False,
    ) -> List[int]:
        """Converts a string of phonemes to a sequence of IDs.

This function looks like it converts raw text into a sequence of phoneme IDs. In my own clone i have refactored the function to `text_to_phoneseq`.

**Comment by erogol** [comment]
Sorry for the confusion but It's not really a bug. This function is removed in the new API.
