### ISSUE TITLE
[Feature request] Is there any chance for a stdout streaming option?

### ISSUE THREAD

**Issue by framilano** [coqui-ai/TTS#1114]
Right now we can only generate WAVs when using coqui TTS, I think a neat option would be to pipe coqui output directly to a wav player like aplay. 
Will something like that be available in the future?

**Comment by erogol** [comment]
We don't plan to implement this feature anytime soon but if contributed, more than welcome.

**Comment by jbg** [comment]
Depends on #1691 since all the print statements will corrupt the audio otherwise...
