### ISSUE TITLE
[Feature request] Partnership with [Jami](https://jami.net/)

### ISSUE THREAD

**Issue by ovari** [coqui-ai/TTS#1127]
Is there a possibility to partnership with [Jami](https://jami.net/) to obtain data?

Perhaps users could opt-in to providing the data?

Please see issue at https://git.jami.net/savoirfairelinux/jami-client-qt/-/issues/576#note_33544

What do you think?

Thank you

https://jami.net/
https://jami.biz/
https://git.jami.net/savoirfairelinux/jami-project/-/wikis/tutorials/Frequently-Asked-Questions
https://review.jami.net/
https://dl.jami.net/
https://www.transifex.com/savoirfairelinux/jami
https://www.transifex.com/savoirfairelinux/jams-jami-account-management-server/
https://www.transifex.com/savoirfairelinux/jami-website/
https://www.youtube.com/channel/UCIe47cCt_ovwKb2Nfr4nBlw/
https://forum.jami.net/
https://git.jami.net/savoirfairelinux/jami-client-gnome/-/wikis/Changelog
https://savoirfairelinux.com/en

**Comment by erogol** [comment]
I am not sure I understand how you want to obtain data from Jami. Can you elaborate on that?
