### ISSUE TITLE
[Bug] Formatter document looks strange.

### ISSUE THREAD

**Issue by yw0nam** [coqui-ai/TTS#1130]
Hello, i'm working to apply coqui-TTS for my custom dataset.

Thanks to kindly writing document, i make training code and Formatter for my dataset.
And my formatter as follow. 

```
def formatter(root_path, meta_file_train):
    temp = pd.read_csv(os.path.join(root_path, meta_file_train), sep='|')
    return list(zip(temp['path'], temp['normalized_text'], temp['name']))
```
But, i find this error

```
  File "/home/ubuntu/anaconda3/envs/coqui_TTS/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'Don't mind, I will take care of it.': System error.
```

And this error comes from soundfile.py.
the text "Don't mind, it just a piece of cake." looks strange because this should be audio file name.

So, i check implemented formatter by couqi-TTS.
And i find formatter implemented as follow.
```
def mozilla(root_path, meta_file):
    """Normalizes Mozilla meta data files to TTS format"""
    txt_file = os.path.join(root_path, meta_file)
    items = []
    speaker_name = "mozilla"
    with open(txt_file, "r", encoding="utf-8") as ttf:
        for line in ttf:
            cols = line.split("|")
            wav_file = cols[1].strip()
            text = cols[0].strip()
            wav_file = os.path.join(root_path, "wavs", wav_file)
            items.append([text, wav_file, speaker_name])
    return items
```

So, Implemented formatter return the items as [Text, wav file, speaker_name].
In contrast, [the coqui TTS format document](https://tts.readthedocs.io/en/latest/formatting_your_dataset.html#) guides the user to implement formatter to return [wav file, text, speaker_name].

So,  [the coqui TTS format document](https://tts.readthedocs.io/en/latest/formatting_your_dataset.html#)  need to be change, i guess.

**Comment by erogol** [comment]
I've changed it in the dev branch and will be released with the next version.
