### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by azgaruning** [coqui-ai/TTS#1131]
I got this error when I try to inference using my own Glow-TTS Multi Speaker.
 > Using model: glow_tts
 > Init speaker_embedding layer.
 > Using Griffin-Lim as no vocoder model defined
 > Text: Selamat sore
 > Text splitted to sentences.
['Selamat sore']
Traceback (most recent call last):
  File "/home/gugi/miniconda3/envs/TTS/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/home/gugi/workspace/TTS/TTS/bin/synthesize.py", line 287, in main
    wav = synthesizer.tts(args.text, args.speaker_idx, args.language_idx, args.speaker_wav)
  File "/home/gugi/workspace/TTS/TTS/utils/synthesizer.py", line 329, in tts
    outputs = synthesis(
  File "/home/gugi/workspace/TTS/TTS/tts/utils/synthesis.py", line 295, in synthesis
    outputs = run_model_torch(model, text_inputs, speaker_id, style_mel, d_vector=d_vector, language_id=language_id)
  File "/home/gugi/workspace/TTS/TTS/tts/utils/synthesis.py", line 93, in run_model_torch
    outputs = _func(
  File "/home/gugi/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/gugi/workspace/TTS/TTS/tts/models/glow_tts.py", line 311, in inference
    g = self._speaker_embedding(aux_input)
  File "/home/gugi/workspace/TTS/TTS/tts/models/glow_tts.py", line 173, in _speaker_embedding
    g = F.normalize(self.emb_g(g)).unsqueeze(-1)  # [b, h, 1]
  File "/home/gugi/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/nn/functional.py", line 4447, in normalize
    denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
  File "/home/gugi/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/_tensor.py", line 442, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "/home/gugi/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/functional.py", line 1465, in norm
    return _VF.norm(input, p, _dim, keepdim=keepdim)  # type: ignore[attr-defined]
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

This is my config.json
```
{
    "model": "glow_tts",
    "run_name": "coqui_tts",
    "run_description": "",
    "epochs": 1000,
    "batch_size": 16,
    "eval_batch_size": 16,
    "mixed_precision": true,
    "scheduler_after_epoch": false,
    "run_eval": true,
    "test_delay_epochs": -1,
    "print_eval": false,
    "dashboard_logger": "tensorboard",
    "print_step": 25,
    "plot_step": 100,
    "model_param_stats": false,
    "project_name": null,
    "log_model_step": 10000,
    "wandb_entity": null,
    "save_step": 10000,
    "checkpoint": true,
    "keep_all_best": false,
    "keep_after": 10000,
    "num_loader_workers": 2,
    "num_eval_loader_workers": 2,
    "use_noise_augment": false,
    "use_language_weighted_sampler": false,
    "output_path": "/home/gugi/workspace/TTS",
    "distributed_backend": "nccl",
    "distributed_url": "tcp://localhost:54321",
    "audio": {
        "fft_size": 1024,
        "win_length": 1024,
        "hop_length": 200,
        "frame_shift_ms": null,
        "frame_length_ms": null,
        "stft_pad_mode": "reflect",
        "sample_rate": 16000,
        "resample": false,
        "preemphasis": 0.0,
        "ref_level_db": 20,
        "do_sound_norm": false,
        "log_func": "np.log10",
        "do_trim_silence": true,
        "trim_db": 45,
        "do_rms_norm": false,
        "db_level": null,
        "power": 1.5,
        "griffin_lim_iters": 60,
        "num_mels": 80,
        "mel_fmin": 0.0,
        "mel_fmax": null,
        "spec_gain": 20,
        "do_amp_to_db_linear": true,
        "do_amp_to_db_mel": true,
        "signal_norm": true,
        "min_level_db": -100,
        "symmetric_norm": true,
        "max_norm": 4.0,
        "clip_norm": true,
        "stats_path": null
    },
    "use_phonemes": false,
    "use_espeak_phonemes": false,
    "phoneme_language": null,
    "compute_input_seq_cache": false,
    "text_cleaner": "basic_cleaners",
    "enable_eos_bos_chars": false,
    "test_sentences_file": "",
    "phoneme_cache_path": null,
    "characters": {
        "pad": "_",
        "eos": "~",
        "bos": "^",
        "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
        "punctuations": "!'(),-.:;? ",
        "phonemes": "iy\u0268\u0289\u026fu\u026a\u028f\u028ae\u00f8\u0258\u0259\u0275\u0264o\u025b\u0153\u025c\u025e\u028c\u0254\u00e6\u0250a\u0276\u0251\u0252\u1d7b\u0298\u0253\u01c0\u0257\u01c3\u0284\u01c2\u0260\u01c1\u029bpbtd\u0288\u0256c\u025fk\u0261q\u0262\u0294\u0274\u014b\u0272\u0273n\u0271m\u0299r\u0280\u2c71\u027e\u027d\u0278\u03b2fv\u03b8\u00f0sz\u0283\u0292\u0282\u0290\u00e7\u029dx\u0263\u03c7\u0281\u0127\u0295h\u0266\u026c\u026e\u028b\u0279\u027bj\u0270l\u026d\u028e\u029f\u02c8\u02cc\u02d0\u02d1\u028dw\u0265\u029c\u02a2\u02a1\u0255\u0291\u027a\u0267\u02b2\u025a\u02de\u026b",
        "unique": true
    },
    "batch_group_size": 0,
    "loss_masking": null,
    "sort_by_audio_len": false,
    "min_seq_len": 3,
    "max_seq_len": 500,
    "compute_f0": false,
    "compute_linear_spec": false,
    "add_blank": false,
    "datasets": [
        {
            "name": "vctk",
            "path": "/home/gugi/workspace/mycode/VCTK_MultiSPK",
            "meta_file_train": "",
            "ignored_speakers": null,
            "language": "",
            "meta_file_val": "",
            "meta_file_attn_mask": ""
        }
    ],
    "optimizer": "RAdam",
    "optimizer_params": {
        "betas": [
            0.9,
            0.998
        ],
        "weight_decay": 1e-06
    },
    "lr_scheduler": "NoamLR",
    "lr_scheduler_params": {
        "warmup_steps": 4000
    },
    "test_sentences": [
        "halo selamat sore",
        "sepatuku kotor belum aku cuci dari kemarin",
        "sekarang di negara kita sedang musim hujan",
        "apa yang dipikirkan oleh pemuda brandal yang biasa meminum minuman keras di ujung jalan itu",
        "rawat wajah kita dengan sarang burung walet yuk guys"
    ],
    "num_chars": 66,
    "encoder_type": "rel_pos_transformer",
    "encoder_params": {
        "kernel_size": 3,
        "dropout_p": 0.1,
        "num_layers": 6,
        "num_heads": 2,
        "hidden_channels_ffn": 768,
        "input_length": null
    },
    "use_encoder_prenet": true,
    "hidden_channels_enc": 192,
    "hidden_channels_dec": 192,
    "hidden_channels_dp": 256,
    "dropout_p_dp": 0.1,
    "dropout_p_dec": 0.05,
    "mean_only": true,
    "out_channels": 80,
    "num_flow_blocks_dec": 12,
    "inference_noise_scale": 0.0,
    "kernel_size_dec": 5,
    "dilation_rate": 1,
    "num_block_layers": 4,
    "num_speakers": 452,
    "c_in_channels": 0,
    "num_splits": 4,
    "num_squeeze": 2,
    "sigmoid_scale": false,
    "d_vector_dim": 0,
    "data_dep_init_steps": 10,
    "style_wav_for_test": null,
    "length_scale": 1.0,
    "use_speaker_embedding": true,
    "speaker_embedding_dim": 512,
    "use_d_vector_file": false,
    "d_vector_file": false,
    "grad_clip": 5.0,
    "lr": 0.001,
    "r": 1
}
```

**Comment by yw0nam** [comment]
I got this error too, and i think this error comes from `self.emb_g(g)` which expect output size [b, h]. 
This is work well in training. in contrast, in inference step, output of above code is [h] which is not expected  `F.normalize(self.emb_g(g))`.

**Comment by azgaruning** [comment]
> I got this error too, and i think this error comes from `self.emb_g(g)` which expect output size [b, h]. This is work well in training. in contrast, in inference step, output of above code is [h] which is not expected `F.normalize(self.emb_g(g))`.

Oh i see. But when i doing inference using Tacotron2 it's fine. How to solve this in glow-tts?

**Comment by robinhad** [comment]
@azgaruning, this helped me:
Find this line in `glow_tts.py`:
```
g = F.normalize(self.emb_g(g)).unsqueeze(-1)
```
and replace with:
```
g = F.normalize(self.emb_g(g).unsqueeze(0)).unsqueeze(-1)
```
But this is a hotfix.

**Comment by azgaruning** [comment]
> @azgaruning, this helped me: Find this line in `glow_tts.py`:
> 
> ```
> g = F.normalize(self.emb_g(g)).unsqueeze(-1)
> ```
> 
> and replace with:
> 
> ```
> g = F.normalize(self.emb_g(g).unsqueeze(0)).unsqueeze(-1)
> ```
> 
> But this is a hotfix.

Thank you sir, this solve the problem.
