### ISSUE TITLE
Trained new Italian TTS (glowtts male and female voice)

### ISSUE THREAD

**Issue by nicolalandro** [coqui-ai/TTS#1148]
**🚀 Feature Description**
Does not exist an italian TTS.

**Solution**
I trained some models using [male dataset](https://huggingface.co/datasets/z-uo/male-LJSpeech-italian) adn [female dataset](https://huggingface.co/datasets/z-uo/female-LJSpeech-italian) :  
* glowtts
  * [male](https://huggingface.co/z-uo/glowtts-male-it)
  * [female](https://huggingface.co/z-uo/glowtts-female-it)
* vits
  * [male](https://huggingface.co/z-uo/vits-male-it)
  * [female](https://huggingface.co/z-uo/vits-female-it).

**Comment by erogol** [comment]
Awesome!! Thanks for sharing the model. I'll add it to the next release.

**Comment by nicolalandro** [comment]
Thank you! Great, if I train also other models I will put in that thread!

**Comment by erogol** [comment]
@nicolalandro  Which models are the best model in the folders?

**Comment by nicolalandro** [comment]
Scuse me for the confusing repo, Ignore the presence of GOOD_* (I copy sometimes when I test it) the best_model.pth.tar should be the best as in standard training with the coqui recipes.

**Comment by Ca-ressemble-a-du-fake** [comment]
Hi @nicolalandro, would you mind sharing the method you used to create Italian voices. I am very interested because I want to create a French voice. Did you fine tune an existing English or multi language model, or di you startbfrom scratch ? What about your dataset, how many samples did you use and how long is it ? Do you have multi speakers, if so how did you achieve to differentiate the different voices when calling tts ?

Thanks

**Comment by e0xextazy** [comment]
@nicolalandro I would also be interested in the details of your implementation. Thank you!

**Comment by nicolalandro** [comment]
@Ca-ressemble-a-du-fake @e0xextazy 

I use the recipes into that codebase, and I modify the path and some parameters like batch size to fit my GPUs. So the code and the guide can be finded in  [this repo](https://github.com/nicolalandro/train_coqui_tts_ita) and the readme should explain what I do. 

I trained from scratch (glowtts seams to be the simplest to use, because it got results and use few ram, less than tacotron) and I use that two datasets:
* [male voice](https://huggingface.co/datasets/z-uo/male-LJSpeech-italian): 31h 45m of one speacker recorded at 16000Hz
* [female voice](https://huggingface.co/datasets/z-uo/female-LJSpeech-italian): 8h 23m of one speacker recorded at 16000Hz
I find that wavs from the [M-AILABS](https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/) dataset (that also have French speakers)

**Comment by e0xextazy** [comment]
@nicolalandro I meant the fine-tuning for one new speaker

**Comment by Ca-ressemble-a-du-fake** [comment]
Great thanks for these insights!

**Comment by nicolalandro** [comment]
New realease [v0.6.0](https://github.com/coqui-ai/TTS/releases/tag/v0.6.0)! Now the italians models are available!

**Comment by nicolalandro** [comment]
Yes it is good, I think that to have better results I also need a better dataset, I'm wandering for It. You think that is possible to train on multiple speaker by using Common Voice?

**Comment by erogol** [comment]
I think so. VITS is quite good for such a task.

**Comment by nicolalandro** [comment]
So I must only adapt the vctk recipe to common voice dataset to train on multiple speakers? I must extend BaseDatasetConfig class to support common voice?

**Comment by erogol** [comment]
You just have to implement your own dataset formatted https://tts.readthedocs.io/en/latest/formatting_your_dataset.html#loading-your-dataset

That's pretty much all.

**Comment by nicolalandro** [comment]
Ok perfect thanks! I will open a new issue when I will train it with Mozilla common voice dataset.

**Comment by carlocastoldi** [comment]
Today I tried the 4 models and, while with `mai_male/vits` it crashed, the results seems promising! They seem a bit tailored to someone voice (e.g. both the female models have strong regional accent), but with Mozilla's Common Voice this should improve, right?
Speaking of which: today the [Common Voice Corpus v9.0](https://commonvoice.mozilla.org/en/datasets) was released!

P.S. the flaws I encountered in a small test included:
 - numbers being pronounced in English
 - accent letters &  some more symbols (such as "%") not being found in the vocabulary

overall thank you for your work, Nicola! Looking forward for your next models :D

**Comment by nicolalandro** [comment]
I was trying to train the model with the 8.0 version of Common Voice in Italian, but also with the double of epochs the results are not satisfying, the model does not speak. Also the regional accent is strong, but that dataset was the only one that I find that is free and open, it only discriminate from nothing in Italian and something.

**Comment by carlocastoldi** [comment]
Thanks for the update!
And yeah, I guess for the female voice it's pretty much unavoidable seeing the unbalance of the dataset :\

I guess our only option now is to make Common Voice submissions more popular in Italy. Going from 8.0 to 9.0 the Italian corpus increased just slightly

**Comment by nicolalandro** [comment]
I tain a VITS on Commonvoice 9.0 in italian ([here](https://huggingface.co/z-uo/vits-commonvoice9.0/tree/main) the train output files) with [this script](https://huggingface.co/z-uo/vits-commonvoice9.0/blob/main/train_vits.py), this an [example of results](https://huggingface.co/z-uo/vits-commonvoice9.0/blob/main/example.wav) but it seams to have problems like voice distortion (or some effects like when you slow down the audio)

**Comment by tieincred** [comment]
Hello @nicolalandro, 
Great work training the on Italian dataset.
I am new to the topic so please forgive for noob question.
I am trying to train a new model on Hindi Dataset however, 
I saw the script you mentioned you used for training, but you have not specified characters for training?
Can you please tell me the reason for that and if specifying characters are not important while training on new language?

**Comment by phamkhactu** [comment]
Hi @erogol @nicolalandro 

Thank you for your great work and sharing how to train multi speakers.
However new language how can I face with this?

As I know only speaker encoder model for English, so I've try to train multi speakers from : ```recipes/vctk/vits/train_vits.py```. I've followed [vtck](https://www.kaggle.com/datasets/pratt3000/vctk-corpus) structure and I've trained successfully. But can not get ```speaker_ids.json```, ... I've kept all original configs:

```
dataset_config = BaseDatasetConfig(
    formatter="vctk", meta_file_train="", path="data/VCTK"
)


audio_config = VitsAudioConfig(
    sample_rate=22050, win_length=1024, hop_length=256, num_mels=80, mel_fmin=0, mel_fmax=None
)

vitsArgs = VitsArgs(
    use_speaker_embedding=True,
)
``` 

I'm very thankful for your sharing to create procedure for training multi speaker with new language.
Thank you very much!

**Comment by GlossyVase** [comment]
Hello 
I would like to use the Italian TTS model, but I'm new to github, TTS and machine learning in general, I don't have the tecnical capabilities to run this. Could someone breifly explain how to?

Thank you very much

**Comment by eginhard** [comment]
@GlossyVase See the documentation: https://coqui-tts.readthedocs.io/en/latest/inference.html

**Comment by GlossyVase** [comment]
@eginhard Thank you
