### ISSUE TITLE
[Feature request] YourTTS integration

### ISSUE THREAD

**Issue by leminhyen2** [coqui-ai/TTS#1152]
This new model has great result and is also implemented with coqui-ai/TTS.
It would be great to see this model integrated with the repo. 
Here the link: https://github.com/Edresson/YourTTS/

**Comment by astricks** [comment]
It has already been integrated. [Here's](https://github.com/coqui-ai/TTS/blob/main/recipes/multilingual/vits_tts/train_vits_tts.py) the recipe.

**Comment by johnkuan506** [comment]
@astricks I'm quite confused about the structure of the multilingual data in train_vits_tts.py (which `mailabs_path` refer to). Could you give me some hints about that. Many thanks.

**Comment by erogol** [comment]
It is already integrated as @astricks  mentioned

**Comment by astricks** [comment]
> 

You honestly don't need to deal with train_vits_tts.py at all. You only need to deal with the recipe file.

So, basically you set [this variable](https://github.com/coqui-ai/TTS/blob/main/recipes/multilingual/vits_tts/train_vits_tts.py#L19) to the path where your mailabs dataset lives.
It seems like mailabs separates the languages by folder (mailabs/en/**, mailabs/es/**, mailabs/fr/**) so each ['path' here](https://github.com/coqui-ai/TTS/blob/main/recipes/multilingual/vits_tts/train_vits_tts.py#L19) would point to a different language folder within the mailabs dataset.

Based on the [name parameter here](https://github.com/coqui-ai/TTS/blob/main/recipes/multilingual/vits_tts/train_vits_tts.py#L19), a [dataloader method](https://github.com/coqui-ai/TTS/blob/main/TTS/tts/datasets/formatters.py) corresponding to the dataset name reads in the data.
