### ISSUE TITLE
[Feature request] [Enhancement] Add Layman Intro + Add Real Life Command/Syntax Examples

### ISSUE THREAD

**Issue by qkum** [coqui-ai/TTS#1153]
I like the style of this repo & project.

But that there is no Layman Explanation is.........................................

It is the norm in the programming world that people assume that new users are experts like themself.................

How hard can it be to write "This repo is about making a good fake human voice".

That sentence had saved me many hours.

It is a general problem, but because I like the karma of this repo I actually care to suggest something that most likely will never be done.

I came here for Speech ID (identification) and got duped because i'm not a born english speaker...like most of planet earth.

Keep up the good style & karma but plz fix the Layman part and add real-life examples so people don't have to sit and guess for hours how to type the commands correctly. (also a general programming mistake - they assume everybody got 10+ years of experience)

**Comment by qkum** [comment]
I don't know how to add the correct label.

I wish Github also took programmers with less than 10 years of experience a little attention.

So it would not take years to figure it all out by accident.....

Maybe add a tooltip or something Github? (what a brain you need to figure that one out)

**Comment by erogol** [comment]
There is the most layman as it could get ATM https://tts.readthedocs.io/en/latest/tutorial_for_nervous_beginners.html

If still too much, we are working on tools to make things even easier. But it'll take time.
