### ISSUE TITLE
[Feature request] please add support for screen readers

### ISSUE THREAD

**Issue by king-dahmanus** [coqui-ai/TTS#1168]
**🚀 Feature Description**
adding support for screenreaders by making an accessible gui which can be used to make models, train them, test them and deploy them in an easy manner

**Solution**
Please also make a synthdriver for the nvda screenreader, then the models can be exported into an nvda addon for use with the screen reader. Make sure that the voices are responsive and don't have any silence or delay before the speech or in the middle of speech output

**Alternative Solutions**
to resolve the responsiveness issue, you may grab the buffer which contains the audio from memory, then trim the silence and fead it back to the audio device

**Additional context**
This can benifit blind people by allowing them to make models and use them in a screen reader so they can read there texts with there own voices, like myself. I'm not a programmer, just a tts adict. So please bare with me, and hope we can make tts creation accessible for everyone.

**Comment by erogol** [comment]
I don't think it is in the scope of the project. I think the screen reader should integrate 🐸TTS than the other way around.

**Comment by king-dahmanus** [comment]
the screen reader is extensible and has an addon api you can use to make
all sorts of extensions including  synthdrivers.  But the thing is, this
project needs some checkups and improvements before you can integrate it
with any screen reader, the main thing is real time inference without
delays or lags before or in the middle of speech, and the ability to change
speed and pitch of the voice without errors or undesirable artifacts. The
main thing is responsivity and speed as that's veeeeery super important for
blind people, we don't want even half a second of delay before speech, not
even 100ms of delay, as less delay as possible
Proposed solutions:
You could do the caching of calculations to reduce the repeated unnecessary
calculations. Also you could make a service that caches all the samples in
memory and do the required things so the models are always responsive.
You guys at coqui don't have to do all the work of writing every single
voice and converting it to be usable by nvda, you could just do the
optimizations, and write a single synthdriver which supports all the models
which are compatible with coqui tts's structure. Then the people who want
to contribute can just make ports of the models themselves as  addons which
the previously written synthdriver will recognize and use. For more
information about NVDA and its sourcecode, documentations, etc, please
check https://github.com/nvaccess/nvda. Thanks!
