### ISSUE TITLE
[Bug] There is something wrong with the import module.

### ISSUE THREAD

**Issue by lanbairua** [coqui-ai/TTS#1186]
um……
I can't use this module, and I don't know if I'm missing something?
Error Message:
```python
from TTS.trainer import Trainer, TrainingArgs
```
> from TTS.trainer import Trainer, TrainingArgs
> multiprocessing.set_start_method("fork")
> self._actual_context = self.get_context(method
> return super().get_context(method))
> raise ValueError('cannot find context for %r' % method) from None
> ValueError: cannot find context for 'fork'

**Comment by erogol** [comment]
Please use the issue template. I close this one.
