### ISSUE TITLE
[Feature request] Custom voice synthesis from personal recordings

### ISSUE THREAD

**Issue by shmueldabomb441** [coqui-ai/TTS#1196]
**🚀 Feature Description**

I did not see a clear description of how to clone your voice so that it would produce your voice on new text - just as almost all of the other tts engines use. I therefore tentatively assumed that it is not possible. I searched pre-existing issues and did not find anything related to that. If it is possible, instructions on how to do so would be appreciated

**Comment by thorstenMueller** [comment]
Of course it's possible to train your own tts model based on your voice dataset (recordings). Check this doc for a starting point (https://tts.readthedocs.io/en/latest/tutorial_for_nervous_beginners.html#) or maybe take a look at my technical walkthrough video showing that process (https://youtu.be/4YT8WZT_x48).

**Comment by jacen92** [comment]
Hi,

Could it be possible to get the sources of the homepage demo (yourTTS)?
It is a great way to test and I guess we could be able to update the tts_server with this app.

Perhaps we can build a docker image to reproduce the demo behavior in an other/local environment.

It could help a lot of people to use the TTS directly directly.

**Comment by Edresson** [comment]
@jacen92  We currently do not provide guidelines for fine-tuning YourTTS due to the potential for misuse of this model. We intend to make these guidelines available in the future as soon as we have an efficient way to detect fake audio/generated speech. This topic is also discussed [here](https://github.com/Edresson/YourTTS/issues/5).

**Comment by DesiKeki** [comment]
> Of course it's possible to train your own tts model based on your voice dataset (recordings). Check this doc for a starting point (https://tts.readthedocs.io/en/latest/tutorial_for_nervous_beginners.html#) or maybe take a look at my technical walkthrough video showing that process (https://youtu.be/4YT8WZT_x48).

Thanks a lot for the informative video @thorstenMueller . I tried the steps in it and got a model generating my voice which sounds robotic/metallic with a buzz/echo in it. Any guidance to fix this? 
FYI... I used glow_TTS for fine tuning, 100 noise free samples of my voice (each 74 characters avg) and training for 600k steps with a batch size of 16.

**Comment by thorstenMueller** [comment]
Sorry for late response @DesiKeki .
`Glow-TTS` is a TTS model. By default a vocoder called "Griffin Lim" will be used and this will sound metallic/robotic. You should check/train a vocoder model (_like HifiGAN_) for your dataset/model. You can see supported vocoder models [here](https://github.com/coqui-ai/TTS/tree/main/TTS/vocoder/models).
Maybe 100 samples are too less for a great TTS model.
