### ISSUE TITLE
use `python TTS/bin/train_tts.py --continue_path` flag

### ISSUE THREAD

**Issue by oelmas** [coqui-ai/TTS#1197]
use `python TTS/bin/train_tts.py --continue_path` flag
I used this command so start where it was left of (for example 78/1000 ) but epoch start from 0/1000 again.  Do I missing something or wrong ?

**Comment by r7sa** [comment]
It seems to be bug, discussed in #1039.

**Comment by erogol** [comment]
I close this for #1039
