### ISSUE TITLE
[Feature request] Mandrain dataset or pretrained model support

### ISSUE THREAD

**Issue by jinfagang** [coqui-ai/TTS#1237]
Hi, really want coqui-tts can have a mandrain model, there also some popular data can be used to train, like Biaobei baker dataset.

**Comment by wangtiance** [comment]
There is a pretrained mandarin model:
tts_models/zh-CN/baker/tacotron2-DDC-GST

**Comment by jinfagang** [comment]
@wangtiance thanks. tacotron2 is slow though. Is there a way to train a customized fastspeech2 model ? what dataset using there for mandrain?

**Comment by wangtiance** [comment]
> @wangtiance thanks. tacotron2 is slow though. Is there a way to train a customized fastspeech2 model ? what dataset using there for mandrain?

I haven't tried training models. There are guides in the docs.
