### ISSUE TITLE
[Feature request]  Using existing model checkpoint from official model repositories.

### ISSUE THREAD

**Issue by adivish1999** [coqui-ai/TTS#1242]
**🚀 Feature Description**

Was thinking about using checkpoints from models trained from the original repository, in my case VITS model. Currently on loading the checkpoints from the model trained from official repo, the keys in state dictionaries are different and I tried to change the basic names of the encoders but they were different at a deeper level. A feature to load checkpoints from original repos could be real useful.

**Comment by erogol** [comment]
Yeah, I agree. Will look at it.
