### ISSUE TITLE
VITIS Out of Memory 

### ISSUE THREAD

**Issue by Rico2000** [coqui-ai/TTS#1295]
Hey,
I always get an out of memory error with the Vitis/YourTTS model with two V100. I get this even with a batch_size of 16 and a sample_rate of 160000 with a max sequence length of 10 seconds. I have included all config files and log data below. The paper mentions that a batch_size of 64 was used with a V100. How is this possible?

Thanks

![grafik](https://user-images.githubusercontent.com/60230024/155840204-df79e325-784d-4e28-91fb-6a141923c480.png)

Config:
`audio_config = BaseAudioConfig(
    sample_rate=16000,
    win_length=1024,
    hop_length=256,
    num_mels=80,
    preemphasis=0.0,
    ref_level_db=20,
    log_func="np.log",
    do_trim_silence=True,
    trim_db=23.0,
    mel_fmin=0,
    mel_fmax=None,
    spec_gain=1.0,
    signal_norm=False,
    do_amp_to_db_linear=False,
    resample=False,
)

vitsArgs = VitsArgs(
    use_language_embedding=False,
    use_speaker_embedding=True,
    use_sdp=False,
)

config = VitsConfig(
    model_args=vitsArgs,
    audio=audio_config,
    run_name="vits_mailabs",
    use_speaker_embedding=True,
    batch_size=16,
    eval_batch_size=8,
    batch_group_size=5,
    num_loader_workers=4,
    num_eval_loader_workers=4,
    run_eval=True,
    test_delay_epochs=-1,
    epochs=1000,
    text_cleaner="basic_german_cleaners",
    use_phonemes=True,
    phoneme_language="de-de",
    phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
    compute_input_seq_cache=True,
    print_step=25,
    use_language_weighted_sampler=False,
    print_eval=True,
    mixed_precision=True,
    min_seq_len=32 * 256 * 4,
    max_seq_len=160000,
    output_path=output_path,
    datasets=dataset_config,
)
ap = AudioProcessor(**config.audio.to_dict())

train_samples, eval_samples = load_tts_samples(dataset_config, eval_split=True, formatter = format_ml)

speaker_manager = SpeakerManager()
speaker_manager.set_speaker_ids_from_data(train_samples + eval_samples)
config.model_args.num_speakers = speaker_manager.num_speakers

model = Vits(config, speaker_manager)

trainer = Trainer(
    args,
    config,
    output_path,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples,
    training_assets={"audio_processor": ap},
    parse_command_line_args = False
)
trainer.fit()`

Logs:
`> Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:23.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 469942 files 
ddp True
 > Using CUDA:  True
 > Number of GPUs:  2
 > `speakers.json` is saved to 
 > `speakers_file` is updated in the config.json.

 > Model has 85503549 parameters

[4m[1m > EPOCH: 0/1000[0m
 --> 

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: de-de
 | > Number of instances : 469942
 | > Computing phonemes ...
 | > Max length sequence: 219246.5
 | > Min length sequence: 35174.5
 | > Avg length sequence: 132966.10140400304
 | > Num. instances discarded by max-min (max=160000, min=32768) seq limits: 89103
 | > Batch group size: 80.

[1m > TRAINING (2022-02-25 11:32:12) [0m

[1m   --> STEP: 0/11901 -- GLOBAL_STEP: 0[0m
     | > loss_gen: 5.98442  (5.98442)
     | > loss_kl: 157.43459  (157.43459)
     | > loss_feat: 0.30652  (0.30652)
     | > loss_mel: 78.40177  (78.40177)
     | > loss_duration: 0.51552  (0.51552)
     | > amp_scaler: 32768.00000  (32768.00000)
     | > loss_0: 242.64282  (242.64282)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_disc: 5.98675  (5.98675)
     | > amp_scaler-1: 16384.00000  (16384.00000)
     | > loss_1: 5.98675  (5.98675)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020 
     | > current_lr_1: 0.00020 
     | > step_time: 2.70340  (2.70336)
     | > loader_time: 2.76340  (2.76342)`

**Comment by MultiTrickFox** [comment]
Take a look at my post & see if it's what you mean..
https://github.com/coqui-ai/TTS/issues/1297

**Comment by Rico2000** [comment]
@MultiTrickFox  could be. how can i observe that hifigan is the problem?

**Comment by MultiTrickFox** [comment]
Hey, try bypassing all the weight_norms in the model you use. I did it, no more memory leak. Talking from knowledge :) it might help you.

use torch.nn.utils.remove_weight_norm to remove ALL the weight norms in your model.
iterate over your modules and try/except remove all weightnorms. My exact solution..
