### ISSUE TITLE
Can't install cloned repo locally (permission denied)

### ISSUE THREAD

**Issue by ProgrammingLife** [coqui-ai/TTS#1317]
## 🐛 Description

Trying to install TTS locally but it tries to install it globally.

### To Reproduce
```
$ git clone https://github.com/coqui-ai/TTS
$ cd TTS
$ python3.9 -m pip install -e . 
Defaulting to user installation because normal site-packages is not writeable
...
 The following error occurred while trying to add or remove files in the
    installation directory:
        [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages'
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
        /usr/lib/python3.9/site-packages/
```
All my pip packages which I install with: `python3.9 -m pip install ...` installs to `~/.local/lib/python3.9/site-packages` without any problem.
Why does TTS want to install it globally instead of existing `~/.local/lib/python3.9/site-packages`?

### Expected behavior

Installed TTS.

### Environment

python: 3.9
TTS: just cloned repo

### Additional context
n/a

**Comment by Edresson** [comment]
Hello @ProgrammingLife,

Looks like the setup installs in development mode (python setup.py develop or pip install  with -e option) install globally. To go around this you can  try to use the option --user in the command:
`python3.9 -m pip install -e .  --user`
