### ISSUE TITLE
[Bug] RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ProgrammingLife** [coqui-ai/TTS#1318]
### To Reproduce

I used this config file: https://github.com/Edresson/Coqui-TTS/blob/main/TTS/tts/configs/config.json
And `LJSpeech-1.1` with:
```
shuf metadata.csv > metadata_shuf.csv
head -n 12000 metadata_shuf.csv > metadata_train.csv
tail -n 1100 metadata_shuf.csv > metadata_val.csv
```

So I just run:
```python3.9 TTS/bin/train_tts.py --config_path config.json```

And then I get out of memory issue:
`RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 3.94 GiB total capacity; 2.18 GiB already allocated; 640.00 KiB free; 2.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

My GPU has 4GB total. 
Is it too little or am I doing something wrong?

### Environment
```
{
    "CUDA": {
        "GPU": [
            "GeForce GTX 980"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.2+cu102",
        "TTS": "0.5.0",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.10",
        "version": "#51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019"
    }
}
```

### Additional context
n/a

**Comment by Edresson** [comment]
Hello @ProgrammingLife, 

First of all, we strongly recommend the use of the latest TTS version, in this way you can avoid bugs present in old versions. 

Probably you will need more than 4 Gb for training the Tacotron 2 model. You can try to reduce the "batch_size" and "eval_batch_size"  however the reduction of the batch size in the Tacotron 2 model might cause hard to learn attention.
Maybe you can try the Glow-TTS model but I'm not sure if you will be able to train with just 4GB of VRAM.
