### ISSUE TITLE
[Bug] Compuation Time Phonems 

### ISSUE THREAD

**Issue by Rico2000** [coqui-ai/TTS#1344]
## 🐛 Description

The problem is the compuation time of Phonems. I tried the LJSpeech recipe for the Vitis Model. The expected time for cumputing the Phonems is arounf 20 hours. I think that should not be that long? I run the scripts on azure on a comput cluster with one V100. 

[train_logs.txt](https://github.com/coqui-ai/TTS/files/8195929/train_logs.txt)

### To Reproduce

[train.txt](https://github.com/coqui-ai/TTS/files/8195932/train.txt)

### Expected behavior

The computation should should not take that long time i think

### Environment

- 🐸TTS Version: 0.5.0
- PyTorch Version (e.g., 1.8)
- Python version: pytorch-1.9.0
- OS (e.g., Linux): Linux Ubuntu
- CUDA/cuDNN version: cudatoolkit=11.2 
- GPU models and configuration:  Tesla V100-PCIE-16GB
- How you installed PyTorch (`conda`, `pip`, source): conda
- Any other relevant information: runs on azure compute cluster

**Comment by erogol** [comment]
How many CPIU cores do you have? 

Can you also try the dev branch ?

**Comment by Rico2000** [comment]
How can i run code in dev branch because there in TTS there no trainer.py

**Comment by Rico2000** [comment]
[70_driver_log(1).txt](https://github.com/coqui-ai/TTS/files/8218185/70_driver_log.1.txt)
same happens with dev branch

**Comment by erogol** [comment]
Try increasing ```precompute_num_workers``` in your config.
