### ISSUE TITLE
[Feature request] Specify Which Speaker ID for Test Sentences

### ISSUE THREAD

**Issue by stanleyshly** [coqui-ai/TTS#1345]
When running test sentences in tensorboard/wandb, with multispeaker models, it would be nice to be specify one or multiple speakers ids, to check if the model is doing better or worse between different regional accents.
This may be already implemented, but I can't find a way to specify the speaker id in the config files.

**Comment by erogol** [comment]
It is already implemented. I think @Edresson  can answer this.

**Comment by Edresson** [comment]
It is already implemented for the VITS model. You can use this just by providing the speaker_id in the test sentence list. 
For example:
```
"test_sentences": [
        ["It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.", "VCTK_p334"],
        ["Be a voice, not an echo.", "VCTK_p340"],
        ["I'm sorry Dave. I'm afraid I can't do that.", "VCTK_p257"],
        ["This cake is great. It's so delicious and moist.", "VCTK_p234"],
        ["Prior to November 22, 1963.", "VCTK_p225"]
    ]

```
