### ISSUE TITLE
[Bug] something wrong with speaker manager and speaker encoding initialization?

### ISSUE THREAD

**Issue by hemath1001** [coqui-ai/TTS#1364]
Hi there~ 
I have tried new dev branch(0.6.1), and find this version have reorganized the code related to speaker manager and speaker encoding, but it results in some NoneType error... It seems that speaker manager and speaker encoding are not initialized.
When only using encoder model:
`tts --text "hello, what's your name?" --speaker_wav "D:\coqui\wav\rick.wav" --encoder_config_path "D:\coqui\models\encoder\LibriTTS-VCTK-VoxCeleb-CommonVoice\config.json" --encoder_path "D:\coqui\models\encoder\LibriTTS-VCTK-VoxCeleb-CommonVoice\best_model.pth.tar" --out_path "D:\coqui\wav\rickTest.wav"`
The error is:
```
Traceback (most recent call last):
  File "D:\coqui\Coqui-TTS-dev\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "d:\coqui\coqui-tts-dev\TTS\bin\synthesize.py", line 287, in main
    wav = synthesizer.tts(args.text, args.speaker_idx, args.language_idx, args.speaker_wav)
  File "d:\coqui\coqui-tts-dev\TTS\utils\synthesizer.py", line 246, in tts
    speaker_embedding = self.tts_model.speaker_manager.compute_d_vector_from_clip(speaker_wav)
AttributeError: 'NoneType' object has no attribute 'compute_d_vector_from_clip'
```
When using encoder model and vits:
`tts --text "hello, what's your name?" --speaker_wav "D:\coqui\wav\rick.wav" --encoder_config_path "D:\coqui\models\encoder\LibriTTS-VCTK-VoxCeleb-CommonVoice\config.json" --encoder_path "D:\coqui\models\encoder\LibriTTS-VCTK-VoxCeleb-CommonVoice\best_model.pth.tar" --out_path "D:\coqui\wav\rickTest.wav" --model_name tts_models/en/vctk/vits`
The error is:
```
Traceback (most recent call last):
  File "D:\coqui\Coqui-TTS-dev\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "d:\coqui\coqui-tts-dev\TTS\bin\synthesize.py", line 287, in main
    wav = synthesizer.tts(args.text, args.speaker_idx, args.language_idx, args.speaker_wav)
  File "d:\coqui\coqui-tts-dev\TTS\utils\synthesizer.py", line 245, in tts
    speaker_embedding = self.tts_model.speaker_manager.compute_d_vector_from_clip(speaker_wav)
  File "d:\coqui\coqui-tts-dev\TTS\tts\utils\speakers.py", line 287, in compute_d_vector_from_clip
    d_vector = _compute(wf)
  File "d:\coqui\coqui-tts-dev\TTS\tts\utils\speakers.py", line 270, in _compute
    waveform = self.speaker_encoder_ap.load_wav(wav_file, sr=self.speaker_encoder_ap.sample_rate)
AttributeError: 'NoneType' object has no attribute 'load_wav'
```

Besides,on Windows, I fixed "ValueError: cannot find context for 'fork'" by changing `multiprocessing.set_start_method("fork")` in trainer.py to `multiprocessing.set_start_method("spawn", force=True)`. I am not sure that this is what I supposed to do, but it works properly.

**Comment by erogol** [comment]
Please use the issue template for the next one.
