### ISSUE TITLE
[Bug] IndexError while training new VITS LJSpeech recipe

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#1371]
## 🐛 Description

Training crashed while training the new VITS LJSpeech recipe, here is the output:

```
   --> STEP: 395/405 -- GLOBAL_STEP: 246025
     | > loss_disc: nan  (nan)
     | > loss_disc_real_0: nan  (nan)
     | > loss_disc_real_1: nan  (nan)
     | > loss_disc_real_2: nan  (nan)
     | > loss_disc_real_3: nan  (nan)
     | > loss_disc_real_4: nan  (nan)
     | > loss_disc_real_5: nan  (nan)
     | > amp_scaler: 0.00000  (0.00000)
     | > loss_0: nan  (nan)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: nan  (nan)
     | > loss_kl: nan  (nan)
     | > loss_feat: nan  (nan)
     | > loss_mel: 21.53698  (21.33673)
     | > loss_duration: nan  (nan)
     | > loss_1: nan  (nan)
     | > grad_norm_1: 0.00000  (0.07407)
     | > current_lr_0: 0.00019
     | > current_lr_1: 0.00019
     | > step_time: 0.75520  (0.56876)
     | > loader_time: 0.05890  (0.04195)

 ! Run is kept in /home/fijipants/repo/coqui-0.6.1/runs/vits_ljspeech-March-07-2022_11+31AM-0cf3265a
Traceback (most recent call last):
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 1403, in fit
    self._fit()
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 1387, in _fit
    self.train_epoch()
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 1167, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 1031, in train_step
    step_optimizer=step_optimizer,
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 888, in _optimize
    outputs, loss_dict = self._model_train_step(batch, model, criterion, optimizer_idx=optimizer_idx)
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/trainer/trainer.py", line 846, in _model_train_step
    return model.train_step(*input_args)
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/TTS/tts/models/vits.py", line 1062, in train_step
    aux_input={"d_vectors": d_vectors, "speaker_ids": speaker_ids, "language_ids": language_ids},
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/TTS/tts/models/vits.py", line 875, in forward
    outputs, attn = self.forward_mas(outputs, z_p, m_p, logs_p, x, x_mask, y_mask, g=g, lang_emb=lang_emb)
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/TTS/tts/models/vits.py", line 784, in forward_mas
    attn = maximum_path(logp, attn_mask.squeeze(1)).unsqueeze(1).detach()  # [b, 1, t, t']
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/TTS/tts/utils/helpers.py", line 177, in maximum_path
    return maximum_path_numpy(value, mask)
  File "/home/fijipants/miniconda3/envs/coqui-0.6.1/lib/python3.7/site-packages/TTS/tts/utils/helpers.py", line 234, in maximum_path_numpy
    path[index_range, index, j] = 1
IndexError: index -329 is out of bounds for axis 1 with size 328
```

### To Reproduce

- Modify the VITS LJSpeech recipe's `dataset_config` to point to your LJSpeech folder.
- Run the training with `CUDA_VISIBLE_DEVICES=0`
- Wait 246k steps and pray

### Expected behavior

It doesn't crash

### Environment

```json
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.2",
        "TTS": "0.6.1",
        "numpy": "1.21.2"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.11",
        "version": "#202202230823 SMP PREEMPT Wed Feb 23 14:53:24 UTC 2022"
    }
}
```

**Comment by arif334** [comment]
@fijipants Are you running it on the new release (0.6.1)? Or the old one? Did the model train okay before 246k? I'm just curious because I'm considering upgrading `TTS` to the new release.

**Comment by fijipants** [comment]
> @fijipants Are you running it on the new release (0.6.1)? Or the old one? Did the model train okay before 246k? I'm just curious because I'm considering upgrading `TTS` to the new release.

It's on the new release (0.6.1), and it trained pretty well before 246k but started to get very weird around 246k.

<details>
  <summary>Here's some samples</summary>

230k:

https://user-images.githubusercontent.com/88913682/158008781-bd03c25f-439a-4df3-a9db-5b2f8ee5013b.mp4

244k:

https://user-images.githubusercontent.com/88913682/158008786-3f1545cc-c169-4108-ab10-d65f84843cbe.mp4

245k:

https://user-images.githubusercontent.com/88913682/158008789-fe7cb1b0-c5fb-4110-bd2c-f0262a78b9b6.mp4

</details>

At least it's much better than the results I had for v0.5.0 (you can see them in #1309.)

I tried resuming the current training but it only got worse, and around 260k all the values became NaN and the audio became a blaringly loud noise. I've since started a new training from scratch which hopefully won't run into this issue, and if it does, I'll make another bug report.

**Comment by laduona** [comment]
I think this issue might come from the usage of "mixed_precision=True", see #918 
For my training, every time I enable it, the loss would be nan after a few hours.
Does the upgrade to 0.6.1 itself solve the issues you mentioned in #1309 ? or have you also changed characters mapping?

**Comment by erogol** [comment]
Try mixed precision False

Your amp_scaler is almost zero meaning that you get very large gradient norms frequently that might also signal that a dataset with problems.

**Comment by fijipants** [comment]
@laduona Yes, I believe the upgrade to 0.6.1 fixed #1309 for me.

@laduona @erogol Thanks, starting a run with `mixed_precision=False` now.

**Comment by erogol** [comment]
👍 closing this then

**Comment by fijipants** [comment]
To wrap this up:

The run with `mixed_precision=False` completed with no issues. Here's how it sounds:

https://user-images.githubusercontent.com/88913682/159064497-1cf28117-6d21-462d-a054-7183580a8a72.mp4

And then I did another run with `mixed_precision=True` and it also completed with no issues. I guess the `IndexError` was just bad luck. Here's how it sounds:

https://user-images.githubusercontent.com/88913682/159064620-23e4a469-95de-45d7-b1ce-a9137f39f795.mp4

**Comment by e0xextazy** [comment]
> To wrap this up:

How did you get rid of the background noise in the navy-400k-fp32.mp4 example? Because the navy-400k.mp4 example has it
