### ISSUE TITLE
[Bug] RuntimeError: Error(s) in loading state_dict for Vits:

### ISSUE THREAD

**Issue by Lizh-TW** [coqui-ai/TTS#1381]
## 🐛 Description
Update to new version, get the error and I never get this on old version.
![image](https://user-images.githubusercontent.com/58511222/158055281-98e58541-b78c-47ba-aa15-3678c4d99847.png)

 and I test official "tts_models--zh-CN--baker--tacotron2-DDC-GST" then get this. 
https://drive.google.com/file/d/1Wt_DoyTOOS5KLFtMHZd6CbQ2cxzKj5--/view?usp=sharing

### Environment

- 🐸TTS Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- Any other relevant information:

**Comment by WeberJulian** [comment]
Here is the PR: https://github.com/coqui-ai/TTS/pull/1399

**Comment by erogol** [comment]
I close this, reopen if the issue still exists

**Comment by Lizh-TW** [comment]
@erogol Hi It’s been a while. I think this problem is still exists... 
![image](https://user-images.githubusercontent.com/58511222/168445934-8949d5f9-02bb-4ca2-80a0-f102088f5443.png)
![image](https://user-images.githubusercontent.com/58511222/168445947-74700e94-0696-4d27-b430-6303dfbc9e03.png)

**Comment by erogol** [comment]
what is your 🐸TTS version ?

**Comment by Lizh-TW** [comment]
@erogol model trained at 0.5.0, I test in new version
