### ISSUE TITLE
[Bug] Speedy Speech Doesn't Work with Multi Speaker Models

### ISSUE THREAD

**Issue by stanleyshly** [coqui-ai/TTS#1388]
When training Speedy Speech on any multispeaker model, I get this error:
 `RuntimeError: Calculated padded input size per channel: (20). Kernel size: (25). Kernel size can't be greater than actual input size
`
However, when training on ljspeech, I do not get this error, with the same settings besides a switch of dataset.

**Comment by WeberJulian** [comment]
Hey, I just did a few epoch of the receipe vctk/speedy_speech and it works fine (it's a mutlispeaker reicepe).
Could you please share more details about you config, dataset and env?

**Comment by arif334** [comment]
@stanleyshly You probably have some samples that are too small for `Speedy Speech`. Have a look at [this](https://github.com/coqui-ai/TTS/discussions/1141) discussion.

**Comment by erogol** [comment]
@WeberJulian maybe we can pad samples that are shorter in ```format_batch``` for SS. It is a very commonly occurring problem.
