### ISSUE TITLE
Image and Audio not showing on Tensorboard

### ISSUE THREAD

**Issue by brianadit24** [coqui-ai/TTS#1401]
### Discussed in https://github.com/coqui-ai/TTS/discussions/1360

<div type='discussions-op-text'>

<sup>Originally posted by **brianadit24** March  9, 2022</sup>
![image](https://user-images.githubusercontent.com/26762668/157387519-6d3e03c6-cf7e-4b4e-974b-260eefe9664b.png)
![image](https://user-images.githubusercontent.com/26762668/157387665-3eeb55b4-2700-4247-a528-7306bbb58e7d.png)

How i can do to solve this problem?</div>

**Comment by erogol** [comment]
Please use the issue template if you are filing an issue.
