### ISSUE TITLE
[Bug] ValueError: No phonemizer found for language de.

### ISSUE THREAD

**Issue by gizmo84** [coqui-ai/TTS#1408]
## 🐛 Description

```
ValueError: No phonemizer found for language de.
    raise ValueError(
  File "/usr/local/lib/python3.9/site-packages/TTS/tts/utils/text/tokenizer.py", line 195, in init_from_config
  File "/usr/local/lib/python3.9/site-packages/TTS/tts/models/tacotron2.py", line 356, in init_from_config
    tokenizer, new_config = TTSTokenizer.init_from_config(config)
    model = MyModel.init_from_config(config, samples)
  File "/usr/local/lib/python3.9/site-packages/TTS/tts/models/__init__.py", line 13, in setup_model
    self.tts_model = setup_tts_model(config=self.tts_config)
  File "/usr/local/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 113, in _load_tts
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/usr/local/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 76, in __init__
    synthesizer = Synthesizer(
  File "/app/worker.py", line 30, in tts
    result = await task
  File "/usr/local/lib/python3.9/site-packages/arq/worker.py", line 525, in run_job
Traceback (most recent call last):
The above exception was the direct cause of the following exception:
KeyError: 'de'
    DEF_LANG_TO_PHONEMIZER[config.phoneme_language], **phonemizer_kwargs
  File "/usr/local/lib/python3.9/site-packages/TTS/tts/utils/text/tokenizer.py", line 192, in init_from_config
                        You may need to install a third party library for this language.
```

I think the "tts_models/de/thorsten/tacotron2-DCA" Model is configured with "de" but gruut-de provide the language as "de-de"

### To Reproduce

```python
from TTS.utils.manage import ModelManager
from TTS.utils.synthesizer import Synthesizer

manager = ModelManager()
model_path, model_config_path, model_item = manager.download_model("tts_models/de/thorsten/tacotron2-DCA")
vocoder_model = model_item.get("default_vocoder")
vocoder_path, vocoder_config_path, _ = manager.download_model(vocoder_model)

synthesizer = Synthesizer(
    tts_checkpoint=model_path,
    tts_config_path=model_config_path,
    vocoder_checkpoint=vocoder_path,
    vocoder_config=vocoder_config_path
)

wav = synthesizer.tts(text)
```

### Expected behavior

No Exception :)

### Environment

{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.9.10",
        "version": "#1 SMP Debian 4.19.132-1 (2020-07-24)"
    }
}

**Comment by gizmo84** [comment]
Ping @thorstenMueller :)

**Comment by erogol** [comment]
```
apt install espeak
```

**Comment by manojubhatia** [comment]
> ```
> apt install espeak
> ```

Hi, I am warming up to this repo. Had the same issue here, and After installing espeak, the problem is gone. But the voice that gets loaded has a clinging sound. Am I doing something wrong, or is this the quality of the model? The voice does match @thorstenMueller though, but the quality is not very appealing. Is it my setup?

**Comment by gizmo84** [comment]
@erogol sorry but I have to ask again. With TTS 0.3.1 I didn't had the espeak dependency anymore because gruut was doing the same job. Now espeak is required again. In https://github.com/coqui-ai/TTS/discussions/492 there was a talk about licensing problems and therefore gruut was introduced. Could you please provide clarification on this ?
