### ISSUE TITLE
[Bug] New VITS pretrained model mispronounces some sounds

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#1417]
## 🐛 Description

The new pretrained LJSpeech VITS model mispronounces some sounds.

Here is a comparison between three models:

[GOOD] The pretrained v0.2.0 model:

https://user-images.githubusercontent.com/88913682/158923247-1ab12feb-6ec4-4e26-95f0-5bc177064455.mp4

[GOOD] My v0.6.1 model trained with the VITS LJSpeech recipe:

https://user-images.githubusercontent.com/88913682/158923365-d52cbf6e-e736-48e1-a08e-c8be11d3fb33.mp4

[BAD] The pretrained v0.6.1 model:

https://user-images.githubusercontent.com/88913682/158923354-240af5b3-941b-4ab5-825f-856c745fd3fb.mp4

As you can see, it mispronounces some sounds that the other models don't.

```
@1s me -> mey
@4s graduated top -> gradshuated tip
@6s navy seals -> navy sulls
@12s: hundred -> hundreed
@16s: top sniper -> tip sniper
```

### To Reproduce

```bash
tts \
  --model_name tts_models/en/ljspeech/vits \
  --text "What the heck did you just hecking say about me, you little witch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire U.S. armed forces." \
  --out_path output.wav \
```

### Expected behavior

It does not mispronounce sounds.

### Environment

```json
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.11",
        "version": "#202202230823 SMP PREEMPT Wed Feb 23 14:53:24 UTC 2022"
    }
}
```

**Comment by fijipants** [comment]
I think I figured out the issue. When `espeak` and `espeak-ng` are installed, the pretrained model sounds perfect:

https://user-images.githubusercontent.com/88913682/159060883-a6302b30-8a6f-4b56-afc1-94006d17448e.mp4

but when they aren't installed, it sounds bad. (See issue for example.)

Conversely, when `espeak` and `espeak-ng` are installed, my own model sounds awful:

https://user-images.githubusercontent.com/88913682/159060891-0fe1bc82-7dc0-4def-81ca-2ee8dcd827ba.mp4

@erogol Could you confirm that having `espeak` installed can change the result of inferences?

**Comment by Edresson** [comment]
@fijipants   yeah, you are right. I debugged in my side as well.  This issue is related to #1420 . To fix this we need to provide the "phonemizer" parameter in the config.json.  @erogol   I think that we need to edit the config.json and added "phonemizer": "espeak" . It will force the user to install the espeak or espeak-ng if the model was trained with this backend.
