### ISSUE TITLE
[Feature request] Set phoneme backend explicitly.

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#1420]
**🚀 Feature Description**

Right now we select the phoneme backend based on the language code as implemented in TTS/tts/utils/text/phonemizers/__init__.py

However, to make sure that we get the same output from a model, it is better to be able to explicitly define the backend.

**Comment by Edresson** [comment]
This feature is already implemented :). We can set the Phonemizer in the config using the parameter "phonemizer". The selection of the phonemizer backend based on the language is used only when config.phonemizer is "None" or not defined, the code can be checked [here](https://github.com/coqui-ai/TTS/blob/0cf3265a4686d7e856bd472cdaf1572d61cab2b8/TTS/tts/utils/text/tokenizer.py#L187).
