### ISSUE TITLE
[Bug] eval_split_size in recipe and config.json don't match up

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#1423]
## 🐛 Description

**Preface:** I'm not sure if this is expected behaviour or not, I'm just guessing here.

**Scenario 1:**

Let's say I want to run a training with a custom `eval_split_size`. I see that `eval_split_size` is in BaseTTSConfig, so I modify this line:

https://github.com/coqui-ai/TTS/blob/0cf3265a4686d7e856bd472cdaf1572d61cab2b8/recipes/ljspeech/vits_tts/train_vits.py#L34

to this:

```python
config = VitsConfig(eval_split_size=0.05,
```

Result: The `eval_split_size` does not get set properly. (It's set to 0.01 instead over [here](https://github.com/coqui-ai/TTS/blob/0cf3265a4686d7e856bd472cdaf1572d61cab2b8/recipes/ljspeech/vits_tts/train_vits.py#L72) instead.)

**Scenario 2:**

Let's say I want to run a training with a custom `eval_split_size`, and I know that editing the base config won't work. Instead I modify this line:

https://github.com/coqui-ai/TTS/blob/0cf3265a4686d7e856bd472cdaf1572d61cab2b8/recipes/ljspeech/vits_tts/train_vits.py#L72

To this:

```python
train_samples, eval_samples = load_tts_samples(dataset_config, eval_split=True, eval_split_size=0.05)
```

Result: Although it works, the outputted `config.json` has the wrong `eval_split_size`:

```json
    "eval_split_size": 0.01,
```

**Scenario 3:**

Let's say I completed a training with a custom `eval_split_size`, and now I want to change the `eval_split_size` and continue it, so I open up the outputted `config.json` and change this line:

```json
    "eval_split_size": 0.01,
```

To this:

```json
    "eval_split_size": 0.07,
```

Then I start the training with `--continue_path`.

Result: It uses whichever `eval_split_size` is set on [this line](https://github.com/coqui-ai/TTS/blob/0cf3265a4686d7e856bd472cdaf1572d61cab2b8/recipes/ljspeech/vits_tts/train_vits.py#L72), instead of the one from `config.json`.

### To Reproduce

See description.

### Expected behavior

1. I should be able to set it with `config = VitsConfig(eval_split_size=0.05,`.
2. If that's not possible, then when I set it with `load_tts_samples(..., eval_split_size=0.05)`, I'd like it to be outputted to the `config.json`.
3. When I continue a run, it should re-use the `eval_split_size` from the `config.json`.

### Environment

```json
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.11",
        "version": "#202202230823 SMP PREEMPT Wed Feb 23 14:53:24 UTC 2022"
    }
}
```

**Comment by Edresson** [comment]
@fijipants  Thanks for report the bug. Indeed in #1251 we forget to change it for all the recipes. The PR #1424 will fix it :).
