### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by Donkey-Doug** [coqui-ai/TTS#1428]
Please release a TTS app for android.

**Comment by realpixelcode** [comment]
It would be very useful for ungoogled Android versions like [/e/ OS](https://e.foundation) though 🙂

**Comment by csukuangfj** [comment]
Please see
https://github.com/coqui-ai/TTS/discussions/3194

You can use [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx) to run VITS models from Coqui on Android.


We have pre-built Android APKs for the VITS English models from Coqui.
https://k2-fsa.github.io/sherpa/onnx/tts/apk.html

![image](https://github.com/coqui-ai/TTS/assets/5284924/56b2ec37-27de-40c0-8dd4-8245ae2ac8be)

**Comment by erogol** [comment]
@csukuangfj maybe you can post also to https://github.com/coqui-ai/TTS/discussions/2602
