### ISSUE TITLE
[Bug] Tensorboardx dependency is unused

### ISSUE THREAD

**Issue by mweinelt** [coqui-ai/TTS#1433]
## 🐛 Description

A maintainer over on nixpkgs noticed that while TTS requires tensorboardx in its requirements.txt it doesn't actually use it. Can it be dropped?

https://github.com/coqui-ai/TTS/blob/0cf3265a4686d7e856bd472cdaf1572d61cab2b8/requirements.txt#L24
https://github.com/coqui-ai/TTS/search?q=tensorboardX

### To Reproduce

n/a

### Expected behavior

Unused dependencies should be removed.

### Environment

- 🐸TTS Version (e.g., 1.3.0): 0.6.1
- PyTorch Version (e.g., 1.8) 1.11.0
- Python version: 3.9
- OS (e.g., Linux): NixOS
- CUDA/cuDNN version: n/a
- GPU models and configuration: n/a
- How you installed PyTorch (`conda`, `pip`, source): n/a
- Any other relevant information:

**Comment by erogol** [comment]
we can drop it as it went to the trainer
