### ISSUE TITLE
[Bug] 'blank' argument error

### ISSUE THREAD

**Issue by shad94** [coqui-ai/TTS#1450]
### To Reproduce
Hi! I am trying to run the GlowTTS recipe on Colab, using train_glowtts.py. 
I am using v. 0.3.1, as it should be suffient to do so.

`!git clone -b v0.3.1 https://github.com/coqui-ai/TTS.git`

They were some files missing for this version, I took them from the latest one (0.6.1), mostly on 'text' and 'phonemizers' part.

I use GPU on Colab.

I also installed requirements:

`!pip3 install -r requirements.txt`
and upgraded **numpy**.

Then, I run the 
`!python3 ./setup.py develop`

and in the end, when it seems everything is ok (because Audio Processor data is showed), I see this error:
File "/content/drive/MyDrive/inzynierka/training/train_glowtts.py", line 57, in <module>
tokenizer, config = TTSTokenizer.init_from_config(config)
File "/content/TTS/TTS/tts/utils/text/tokenizer.py", line 171, in init_from_config
characters, new_config = IPAPhonemes().init_from_config(config)
File "/content/TTS/TTS/tts/utils/text/characters.py", line 389, in init_from_config
new_config = replace(config, characters=characters.to_config())
File "/content/TTS/TTS/tts/utils/text/characters.py", line 311, in to_config
is_sorted=self.is_sorted,
TypeError: init() got an unexpected keyword argument 'blank'

I checked the function: https://github.com/coqui-ai/TTS/blob/main/TTS/tts/utils/text/characters.py
![image](https://user-images.githubusercontent.com/31577720/160276048-1106809a-e363-4b59-b26e-2d92a3fda541.png)

### Expected behavior

The training is running.

### Environment

- 🐸TTS Version (0.3.1):
- Colab (free)

### Additional context

I also tried with 0.6.1 version and it was giving other unexpected errors.

**Comment by lexkoro** [comment]
`They were some files missing for this version, I took them from the latest one (0.6.1), mostly on 'text' and 'phonemizers' part.`

Mixing releases and randomly adding files from different releases is a very bad idea and will most likely lead to unexpected  errors as seen above. 

I think you should use the latest release (0.6.1) and post the `unexpected errors` you got there.

**Comment by shad94** [comment]
I just dug further- it seems that in 'shared_configs.py' (TTS->tts->configs) this part:
![image](https://user-images.githubusercontent.com/31577720/160278001-1b17d7a5-4224-465e-8837-c804fd90fb79.png)
in CharactersConfig was missing (as I wrote it).
I will check upon that in colab.

**Comment by shad94** [comment]
@lexkoro, 5 months ago it was working perfectly fine on version 0.3.1. Was the version in a meantime stripped of files? Does not sound nice :/

**Comment by lexkoro** [comment]
I just tested 0.3.1 on colab and it works without problems.

```
File "/content/drive/MyDrive/inzynierka/training/train_glowtts.py", line 57, in
tokenizer, config = TTSTokenizer.init_from_config(config)
File "/content/TTS/TTS/tts/utils/text/tokenizer.py", line 171, in init_from_config
characters, new_config = IPAPhonemes().init_from_config(config)
File "/content/TTS/TTS/tts/utils/text/characters.py", line 389, in init_from_config
new_config = replace(config, characters=characters.to_config())
File "/content/TTS/TTS/tts/utils/text/characters.py", line 311, in to_config
is_sorted=self.is_sorted,
TypeError: init() got an unexpected keyword argument 'blank'
```
It seems like you are using the train_glowtts.py recipe from 0.6.1? Use the train_glowtts.py recipe from 0.3.1 and it will work.
But don't mix stuff from different versions.

**Comment by shad94** [comment]
Can 'mailabs' be used under 'ljspeech' recipes? 
I'm asking because I'm still receiving a lot of errors.

**Comment by shad94** [comment]
Alright, it keeps asking me for 'missing' files:
![image](https://user-images.githubusercontent.com/31577720/160304723-33f6a703-2d4e-4663-b499-eeccf032406a.png)

I am using 'pl' phonemes set.
Moreover, this 'phonemizers' file is called in TTS/tts/utils/__init__.py.

I am getting little bit confused- or should I write my own phonemizer to run the training? (eSpeak supports Polish)

**Comment by erogol** [comment]
Install the latest version from scratch. It looks like you just C&P the recipe from v0.6.1
