### ISSUE TITLE
[Bug] strange output when a period is excluded

### ISSUE THREAD

**Issue by meonkeys** [coqui-ai/TTS#1466]
## 🐛 Description

Synthesizing "No." sounds alarmingly different than "No" (without a period). Sound clips:

* links to both samples: https://gitter.im/coqui-ai/TTS?at=62478c959bd1c71ecacfa6e2 (play in browser from gitter)
* play "No." sample: `curl --output - https://gitter.ems.host/_matrix/media/v1/download/matrix.org/XkiSqLxxTQOlkDqiLlRDLcdu | aplay`
* play "No" sample: `curl --output - https://gitter.ems.host/_matrix/media/v1/download/matrix.org/OpWHHNCcYtbpFCIDYsuxyhWm | aplay`

### To Reproduce

1. Build a coqui tts server with the Dockerfile at the end of this bug report description.
2. Stand up a server and translate "No.". Sounds great.
3. Stand up a server and translate "No" (without a period). Sounds... very unexpected.

### Expected behavior

Both sound like the word "No".

### Environment

- 🐸TTS Version (e.g., 1.3.0): v0.6.1
- PyTorch Version (e.g., 1.8): 1.11.0+cu102
- Python version: 3.8.10
- OS (e.g., Linux): 64-bit Ubuntu GNU/Linux server, kernel 5.4.0-105-generic
- CUDA/cuDNN version: n/a
- GPU models and configuration: n/a
- How you installed PyTorch (`conda`, `pip`, source): 
- Any other relevant information: running in Docker

### Additional context

Model: `tts_models/en/ljspeech/tacotron2-DDC`

Dockerfile follows. Note, this Dockerfile is derived from https://github.com/coqui-ai/TTS/discussions/978 -- credit to @AndrewBarfield .

```
FROM ubuntu:20.04

LABEL maintainer="Andrew Barfield <barfield2256@gmail.com>"

ARG NB_USER="coqui" NB_UID="1377" NB_GROUP="coqui" NB_GID="1377"

USER root

ENV DEBIAN_FRONTEND=noninteractive \
    TERM=xterm \
    TZ=America/Los_Angeles

RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends \
        sudo git make locales apt-utils g++ libsndfile1-dev && \
    apt-get -yqq clean autoclean && \
    apt-get -yqq autoremove --purge && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

ENV SHELL=/bin/bash \
    NB_USER="${NB_USER}" \
    NB_UID=${NB_UID} \
    NB_GID=${NB_GID} \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    PATH="/home/${NB_USER}/.local/bin:${PATH}" \
    HOME="/home/${NB_USER}"

RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc && \
    echo "auth requisite pam_deny.so" >> /etc/pam.d/su && \
    sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers && \
    sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers && \
    groupadd -g "${NB_GID}" "${NB_GROUP}" && \
    useradd -l -m -s /bin/bash -N -g "${NB_GID}" -u "${NB_UID}" "${NB_USER}" && \
    chmod g+w /etc/passwd && \
    chown -R "${NB_UID}":"${NB_GID}" "${HOME}" && \
    cd "${HOME}" && \
    apt-get install -yqq --no-install-recommends python3-dev python3-pip && \
    git clone https://github.com/coqui-ai/TTS/ && \
    cd TTS && \
    git checkout v0.6.1 && \
    make system-deps && \
    make install && \
    cd "${HOME}" && \
    apt-get -yqq remove --purge git make g++ apt-utils && \    
    apt-get -yqq autoclean && \
    apt-get -yqq autoremove --purge && \
    apt-get -yqq purge $(dpkg --get-selections | grep deinstall | sed s/deinstall//g) && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/cache/* /var/tmp/* "${HOME}/TTS/*"

USER ${NB_UID}:${NB_GID}

EXPOSE 5002

ENV PYTHONPATH="$HOME/TTS"

CMD ["tts-server", "--use_cuda=false"]
```

**Comment by meonkeys** [comment]
Aha: https://github.com/coqui-ai/TTS/issues/484

So maybe this is a dup?

**Comment by AndrewBarfield** [comment]
See: https://github.com/coqui-ai/TTS/discussions/978#discussioncomment-2489224 for 'fix-permissions'.

**Comment by meonkeys** [comment]
> See: [#978 (reply in thread)](https://github.com/coqui-ai/TTS/discussions/978#discussioncomment-2489224) for 'fix-permissions'.

I don't think this is relevant here.

**Comment by meonkeys** [comment]
Closing. Very likely dup of #484
