### ISSUE TITLE
[Bug] VITS model needs its own AudioConfig class

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#1474]
## 🐛 Description
Some of the fields in BaseAudioConfig are not used in VITS models and it is misleading.

This was also the reason for our silence issues when training our latest VITS models @Edresson 

### To Reproduce
You can set for instance silence trimming True but it would not work since VITS uses a custom load_audio function without 
silence trimming. 

### Expected behavior
I've 3 solutions

1. VITSAudioConfig
2. Raise an error when a field in BaseAudioConfig is not being used  (probably harder )
3. Find a smart way to override AudioProcessor instead of writing custom standalone functions.

**Comment by e0xextazy** [comment]
Has this problem been solved?
