### ISSUE TITLE
Where to find/download Judy Wave1 ?

### ISSUE THREAD

**Issue by CryptoCashCashoo** [coqui-ai/TTS#1481]
Where can download Judy Wave 1? (The main page says is made by Coqui-ai / TTS )

Also, what liscenses are applied to the .wav produced by the program? Can I for example, make a film with that sound and commercialize it? Do I need to cite TTS? The Algotithm used?

Thanks a lot, your repository is just amaizing!

**Comment by erogol** [comment]
Judy was an internal dataset, unfortunately. As it is not granted by the voice talent, we cannot release it.

**Comment by da3dsoul** [comment]
Can you put this in a FAQ? It was kind of hard to find this
