### ISSUE TITLE
[Bug]wandb logger broken

### ISSUE THREAD

**Issue by a-froghyar** [coqui-ai/TTS#1486]
## 🐛 Description

Setting `dashboard_logger='wandb'` in a config file produces the following error:

```
TypeError: Can't instantiate abstract class WandbLogger with abstract methods add_audio, add_figure, add_scalar
```

## Environment

Current `main` branch.

**Comment by AyushExel** [comment]
@a-froghyar It seems like the dashboard logger module was removed. @erogol Can you elaborate here? Thanks!

**Comment by AyushExel** [comment]
It looks like the trainer module was moved here - https://github.com/coqui-ai/Trainer/tree/main/trainer .
It contains all the logger utils. You probably want to use this trainer.

**Comment by erogol** [comment]
wandb logger is missing some of the concrete implementations.

**Comment by AyushExel** [comment]
@erogol could you elaborate? I'd be happy to add the missing features

**Comment by erogol** [comment]
hey @AyushExel, the error message above explains the situation enough I guess. But let me known if you need more info.

**Comment by AyushExel** [comment]
@erogol thanks..yeah I see now that some of the abstract functions have been added. I'll put up a PR implementing those. 
One more question - I think the logger is broken in more ways. I see the base logger uses step as a hard parameter and wandblogger doesn't take step param. I think that'll need to be fixed as well right?

**Comment by erogol** [comment]
@AyushExel there is no testing for now unfortunately.
