### ISSUE TITLE
[Bug] It has problem for run train_vits_tts.py

### ISSUE THREAD

**Issue by kampores** [coqui-ai/TTS#1493]
## 🐛 Description
It looks like the parameter for Vits is wrong. TTS/recipes/multilingual/vits_tts/train_vits_tts.py, line 121.
    model = Vits(config, speaker_manager, language_manager)
Vits requires 5 parameters.
at TTS/TTS/tts/models/vits.py, line 539
    def __init__(
        self,
        config: Coqpit,
        ap: "AudioProcessor" = None,
        tokenizer: "TTSTokenizer" = None,
        speaker_manager: SpeakerManager = None,
        language_manager: LanguageManager = None,
    ):
So I added ap and tokenizer, but it doesn't work. Please correct it.

### To Reproduce

1. Run the following command '...'
2. python train_vits_tts.py
3. ...
5. Traceback (most recent call last):
...
 | > Found 34189 files in /data/voice/open/m-ailabs/uk_UK
  File "/home/yskim2/PycharmProjects/TTS/recipes/multilingual/vits_tts/train_vits_tts.py", line 121, in <module>
    model = Vits(config, speaker_manager, language_manager)
  File "/home/yskim2/PycharmProjects/TTS/TTS/tts/models/vits.py", line 548, in __init__
    super().__init__(config, ap, tokenizer, speaker_manager, language_manager)
  File "/home/yskim2/PycharmProjects/TTS/TTS/tts/models/base_tts.py", line 42, in __init__
    self._set_model_args(config)
  File "/home/yskim2/PycharmProjects/TTS/TTS/tts/models/base_tts.py", line 61, in _set_model_args
    num_chars = config_num_chars if self.tokenizer is None else self.tokenizer.characters.num_chars
AttributeError: 'LanguageManager' object has no attribute 'characters'

Process finished with exit code 1

### Environment

> 

{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060"
        ],
        "available": true,
        "version": "11.5"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu115",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022"
    }
}
> 

- 🐸TTS Version (e.g., 1.3.0): 0.6.1 main
- PyTorch Version (e.g., 1.8) : 1.11.0+cu115
- Python version: 3.8.10
- OS (e.g., Linux): ubuntu 20.04
- CUDA/cuDNN version: 11.5/8.3.3
- GPU models and configuration: rtx3060 / 510.54
- How you installed PyTorch (`conda`, `pip`, source): pip
- Any other relevant information:

**Comment by p0p4k** [comment]
Can you paste your config file? It helps for better debugging.
