### ISSUE TITLE
[Bug]  --list_speaker_idxs flag return  'NoneType' object has no attribute 'speaker_ids'

### ISSUE THREAD

**Issue by BattashB** [coqui-ai/TTS#1495]
## 🐛 Description

I'm using this repo just for inference, hence this entire repo is only about inference.
I'm running the following command:
` tts   --model_name tts_models/en/ljspeech/glow-tts --vocoder_name vocoder_models/en/ek1/wavegrad --list_speaker_idxs`
In order to see the least of speakers available, just as in the documentation, but I'm getting:
 > Available speaker ids: (Set --speaker_idx flag to one of these values to use the multi-speaker model.
Traceback (most recent call last):
  File "/opt/conda/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/TTS/bin/synthesize.py", line 264, in main
    print(synthesizer.tts_model.speaker_manager.speaker_ids)
AttributeError: 'NoneType' object has no attribute 'speaker_ids'

** Non related question: can I output a wav file with 16000Hz and not 22050Hz?? using the command line.
### Environment
The script's output.
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti"
        ],
        "available": true,
        "version": "11.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.8.1+cu111",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.5",
        "version": "#1 SMP Tue Nov 30 15:51:32 UTC 2021"
    }
}

Thanks a lot !!!

**Comment by p0p4k** [comment]
Is ljspeech multi-speaker dataset?

**Comment by erogol** [comment]
It's a single-speaker model.
