### ISSUE TITLE
[Bug] Multi speaker model inference -> error with shapes of input

### ISSUE THREAD

**Issue by BattashB** [coqui-ai/TTS#1503]
Hi, I'm trying to run a simple inference:
` tts --text "Hi User, how are you" --model_name tts_models/en/vctk/vits  --vocoder_name vocoder_models/en/vctk/hifigan_v2 --speaker_idx "p340"`

But I'm getting:
>RuntimeError: Given groups=1, weight of size [128, 80, 7], expected input[1, 20224, 11] to have 80 channels, but got 20224 channels >instead

What am I missing? 

### To Reproduce
I've installed using pip, didn't touch even one line of code.

### Environment
The script's output.
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti"
        ],
        "available": true,
        "version": "11.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.8.1+cu111",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.5",
        "version": "#1 SMP Tue Nov 30 15:51:32 UTC 2021"
    }
}

**Comment by WeberJulian** [comment]
Hey, VITS is an end to end model, it doesn't require any vocoder. Try this instead `tts --text "Hi User, how are you" --model_name tts_models/en/vctk/vits --speaker_idx "p340"`
