### ISSUE TITLE
[Bug] Multi-GPU training on v0.6.2 fails with error message, references non-existant file "TTS/bin/distribute.py"

### ISSUE THREAD

**Issue by astricks** [coqui-ai/TTS#1536]
### Describe the bug

Trying to run the multilingual recipe on 2 GPUs on version 0.6.2, my command fails with the following message.

> CUDA_VISIBLE_DEVICES="0,1" python recipes/multilingual/vits_tts/train_vits_tts.py

> RuntimeError:  [!] 2 active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`.

### To Reproduce

1. Run the following command
> CUDA_VISIBLE_DEVICES="0" python recipes/multilingual/vits_tts/train_vits_tts.py
2. See error.

### Expected behavior

Command should not fail and reference a non-existent distribute.py file.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0",
        "TTS": "0.6.2",
        "numpy": "1.21.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.13",
        "version": "#121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022"
    }
}
```

**Comment by p0p4k** [comment]
Did you try using a single GPU and train.py file? 
The distribute.py file is [here](https://github.com/coqui-ai/TTS/blob/main/TTS/utils/distribute.py).

**Comment by dmizelle** [comment]
> Did you try using a single GPU and train.py file? The distribute.py file is [here](https://github.com/coqui-ai/TTS/blob/main/TTS/utils/distribute.py).

This is not correct. Documentation states that this is supposed to in `bin`, not `utils`.  This script was removed and moved to `trainer.distribute`.

@astricks -- please try ```python3 -m trainer.distribute --gpus "0,1" --script recipes/multilingual/vits_tts/train_vits_tts.py --continue_path denoised/run-April-29-2022_10+34PM-0000000```

**Comment by astricks** [comment]
@dmizelle thank you, that works.

**Comment by astricks** [comment]
Put up a PR to fix the documentation : https://github.com/coqui-ai/TTS/pull/1558
