### ISSUE TITLE
VITS LJspeech Model Contribution

### ISSUE THREAD

**Issue by mueller91** [coqui-ai/TTS#1549]
Dear all,
please find attached my VITS LJSpeech model, trained with default configurations to 300k steps, which took me about 4 days on an A100 GPU.
Hoping you find it useful.
https://drive.google.com/file/d/1gn9H9XlemBVRH8NfGZG6WkBG2WYtP_C1/view?usp=sharing

![image](https://user-images.githubusercontent.com/9288660/166222697-fba00e21-9ee1-4a0e-b779-8155c3dff4ac.png)

**Comment by erogol** [comment]
Hey Mueller, thanks for sharing your work!! 
Just curious, have you made any comparison against the current VITS LJSpeech model in our model zoo?

**Comment by mueller91** [comment]
I did not know you released a VITS LJspeech model!
I didn't find it here (1) so I trained my own.

(1)
https://github.com/coqui-ai/TTS/wiki/Experimental-Released-Models

**Comment by erogol** [comment]
Those are legacy models.

This might help https://tts.readthedocs.io/en/latest/inference.html

**Comment by mueller91** [comment]
awesome, thank you.

**Comment by ikcla** [comment]
> 

hi mueller91, Can you share your loss_mel and loss_feat? It would be helpful for me. Thanks
