### ISSUE TITLE
[Bug] ValueError: Phonemizer is not defined in the TTS config.

### ISSUE THREAD

**Issue by EurekaTesla** [coqui-ai/TTS#1577]
### Describe the bug

ValueError: Phonemizer is not defined in the TTS config.

### To Reproduce

run
 `python TTS/server/server.py --model_name tts_models/en/ljspeech/tacotron2-DCA --vocoder_name vocoder_models/en/ljspeech/multiband-melgan` 

show:
> tts_models/en/ljspeech/tacotron2-DCA is already downloaded.
 > vocoder_models/en/ljspeech/multiband-melgan is already downloaded.
Traceback (most recent call last):
  File "TTS/server/server.py", line 111, in <module>
    use_cuda=args.use_cuda,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/TTS/utils/synthesizer.py", line 76, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/TTS/utils/synthesizer.py", line 113, in _load_tts
    raise ValueError("Phonemizer is not defined in the TTS config.")
ValueError: Phonemizer is not defined in the TTS config.

It's OK when running `python TTS/server/server.py`

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3070"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.0+cu113",
        "TTS": "0.6.2",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.10",
        "version": "#86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021"
    }
}
```

**Comment by WeberJulian** [comment]
Hey, I can't reproduce your issue but I suspect this is an issue with your cache being incompatible with the most recent TTS.

I would suggest running `rm -rf ~/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/` and trying again.

**Comment by EurekaTesla** [comment]
> Hey, I can't reproduce your issue but I suspect this is an issue with your cache being incompatible with the most recent TTS.
> 
> I would suggest running `rm -rf ~/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/` and trying again.

thanks!
