### ISSUE TITLE
KeyError while using the (multilingual) your_tts model

### ISSUE THREAD

**Issue by besacier** [coqui-ai/TTS#1582]
### Describe the bug

hi

i get a KeyError while using the (multilingual) your_tts model

### To Reproduce

running the following command
tts --text "text is here" --out_path test-multilingual.wav --model_name "tts_models/multilingual/multi-dataset/your_tts"  --speaker_idx 1
(speaker ids were obtained using the command  tts --model_name "tts_models/multilingual/multi-dataset/your_tts"  --list_speaker_idxs )

here is the error i get
Traceback (most recent call last):
  File "/home/lbesacie/COQUI/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/home/lbesacie/COQUI/TTS/TTS/bin/synthesize.py", line 305, in main
    wav = synthesizer.tts(
  File "/home/lbesacie/COQUI/TTS/TTS/utils/synthesizer.py", line 219, in tts
    speaker_embedding = self.tts_model.speaker_manager.get_mean_embedding(
  File "/home/lbesacie/COQUI/TTS/TTS/tts/utils/managers.py", line 192, in get_mean_embedding
    embeddings = self.get_embeddings_by_name(idx)
  File "/home/lbesacie/COQUI/TTS/TTS/tts/utils/managers.py", line 165, in get_embeddings_by_name
    return self.embeddings_by_names[idx]
KeyError: '1'

### Expected behavior

expected behavior should be a wav file created

### Environment

```shell
COQUI) python TTS/bin/collect_env_info.py
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.4",
        "version": "#1 SMP Tue Feb 4 23:02:59 UTC 2020"
    }
}
```

**Comment by p0p4k** [comment]
Try this: 
`tts --text "text is here" --out_path output.wav --model_name "tts_models/multilingual/multi-dataset/your_tts" --speaker_idx female-en-5 --language_idx en `
speaker_idx takes 'key' as input from the following dictionary :
`{'female-en-5': 0, 'female-en-5\n': 1, 'female-pt-4\n': 2, 'male-en-2': 3, 'male-en-2\n': 4, 'male-pt-3\n': 5}`
language_idx takes 'key' as input from the following dictionary:
`{'en': 0, 'fr-fr': 1, 'pt-br': 2}`
You mistook the idx to be the 'item' instead of the 'key'. I know it is slightly confusing, but is a very minor inconvenience. It can be fixed later.

**Comment by besacier** [comment]
many tks it is working just fine now... my next step would be to condition this multilingual/multispeaker model on my own voice, is there a recipe/tuto for doing that please ?

**Comment by p0p4k** [comment]
Refer to https://github.com/coqui-ai/TTS/tree/dev/recipes%2Fmultilingual%2Fvits_tts

Don't be afraid to use the search bar in discussion or issues (open+closed) , before posting here. If nothing works, do post here. We will try to help as much as we can. Thanks.

**Comment by erogol** [comment]
Looks like solved
