### ISSUE TITLE
Multispeaker TTS Inference Support

### ISSUE THREAD

**Issue by Aya-AlJafari** [coqui-ai/TTS#1585]
Adding the ability to synthesize speech using TTS CLI by supplying multiple speaker waves that are out of the speaker list in which the model has trained on.

**Comment by WeberJulian** [comment]
I don't think it really make sense to have that feature on the CLI. This use case is far too specific. I think on the contrary, if you pass multiple reference file, the expected behavior would be for TTS to average the references. 

But maybe I'm wrong, what do you think @Edresson @erogol

**Comment by erogol** [comment]
I'd agree that it is too specific and to me averaging all the speaker_wavs sounds more natural than synthesizing multiple outputs.

**Comment by WeberJulian** [comment]
I'm closing the issue, but feel free to argument more if you fine use-cases for regular users :)
