### ISSUE TITLE
Adding Model List Guid

### ISSUE THREAD

**Issue by Aya-AlJafari** [coqui-ai/TTS#1586]
Adding a guide on the available model types listed under `tts --list_models`

**Comment by WeberJulian** [comment]
What kind of information would you expect in the guide?

**Comment by WeberJulian** [comment]
Ok, I see what you mean. I think you are right, we do need that kind of information. But it would make more sense to me on a model card, hosted on our website. I don't think you have room to write all this on the `tts --list_models` command, without sacrificing readability. Or maybe once you specify a model via --model_name, you can --help to get a description of that specific model.

But maybe you have something that would work in mind? What would be a good toy output of the `tts --list_models` in your opinion?

**Comment by Aya-AlJafari** [comment]
I agree, that hosting all of this information within `tts --list_models` is not a good idea. maybe just add the help availability with a reference link to the model card.

**Comment by p0p4k** [comment]
Hello, I added a straightforward model_info implementation in #1623. Please give me your feedback. Thanks.

**Comment by erogol** [comment]
I think https://github.com/coqui-ai/TTS/pull/1623 closes this
