### ISSUE TITLE
NaturalSpeech support

### ISSUE THREAD

**Issue by dtx525942103** [coqui-ai/TTS#1592]
NaturalSpeech is based on vits. NaturalSpeech: End-to-End Text to Speech Synthesis with Human-Level Quality https://arxiv.org/abs/2205.04421

**Comment by erogol** [comment]
Natural Speech is more of a finetuning regime for VITS. I am not sure it's worth the effort but if anyone is willing to give it a try, I am here for help

**Comment by ganesh-rao** [comment]
> yes, even the sound of that makes me want to breeth fire untill I fry my last braincell. As far as hunting for tts model open source implementations went, this one hasn't been implemented yet. I'm pretty sure I hunted enough, though I can always redo the process to maybe discover what little new implementations rise between the scouts. +1 @dtx525942103

@heatz123 has done it here: https://github.com/heatz123/naturalspeech

**Comment by erogol** [comment]
someone is interested in pulling it into 🐸TTS?

**Comment by ganesh-rao** [comment]
@lucidrains appears to be implementing naturalspeech2 at an incredible pace here: https://github.com/lucidrains/naturalspeech2-pytorch

Might it be worth including the model in :frog:?
