### ISSUE TITLE
[Bug] UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)

### ISSUE THREAD

**Issue by BartSar** [coqui-ai/TTS#1600]
### Describe the bug

TTS requires "numpy-1.21.6" but this time torch cries with the above error

if I upgrade numpy to 1.22.4, this time torch works but TTS cries:

``pkg_resources.DistributionNotFound: The 'numpy==1.21.6' distribution was not found and is required by TTS````

How can I fix this dilemma?

### To Reproduce

Typing

tts --list_models

in CMD window

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cpu",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 165 Stepping 2, GenuineIntel",
        "python": "3.10.4",
        "version": "10.0.22000"
    }
}
```

**Comment by AuroraBee** [comment]
I have this same problem running "tts --text "Hello, World!"

Console output:
`
C:\Users\404fr>tts --text "Hello World!"
C:\Users\404fr\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
 > tts_models/en/ljspeech/tacotron2-DDC is already downloaded.
[...]
 | > win_length:1024
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 > Text: Hello World!
 > Text splitted to sentences.
['Hello World!']
Traceback (most recent call last):
  File "C:\Users\404fr\AppData\Local\Programs\Python\Python310\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "c:\users\404fr\tts\TTS\bin\synthesize.py", line 309, in main
    wav = synthesizer.tts(
  File "c:\users\404fr\tts\TTS\utils\synthesizer.py", line 272, in tts
    outputs = synthesis(
  File "c:\users\404fr\tts\TTS\tts\utils\synthesis.py", line 217, in synthesis
    model_outputs = model_outputs[0].data.cpu().numpy()
RuntimeError: Numpy is not available`

**Comment by AuroraBee** [comment]
Au Contrairé!

The NumPy version installed upon my fresh Python 3.10.4 installation and the current main branch release of TTS is the NumPy version specified within its requirements.txt file, and is definitely and clearly: one the same, as defined in the formerly mentioned requirements file.

As you seem to have said that it is not a bug, i am inclined to believe you, yet, you leave us without proper solution.
Or rather, one that we have already attempted.

FRUITLESS, was this endeavour, as though we had just spoken to a wall.

So please, look a bit deeper into this, as your closure really didnt help.

**Comment by Nicholas-Ho** [comment]
Hey, I'm also facing this issue! Already have numpy=1.21.6 installed in a conda environment as per requirements.txt.

According to https://stackoverflow.com/questions/49756080/opencv-numpy-issue-module-compiled-against-api-version-x-but-this-version-of-n is it seems like something somewhere (torch maybe?) is expecting numpy v1.22.x, but numba is expecting v1.21.x and below.

@erogol Which is the right numpy version?

**Comment by wasertech** [comment]
It may not be a bug but it's an issue. We should keep track of it.
```
❯ tts --text "This is a wonderful day, and I think I'm going to celebrate with a cookie" --model_name tts_models/en/vctk/vits --speaker_idx p335
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/home/waser/.local/bin/tts", line 5, in <module>
    from TTS.bin.synthesize import main
  File "/home/waser/.local/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/waser/.local/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/waser/.local/lib/python3.10/site-packages/TTS/utils/audio.py", line 3, in <module>
    import librosa
  File "/home/waser/.local/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/waser/.local/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/waser/.local/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/waser/.local/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/waser/.local/lib/python3.10/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/waser/.local/lib/python3.10/site-packages/librosa/util/utils.py", line 6, in <module>
    import scipy.ndimage
  File "/usr/lib/python3.10/site-packages/scipy/ndimage/__init__.py", line 151, in <module>
    from ._filters import *  # noqa: F401 F403
  File "/usr/lib/python3.10/site-packages/scipy/ndimage/_filters.py", line 37, in <module>
    from . import _nd_image
ImportError: numpy.core.multiarray failed to import
```
Using venv with python 3.10.5.

TTS v0.7.1 needs (according to `requirements.txt`):

- numba==0.55.1
- numpy==1.21.6

Numba needs numpy >=1.11, <=1.18 (according to it's `setup.py`)

See the issue? `[Numba]numpy==1.18 < [TTS]numpy==1.21.6`

**Comment by wasertech** [comment]
Wait, no numba on py310 has numpy requirement of:
`Requirement: numpy<1.23,>=1.18 in /home/waser/Projets/Données/TTS/venv-tts/lib/python3.10/site-packages (from numba) (1.21.6)`
So 1.21.6 should work perfectly, yet here we are...

**Comment by tmfksoft** [comment]
Any luck with this?
I'm running into the same issue. I've got very little experience with Python.
I've tried to upgrade to NumPy 1.22 (0xf) but numba complains and back and forth.

Really would like to solve this without messing with venv etc.

**Comment by AuroraBee** [comment]
I completely forgot this issue exists.

The problem seems to be fixed on my end, and i cannot reproduce it anymore.
However, i didn't change anything except update to a newer version of
python, perhaps you could try that?

**Comment by tmfksoft** [comment]
Yeah, I poked around and was able to find when using Python 3.120 numba allowed a newer version of numpy.
Running Python 3.10 under venv allowed me to update numpy and it now works fine under Rpi 4 Model B.

Though it works fine on Python 3.8.10 under Ubuntu 20.04 in WSL.
