### ISSUE TITLE
[Feature request] Torch hub alternative

### ISSUE THREAD

**Issue by Techno-Fox** [coqui-ai/TTS#1606]
I've read in other issues that Torch hub support was being dropped. If that is the case then what are the alternatives for runtime speech synthesis (in a program that would use TTS, and not on the command line).

There's the obvious such as a sub process call the command line, but that means every time you want to synthesis speech that the models have to be reloaded. This takes time, and can feel awkward  when your users are waiting for speech to synthesis but then you've got the loading time with it. 

A proposed idea is perhaps offering a class to offer runtime speech synthesis, instead of relying on torch hub, one could do (Just an example)

```py
from TTS import Synthesizer

synthesizer = Synthesizer(model_name="model/name/here", speaker_idx="speaker_idx_here")

wav = synthesizer.tts("Hello world")

```

again this is just an example, not saying that this could work, perhaps there's reason as to why you used Torch hub in the first place.

**Comment by Techno-Fox** [comment]
Gonna be honest with you. I didn't see that. It's not in the documentation, turns out i was dumb, and didn't look at the tts bin itself. 

That being said, is this is the documentation somewhere, and I just didn't see it?

**Comment by erogol** [comment]
There is some tutorials coming with the new version. You can also see it on the dev branch.

**Comment by Techno-Fox** [comment]
This is nice to know. Sorry took so long to reply.
