### ISSUE TITLE
[Bug] Wrong number of warmup steps in recipes with default Trainer.scheduler_after_epoch=True

### ISSUE THREAD

**Issue by vanIvan** [coqui-ai/TTS#1611]
### Describe the bug

It seems like default number of warmup steps for lr scheduler in most recipes is wrong (or not?). It is set to 4000 for default `NoamLR` scheduler, however in Trainer, default value `scheduler_after_epoch=True`,  and it will never get to highest lr value during training for 1000 epochs (also default value for num epochs in most configs).

### To Reproduce

Just run:
```
python recipes/ljspeech/glow_tts/train_glowtts.py
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "GeForce RTX 3090",
            "GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.9.0+cu111",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.13",
        "version": "#170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021"
    }
}
```

**Comment by erogol** [comment]
Can you check @loganhart420?

**Comment by erogol** [comment]
@loganhart420 ?

**Comment by loganhart420** [comment]
@vanIvan Can you try again on the latest version?
