### ISSUE TITLE
[Feature request] Get support for LibriTTS | Common Voice | VoxCeleb dataset format support.

### ISSUE THREAD

**Issue by TrycsPublic** [coqui-ai/TTS#1613]
These are datasets I think has good structure with/for large amount of speakers instead of one meta.txt and wavs.

**Alternative Solutions**

Include a script to convert other datasets into supported format.

**Comment by WeberJulian** [comment]
Maybe you should take a look here https://github.com/coqui-ai/TTS/blob/dev/TTS/tts/datasets/formatters.py

All the ones you cited are implemented :)

**Comment by TrycsPublic** [comment]
@WeberJulian How do i use the formatters correctly?

like this?

```
dataset_config = BaseDatasetConfig(
    name="libri_tts", meta_file_train=none, path=os.path.join(output_path, "train-clean-100/")
)
```
