### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by noranraskin** [coqui-ai/TTS#1691]
**Problem**

As of right now, all logging is done through `print` statements. When using the TTS library in different projects it spams the console on every call.

**Solution**

Instead of print statements, a logging library should be used. [Loguru](https://pypi.org/project/loguru/) or pythons standard logging library are viable options.
This would allow for better filtering using **logging levels**, custom handlers to allow writing log files without rerouting stdout, turn all logging off, highlight errors more clearly, etc.

**Comment by erogol** [comment]
I don't know who is gonna take on this issue but I agree. It'd be nice to have logging scope.

**Comment by jjxtra** [comment]
Something to suppress all std out would be nice

**Comment by tadeodonegana** [comment]
Any updates on this issue?

**Comment by eginhard** [comment]
> Any updates on this issue?

I've started work on this and will add it to my fork eventually, but it's not a main priority at the moment.

**Comment by tadeodonegana** [comment]
> > Any updates on this issue?
> 
> I've started work on this and will add it to my fork eventually, but it's not a main priority at the moment.

Thanks, let me know if i can help!

**Comment by LagSlug** [comment]
You can redirect the output using this pattern:

```
from contextlib import redirect_stdout
import io

stdout_capture = io.StringIO()
with redirect_stdout(stdout_capture):

  tts = TTS(model).to('cpu') # or 'gpu' if you have cuda
  tts.tts_to_file(text="Hello", file_path="hello.wav")

print('done')
```

**Comment by eginhard** [comment]
> > > Any updates on this issue?
> > 
> > 
> > I've started work on this and will add it to my fork eventually, but it's not a main priority at the moment.
> 
> Thanks, let me know if i can help!

@tadeodonegana (and others interested in this), feel free to test/review this PR: https://github.com/idiap/coqui-ai-TTS/pull/3

**Comment by eginhard** [comment]
In our fork we've now switched uses of `print` to use standard Python logging, allowing for configurable output: https://github.com/idiap/coqui-ai-TTS
