### ISSUE TITLE
duplicate characters in the character set of multilingual VITS

### ISSUE THREAD

**Issue by mbarnig** [coqui-ai/TTS#1693]
### Describe the bug

I installed Coqui-TTS version 0.7.1 with `pip install TTS` and tested the multilingual model with the script `tts --text "How are you?" --model_name tts_models/multilingual/multi-dataset/your_tts --language_idx "en" --out_path speech.wav`.

An error 

```   
...
 File "/home/mbarnig/COQUI_TTS_0.7.1/TTS/TTS/tts/utils/text/characters.py", line 261, in _create_vocab
    assert (
AssertionError:  [!] There are duplicate characters in the character set. {'-', ',', ';', '(', '?', ':', '!', '.', ')', ' ', "'"}
```   

is issued.

I tried to remove the duplicate characters in the recipe `multilingual/vits_tts/train_vits_tts.py` and to install the project locally on my Ubuntu desktop, without success.

### To Reproduce

run `tts --text "How are you?" --model_name tts_models/multilingual/multi-dataset/your_tts --language_idx "en" --out_path speech.wav`

### Expected behavior

save speech.wav

### Logs

```shell
...
 File "/home/mbarnig/COQUI_TTS_0.7.1/TTS/TTS/tts/utils/text/characters.py", line 261, in _create_vocab
    assert (
AssertionError:  [!] There are duplicate characters in the character set. {'-', ',', ';', '(', '?', ':', '!', '.', ')', ' ', "'"}
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 2070 SUPER"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.7.1",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022"
    }
}
```
```


### Additional context

_No response_

**Comment by Edresson** [comment]
Hi @mbarnig  here the YourTTS inference works fine with version 0.7.1. Please remove the cache of this model with the following command and try again:
```
rm -rf ~/.local/share/tts/tts_models--multilingual--multi-dataset--your_tts/
```
If it didn't works try to remove the current TTS version with the command `pip uninstall tts` and then install it again `pip install tts`

**Comment by mbarnig** [comment]
Thank you very much @Edresson for the quick answer. Removing the cache did the job. This tip will be my first action in the future when I meet similar problems with other TTS models.

Now YourTTS works really great for inference. Changing languages, changing speakers, using speaker_wavs, everything works as expected.

In a next step I will try to add german and luxembourgish languages to the model. I will keep the community informed about my progress.

I will close now this issue which was not a bug, but a lack of knowledge from my side.

All the best.

Marco Barnig
