### ISSUE TITLE
[Feature request] Trim silence with precomputed feats

### ISSUE THREAD

**Issue by LaughingC0ffin** [coqui-ai/TTS#1771]
**🚀 Feature Description**

Hello folks

im currently working with your project and discovered some... unfortunate behavior that costed me some time.
Your audio processor is having some strange behavior with precomputed feats. When loading the wavs trime_silence() is called which truncates my wave. Fair enough if there is ONLY a wave file. In the case of precomputed mel feats, it still trims the wav and ONLY the wave, which leads to some errors.

**Solution**

Somehow the AP needs to now whether there are precomputed mels. I know that the AP only knows about the wavs but there should be a way.

**Alternative Solutions**

Overload the load_wave function and give it the mel as well. Then truncate both. The overloaded function is called from the dataset and the dataset knows if there are feats precomputed. Just an if else I guess.

**Additional context**

Thanks for your attention.

Have a nice day

LaughingCoffin

**Comment by lexkoro** [comment]
It should only trim silence if `do_trim_silence` is set to True in the AP.

**Comment by LaughingC0ffin** [comment]
Oh yeah. After a long time of debugging :). The AP sets it default to False. But the shared config overwrites that with True.
Maybe one could define it to false in the train.py while init the config. But im unsure about that.

**Comment by lexkoro** [comment]
You can just set it to False in your config.

**Comment by LaughingC0ffin** [comment]
Ye ye and i did that. I figured it out. Its not a bug or sth like that. Its just an obstacle when feeding own feats. Thats why im suggesting a feature ("feature request"). My solutions are easy/medium hard to implement. 

Im only making a suggestion.

**Comment by lexkoro** [comment]
Okay, I guess I don't really understand the feature request then. 😅

**Comment by LaughingC0ffin** [comment]
Oh I'm sorry about that. I will try again. 

When I put in waves and mels then the wave is clipped (by trim silence). Of course it would only make sense to set trim_silence to false and thus avoid the errors that occur because mel and wave no longer fit in length.

I personally needed a bit to figure it out and get the whole thing to work for me. The shared config always overwrites the AP init.

My idea now was to save subsequent programmers some work and to include a feature whereby the AP either knows that there are feats and accordingly does not trim the silence. or that you also trim the mels. For both approaches I have described a short possible approach.

I thought it might be similar to others like me.

Was this any better? If all this is completely irrelevant to you, I apologize.

And before I forget about it, in wavernn.py after line 606 a "rank: int = None, " is missing in case you train with MultiGPU (then it gets 9 parameters). Unless MultiGPU is not provided on wavernn. But as far as I know "rank: int = None, " is only a quickfix.

**Comment by erogol** [comment]
You can use https://github.com/edresson/coqui-tts/blob/somethingtts/TTS/bin/remove_silence_using_vad.py

**Comment by erogol** [comment]
We compute almost everything dynamically. So I am not sure what you mean about pre-computing spectrograms. Are you training a vocoder model?

**Comment by LaughingC0ffin** [comment]
Ye im training vocoder models with precomputed mel spectograms. So another model is computing specific mel specs. And i just feed them in as a tupel with the wavs

**Comment by LaughingC0ffin** [comment]
Im not having permission to see that I guess. 404



Von: Eren Gölge ***@***.***>
Gesendet: Dienstag, 26. Juli 2022 13:31
An: coqui-ai/TTS ***@***.***>
Cc: LaughingC0ffin ***@***.***>; Author ***@***.***>
Betreff: Re: [coqui-ai/TTS] [Feature request] Trim silence with precomputed feats (Issue #1771)



You can use https://github.com/edresson/coqui-tts/blob/somethingtts/TTS/bin/remove_silence_using_vad.py

**Comment by erogol** [comment]
then just turn off silence trimming "do_trim_silence=False" in that config. Would that work?
