### ISSUE TITLE
[Bug]  Delay and high CPU load before working

### ISSUE THREAD

**Issue by WickedSmoke** [coqui-ai/TTS#1787]
### Describe the bug

There is an 11 second delay before the tts program does anything.  Even commands such as "tts --help" which do no processing have this pause.  During this time the CPU usage goes over 100%.

I installed from the repository (commt 5cef6fa) on Fedora 33.  strace shows the program is mostly examining files under ~/.local/lib/python3.9/.  There are over 3000 open calls and over 16000 stat calls, but that could just be the crazy overhead that most python programs have (I see that "dnf --help" makes 703 & 2545 such calls).

### To Reproduce

tts --help

### Expected behavior

No delay before operation.

### Environment

```shell
$ python collect_env_info.py 
{
    "CUDA": {
        "GPU": [
            "GeForce GTX 960"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.12.0+cu102",
        "TTS": "0.7.1",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.9",
        "version": "#1 SMP Wed Jun 23 16:20:26 UTC 2021"
    }
}
```

**Comment by WickedSmoke** [comment]
Running tts in a Debian 11 container also has this same delay.

**Comment by WickedSmoke** [comment]
The biggest chunk of time between open calls is 8 seconds after loading the numba package and before librosa.  There are lots of stat calls on .numba_config.yaml (which does not exist) during this time.

```
09:10:02 openat(AT_FDCWD, "/home/karl/.local/lib/python3.9/site-packages/numba/np/ufunc/omppool.cpython-39-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 11
09:10:02 openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 11
09:10:02 openat(AT_FDCWD, "/lib64/libgomp.so.1.0.0", O_RDONLY|O_CLOEXEC) = 11
09:10:02 openat(AT_FDCWD, "/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 11
09:10:10 openat(AT_FDCWD, "/home/karl/.local/lib/python3.9/site-packages/librosa/core/__pycache__/fft.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 110
```

**Comment by erogol** [comment]
This is not something I can replicate on my system. 

Maybe try the dev branch. You might have some luck.

**Comment by nepeee** [comment]
I have the same issue on wsl2 but without the cpu usage. The tts command just sits there, doing nothing, no cpu or disk usage then suddenly it starts to generate the text. Same thing with the synthesizer.tts method.
