### ISSUE TITLE
[Bug] default VCTK / Fastpitch recipe fails (f0_cache pitch folder is empty)

### ISSUE THREAD

**Issue by slegroux** [coqui-ai/TTS#1798]
### Describe the bug

After downloading VCTK dataset at the appropriate location, when running default training pipeline for vctk / fastpitch, no pitch information is computed and saved in f0_cache pitch folder, so pitch_stats can't be computed, and training fails.

### To Reproduce

cd $COQUI_ROOT
bash recipes/vctk/download_vctk.sh
python -m trainer.distribute --gpus "0, 1, 2, 3, 4, 5, 6, 7" --script recipes/vctk/fast_pitch/train_fast_pitch.py

### Expected behavior

Training pipeline should start training!

### Logs

```shell
File "/home/syl20/anaconda3/envs/coqui/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/syl20/Coqui/recipes/vctk/fast_pitch/f0_cache/pitch_stats.npy'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.13",
        "version": "#180-Ubuntu SMP Wed Mar 2 17:25:05 UTC 2022"
    }
}
```

**Comment by p0p4k** [comment]
IN the file, TTS/tts/datasets/dataset.py, add the following at [L703](https://github.com/coqui-ai/TTS/blob/5094499eba440efd41031ad8d7739c4b49c6045b/TTS/tts/datasets/dataset.py#L703).
`print(os.path.join(self.cache_path, "pitch_stats"))`
Does it print a path ? Let me know.

**Comment by slegroux** [comment]
Nothing changes, there's no print. Looks like it's not even going in that branch of the code.

If I delete the f0_cache (empty folder) `rm -rf f0_cache` before re-running train_fast_pitch.py to make sure it runs the self.precompute(precompute_num_workers) function
I get another error:
wav = ap.load_wav(wav_file)
  File "/home/syl20/Coqui/TTS/utils/audio.py", line 840, in load_wav
    assert self.sample_rate == sr, "%s vs %s" % (self.sample_rate, sr)
AssertionError: 22050 vs 48000

Should I convert VCTK sample rate in a pre-processing stage independently?

**Comment by p0p4k** [comment]
Although the audioprocessor in 🐸 TTS has a resampler, I suggest manually resampling everything first. Try and let me know.

**Comment by slegroux** [comment]
Yeah strangely enough I believe the audioprocessor resampler worked for the ljspeech fastpitch recipes but not for the vctk fastpitch recipe. Isn't this a bug?
Is there a script available to easily manually resample the data and format the dataset  accordingly?

**Comment by p0p4k** [comment]
The resampler in audioprocessor resamples at every iteration making it too slow.
Use this file for resampling all files at once ->
https://github.com/coqui-ai/TTS/blob/dev/TTS/bin/resample.py

**Comment by slegroux** [comment]
Indeed! thanks for the info.
Should I make a PR to have resample=True by default in the recipe? or/and add a comment that points to resampling script path in case audioprocessor-based sampling is too slow? 
These changes might be obvious to experienced users, but not when you're getting started and just trying out recipes.

**Comment by p0p4k** [comment]
@slegroux maybe add comments at the appropriate places. An informative Jupyter notebook could also be an alternative. Good luck!

**Comment by lexkoro** [comment]
Always check the documentation first 
https://tts.readthedocs.io/en/latest/main_classes/audio_processor.html#baseaudioconfig

**Comment by erogol** [comment]
I guess this is fixed. I close this one.
