### ISSUE TITLE
[Feature request] Caching synthesized wav files

### ISSUE THREAD

**Issue by KyuubiYoru** [coqui-ai/TTS#1800]
**🚀 Feature Description**
Currently each api access generates a new wave file, i have a scenario where multiple users access the api for the same result at the same time, what causes huge performance issues on the server.

**Solution**

Additional api function to generate a wave file and returns the link to access the wave file without generating a new one.

**Comment by p0p4k** [comment]
Meaning if users request same text, just give out the same wav file as output instead of generating a new one?

**Comment by KyuubiYoru** [comment]
Yes basically, but i figure out I can just use nginx proxy cache for this.

I still need to figure out why it breaks if I request multiple different wav's simultaneously. It feels almost as if the API server handles requests with multiple threads and something is not thread safe.

**Comment by p0p4k** [comment]
Just my 2 cents..
Thing is even slight difference in spelling or punctuation could produce difference wav. An addition of single character would change the outcome too. I am not sure about the caching idea unless it is a "kiosk"-like service where responses are more or less same and require very little punctuation. That being said, earlier I had made my own Django webapp using this repo which could handle multiple requests just fine. Also, modified the code to do the process in-memory, thereby storing nothing in the server.  Good luck!

**Comment by erogol** [comment]
We don't intend to provide a deployment solution for now. 🐸TTS is mostly for training the best possible TTS model. I think this would be out of scope for now. I close this one. But thanks for the feature request.
