### ISSUE TITLE
[Bug] fit error

### ISSUE THREAD

**Issue by TrycsPublic** [coqui-ai/TTS#1838]
### Describe the bug

home/ubuntu/.local/lib/python3.8/site-packages/TTS/tts/models/glow_tts.py:517: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  y_lengths = (y_lengths // self.num_squeeze) * self.num_squeeze

   --> STEP: 0/406 -- GLOBAL_STEP: 0
     | > current_lr: 0.00000 
     | > step_time: 2.09700  (2.09696)
     | > loader_time: 1.37900  (1.37896)

   --> STEP: 25/406 -- GLOBAL_STEP: 25
     | > loss: 3.70217  (3.66141)
     | > log_mle: 0.93073  (0.92907)
     | > loss_dur: 2.77144  (2.73233)
     | > amp_scaler: 16384.00000  (16384.00000)
     | > grad_norm: 10.16473  (9.51002)
     | > current_lr: 0.00000 
     | > step_time: 0.19770  (0.30550)
     | > loader_time: 0.00300  (0.00567)

   --> STEP: 50/406 -- GLOBAL_STEP: 50
     | > loss: 3.70430  (3.64614)
     | > log_mle: 0.93022  (0.93042)
     | > loss_dur: 2.77409  (2.71572)
     | > amp_scaler: 16384.00000  (16384.00000)
     | > grad_norm: 10.26010  (9.92163)
     | > current_lr: 0.00000 
     | > step_time: 0.26790  (0.31091)
     | > loader_time: 0.01590  (0.00611)

   --> STEP: 75/406 -- GLOBAL_STEP: 75
     | > loss: 3.67814  (3.64279)
     | > log_mle: 0.94044  (0.93133)
     | > loss_dur: 2.73771  (2.71145)
     | > amp_scaler: 16384.00000  (16384.00000)
     | > grad_norm: 10.22904  (10.01977)
     | > current_lr: 0.00000 
     | > step_time: 0.44270  (0.32614)
     | > loader_time: 0.09360  (0.00793)

   --> STEP: 100/406 -- GLOBAL_STEP: 100
     | > loss: 3.64119  (3.63406)
     | > log_mle: 0.93588  (0.93176)
     | > loss_dur: 2.70531  (2.70230)
     | > amp_scaler: 16384.00000  (16384.00000)
     | > grad_norm: 10.23089  (10.05122)
     | > current_lr: 0.00000 
     | > step_time: 0.40280  (0.33374)
     | > loader_time: 0.00270  (0.00724)

   --> STEP: 125/406 -- GLOBAL_STEP: 125
     | > loss: 3.63282  (3.63001)
     | > log_mle: 0.93790  (0.93201)
     | > loss_dur: 2.69493  (2.69800)
     | > amp_scaler: 16384.00000  (16384.00000)
     | > grad_norm: 10.16645  (10.07276)
     | > current_lr: 0.00000 
     | > step_time: 0.31530  (0.34196)
     | > loader_time: 0.00280  (0.00708)

   --> STEP: 150/406 -- GLOBAL_STEP: 150
     | > loss: 3.62619  (3.62848)
     | > log_mle: 0.93594  (0.93225)
     | > loss_dur: 2.69025  (2.69623)
     | > amp_scaler: 16384.00000  (16384.00000)
     | > grad_norm: 10.17985  (10.08464)
     | > current_lr: 0.00000 
     | > step_time: 0.38600  (0.35279)
     | > loader_time: 0.00340  (0.00704)

### To Reproduce

use the notebook 2

### Environment

```shell
lambdalabs
```

**Comment by TrycsPublic** [comment]
also its using one core and 0% gpu when using the default notebook?

**Comment by p0p4k** [comment]
That is just `numpy` warning you can ignore. To use GPU, add the following in the first cell of the notebook.
```
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0"
```
