### ISSUE TITLE
[Bug] Can't find distribute.py mentioned in the tutorial

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#1870]
### Describe the bug

The tutorial mentions in [point 6](https://tts.readthedocs.io/en/latest/faq.html#how-can-i-train-my-own-tts-model)  that the multi gpu training should be launched with

`
CUDA_VISIBLE_DEVICES="0,1,2" python distribute.py --script train_tts.py --config_path config.json
`

Yet there is no such file in `bin` folder. 

So the multi gpu command should be updated maybe with :

`
python -m trainer.distribute --script path/to/your/train.py --gpus "0,1"
`

### To Reproduce

Follow the tutorial.

### Expected behavior

THe command in the tutorial should be runnable.

### Environment

```shell
Latest online TTS tutorial https://tts.readthedocs.io/en/latest/faq.html
```

**Comment by p0p4k** [comment]
It is in utils folder.

**Comment by Ca-ressemble-a-du-fake** [comment]
Oh blimey I missed that. Thank you. I close this.

**Comment by erogol** [comment]
You should use the one in the 👟 trainer not the one in the utils. it is deprecated but I forgot to remove it. Now I'll.

**Comment by p0p4k** [comment]
Oh, my bad.
