### ISSUE TITLE
chinese voice conversion failed

### ISSUE THREAD

**Issue by kdtiankong** [coqui-ai/TTS#1900]
### Describe the bug

tts --model_name tts_models/multilingual/multi-dataset/your_tts --encoder_path model_se.pth.tar --encoder_config config_se.json  --speaker_wav D:\voice\TTS-0.7.1\TTS-model\dst.wav --reference_wav D:\voice\TTS-0.7.1\TTS-model\ref.wav --language_idx "zh-cn"

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tts\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "d:\voice\tts-0.7.1\tts-0.7.1\TTS\bin\synthesize.py", line 350, in main
    wav = synthesizer.tts(
  File "d:\voice\tts-0.7.1\tts-0.7.1\TTS\utils\synthesizer.py", line 247, in tts
    language_id = self.tts_model.language_manager.ids[language_name]
KeyError: 'zh-CN'

english module version is ok. chinese module is failed!!!

### To Reproduce

tts --model_name tts_models/multilingual/multi-dataset/your_tts --encoder_path model_se.pth.tar --encoder_config config_se.json --speaker_wav D:\voice\TTS-0.7.1\TTS-model\cyw-out-002.wav --reference_wav D:\voice\TTS-0.7.1\TTS-model\cyw-out-002.wav  --language_idx "zh-CN"

### Environment

```shell
{
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cpu",
        "TTS": "0.8.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021"
    }
}
```

**Comment by xiaocdh** [comment]
The problem still exists
