### ISSUE TITLE
[Feature request] Tutorial should mention when to use Espeak (or Espeak-ng) and when to use Gruut phonemizer

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#1904]
**🚀 Feature Description**

It seems that the tutorial deals with Gruut ("If you use phonemes for training and your language is supported [here](https://github.com/rhasspy/gruut#supported-languages), you don’t need to set your character list.") but some models provided with YourTTS contain Espeak as phonemizer (like the English one). 
By reading some comments here and there (discussion) some users even report using espeak-ng.

**Solution**

Tutorial should explain when to use one phonemizer over the other and what the differences in the config.json should be.

**Alternative Solutions**

**Additional context**

**Comment by p0p4k** [comment]
Hello, if you feel something is missing or would be helpful for the community, please contribute by issuing a PR. Thanks a lot!

**Comment by Ca-ressemble-a-du-fake** [comment]
@p0p4k now that things are clearer, I will try and write something. According to @WeberJulian in [gitter](https://matrix.to/#/@weberjulian:matrix.org?utm_source=gitter) : 
 > No it was for a time since phonemizer wasn't in a compatible licence
 But we wrote our own espeak wrapper
Now it's supported and espeaker is prefered over gruut

So espeak should be used when training from scratch. When fine tuning a model (restore_path) or continuing a previous one (continue_path), then the same phonemizer than used in the original config.json has to be used.

**Comment by WeberJulian** [comment]
Yeah, you can also finetune from gruut to espeak. By default you should use espeak.

**Comment by Ca-ressemble-a-du-fake** [comment]
Good to know thank you @WeberJulian !

**Comment by naveed81** [comment]
How to use espeak-ng instead of espeak? I got this error:
Traceback (most recent call last):
  File "/home/ubuntu/TTS/vctk_vits_train.py", line 100, in <module>
    tokenizer, config = TTSTokenizer.init_from_config(config)
  File "/home/ubuntu/TTS/TTS/tts/utils/text/tokenizer.py", line 198, in init_from_config
    phonemizer = get_phonemizer_by_name(config.phonemizer, **phonemizer_kwargs)
  File "/home/ubuntu/TTS/TTS/tts/utils/text/phonemizers/__init__.py", line 75, in get_phonemizer_by_name
    raise ValueError(f"Phonemizer {name} not found")
ValueError: Phonemizer espeak-ng not found
