### ISSUE TITLE
[Feature request] Loading a pretrained model with a single function call

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#1906]
**🚀 Feature Description**

Currently, we need to load the model config and file separately as

```python
config = load_config(config_path)
model = Vits.init_from_config(config)
model.load_checkpoint(config, model_path, eval=True)
```

Merging all these in a single call `load_pretrained` would make things easier. It should also be using fsspec to be 
cloud compatible. 

**Solution**

We can introduce `from_pretrained` in `BaseTrainerModel` of `TTS/model.py` and the user can override it as they want. 
HF's `from_pretrianed` might be an inspiration.

**Comment by padmalcom** [comment]
This FR is a fantastic idea, furthermore I'm looking for 20 minutes how to create a TTS object from a model using the API :-)

**Comment by Gabriel-Mabel** [comment]
Would love to see this! :)
