### ISSUE TITLE
[Bug] Find unique phonemes script returns empty result and when corrected outputs duplicate phonemes

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#1913]
### Describe the bug

When running script `find_unique_phonemes.py` as `python3 path/to/bin/find_unique_phonemes.py --config_path path/to/config.json` ("datasets" section must have language field, and there must be a field on the main section called "phoneme_language" in config.json), the result is always empty.
```

100%|███████████████████████████████████████████████████████████████████████████████| 563/563 [00:00<00:00, 86669.35it/s]
 > Number of unique phonemes: 0
 > Unique phonemes: 
 > Unique lower phonemes: 
 > Unique all forced to lower phonemes:
```

This is due to compute_phonemes function that uses `text = item[0]` instead of `text = item["text"]` with the new formatters (v 0.7 +).

Moreover when this first bug leveraged the output showed duplicates (eg 8k unique phonemes reported!). 

**PR 1914 has been submitted to address these bugs.**

### To Reproduce

Use YourTTS version 0.8.0 with and run script `find_unique_phonemes.py` as `python3 path/to/bin/find_unique_phonemes.py --config_path path/to/config.json` 

Config.json must contain a "language" field in the "datasets" section and a "phoneme_language" in the main section.

ESpeak Wrapper is used in find unique phonemes

```
from TTS.tts.utils.text.phonemizers.espeak_wrapper import ESpeak

phonemizer = ESpeak(language="fr-fr")
```

### Expected behavior

A list of unique phonemes used in the dataset should be returned.

### Environment

```shell
TTS version 0.8.0
Linux
eSpeak NG text-to-speech: 1.50
```

**Comment by Edresson** [comment]
Hi @Ca-ressemble-a-du-fake  thanks for the bug report :). I fixed this issue on PR #1928 :).
