### ISSUE TITLE
[Bug] VITS LJSpeech model producing robotic speech

### ISSUE THREAD

**Issue by ac-alpha** [coqui-ai/TTS#1936]
### Describe the bug

I am trying to train the VITS model using the default recipe given [here](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/vits_tts/train_vits.py). After training the model for around 400k steps, the speech produced by the model seems robotic. 

Sample audio generated from the model: 

https://user-images.githubusercontent.com/34041476/188597596-26943508-d428-4cd6-820c-b0c2cb6b917e.mp4

What might be going wrong?

### To Reproduce

1. Train the VITS model using this [here](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/vits_tts/train_vits.py).
2. Generate the samples using this command 
`tts --model_path=vits_run/vits_ljspeech-August-01-2022_06+14AM-0000000/best_model.pth --config_path=vits_run/vits_ljspeech-August-01-2022_06+14AM-0000000/config.json --out_path=sample_3.wav --text="What the heck did you just hecking say about me, you little witch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire U.S. armed forces."`

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.0+cu113",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.12",
        "version": "#127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022"
    }
}
```

**Comment by erogol** [comment]
In the paper they trained 1M steps with 128 active batch size. So you might need more training. I also close this since it is not a real bug. But feel free to post on the discussions.
