### ISSUE TITLE
[Bug] you have to install python-mecab-ko. install it...

### ISSUE THREAD

**Issue by neurlang** [coqui-ai/TTS#1947]
### Describe the bug

when i start training my dataset which is not korean, I get detected:
you have to install python-mecab-ko. install it...

and it proceed installing it automatically and it crashes.

Pls make it not install automatically for non-korean or at least fix it so it install it somehow and not crash every time.

### To Reproduce

python3 ./train_vits.py

### Expected behavior

no crash / successful install of python-mecab-ko / no installation attempted for my dataset

### Logs

```shell
import pybind11
      ModuleNotFoundError: No module named 'pybind11'
      [end of output]
```

### Environment

```shell
TTS latest dev (371772c355124556531c089770d6a8b110daf160)
OS Ubuntu 22.04.01
```

**Comment by neurlang** [comment]
TTS/TTS/tts/utils/text/korean/phonemizer.py

```
 from TTS.tts.utils.text.korean.korean import normalize
 
-g2p = G2p()
+g2p = None
 
```
in def korean_text_to_phonemes

```
+    if g2p is None:
+        g2p = G2p()
```

**Comment by harmlessman** [comment]
As a result of checking, it seems that the problem is g2pkk, which is the library needed by KOREAN phonemizer.
While modifying g2pkk, in order to escape this error,
Please install eunjeon for windows and python-mecab-ko for lunux.

Cause: G2pkk update

**Comment by erogol** [comment]
I actually see in the CI tests that `python-mecab-ko` is being installed automatically. I don't know why it is not installed in your case.

**Comment by BrukArkady** [comment]
I have the same issue.

**Comment by harmlessman** [comment]
What you're saying is
```
import pybind11
ModuleNotFoundError: No module named 'pybind11'
[end of output]
``` 
Do you mean an error occurs?

Or does a crash occur after 'you have to install python-mecab-ko.install it...' is printed?

If possible, could you upload the error log?

Apart from the error, as @neurlang said,
-g2p = G2p()
+g2p = None

+ global g2p
+  if g2p is None:
+  g2p = G2p()
I think it's a good idea to add. I'll keep that in mind.

**Comment by neurlang** [comment]
regardless if the pip package is broken or not

guys who have python-mecab-ko installed automatically or successfully... could
you check if you can still train Korean with the proposed change in:

TTS/TTS/tts/utils/text/korean/phonemizer.py

the G2p() constructor in global scope which auto installs pip install python-mecab-ko , and it should really not happen, unless you run korean_text_to_phonemes(), thank you.

**Comment by harmlessman** [comment]
https://github.com/coqui-ai/TTS/commit/b95cf3363cca4563400cf95dd9fef75cf02a17b9 @erogol pushed the pr with the solution of this problem.


The cause of the error logs above appears to be `pybind11` installation failure.

`install_requires` of `python-mecab-ko/setup.py` contains `pybind11` but sometimes it doesn't seem to be installed.
We plan to prevent the above error by adding `pybind11` as `install_requires` to the `g2pkk` library.

If you have a better idea or find another reason for the error, please leave a comment. :)

**Comment by neurlang** [comment]
thank you, currently it crashes because it doesn't have root privileges for make install.
any way to install to a local folder, when running automatically? users might not have root rights.

about the workaround in b95cf33, i don't know what the unrelated assert does there. It's hard to cherry pick.

**Comment by erogol** [comment]
why do you need root-priv for installing `pybind11`? It is just `pip install`. But C compiler might need a root priv and you can use conda to overcome that.
