### ISSUE TITLE
trim_silence in processor should get sr. [Bug]

### ISSUE THREAD

**Issue by amitaie** [coqui-ai/TTS#1965]
### Describe the bug

Hello,
I think there is a bug in the processor. when we load_wav we can get different sr than self.sample_rate  in order to resample the audio to it. the function trim_silence is using sample rate in order to determinate the margin but it will always use self.sample_rate.

### To Reproduce

.

### Environment

```shell
wget https://raw.githubusercontent.com/coqui-ai/TTS/main/TTS/bin/collect_env_info.py
python collect_env_info.py
```

**Comment by erogol** [comment]
It sounds like a feature request to me as it does not fail any code. 

Feel free to shoot a ✨PR✨
