### ISSUE TITLE
Colab Implementation of TTS With personal dataset in zip folder.

### ISSUE THREAD

**Issue by kudzaijaure-dot** [coqui-ai/TTS#1972]
**🚀 Feature Description**

**A colab notebook allowing for TTS synthesis with our own zip dataset for both training the model and inferencing.**

**Souvigk554 provides a decent solution but does not run correctly and is not maintained at https://github.com/souvikg544/TTS_Data_Maker**

**No other mentions**

**Comment by erogol** [comment]
Would [this](https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b) work?
