### ISSUE TITLE
[Bug] Naming of new Thorsten Vocoder Model mismatch

### ISSUE THREAD

**Issue by r4nc0r** [coqui-ai/TTS#1976]
### Describe the bug

After unzip of "vocoder_models--de--thorsten--hifigan_v1" the unzipped directory is: "vocoder_models--de-thorsten-hifigan_v1" could you please rename the zipped directory so that the two missing "-" at "de-thorsten-" are added? 

I work with variables for the model and vocoder names and I think this would be useful to others too.  

### To Reproduce

1. pip install TTS==0.8.0
2. download https://coqui.gateway.scarf.sh/v0.8.0_models/vocoder_models--de--thorsten--hifigan_v1.zip
3. unzip '*.zip'

### Environment

```shell
- TTS Version 0.8.0
- python 3.10
```

**Comment by erogol** [comment]
What is wrong is not the zip name but the directory name. Is there any functional issue that it causes?

**Comment by r4nc0r** [comment]
I have my own Dockerfile for the coqui Deployment

```
ENV modelName=tts_models--de--thorsten--tacotron2-DDC
ENV vocoderName=vocoder_models--de--thorsten--hifigan_v1
ENV modelURL=https://coqui.gateway.scarf.sh/v0.8.0_models/${modelName}.zip
ENV vocoderURL=https://coqui.gateway.scarf.sh/v0.8.0_models/${vocoderName}.zip

WORKDIR /workdir
RUN aria2c -x16 -Z ${modelURL} ${vocoderURL}
RUN unzip '*.zip'
RUN rm *.zip

HEALTHCHECK CMD curl --fail -I http://localhost:5002 || exit 1  
EXPOSE 5002
#Change vocoder Path to variable if: https://github.com/coqui-ai/TTS/issues/1976
CMD tts-server --model_path /workdir/${modelName}/model_file.pth --config_path /workdir/${modelName}/config.json --vocoder_path /workdir/vocoder_models--de-thorsten-hifigan_v1/model_file.pth.tar --vocoder_config_path /workdir/vocoder_models--de-thorsten-hifigan_v1/config.json
```

And I would like to use the variables for the vocoder in the last line (same as the model variables) but i cannot use them because unzipped the filedir is named different.

**Comment by erogol** [comment]
You can match things using `.model.json` until we fix it at some point.
