### ISSUE TITLE
[Feature request] Google Colab Training Tutorial 

### ISSUE THREAD

**Issue by freds0** [coqui-ai/TTS#2010]
**🚀 Feature Description**

The training tutorial available at TTS/notebooks/Tutorial_2_train_your_first_TTS_model.ipynb does not work in Google Colab

**Solution**

I made some adaptations in jupyter notebook, to run the GlowTTS training in Google colab using a dataset in Portuguese. This makes it easier if someone wants to adapt to another language. It is also possible to perform fine tuning from an official model. I decided to share in case anyone is interested in using it. I hope it helps.

[https://colab.research.google.com/drive/1FYKY9TDGXwPJCiqmgLxnH-Lyu62nK6wb?usp=sharing](https://colab.research.google.com/drive/1FYKY9TDGXwPJCiqmgLxnH-Lyu62nK6wb?usp=sharing)

**Comment by erogol** [comment]
https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b ❓

**Comment by leechien0710** [comment]
when i train using ljspeech dataset it shows the following error
![image](https://user-images.githubusercontent.com/82867850/198264920-af338212-ea0d-404f-b8a1-6a6a3bd0fd2b.png)
please help me

**Comment by erogol** [comment]
You don't have the training files in the right path.

**Comment by leechien0710** [comment]
How should I put the path correctly?

Vào Th 2, 7 thg 11, 2022 vào lúc 16:46 Eren Gölge <
***@***.***> đã viết:

**Comment by leechien0710** [comment]
Is the standard training file format audio|text? such as LJ001.wav|text

Vào Th 3, 22 thg 11, 2022 vào lúc 22:16 B19DCCN099 - Lê Văn Chiến <
***@***.***> đã viết:

**Comment by sudip550** [comment]
> **🚀 Feature Description**
> 
> The training tutorial available at TTS/notebooks/Tutorial_2_train_your_first_TTS_model.ipynb does not work in Google Colab
> 
> **Solution**
> 
> I made some adaptations in jupyter notebook, to run the GlowTTS training in Google colab using a dataset in Portuguese. This makes it easier if someone wants to adapt to another language. It is also possible to perform fine tuning from an official model. I decided to share in case anyone is interested in using it. I hope it helps.
> 
> https://colab.research.google.com/drive/1FYKY9TDGXwPJCiqmgLxnH-Lyu62nK6wb?usp=sharing

please sir give example for hindi dataset

**Comment by irenepenasperez** [comment]
> **🚀 Feature Description**
> 
> The training tutorial available at TTS/notebooks/Tutorial_2_train_your_first_TTS_model.ipynb does not work in Google Colab
>
> **Solution**
> 
> I made some adaptations in jupyter notebook, to run the GlowTTS training in Google colab using a dataset in Portuguese. This makes it easier if someone wants to adapt to another language. It is also possible to perform fine tuning from an official model. I decided to share in case anyone is interested in using it. I hope it helps.
> 
> https://colab.research.google.com/drive/1FYKY9TDGXwPJCiqmgLxnH-Lyu62nK6wb?usp=sharing

Hello @freds0 . Your notebook it's trully interesting. I am trying to run it in Colab. I have encountered an error, at this point: from TTS.utils.synthesizer import Synthesizer

# load models
synthesizer = Synthesizer(
    model_path,
    config_path,
    speakers_file_path,
    language_ids_file_path,
    vocoder_path,
    vocoder_config_path,
    encoder_path,
    encoder_config_path,
    use_cuda
)

The error is the following: ---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-35-fe65264003f1>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # load models
----> 4 synthesizer = Synthesizer(
      5     model_path,
      6     config_path,

2 frames

[/content/coqui-TTS/TTS/config/__init__.py](https://localhost:8080/#) in load_config(config_path)
     89             data = read_json_with_comments(config_path)
     90     else:
---> 91         raise TypeError(f" [!] Unknown config file type {ext}")
     92     config_dict.update(data)
     93     model_name = _process_model_name(config_dict)

TypeError:  [!] Unknown config file type

I have the congig.json file, but it is still not running. 

I would appreciate a lot your help. Thanks in advance.

Muito obrigada
