### ISSUE TITLE
[Bug] "Training a model" tutorial shows parameters in recipe but different ones as output

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#2015]
### Describe the bug

Hi,

I was looking for a solution to an issue I am facing [2013](https://github.com/coqui-ai/TTS/discussions/2013) and so read again the doc "Training a model". 
In this doc point "3. Check the recipes" reads `use_phonemes=True` but then point "4. Run the training" reads the opposite 
```
    > DataLoader initialization
  | > Use phonemes: False
```
So this is not clear to me why/how this value changed.

### To Reproduce

Read the tutorial for [training a model](https://tts.readthedocs.io/en/latest/training_a_model.html#multi-speaker-training).

### Expected behavior

The output should show `Use phonemes: True` to match the recipe or if it is the expected behavior it should be explained why another value is shown.

### Environment

```shell
- CoquiTTS 0.8.0
```

**Comment by lexkoro** [comment]
Seems just like a mistake in the documentation.

**Comment by erogol** [comment]
Can't replicate this. My output.

```
> DataLoader initialization
| > Tokenizer:
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: espeak
```
