### ISSUE TITLE
[Bug] Min_seq_length Max_seq_length having no effect on VITS training

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#2036]
### Describe the bug

Hi,

I wanted to exclude some short samples from my dataset. So instead of removing all of these from metadata.csv, I tried to set Min_seq_length to 16000 * 1.26 = 20160 (audio is  sampled at 16kHz) but it did not change the number of discarded samples. I tried bigger values without effect on the number of discarded samples.
I also tried to set max_seq_length to 10 without effect either on the number of discarded samples.

So the only fix was to set the minimum text length (min_text_len).

### To Reproduce

Take a VITS model, set in config.json `min_seq_length` to the maximum wav length for example and run the training. There won't be any discarded samples.

### Expected behavior

Setting `min_seq_length` to a value equal to sample rate * sec should discard all samples which are shorter than this threshold.

Or if it has no effect purposely, then a warning / error could be shown eg : ` min_seq_length` parameters does not exist.

### Environment

```shell
TTS 0.8.0
```

**Comment by erogol** [comment]
`min_seq_len` is replaces by 

```
  min_text_len (int):
            Minimum length of input text to be used. All shorter samples will be ignored. Defaults to 0.

        max_text_len (int):
            Maximum length of input text to be used. All longer samples will be ignored. Defaults to float("inf").

        min_audio_len (int):
            Minimum length of input audio to be used. All shorter samples will be ignored. Defaults to 0.

        max_audio_len (int):
            Maximum length of input audio to be used. All longer samples will be ignored. The maximum length in the
            dataset defines the VRAM used in the training. Hence, pay attention to this value if you encounter an
            OOM error in training. Defaults to float("inf").
```

**Comment by erogol** [comment]
I close this for now.
