### ISSUE TITLE
[Bug] Tokenization does not properly handle opening question/exclamation marks at phrase begin (Spanish)

### ISSUE THREAD

**Issue by jpmayos** [coqui-ai/TTS#2093]
### Describe the bug

Spanish has opening question/exclamation marks (¡¿), but after adding them to the list of punctuation marks, the tokenization is wrong when they appear at the beginning of the phrase (it is working properly when they appear in the middle of the phrase).

This occurs because the tokenization expects a punctuation mark to occur after a chunk of text. The problem is the postprocessing part, in `TTS>tts>utils>text>phonemizers>base.py line 135`: 

`phonemized = self._phonemize_postprocess(phonemized, punctuations)`

The way coqui does the splitting into segments does only consider that punctuation marks close a segment. I haven´t found an easy way to fix this, other than removing the opening marks from the training metadata.

### To Reproduce

Simply have a phrase like this in the data:
original text: "-¡Ah! no conocéis sin duda que nosotras, las hijas de Inglaterra estamos protegidas por las leyes de tal manera y con tanto rigor, **que ningún hombre se atreve a faltarnos al respeto.**"

phonemized text: "**¡!** a, no konoθeis sin duda ke nosotɾas, las ixas de inɡlatera estamos pɾotexidas poɾ las leʝes de tal maneɾa i kon tanto riɡoɾ."

You see that the last segment of the origina text is missing in the transcription (in bold in the original text), and the phonemized text includes the first two punctuation marks together at the start of the phrase.

### Expected behavior

Ideally, the phonemized text should look like:

"¡a! no konoθeis sin duda ke nosotɾas, las ixas de inɡlatera estamos pɾotexidas poɾ las leʝes de tal maneɾa i kon tanto riɡoɾ, ke ninɡun ombɾe se atɾebe a faltaɾnos al respeto."

Removing the opening exclamation mark from the text, results in:

"a! no konoθeis sin duda ke nosotɾas, las ixas de inɡlatera estamos pɾotexidas poɾ las leʝes de tal maneɾa i kon tanto riɡoɾ, ke ninɡun ombɾe se atɾebe a faltaɾnos al respeto."

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A40",
            "NVIDIA A40",
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.6"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.12.1+cu116",
        "TTS": "0.8.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022"
    }
}
```

**Comment by erogol** [comment]
I am not sure when we can deal with that but as a temp fix you can override the phonemizer with that exception and use it for your training.
