### ISSUE TITLE
[Discussion] Ideas for better model config management

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#21]
(I keep it in the issues to refer back to the initial discussion)

Hi All!! 

I guess one of the biggest issues in TTS is the way we handle the configs for models and training. Putting example config files under the config folder is hard to maintain and looks complicated for people to start using TTS. 

So I want to discuss here some better alternatives and ask for the wisdom of the crowd 🧑‍🤝‍🧑.

Couple of constraints we need to consider from the top of my head.

- configs should not be python specific, and they should be in a generic form to be serialized and loaded by other systems and programming languages. So if someone likes to export the model and use it in an embedded system config file should not be a problem. 
- configs should allow easy experimentation, collaboration, and reproduction. 
- Each model should explain its config fields. Right now I do this in ```config.json``` by violating the JSON format with comments. It is not optimal ☹️.

If you have an idea please share it below and let's discuss it. 

**Edit:** 

I should also add one more constraint.
-  We should solve this with no dependencies if possible. 

**NOTE**: This is a continuation of previously started conversion https://github.com/mozilla/TTS/issues/660

_Originally posted by @erogol in https://github.com/coqui-ai/TTS/discussions/20_

**Comment by thorstenMueller** [comment]
In addition to the previous conversation i'd like to add:
* different training configs should be easy to compare (even if additional attributes in config has been added/removed)
* maybe a finer grouping of attributes which affect each other (eg: if you change a it's recommended to change b also)

**Comment by WeberJulian** [comment]
Maybe we could have an internal default for each model and only write default override in a YAML file (which allows for comments and is more user friendly). And since we don't have the json to explain the fields, we can have a .md per model or concept (like the audio processor) explaining the fields.

**Comment by gerazov** [comment]
If we're leaning towards YAML maybe [strict-yaml](https://github.com/crdoconnor/strictyaml) is worth considering.

On the other hand Python devs seem to be going for TOML - [PEP 621](https://www.python.org/dev/peps/pep-0621/)

**Comment by WeberJulian** [comment]
> On the other hand Python devs seem to be going for TOML - [PEP 621](https://www.python.org/dev/peps/pep-0621/)

I don't know the ambitions of coqui-TTS but if one day you decide to have model run on iOS or android (or something else) it seems that keeping the config in a non specific to python format might be a good idea

**Comment by erogol** [comment]
do you know what are good formats with multiple platform support?

I guess json is one and that was the reason I choose it initially.

Btw one good option could be using just Python classes as config files and export them to generic formats when necessary.

**Comment by gerazov** [comment]
:+1: for a Python class that could get exported if need be.

**Comment by erogol** [comment]
this looks like a good option https://pypi.org/project/dataclasses-json/ as @reuben suggested

**Comment by erogol** [comment]
I created this to use an in house solution https://github.com/erogol/coqpit

**Comment by erogol** [comment]
here we go https://github.com/coqui-ai/TTS/pull/476

**Comment by erogol** [comment]
I think we can close this as it is solved with the new Coqpit integration. 

Thx everyone for your discussion.

**Comment by omkarade** [comment]
how train model using word embedding as input??
I have large data of wav and csv text single person. I want to train TTS model for other language(not English) which model should i use and I want to know how use word embedding as input. I hope you help me.

thanks in advance 🙏🙏

**Comment by erogol** [comment]
@omkarade why are you spamming here and there? Please create a new topic under discussion and ask your questions there.
