### ISSUE TITLE
[Bug] Error Synthesizing test sentences VITS 

### ISSUE THREAD

**Issue by NK990** [coqui-ai/TTS#2118]
### Describe the bug

Error while Synthesizing test sentences after continuing training, I also noticed that config.json is now different then original one:

`"test_sentences": [
        "Duga je \u010desta opti\u010dka pojava u Zemljinoj atmosferi u obliku jednog ili vi\u0161e obojenih kru\u017enih lukova.",
    ]`

after: 

`"test_sentences": [
        [
            "D",
            "u",
            "g",
            "a",
            " ",
            "j",
            "e",
            " ",
            "\u010d",
            "e",
            "s",
            "t",
            "a",
            " ",
            "o",
            "p",
            "t",
            "i",
            "\u010d",
            "k",
            "a",
            " ",
            "p",
            "o",
            "j",
            "a",
            "v",
            "a",
            " ",
            "u",
            " ",
            "Z",
            "e",
            "m",
            "l",
            "j",
            "i",
            "n",
            "o",
            "j",
            " ",
            "a",
            "t",
            "m",
            "o",
            "s",
            "f",
            "e",
            "r",
            "i",
            " ",
            "u",
            " ",
            "o",
            "b",
            "l",
            "i",
            "k",
            "u",
            " ",
            "j",
            "e",
            "d",
            "n",
            "o",
            "g",
            " ",
            "i",
            "l",
            "i",
            " ",
            "v",
            "i",
            "\u0161",
            "e",
            " ",
            "o",
            "b",
            "o",
            "j",
            "e",
            "n",
            "i",
            "h",
            " ",
            "k",
            "r",
            "u",
            "\u017e",
            "n",
            "i",
            "h",
            " ",
            "l",
            "u",
            "k",
            "o",
            "v",
            "a",
            "."
        ]
]`

### To Reproduce

`!python /usr/local/lib/python3.7/dist-packages/TTS/bin/train_tts.py --config_path='/content/drive/MyDrive/TTS/config.json' \
 --continue_path='/content/drive/MyDrive/TTS/vits_ljspeech-November-02-2022_12+20AM-0000000' `

### Expected behavior

moving to next epoch after synthesizing test sentences

### Logs

```shell
| > Synthesizing test sentences.
 ! Run is kept in /content/drive/MyDrive/TTS/vits_ljspeech-November-02-2022_12+20AM-0000000
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1538, in fit
    self._fit()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1526, in _fit
    self.test_run()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1444, in test_run
    test_outputs = self.model.test_run(self.training_assets)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/models/vits.py", line 1445, in test_run
    do_trim_silence=False,
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/utils/synthesis.py", line 180, in synthesis
    model.tokenizer.text_to_ids(text, language=language_id),
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/utils/text/tokenizer.py", line 107, in text_to_ids
    text = self.text_cleaner(text)
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/utils/text/cleaners.py", line 105, in phoneme_cleaners
    text = en_normalize_numbers(text)
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/utils/text/english/number_norm.py", line 92, in normalize_numbers
    text = re.sub(_comma_number_re, _remove_commas, text)
  File "/usr/lib/python3.7/re.py", line 194, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla T4"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.8.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.15",
        "version": "#1 SMP Fri Aug 26 08:44:51 UTC 2022"
    }
}
```

**Comment by erogol** [comment]
Can't reproduce

**Comment by do-web** [comment]
I got the same error.
