### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BWJ2310** [coqui-ai/TTS#2131]
### Describe the bug

I think this problem is quite stupid but when I try to synthesize sentences with numbers using tts-server, the numbers would be unspeakable, and the output would just be a sentence without the number. Say "today's weather is expecting to snow with 4 degree high and -10 degree low" the output will be "today's weather is expecting to snow with degree high and degree low", the error is "Character '4' is not in the vocabulary. Discarding it." Should I write a code to convert all the numbers to their corresponding text before passing it to synthesizer? or there is a better way to do it, I can't figure it out😂

### To Reproduce

tts-server 
type in "number 4 is pronounced number four"

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.12.1",
        "TTS": "0.8.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "i386",
        "python": "3.8.0",
        "version": "Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64"
    }
}
```

**Comment by erogol** [comment]
Some models do not expand numbers correctly, it is just how the model is trained. You should use them in text form.
