### ISSUE TITLE
[Bug] Notebooks don't work on branch dev

### ISSUE THREAD

**Issue by lumpidu** [coqui-ai/TTS#2145]
### Describe the bug

E.g. `notebooks/ExtractTTSpectrogram.ipynb`:

![grafik](https://user-images.githubusercontent.com/734966/201431549-5737480f-4426-42cc-ba39-56e78c15788c.png)

`notebooks/Tutorial_2_train_your_first_TTS_model.ipynb`:

![grafik](https://user-images.githubusercontent.com/734966/201434903-9c369922-49d1-46ee-a18d-f39647bc0952.png)

### To Reproduce

Run the notebooks

### Expected behavior

All notebooks run against current default branch (`dev`).

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA RTX A6000",
            "NVIDIA RTX A6000",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.0+cu117",
        "TTS": "0.8.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022"
    }
}

installed via virtual env
```

**Comment by erogol** [comment]
Can you check @Aya-AlJafari

**Comment by Aya-AlJafari** [comment]
@erogol  will get on it right away.

**Comment by erogol** [comment]
@Aya-AlJafari any updates on this?
