### ISSUE TITLE
Turkish model "tts_models/tr/common-voice/glow-tts" fails to render capitalized letters

### ISSUE THREAD

**Issue by trappedinspacetime** [coqui-ai/TTS#2190]
First of all, thank you for maintaining this project.

When I run  following line I get an error:

          tts --text "Saat kaç acaba?" --model_name "tts_models/tr/common-voice/glow-tts" --out_path /dev/shm/jarvis.mp3 && aplay /dev/shm/jarvis.mp3

   > tts_models/tr/common-voice/glow-tts is already downloaded.
   > vocoder_models/tr/common-voice/hifigan is already downloaded.
   > Using model: glow_tts
   > Setting up Audio Processor...
   | > sample_rate:22050
   | > resample:False
   | > num_mels:80
   | > log_func:np.log10
   | > min_level_db:-100
   | > frame_shift_ms:None
   | > frame_length_ms:None
   | > ref_level_db:20
   | > fft_size:1024
   | > power:1.5
   | > preemphasis:0.0
   | > griffin_lim_iters:60
   | > signal_norm:True
   | > symmetric_norm:True
   | > mel_fmin:0
   | > mel_fmax:None
   | > pitch_fmin:1.0
   | > pitch_fmax:640.0
   | > spec_gain:20.0
   | > stft_pad_mode:reflect
   | > max_norm:4.0
   | > clip_norm:True
   | > do_trim_silence:True
   | > trim_db:45
   | > do_sound_norm:False
   | > do_amp_to_db_linear:True
   | > do_amp_to_db_mel:True
   | > do_rms_norm:False
   | > db_level:None
   | > stats_path:None
   | > base:10
   | > hop_length:256
   | > win_length:1024
   > Vocoder Model: hifigan
   > Setting up Audio Processor...
   | > sample_rate:22050
   | > resample:False
   | > num_mels:80
   | > log_func:np.log10
   | > min_level_db:-100
   | > frame_shift_ms:None
   | > frame_length_ms:None
   | > ref_level_db:20
   | > fft_size:1024
   | > power:1.5
   | > preemphasis:0.0
   | > griffin_lim_iters:60
   | > signal_norm:True
   | > symmetric_norm:True
   | > mel_fmin:0
   | > mel_fmax:None
   | > pitch_fmin:1.0
   | > pitch_fmax:640.0
   | > spec_gain:20.0
   | > stft_pad_mode:reflect
   | > max_norm:4.0
   | > clip_norm:True
   | > do_trim_silence:True
   | > trim_db:45
   | > do_sound_norm:False
   | > do_amp_to_db_linear:True
   | > do_amp_to_db_mel:True
   | > do_rms_norm:False
   | > db_level:None
   | > stats_path:None
   | > base:10
   | > hop_length:256
   | > win_length:1024
   > Generator Model: hifigan_generator
   > Discriminator Model: hifigan_discriminator
  Removing weight norm...
   > Text:  Saat kaç acaba?
   > Text splitted to sentences.
  ['Saat kaç acaba?']
  Saat kaç acaba?
   [!] Character 'S' not found in the vocabulary. Discarding it.
   > Processing time: 0.7631030082702637
   > Real-time factor: 0.4351060543121461
   > Saving output to /dev/shm/jarvis.mp3
  Playing WAVE '/dev/shm/jarvis.mp3' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono

How can I add capital letters and other phonemes?

**Comment by erogol** [comment]
You can lower case before inputting to the model for an easy fix. It makes no difference.

**Comment by trappedinspacetime** [comment]
@erogol Thank you for responding. Is there a configuration file to add missing phonemes?

**Comment by trappedinspacetime** [comment]
@erogol Actually, I want to train my own Turkish model but I don't know how to do. Unfortunately, there is no Turkish model out there. I saw some exampes at soundcloud.com such as https://soundcloud.com/mert-hac-ahmeto-lu/sesler
but it's not published.

**Comment by erogol** [comment]
If you have a data I can try to help you with that.

**Comment by trappedinspacetime** [comment]
And I also need a high performance computer. Mine is Ryzen 5500u with 8GB RAM without GPU.

**Comment by erogol** [comment]
not ~100hrs but yeah >= 5hrs

Are "TRT archive audio files." available somewhere?

**Comment by trappedinspacetime** [comment]
@erogol I found ["Seesli Kitap"](https://www.trtdinle.com/show/portre) section. I think it's suitable for tts model. You need to sign up to listen to the books.

**Comment by erogol** [comment]
@trappedinspacetime thanks for the link 👍

**Comment by trappedinspacetime** [comment]
@erogol I have another problem. I am coding a virtual assistant on Ubuntu 22.04. It works well except `tts` takes long time to load and create audio file. 
Is it possible to preload `tts` into memory to speed up the process?

**Comment by erogol** [comment]
You can use the Python API now to load the model once and serve it.
