### ISSUE TITLE
[Bug] Error while testing a trained VITS Model (Gibberish)

### ISSUE THREAD

**Issue by prateek-77** [coqui-ai/TTS#2193]
### Describe the bug

Thanks for the amazing codebase!

When I try to test my trained VITS model for TTS, the model produces a gibber for 3-4 seconds at the beginning of every sentence and at every punctuation mark (full stop, commas). It is able to speak the rest of the text correctly.

Following is the output generated by the test command:

> Using model: vits
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Text: As company has expanded its datacenters. to meet demands
 > Text splitted to sentences.
['As company has expanded its datacenters.', 'to meet demands']
['<BLNK>', 'F', '<BLNK>', 'a', '<BLNK>', 'i', '<BLNK>', 'l', '<BLNK>', 'e', '<BLNK>', 'd', '<BLNK>', ' ', '<BLNK>', 't', '<BLNK>', 'o', '<BLNK>', ' ', '<BLNK>', 'c', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', 'a', '<BLNK>', 't', '<BLNK>', 'e', '<BLNK>', ' ', '<BLNK>', 's', '<BLNK>', 'e', '<BLNK>', 'c', '<BLNK>', 'u', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', ' ', '<BLNK>', 'd', '<BLNK>', 'i', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', 'c', '<BLNK>', 't', '<BLNK>', 'o', '<BLNK>', 'r', '<BLNK>', 'y', '<BLNK>', ' ', '<BLNK>', ':', '<BLNK>', ' ', '<BLNK>', 'N', '<BLNK>', 'o', '<BLNK>', ' ', '<BLNK>', 's', '<BLNK>', 'u', '<BLNK>', 'c', '<BLNK>', 'h', '<BLNK>', ' ', '<BLNK>', 'f', '<BLNK>', 'i', '<BLNK>', 'l', '<BLNK>', 'e', '<BLNK>', ' ', '<BLNK>', 'o', '<BLNK>', 'r', '<BLNK>', ' ', '<BLNK>', 'd', '<BLNK>', 'i', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', 'c', '<BLNK>', 't', '<BLNK>', 'o', '<BLNK>', 'r', '<BLNK>', 'y', '<BLNK>', 'æ', '<BLNK>', 'z', '<BLNK>', ' ', '<BLNK>', 'm', '<BLNK>', 'ˈ', '<BLNK>', 'a', '<BLNK>', 'ɪ', '<BLNK>', 'k', '<BLNK>', 'ɹ', '<BLNK>', 'ə', '<BLNK>', 's', '<BLNK>', 'ˌ', '<BLNK>', 'ɑ', '<BLNK>', 'ː', '<BLNK>', 'f', '<BLNK>', 't', '<BLNK>', ' ', '<BLNK>', 'h', '<BLNK>', 'ɐ', '<BLNK>', 'z', '<BLNK>', ' ', '<BLNK>', 'ɛ', '<BLNK>', 'k', '<BLNK>', 's', '<BLNK>', 'p', '<BLNK>', 'ˈ', '<BLNK>', 'æ', '<BLNK>', 'n', '<BLNK>', 'd', '<BLNK>', 'ᵻ', '<BLNK>', 'd', '<BLNK>', ' ', '<BLNK>', 'ɪ', '<BLNK>', 't', '<BLNK>', 's', '<BLNK>', ' ', '<BLNK>', 'd', '<BLNK>', 'ˈ', '<BLNK>', 'e', '<BLNK>', 'ɪ', '<BLNK>', 'ɾ', '<BLNK>', 'ə', '<BLNK>', 's', '<BLNK>', 'ˌ', '<BLNK>', 'ɛ', '<BLNK>', 'n', '<BLNK>', 't', '<BLNK>', 'ɚ', '<BLNK>', 'z', '<BLNK>', '.', '<BLNK>']
 [!] Character 'F' not found in the vocabulary. Discarding it.
['<BLNK>', 'F', '<BLNK>', 'a', '<BLNK>', 'i', '<BLNK>', 'l', '<BLNK>', 'e', '<BLNK>', 'd', '<BLNK>', ' ', '<BLNK>', 't', '<BLNK>', 'o', '<BLNK>', ' ', '<BLNK>', 'c', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', 'a', '<BLNK>', 't', '<BLNK>', 'e', '<BLNK>', ' ', '<BLNK>', 's', '<BLNK>', 'e', '<BLNK>', 'c', '<BLNK>', 'u', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', ' ', '<BLNK>', 'd', '<BLNK>', 'i', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', 'c', '<BLNK>', 't', '<BLNK>', 'o', '<BLNK>', 'r', '<BLNK>', 'y', '<BLNK>', ' ', '<BLNK>', ':', '<BLNK>', ' ', '<BLNK>', 'N', '<BLNK>', 'o', '<BLNK>', ' ', '<BLNK>', 's', '<BLNK>', 'u', '<BLNK>', 'c', '<BLNK>', 'h', '<BLNK>', ' ', '<BLNK>', 'f', '<BLNK>', 'i', '<BLNK>', 'l', '<BLNK>', 'e', '<BLNK>', ' ', '<BLNK>', 'o', '<BLNK>', 'r', '<BLNK>', ' ', '<BLNK>', 'd', '<BLNK>', 'i', '<BLNK>', 'r', '<BLNK>', 'e', '<BLNK>', 'c', '<BLNK>', 't', '<BLNK>', 'o', '<BLNK>', 'r', '<BLNK>', 'y', '<BLNK>', 'æ', '<BLNK>', 'z', '<BLNK>', ' ', '<BLNK>', 'm', '<BLNK>', 'ˈ', '<BLNK>', 'a', '<BLNK>', 'ɪ', '<BLNK>', 'k', '<BLNK>', 'ɹ', '<BLNK>', 'ə', '<BLNK>', 's', '<BLNK>', 'ˌ', '<BLNK>', 'ɑ', '<BLNK>', 'ː', '<BLNK>', 'f', '<BLNK>', 't', '<BLNK>', ' ', '<BLNK>', 'h', '<BLNK>', 'ɐ', '<BLNK>', 'z', '<BLNK>', ' ', '<BLNK>', 'ɛ', '<BLNK>', 'k', '<BLNK>', 's', '<BLNK>', 'p', '<BLNK>', 'ˈ', '<BLNK>', 'æ', '<BLNK>', 'n', '<BLNK>', 'd', '<BLNK>', 'ᵻ', '<BLNK>', 'd', '<BLNK>', ' ', '<BLNK>', 'ɪ', '<BLNK>', 't', '<BLNK>', 's', '<BLNK>', ' ', '<BLNK>', 'd', '<BLNK>', 'ˈ', '<BLNK>', 'e', '<BLNK>', 'ɪ', '<BLNK>', 'ɾ', '<BLNK>', 'ə', '<BLNK>', 's', '<BLNK>', 'ˌ', '<BLNK>', 'ɛ', '<BLNK>', 'n', '<BLNK>', 't', '<BLNK>', 'ɚ', '<BLNK>', 'z', '<BLNK>', '.', '<BLNK>']
 [!] Character 'N' not found in the vocabulary. Discarding it.
 > Processing time: 13.786689043045044
 > Real-time factor: 1.211566180171308

I am also not sure why the last 2 lists of letters and <BLNK> is being generated. 

I would be grateful for any help on this. Thank you very much.

### To Reproduce

`tts --text 'As company has expanded its datacenters. to meet demands' --model_name ./model.pth --config_path ./config.json --out_path ./output.wav`

### Environment

```shell
- TTS Version - 0.8.0
- PyTorch - 1.13.0
- Python - 3.8.10
- OS - Linux
- CPU
- TTS, PyTorch installed through Pip
```

**Comment by p0p4k** [comment]
Hello, for some reason your `<input text>` is getting converted into `<"failed to create secure directory....." + input text>`
Something went wrong while reading the metadata.txt, during training, probably.

**Comment by prateek-77** [comment]
Thanks for your comment! 

Do you have any idea why is it concatenating "failed to create secure directory....." to the input text and how do I avoid this? Also, this gibber happens at all punctuation marks (commas, fullstops).

**Comment by p0p4k** [comment]
You need to add the symbols during training, plus you can add a simple line at the dataset loader to verify what the metadata.txt's text is getting converted into as follows:
(assuming your formatter is ljspeech)
```
def ljspeech(root_path, meta_file, **kwargs):  # pylint: disable=unused-argument
    """Normalizes the LJSpeech meta data file to TTS format
    https://keithito.com/LJ-Speech-Dataset/"""
    txt_file = os.path.join(root_path, meta_file)
    items = []
    speaker_name = "ljspeech"
    with open(txt_file, "r", encoding="utf-8") as ttf:
        for line in ttf:
            cols = line.split("|")
            wav_file = os.path.join(root_path, "wavs", cols[0] + ".wav")
            text = cols[2]
            items.append({"text": text, "audio_file": wav_file, "speaker_name": speaker_name, "root_path": root_path})
           print(f'text -> {text}, file -> {wav_file}')
    return items
```
This will help you debug further. 
If you are using phonemizer, maybe print a similar output at the end of the conversion to make sure your text is being cleanly read. I suspect certain log message is being mistakenly appended to your text.
Good luck.

**Comment by prateek-77** [comment]
@p0p4k the training and validation results were normal. The error comes during testing only. I agree with you that certain log message is being mistakenly appended to your text. Do you have any idea about why is it happening and how can I avoid this?

I have checked that the command `tts --text 'As company has expanded its datacenters. to meet demands' --model_name ./model.pth --config_path ./config.json --out_path ./output.wav` is being passed correctly, but the log message is still getting appened during inference. 

Thank you.

**Comment by p0p4k** [comment]
![image](https://user-images.githubusercontent.com/8834712/206402764-80645a31-304a-4593-a199-09cf2f6ce027.png)
I believe the problem is when converting to phonemes. 
If you ignore the `Failed to create secure directory: No such file or directory` error message, rest of the appended gibberish is the phonetized input sentence. 
The error message (when googled), corresponds to something called Pulseaudio. Maybe that could be the root of error instead?
Maybe you can check what the model takes as input after all the phonetizing during training/inference and then debug from there.
Good luck.

**Comment by prateek-77** [comment]
Thank you very much for your help @p0p4k !

**Comment by iamkhalidbashir** [comment]
Same error on lambda

**Comment by iamkhalidbashir** [comment]
@prateek-77 Did you find solution?
It seems this is the solution https://unix.stackexchange.com/questions/89977/pulseaudio-failed-to-create-secure-directory-in-nfs-share
but it dosent work for lambda

**Comment by prateek-77** [comment]
@iamkhalidbashir Can you check if espeak is properly installed on your system?
apt-get install espeak -y

**Comment by iamkhalidbashir** [comment]
Hey @prateek-77 Yes is was installed correctly using `apt install espeak-ng`, I know it because the same image works fine on local system but gives above giberrish audio on lambda. It was because espeak was using pulse audio (even if -q param was provided) and pulse audio was failing because of restricted lambda access

The solution was to compile espeak from source with no pulse audio, and now it works fine.
