### ISSUE TITLE
[Readme] Does not mention API needs to be installed separately

### ISSUE THREAD

**Issue by Iaotle** [coqui-ai/TTS#2209]
![image](https://user-images.githubusercontent.com/43072246/207241754-2911ad13-4f1a-4334-9f26-1d85fc3db08f.png)

This does not mention that the API module (needed to code with TTS) is an optional install. Readme should be amended to mention this option.

**Comment by p0p4k** [comment]
Hello, if you feel something is incorrect in the ReadMe, please add a PR. Every contribution matters to keep this open source project running. Thanks!

**Comment by erogol** [comment]
you don't need to install the API separately. I should be available after `pip install TTS`
