### ISSUE TITLE
Mary-TTS API compatibility 

### ISSUE THREAD

**Issue by fquirin** [coqui-ai/TTS#2227]
Many screen-readers and programs like Mycroft, SEPIA, Home Assistant, etc. support the Mary-TTS HTTP API introduced many years ago to communicate with a TTS system. Coqui TTS would work out-of-the-box with all of these programs if the server could offer a compatible API.
I've listed some endpoints [here](https://github.com/SEPIA-Framework/sepia-assist-server/blob/master/Xtensions/TTS/marytts/INSTALL.md#server-endpoints) (old Javadocs [here](http://mary.dfki.de/javadoc/marytts/server/http/MaryHttpServer.html)). The most important ones (all HTTP GET) are probably:

- `/locales` - returns a list of supported locales in the format `[locale]\n...`
- `/voices` - returns a list of supported voices in the format `[name] [locale] [gender]\n...`. 'name' can be anything without spaces(!), 'locale' is e.g. en_US or de_DE (probably [this](https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html)) and 'gender' is female/male but could be extended with other/custom/diverse or whatever
- `/process?INPUT_TEXT=..text..&INPUT_TYPE=TEXT&LOCALE=[locale]&VOICE=[name]&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE` - Processes the text and returns a wav file. We can probably ignore `INPUT_TYPE`, `OUTPUT_TYPE` and `AUDIO` as I've never seen any program using a different setting.

There is an existing PR by @mhetzi that implemented a bit of the `/process` endpoint: https://github.com/coqui-ai/TTS/pull/2162 . We can build on that.

One issue to solve:

The Coqui TTS [server](https://github.com/coqui-ai/TTS/blob/main/TTS/server/server.py) usually starts with a specific model pre-loaded and does not support hot-swapping of voices. So the questions are:
- Can we support the `VOICE` parameter of the Mary-TTS `/process` endpoint and set an individual voice for each request?
- Or should we simply return the active voice for `/voices`, the active language for `/locales` and ignore the parameter for `/process`?

Any thoughts about that? 🙂

**Comment by fquirin** [comment]
No interest in Mary-TTS compatibility?
I guess the most basic support where we just return the active voice (instead of all available voices) would still be better than nothing and easy to implement 🤔

**Comment by mhetzi** [comment]
Seems liker there is no interest. I too got no comment on my PR.

**Comment by thorstenMueller** [comment]
I think MaryTTS compatibility would be a great enhancement for Coqui TTS.

**Comment by erogol** [comment]
> No interest in Mary-TTS compatibility? I guess the most basic support where we just return the active voice (instead of all available voices) would still be better than nothing and easy to implement 🤔

Your PR is not passing tests 

Though I have no idea about Mary-TTS. It'd be nicer to have a review from someone else familiar with it.

**Comment by fquirin** [comment]
> Your PR is not passing tests

That was not my PR, but I'll try to make a new one, probably next month. The code in the PR can be reused for "basic" support. Any "advanced" support is probably not possible the way the server works (see concerns above).

**Comment by fquirin** [comment]
I've implemented basic support now 🙂: https://github.com/coqui-ai/TTS/pull/2352

**Comment by erogol** [comment]
PR went into dev. Thanks @fquirin for the PR.
