### ISSUE TITLE
[Bug] 5 second delay when calling --help or any other feature from commandline

### ISSUE THREAD

**Issue by chrisbward** [coqui-ai/TTS#2241]
### Describe the bug

There's a 5 second delay, even when I run `tts --help`

```
tts --text "Hello, I'm just testing text to speech for realtime inference"  --model_name "tts_models/en/ljspeech/tacotron2-DCA" --use_cuda true
```

### To Reproduce

Run `tts --help`

or run the following;
```
tts --text "Hello, I'm just testing text to speech for realtime inference"  --model_name "tts_models/en/ljspeech/tacotron2-DCA" --use_cuda true
```

There is a 5 second delay before processing begins.

### Environment

```shell
Ubuntu 20.04
tts installed from latest commit
```

**Comment by p0p4k** [comment]
Not a bug technically. It's just that we didn't optimize the cli command calls for performance. Just a quick TTS run demo.

**Comment by chrisbward** [comment]
ok, got ya - going to spin up the server and stream back outputs instead, thanks!

**Comment by p0p4k** [comment]
Better use the hub file or see synthesis.py.
