### ISSUE TITLE
[Bug] Docker run does not start a server on port 5002

### ISSUE THREAD

**Issue by chrisbward** [coqui-ai/TTS#2250]
### Describe the bug

Hi, Just ran the following to get the GPU server running;

```
docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash ghcr.io/coqui-ai/tts
```

But it seems that I cannot connect to http://0.0.0.0:5002 in the browser.

I can confirm that the docker container is running and can interact with the terminal from the command above.

### To Reproduce

Run the command;
```
docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash ghcr.io/coqui-ai/tts
```
Observe that the server does not run in the browser

### Expected behavior

Should be able to visit the server in the browser

### Environment

```shell
Docker GPU image on Ubuntu 20.04
```

**Comment by chrisbward** [comment]
Oh, checking the docs - you might want me to run `python3 TTS/server/server.py --model_name tts_models/en/vctk/vits --use_cuda true` to start the daemon?

I've not seen that before with containers. The services are usually running already, although I'm now hitting another problem with GPU support...

**Comment by erogol** [comment]
I close this one. You can create a new issue for the new one.
