### ISSUE TITLE
[Feature request] Vall-e implementation

### ISSUE THREAD

**Issue by iamkhalidbashir** [coqui-ai/TTS#2269]
Vall-e by microsoft seems to have out performed the yourTTS model in zero short tts.
Link: https://arxiv.org/abs/2301.02111

**Solution**

An implementation of it would be amazing

**Comment by tekakutli** [comment]
An independent PyTorch implementation  https://github.com/enhuiz/VALL-E

**Comment by erogol** [comment]
We can pull it from there. I hope they will be able to train the model. In my own implementation, the model is prohibitively large and consuming to train.

**Comment by stanleyshly** [comment]
@erogol Someone appears to have trained a model, with some success: [line](https://github.com/lifeiteng/vall-e/issues/58). It took a lot of compute(4 days on 8 A100s).

**Comment by jav-ed** [comment]
There is now also the X version, see: https://vallex-demo.github.io/
