### ISSUE TITLE
[Feature request] Please document how to load a model from a local directory

### ISSUE THREAD

**Issue by padmalcom** [coqui-ai/TTS#2281]
Hi, I trained a vits model and I just want to load it from my local file path. But I'm either blind or it is not documented how to load a (vits) model from a local file path. Looking at the api.py in TTS only describes how to load an online model.

Can you point me to the right doc? Or in case it does not exists, this is a FR to write a short note on how to load local models.

**Comment by padmalcom** [comment]
Okay after some hours I found a working solution but I'm not sure if this is the optimal way.
```
from TTS.api import TTS

from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.models.vits import Vits
from TTS.config import load_config
from TTS.utils.synthesizer import Synthesizer

config = VitsConfig()
model = Vits(config)

config = load_config("config.json")
model = Vits.init_from_config(config)
model.load_checkpoint(config, 'best_model_226300.pth', eval=True)

speakers_file_path = None
language_ids_file_path = None
vocoder_path = None
vocoder_config_path = None
encoder_path = None
encoder_config_path = None
cuda = True

synthesizer = Synthesizer("best_model_226300.pth", "config.json", speakers_file_path, language_ids_file_path, vocoder_path, vocoder_config_path, encoder_path, encoder_config_path, cuda)

speaker_idx = None
language_idx = None
speaker_wav = None
reference_wav = None
style_wav = None
style_text = None
reference_speaker_name = None
wav = synthesizer.tts(
	"Mein Name ist Jonas und ich bin groß!",
	speaker_idx,
	language_idx,
	speaker_wav,
	reference_wav,
	style_wav,
	style_text,
	reference_speaker_name
)
synthesizer.save_wav(wav, "output.wav")
```

**Comment by erogol** [comment]
If you want to synthesize, just use the synthesizer

Otherwise use the way you initially do above, using the model class. It is the right way 👍

**Comment by HenryYuen128** [comment]
> 

@erogol Hi, I have to load the model **tts_models--zh-CN--baker--tacotron2-DDC-GST** from local since the connection problem while downloading. However, i tried method by @padmalcom , got this issue
```python
Traceback (most recent call last):
  File "/data/henry.yuan/code/asr-annotation/ds-free-dataset/get_preannotation_from_tencentASR/tts_make_data_by_model/by_tool.py", line 23, in <module>
    model = Vits.init_from_config(config)
  File "/home/henry.yuan/miniconda3/envs/torch_tf2/lib/python3.8/site-packages/TTS/tts/models/vits.py", line 1728, in init_from_config
    upsample_rate = torch.prod(torch.as_tensor(config.model_args.upsample_rates_decoder)).item()
  File "/home/henry.yuan/miniconda3/envs/torch_tf2/lib/python3.8/site-packages/coqpit/coqpit.py", line 626, in __getattribute__
    value = super().__getattribute__(arg)
AttributeError: 'Tacotron2Config' object has no attribute 'model_args'
```

**Comment by m-aliabbas** [comment]
I am facing the same problem. When I load the model with config file. Its throw an error

`TypeError                                 Traceback (most recent call last)
Cell In [23], line 9
      6 encoder_config_path = None
      7 cuda = True
----> 9 synthesizer = Synthesizer("idrak_pizza/ljspeaks/Trainer_Results/vits_ljspeech-August-15-2023_10+23AM-d0ecbf7/best_model_1008371.pth",  
     10                           'idrak_pizza/ljspeaks/Trainer_Results/vits_ljspeech-August-15-2023_10+23AM-d0ecbf7/config.json',
     11                           speakers_file_path, 
     12                           language_ids_file_path, 
     13                           vocoder_path, 
     14                           vocoder_config_path, 
     15                           encoder_path, 
     16                           encoder_config_path, cuda)

File /usr/local/lib/python3.9/dist-packages/TTS/utils/synthesizer.py:99, in Synthesizer.__init__(self, tts_checkpoint, tts_config_path, tts_speakers_file, tts_languages_file, vocoder_checkpoint, vocoder_config, encoder_checkpoint, encoder_config, vc_checkpoint, vc_config, model_dir, voice_dir, use_cuda)
     96     self.output_sample_rate = self.vocoder_config.audio["sample_rate"]
     98 if vc_checkpoint:
---> 99     self._load_vc(vc_checkpoint, vc_config, use_cuda)
    100     self.output_sample_rate = self.vc_config.audio["output_sample_rate"]
    102 if model_dir:

File /usr/local/lib/python3.9/dist-packages/TTS/utils/synthesizer.py:136, in Synthesizer._load_vc(self, vc_checkpoint, vc_config_path, use_cuda)
    123 """Load the voice conversion model.
    124 
    125 1. Load the model config.
   (...)
    133     use_cuda (bool): enable/disable CUDA use.
    134 """
    135 # pylint: disable=global-statement
--> 136 self.vc_config = load_config(vc_config_path)
    137 self.vc_model = setup_vc_model(config=self.vc_config)
    138 self.vc_model.load_checkpoint(self.vc_config, vc_checkpoint)

File /usr/local/lib/python3.9/dist-packages/TTS/config/__init__.py:91, in load_config(config_path)
     89         data = read_json_with_comments(config_path)
     90 else:
---> 91     raise TypeError(f" [!] Unknown config file type {ext}")
     92 config_dict.update(data)
     93 model_name = _process_model_name(config_dict)

TypeError:  [!] Unknown config file type `

**Comment by naveed81** [comment]
> If you want to synthesize, just use the synthesizer
> 
> Otherwise use the way you initially do above, using the model class. It is the right way 👍

Hey erogol,

I tried to do what you said, like this:
#!/usr/bin/env python
from TTS.api import TTS

from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.models.vits import Vits
from TTS.config import load_config
from TTS.utils.synthesizer import Synthesizer

# config = VitsConfig('vits_telugu_phonemes-November-05-2023_05+17PM-99635193')
# model = Vits(config)

# config = load_config("vits_telugu_phonemes-November-05-2023_05+17PM-99635193/config.json")
# model = Vits.init_from_config(config)
# model.load_checkpoint(config, 'best_model_50232.pth', eval=True)

speakers_file_path = None
language_ids_file_path = None
vocoder_path = None
vocoder_config_path = None
encoder_path = None
encoder_config_path = None
cuda = True

synthesizer = Synthesizer("vits_telugu_phonemes-November-05-2023_05+17PM-99635193/best_model_50232.pth", "vits_telugu_phonemes-November-05-2023_05+17PM-99635193/config.json", speakers_file_path, language_ids_file_path, vocoder_path, vocoder_config_path, encoder_path, encoder_config_path, cuda)

speaker_idx = None
language_idx = None
speaker_wav = None
reference_wav = None
style_wav = None
style_text = None
reference_speaker_name = None
wav = synthesizer.tts(
	"నమస్తే సయ్యద్ అఫ్జల్ హుస్సేన్ గారు",
	speaker_idx,
	language_idx,
	speaker_wav,
	reference_wav,
	style_wav,
	style_text,
	reference_speaker_name
)
synthesizer.save_wav(wav, "output_tel.wav")

but got this error: 
Traceback (most recent call last):
  File "/home/ubuntu/TTS/./infer.py", line 24, in <module>
    synthesizer = Synthesizer("vits_telugu_phonemes-November-05-2023_05+17PM-99635193/best_model_50232.pth", "vits_telugu_phonemes-November-05-2023_05+17PM-99635193/config.json", speakers_file_path, language_ids_file_path, vocoder_path, vocoder_config_path, encoder_path, encoder_config_path, cuda)
  File "/home/ubuntu/TTS/TTS/utils/synthesizer.py", line 101, in __init__
    self._load_vc(vc_checkpoint, vc_config, use_cuda)
  File "/home/ubuntu/TTS/TTS/utils/synthesizer.py", line 138, in _load_vc
    self.vc_config = load_config(vc_config_path)
  File "/home/ubuntu/TTS/TTS/config/__init__.py", line 97, in load_config
    raise TypeError(f" [!] Unknown config file type {ext}")
TypeError:  [!] Unknown config file type 

Can you please point what I am doing wrong?

From the command line, this is working fine:
tts --text "నమస్తే సయ్యద్ అఫ్జల్ హుస్సేన్ గారు" --model_path vits_telugu_phonemes-November-05-2023_05+17PM-99635193/best_model_50232.pth --config vits_telugu_phonemes-November-05-2023_05+17PM-99635193/config.json --out_path output_tel.wav

**Comment by biswas** [comment]
In version `0.27.3` (the one I'm using), you can load a model from your local path using the `TTS` API with the `model_path` and `config_path` args:

```
from TTS.api import TTS

tts = TTS(model_path="/app/tts_models/jenny/model_file.pth",
          config_path="/app/tts_models/jenny/config.json")

# Generate speech and check if it worked (worked for me!)
tts.tts_to_file(text="Hello, this is a test using the local Jenny model.",
                file_path="output.wav")
```
