### ISSUE TITLE
[RFC][Feature request] Loading model onto specific GPU

### ISSUE THREAD

**Issue by jaketae** [coqui-ai/TTS#2282]
## Context

The general API for TTS inference looks like this:

```python
from TTS.api import tts
model = tts("tts_models/en/ljspeech/glow-tts", gpu=True)
```

`gpu` is a `bool`, so users can only specify `True` or `False`.

## Problem

If the user is trying to load the model on a machine with multiple GPU cards, perhaps they might want to do something like

```python
model = tts("tts_models/en/ljspeech/glow-tts", gpu="cuda:1")
```

Although running a script with the `CUDA_VISIBLE_DEVICES` is an option, this could be limiting if the user is dealing with loading multiple models, and they want the specific TTS model to go to `cuda:x` and another NLP model to go to `cuda:y`, for example.

## Proposed Solution

Tracing the `gpu` flag, it appears to be used in places like `synthesizer.py`:

https://github.com/coqui-ai/TTS/blob/14d45b53470d862d4df1966d3984ef883077aa5c/TTS/utils/synthesizer.py#L118-L119

Instead of calling `.cuda()`, perhaps we can make the flag more flexible, say `device`, and call `.to(device)` instead. Obviously, changing the name of the argument would be breaking, so to preserve BC, we should introduce this as another optional keyword argument.

I'm not too familiar with the details of the TTS API, so any feedback would be appreciated!

**Comment by jaketae** [comment]
Unstale

**Comment by Edresson** [comment]
Hi @jaketae,

You can easily select the device using the "CUDA_VISIBLE_DEVICES=1". Using this only GPU 1 will be visible for the Pytorch and it will be forced to use this GPU. Example:

```
CUDA_VISIBLE_DEVICES=1 python3  api.py 
```

You can also use the "torch.cuda.set_device(device_num)" to set the device however I recommend you to use "CUDA_VISIBLE_DEVICES".

**Comment by jaketae** [comment]
@Edresson, thanks for the reply.

I'm aware of `CUDA_VISIBLE_DEVICES`. However, this sets the visibility of GPUs on the script level. If the user is loading multiple models onto the GPU in a single script (e.g., a language model, TTS model, and an image generation model), they might want to load these models to different GPU cards. Using `CUDA_VISIBLE_DEVICES` would force the script to load all models to a single GPU, which is not the desired behavior.

For context, I am building [StoryTeller](https://github.com/jaketae/storyteller), a package that leverages TTS, diffusion, and GPT to create a narrated video of a story. I was wondering if there is a way to specify to which `cuda:x` device a TTS module can be loaded onto. 

If this is not supported in CoquiTTS, I'm happy to open a PR. I'm thinking that the line I cited above can be modified, but if maintainers have other thoughts or design philosophies, I'm happy to hear them as well.

**Comment by erogol** [comment]
I just reopen this if anyone is willing to contribute

**Comment by jaketae** [comment]
@erogol @Edresson, thanks for the reply. 

I'm interested in contributing. Some questions:

1. Is there a policy on deprecation or backward compatibility? One way is using a `device` argument instead of `gpu`, but getting rid of the `gpu` argument would break BC. In this case, should we keep the flag and maybe raise a warning that `gpu` will be deprecated in future releases?
2. Alternatively, we could add a `.to(device)` method directly to the `TTS` or `Synthesizer` class, either by creating these methods or by subclassing from `nn.Module.`

Once there is some agreement around the design, I'll submit a PR soon. Thanks!

**Comment by erogol** [comment]
thanks @jaketae for you interest

I like the second option. I'd not worry about BC since we have not released a major version by definition we don't promise BC. But of course for convenience it'd be nice to do the transition with a warning.

**Comment by jaketae** [comment]
Apologies for the delay; I was carried away by other work and did not get the chance to work on this.

I can still give it a try in the next few weeks, but if anyone else wants to give it a shot, feel free!

**Comment by erogol** [comment]
Feel free to send a PR whenever.

**Comment by jaketae** [comment]
Unstale. WIP draft PR in https://github.com/coqui-ai/TTS/pull/2855.
