### ISSUE TITLE
Windows problem wrong audio output

### ISSUE THREAD

**Issue by Mlaz2022** [coqui-ai/TTS#2290]
### Describe the bug

Hi first thank  you for all your hard work !!!
the problem it's is

i try run model from Greece (Greek) "**tts_models/el/cv/vits**"
and working great in Google Colab test and linux it's correct the output and listen good
the problem it's in windows give wrong output and listen confuse nothing correct
can you please tell me how i can fix this in windows because i working in this system i need please

i test English model and working fine in windows with out any  problem like i face in Greek model i am not sure
if there is the same problem in other language , 

here simple script i use for Greek model

```
from TTS.api import TTS
model_name="tts_models/el/cv/vits"
tts = TTS(model_name=model_name, progress_bar=True, gpu=False)
text = "Μια φορά κι έναν καιρό ήταν ο άνθρωπος" 
tts.tts_to_file(text=text, file_path="greek_windown.wav")
```

Linux OR Google Colab Version **Correct** !!!
https://user-images.githubusercontent.com/102923562/212537781-327de3be-d868-4265-b82b-555be6ae1310.mp4

Windows  Version **Wrong** !!!
https://user-images.githubusercontent.com/102923562/212537819-4f3530d5-a0df-4d1a-8426-2ad29bd6126c.mp4

thank your for your time

### To Reproduce

```
from TTS.api import TTS
model_name="tts_models/el/cv/vits"
tts = TTS(model_name=model_name, progress_bar=True, gpu=False)
text = "Μια φορά κι έναν καιρό ήταν ο άνθρωπος" 
tts.tts_to_file(text=text, file_path="greek_windown.wav")
```

### Expected behavior

give wrong output in windows system

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.1+cpu",
        "TTS": "0.10.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD",
        "python": "3.9.7",
        "version": "10.0.19045"
    }
}
```

**Comment by Mlaz2022** [comment]
i make some more test with other languages and i found this not correct 
also like i notice some others language you can listen same stuff but not 100% the file it's not same if you compare
win with Linux output

now i write the complete wrong models

FORMAT I USE NAME 
MODEL = TEXT

**tts_models/en/blizzard2013/capacitron-t2-c150_v2** = "It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."

**tts_models/de/thorsten/tacotron2-DDC** = "und überzeugen dank feingefühl für den ganz großen leinwand-stoff."

**tts_models/it/mai_female/vits** = "It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."

**tts_models/it/mai_male/vits** = "It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."

**tts_models/el/cv/vits** = "Το ουράνιο τόξο εμφανίζεται όταν οι ακτίνες του ήλιου χτυπούν σταγόνες βροχής στην ατμόσφαιρα της Γης και είναι ένα παράδειγμα διάθλασης μετά την ανάκλαση."

**tts_models/fa/custom/glow-tts** ="سلطان محمود در زمستانی سخت به طلخک گفت که: با این جامه ی یک لا در این سرما چه می کنی " 

i upoload the files to see and compare in linux VS Windows

[test compare win vs linux.zip](https://github.com/coqui-ai/TTS/files/10420413/test.compare.win.vs.linux.zip)

please let me know how i can fix this i want to fix the model 47 **tts_models/el/cv/vits** 
i hope this more help and understand where is the  problem

**Comment by Mlaz2022** [comment]
here script you can test and run to compare in win and linux

```
from TTS.api import TTS

models={
    "tts_models/en/blizzard2013/capacitron-t2-c150_v2":"It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
    "tts_models/de/thorsten/tacotron2-DDC":"und überzeugen dank feingefühl für den ganz großen leinwand-stoff.",
    "tts_models/it/mai_female/vits":"It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
    "tts_models/it/mai_male/vits":"It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
    "tts_models/el/cv/vits":"Το ουράνιο τόξο εμφανίζεται όταν οι ακτίνες του ήλιου χτυπούν σταγόνες βροχής στην ατμόσφαιρα της Γης και είναι ένα παράδειγμα διάθλασης μετά την ανάκλαση.",
    "tts_models/fa/custom/glow-tts":"سلطان محمود در زمستانی سخت به طلخک گفت که: با این جامه ی یک لا در این سرما چه می کنی "
}

for model_name,text in models.items():
    wav_name=model_name.replace("/","--") +".wav"
    tts = TTS(model_name=model_name, progress_bar=True, gpu=False)
    tts.tts_to_file(text=text, file_path=wav_name)
```

**Comment by nanafy** [comment]
Having the exact same issue. The output is nonsense

**Comment by kerlon123depaixao** [comment]
have the same problem any progress?

**Comment by nsourlos** [comment]
same issue here
