### ISSUE TITLE
[Bug] Training multiple TTS models on a single GPU increases step time significantly

### ISSUE THREAD

**Issue by ajaiswal1008** [coqui-ai/TTS#2296]
### Describe the bug

When i am training a single TTS model my step time of the model is around 1.3 seconds. Since i have extra memory in my GPU i want to train another TTS model in parallel. 
When i start training my second model the step time of my model increased from 1.3 to 3.5 . 
Is there any way I can train two models without compromising on the training time? 

### To Reproduce

NA

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A100 80GB PCIe"
        ],
        "available": true,
        "version": "11.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.9.0+cu111",
        "TTS": "0.10.1",
        "numpy": "1.21.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.7.15",
        "version": "#36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022"
    }
}
```

**Comment by shivammehta25** [comment]
I think this is because of CPU instead of GPU, your dataloader might be fighting for resources with each other. can you try setting the num_workers equally? Run a `torch.get_num_threads()` and divide the number equally or proportionally.

**Comment by ajaiswal1008** [comment]
_htop_ shows that the CPU cores are highly underutilised. So i think that can't be the bottleneck

**Comment by erogol** [comment]
It is pretty normal.
