### ISSUE TITLE
[Bug] --list_speaker_idx giving me empty list 

### ISSUE THREAD

**Issue by ZimmanJ** [coqui-ai/TTS#2331]
### Describe the bug

my trained multispeaker with 20 speakers can't give me speaker idx, 
( if i use my speaker names like John it won't infer )
 --list_speaker_idx isn't working ?....   it give me an error  > Available speaker ids: (Set --speaker_idx flag to one of these values to use the multi-speaker model.
{}

I also get the error below.... 

Removing weight norm...
Available speaker ids: (Set --speaker_idx flag to one of these values to use the multi-speaker model.
Traceback (most recent call last):
  File "C:\Users\yells\anaconda3\envs\python38-env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yells\anaconda3\envs\python38-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yells\anaconda3\envs\python38-env\Scripts\tts.exe__main__.py", line 7, in <module>
  File "C:\Users\yells\anaconda3\envs\python38-env\lib\site-packages\TTS\bin\synthesize.py", line 326, in main
    print(synthesizer.tts_model.speaker_manager.ids)
AttributeError: 'NoneType' object has no attribute 'ids'

### To Reproduce

list speaker idx on windows 10

### Environment

```shell
tts version 0.8.0
python version
python version 3.8
os windows
cuda /cunn 11
gpu nvidia rtx5000
conda env
```

**Comment by p0p4k** [comment]
Hello,
can you give me output for following in your CLI ?
`tts --list_speaker_idx --model_name tts_models/en/vctk/vits`
Thanks.

**Comment by ZimmanJ** [comment]
> initialization of speaker-embedding layers.
 > Available speaker ids: (Set --speaker_idx flag to one of these values to use the multi-speaker model.
{'ED\n': 0, 'p225': 1, 'p226': 2, 'p227': 3, 'p228': 4, 'p229': 5, 'p230': 6, 'p231': 7, 'p232': 8, 'p233': 9, 'p234': 10, 'p236': 11, 'p237': 12, 'p238': 13, 'p239': 14, 'p240': 15, 'p241': 16, 'p243': 17, 'p244': 18, 'p245': 19, 'p246': 20, 'p247': 21, 'p248': 22, 'p249': 23, 'p250': 24, 'p251': 25, 'p252': 26, 'p253': 27, 'p254': 28, 'p255': 29, 'p256': 30, 'p257': 31, 'p258': 32, 'p259': 33, 'p260': 34, 'p261': 35, 'p262': 36, 'p263': 37, 'p264': 38, 'p265': 39, 'p266': 40, 'p267': 41, 'p268': 42, 'p269': 43, 'p270': 44, 'p271': 45, 'p272': 46, 'p273': 47, 'p274': 48, 'p275': 49, 'p276': 50, 'p277': 51, 'p278': 52, 'p279': 53, 'p280': 54, 'p281': 55, 'p282': 56, 'p283': 57, 'p284': 58, 'p285': 59, 'p286': 60, 'p287': 61, 'p288': 62, 'p292': 63, 'p293': 64, 'p294': 65, 'p295': 66, 'p297': 67, 'p298': 68, 'p299': 69, 'p300': 70, 'p301': 71, 'p302': 72, 'p303': 73, 'p304': 74, 'p305': 75, 'p306': 76, 'p307': 77, 'p308': 78, 'p310': 79, 'p311': 80, 'p312': 81, 'p313': 82, 'p314': 83, 'p316': 84, 'p317': 85, 'p318': 86, 'p323': 87, 'p326': 88, 'p329': 89, 'p330': 90, 'p333': 91, 'p334': 92, 'p335': 93, 'p336': 94, 'p339': 95, 'p340': 96, 'p341': 97, 'p343': 98, 'p345': 99, 'p347': 100, 'p351': 101, 'p360': 102, 'p361': 103, 'p362': 104, 'p363': 105, 'p364': 106, 'p374': 107, 'p376': 108}

**Comment by ZimmanJ** [comment]
speaker_file is there
"speakers_file": "D:\\train\\vits_vctk-February-09-2023_12+01AM-0000000\\speakers.pth",

but speakers_file.json is **not** there
-

**Comment by karim23657** [comment]
I have the same issue.

**Comment by phamkhactu** [comment]
> speaker_file is there "speakers_file": "D:\train\vits_vctk-February-09-2023_12+01AM-0000000\speakers.pth",
> 
> ## but speakers_file.json is **not** there

Hi @ZimmanJ @karim23657 
I have same issue, How to face with it??


Thank you!

**Comment by Pravekyadav** [comment]
Same issue, got the .pth file, but no .json. Empty list in speaker ids.
Please reply if figured the bug out.
