### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by jjxtra** [coqui-ai/TTS#2335]
**🚀 Feature Description**
Throttle audio generation

Problem:
Using on my server it pegs all 16 cores. I could tolerate 5-10 minutes of generation time with an option to restrict to some number of cores, 1-n where n is total cores on the system.

**Solution**
Provide a max number of threads parameter in the python and command line interfaces.

**Comment by erogol** [comment]
You can try to set `https://pytorch.org/docs/stable/generated/torch.set_num_threads.html`

**Comment by jjxtra** [comment]
Do I need to import anything in my python script for this to work?

```py
import os
import subprocess
import sys
from TTS.api import TTS

# this line here, do I have to import something?
torch.set_num_threads(int)

# requires one argument, the file prefix for the .txt input and the .wav and .mp3 output
file = sys.argv[1]
model = "tts_models/en/ljspeech/vits"

textToSpeak = ""
wavFile = file + '.wav'
oggFile = file + '.ogg'
mp3File = file + '.mp3'
with open(file + '.txt', 'r') as f: textToSpeak = f.read()
tts = TTS(model_name=model, progress_bar=False, gpu=False)
tts.tts_to_file(text=textToSpeak, file_path=wavFile)
subprocess.run(["ffmpeg","-i",wavFile,mp3File])
print(oggFile)
```

**Comment by jjxtra** [comment]
Used this, can close. https://www.geeksforgeeks.org/install-pytorch-on-linux/
