### ISSUE TITLE
[Bug] tacotron2-DDC_ph fails to say some sentences

### ISSUE THREAD

**Issue by Alex25820** [coqui-ai/TTS#2359]
### Describe the bug

I have noticed that "tts_models/en/ljspeech/tacotron2-DDC_ph" fails to say some sentences. One such example is the sentence
`It has been almost two weeks since the US first accused China of floating a spy balloon over its territory.`
retrieved from a [BBC article](https://www.bbc.com/news/world-asia-china-64633990).

When trying to synthesize this sentence I get an audio file saying "It has been almost two weeks". After that the audio file ends. I have tried this with other models and they can handle the sentence just fine.

Here is the audio file (converted to mp4 since GitHub doesn't support wav or mp3)

https://user-images.githubusercontent.com/50142558/220702378-1ef1f57d-9cfa-4674-a3ee-a1164c9b27f5.mp4

### To Reproduce

Run the following command:
`tts --text "It has been almost two weeks since the US first accused China of floating a spy balloon over its territory." --model_name "tts_models/en/ljspeech/tacotron2-DDC_ph" --out_path file_name.wav`

### Expected behavior

The audio file contains the full sentence.

### Logs

```shell
> tts_models/en/ljspeech/tacotron2-DDC_ph is already downloaded.
 > vocoder_models/en/ljspeech/univnet is already downloaded.
 > Using model: Tacotron2
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:/home/alex/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC_ph/scale_stats.npy
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Model's reduction rate `r` is set to: 2
 > Vocoder Model: univnet
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:/home/alex/.local/share/tts/vocoder_models--en--ljspeech--univnet/scale_stats.npy
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Generator Model: univnet_generator
 > Discriminator Model: univnet_discriminator
 > Text: It has been almost two weeks since the US first accused China of floating a spy balloon over its territory.
 > Text splitted to sentences.
['It has been almost two weeks since the US first accused China of floating a spy balloon over its territory.']
ɪt hæz bɪn ɔlmoʊst tu wiks sɪns ðə ʌs fɚst əkjuzd t͡ʃaɪnə əv floʊtɪŋ ə spaɪ bəlun oʊvɚ ɪts tɛɹɪtɔɹi.
 [!] Character '͡' not found in the vocabulary. Discarding it.
 > Processing time: 0.6564991474151611
 > Real-time factor: 0.289887179599974
 > Saving output to tacotron2-DDC-ph-bug.wav
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060 Laptop GPU"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.1+cu117",
        "TTS": "0.11.1",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.6",
        "version": "#1 SMP Wed Nov 23 01:01:46 UTC 2022"
    }
}
```

**Comment by erogol** [comment]
the model can act like this sometimes if the stopnet is not tuned well. It is not a code issue but mostly a model issue. So I close this one. As a fix, I'd suggest fine-tuning the model with a different stopnet loss weight or configuration.

**Comment by mahorad** [comment]
Tacotron2-DDC does not have this cut-off issue but it greatly suffers from hallucination, it will start saying gibberish in no time. Tacotron2-DDC_ph however has no hallucination but the output truncation (sentence cut-offs) are occurring like 3 out of 10 random sentences. I could only find Coqui/Mozilla TTS as the fastest free open source TTS with natural voice that works offline.
I'd appreciate if anyone could point me to  a complete instruction of how to fix this issue.
