### ISSUE TITLE
[Bug]  [!] Model file not found in the output path

### ISSUE THREAD

**Issue by zypotato** [coqui-ai/TTS#2362]
### Describe the bug

I've been trying to download TTS on my M1 Mac for three days and finally succeeded. However, I keep getting an error message saying '[!] Model file not found in the output path.' Could someone please help me? Thank you very much.

### To Reproduce

<img width="871" alt="image" src="https://user-images.githubusercontent.com/102522568/220940176-1efb59ac-0f4b-4ae3-b52b-eb86c8e7f483.png">

from TTS.api import TTS

model_name = TTS.list_models()[0]
tts = TTS(model_name)
wav = tts.tts("This is a test! This is also a test!!", speaker=tts.speakers[0], language=tts.languages[0])

### Environment

```shell
-TTS 0.11.1
-pychram
-conda
-mac m1
```

**Comment by zypotato** [comment]
I just want to convert a piece of text to speech. Can anyone help me please? Thank you very much.

**Comment by erogol** [comment]
if you have stopped the run before it downloaded all the files once, then the folder is there but it missing the necessary files. Remove the tts folder and start again.

**Comment by VjayalakshmiK** [comment]
I am facing the same issue as the OP. the tts folder that you mention does not have any model files; only .py files. Could you clarify how or from where can we the models and configs?

**Comment by pyh007** [comment]
这个问题解决了吗 我也遇到这个问题了
