### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by VjayalakshmiK** [coqui-ai/TTS#2371]
### Describe the bug

For starters, I wanted to try out a simple execution of TTS, for which I used the default command suggested in the repo

```tts --text "Text for TTS" --out_path output/path/speech.mp3```

The model started to download, but it freezes after x% of completion. I tried download for a few other models, and facing the issue.  Any leads on why this might be happening?

### To Reproduce

To reproduce, run the code mentioned in the post

### Environment

```shell
-  "TTS": "0.11.1",
-  "python": "3.9.16",
- "numpy": "1.21.6"
- processor": "Intel64 Family 6 Model 140 Stepping 1, GenuineIntel",
-  "OS": "Windows",
-  "PyTorch_version": "1.13.1+cpu",
```

**Comment by erogol** [comment]
I could not replicate it. It might be a temporary network issue on your/our side.
