### ISSUE TITLE
[Bug] Too-high CPU usage training Hifi-GAN

### ISSUE THREAD

**Issue by shenberg** [coqui-ai/TTS#2375]
### Describe the bug

I'm fine-tuning Hifi-GAN on my own dataset on a GPU with 6 loader workers, and CPU use is through the roof (all 64 cores at ~50% utilization):

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/653972/222684053-3d732680-fed9-4588-ba77-3f7c2a29b0d2.png">
(Note: this is with detailed CPU time tracking enabled, so none of the red kernel time is actually IO-wait, the CPUs are actually spinning)

About the dataset: it's a collection of 5-second .wavs sampled at 22050KHz.

Settings:
I based the code on `recipes/ljspeech/hifigan/train_hifigan.py`, and modified the following fields:

audio config: copied from `recipes/ljspeech/overflow/train_overflow.py`
`data_path` points at my new data
`num_loader_workers` increased to 6.
`dashboard_logger` changed to `'wandb'` (note: I have a [PR open on Trainer](https://github.com/coqui-ai/Trainer/pull/98) fixing WandbLogger)
finally, for compatibility with the ljspeech hifigan checkpoint:
```python
generator_model_params={
         "resblock_type": "1",
         "upsample_factors": [8,8,2,2],
         "upsample_kernel_sizes": [16,16,4,4],
         "upsample_initial_channel": 128,
         "resblock_kernel_sizes": [3,7,11],
         "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]]
     },
```

### To Reproduce

After modifying `train_hifigan.py` as described above, and additionally modifying `Trainer` in order to successfully load old-style GAN vocoder checkpoints (will open a PR for that on Trainer repo), I ran:

```
CUDA_VISIBLE_DEVICES=1 python train_hifigan.py --restore_path ~/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2/model_file.pth
```

### Expected behavior

HifiGAN model trains while CPU usage is capped around 7 whole cores in use (6 for dataloader workers, 1 for main thread).

In practice, I see a `load_average` of 30, so it's 30 cores worth of compute on average, not worst-case.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA TITAN RTX",
            "NVIDIA TITAN RTX"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.1+cu117",
        "Trainer": "v0.0.22",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.9",
        "version": "#141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022"
    }
}
```

**Comment by erogol** [comment]
torch uses the available core by default. You can set it using `torch.set_num_threads`
