### ISSUE TITLE
[Feature request]  Easier running of tts under Windows

### ISSUE THREAD

**Issue by domasofan** [coqui-ai/TTS#2384]
**🚀 Feature Description**

Currently running tts under windows requires a lot of dependencies and tools preinstalled before.
It also requires visual studio installed as well.

**Solution**

Is it possible to compile all the required libraries and tools using py2exe or similar tool?
So it is easier to run and install on Windows?
NVDA which is a screenreader for Windows is also written mostly in Python 3 but also has some various c/c++ libraries.

Would be great if someone could have a look into that.

Greetings and thanks.

**Alternative Solutions**

An alternative which isn't all that handy and convenient is to pack the virtual environment from another computer on which tts was running and moving it over to other computers.
After cleaning the virtual environment with
$ pip  cache purge
and using cleanpy you can bring it down to 1.5 gb without voices.
Though that isn't as said previously all that nice.

**Additional context**

**Comment by erogol** [comment]
We don't use windows. If someone from the community is willing to create/maintain windows' backend, we can go for it.

**Comment by king-dahmanus** [comment]
Ah, this is frustrating! How will it perform on 2 gb of ram and 1 core of cpu under a linux vm?

**Comment by erogol** [comment]
not sure never tried but it should be fine depending on the model.

**Comment by Vuizur** [comment]
I tried applying pyinstaller to get an exe for the server and got this far:

```
# Having Python 3.10 selected
pip install git+https://github.com/coqui-ai/TTS
pip install pyinstaller
pip install numba==0.56.4
pip install numpy==1.23.5
cd TTS/server
pyinstaller server.py --collect-data "jamo" --collect-data "unidic_lite" --collect-all "pycrfsuite" --collect-data "gruut" --add-data "../VERSION;TTS/." --add-data "../.models.json;TTS/." --collect-all "torchaudio" --collect-data "trainer" --collect-all "TTS" --collect-data "librosa" --noconfirm --hidden-import "sklearn.metrics._pairwise_distances_reduction._datasets_pair" --hidden-import "sklearn.metrics._pairwise_distances_reduction._middle_term_computer" 
```

It doesn't work yet, there still needs to be something fixed with flask and index.html. This might also require a tiny change in the TTS code, I didn't look into it further though. But the steps above might be a good starting point if someone wants to continue.

**Comment by TeamDman** [comment]
Thank you Vuizur for your snippet.
Saved me from dependency hell.
Originally was getting `Numpy is not available` because of pytorch

[This post](https://stackoverflow.com/a/75015427/11141271) recommended upgrading numpy to fix this, however that broke numba: https://github.com/numba/numba/issues/8615

Now it's working with
```
numpy 1.23.5
numba 0.56.4
torch 1.13.1+cu117
```

**Comment by thorstenMueller** [comment]
Sorry for barging in, but as it's about Coqui TTS in Windows context i thought these tutorials might be on interest for you:

- Using Coqui TTS on Windows (https://youtu.be/zRaDe08cUIk)
- Training a TTS model on Windows (https://youtu.be/bJjzSo_fOS8)

**Comment by domasofan** [comment]
Hi,

It would be great if it is possible to at least the tts command line tool to be more portable and to be able to use it easier under windows and maybe other OSes as well.
TTS is very important for us blind people and a good TTS is pretty difficult to find.
So if someone finds a good solution that would be a very welcome thing.
We blind use the TTS not just because it is interesting or funny but more for daily use and a lot of text.

Greetings and thanks,
Simon

**Comment by thorstenMueller** [comment]
Btw. @domasofan i've been chatting with @zstanecic from RHVoice on an open issue on adding german to RHVoice which might be an improvement for blind user.
If you find this idea useful, you might want to check this tread.
https://github.com/RHVoice/RHVoice/issues/24#issuecomment-1466388168

**Comment by domasofan** [comment]
Hi Thorsten,

Thanks.
Good idea. 👍

Though i find that both solutions should be considered.
Having multiple options is always a good idea.
Especially in TTS systems and high quality voices.

So I still think we need to have a look into making at least the tts command line tool to be much more portable and easier to install and a switch for the command line tool to convert a text file into speech.

Greetings,
Simon

**Comment by qf63633984** [comment]
good

**Comment by nanafy** [comment]
I am having an issue with MeCab. I run TTS.exe and get this:
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: %1 is not a valid Win32 application.

I put the libmecab.dll in the site-packages folder to get over the import error but now I am faced with this. Anyone deal with this?

**Comment by nanafy** [comment]
> I am having an issue with MeCab. I run TTS.exe and get this: from . import _MeCab ImportError: DLL load failed while importing _MeCab: %1 is not a valid Win32 application.
> 
> I put the libmecab.dll in the site-packages folder to get over the import error but now I am faced with this. Anyone deal with this?

I got it, use python 3.8

**Comment by simeonradivoev** [comment]
for me I hat to put `libmecab.dll` from `C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\lib\site-packages\MeCab` to `C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\MeCab`

**Comment by checksummaster** [comment]
The voodoo line from Vuizur can compile my own Python code I used in my project ...
I made a simple python code that init the tts then send to stdout in binary all text enter in stdin (Similar as Piper that don't support yet Japanese).... 

Then it makes my "Japanese piper"

Thanks.
