### ISSUE TITLE
[Bug] text with .. takes way too long and generate an output file which is too big and has random noise

### ISSUE THREAD

**Issue by kmoulins** [coqui-ai/TTS#2385]
### Describe the bug

when using tts with a sentence that contains '..' it will split a single . as a sentence, which for some reason outputs 2 minutes of random noise.

### To Reproduce

run : `tts --text Guys..`

> Text splitted to sentences.
['Guys.', '.']

wait ~3 minutes (depending on cpu of course)
> Decoder stopped with `max_decoder_steps` 10000

tts_output.wav is around 5MB and lasts 2 minutes with "Guys." followed by random noises.

### Expected behavior

similar behavior as running `tts --text Guys...` :

tts_output.wav is a ~60kB file which only says Guys... and takes a few seconds to generate.

### Logs

```shell
(tts) (base) user@machine:~$ tts --text Guys..
 > tts_models/en/ljspeech/tacotron2-DDC is already downloaded.
 > vocoder_models/en/ljspeech/hifigan_v2 is already downloaded.
 > Using model: Tacotron2
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Model's reduction rate `r` is set to: 1
 > Vocoder Model: hifigan
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 > Text: Guys..
 > Text splitted to sentences.
['Guys.', '.']
   > Decoder stopped with `max_decoder_steps` 10000
 > Processing time: 185.3213918209076
 > Real-time factor: 1.5706047789384927
 > Saving output to tts_output.wav
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.1+cu117",
        "TTS": "0.11.1",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

### Additional context

using ubuntu 20.04 on wsl2
ran inside a venv

**Comment by kmoulins** [comment]
similar issue with quotes after a '.' , I think removing single character sentences after splitting might be a solution to a few issues



In effect, becoming the name it had failed to be imbued with."
 > Text splitted to sentences.
['In effect, becoming the name it had failed to be imbued with.', '"']
Traceback (most recent call last):
  File "script.py", line 114, in <module>
    tts.tts_to_file(text=txt, file_path=filename)
  File "/home/user/tts/lib/python3.8/site-packages/TTS/api.py", line 220, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav)
  File "/home/user/tts/lib/python3.8/site-packages/TTS/api.py", line 183, in tts
    wav = self.synthesizer.tts(
  File "/home/user/tts/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 276, in tts
    outputs = synthesis(
  File "/home/user/tts/lib/python3.8/site-packages/TTS/tts/utils/synthesis.py", line 213, in synthesis
    outputs = run_model_torch(
  File "/home/user/tts/lib/python3.8/site-packages/TTS/tts/utils/synthesis.py", line 50, in run_model_torch
    outputs = _func(
  File "/home/user/tts/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/tts/lib/python3.8/site-packages/TTS/tts/models/tacotron2.py", line 248, in inference
    encoder_outputs = self.encoder.inference(embedded_inputs)
  File "/home/user/tts/lib/python3.8/site-packages/TTS/tts/layers/tacotron/tacotron2.py", line 108, in inference
    o = layer(o)
  File "/home/user/tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/tts/lib/python3.8/site-packages/TTS/tts/layers/tacotron/tacotron2.py", line 40, in forward
    o = self.convolution1d(x)
  File "/home/user/tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/tts/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tts/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (4). Kernel size: (5). Kernel size can't be greater than actual input size

**Comment by erogol** [comment]
It is about the trained model. it sometimes works like this with short inputs since it did not see a lot of short ones while training. I don't think there is an easy fix for that without retraining the model. I close this since it is not a dev issue.

**Comment by jiten634** [comment]
Is there any fix for this? still same in xtts v2.
