### ISSUE TITLE
docker image for mac m1 ship

### ISSUE THREAD

**Issue by ans1genie** [coqui-ai/TTS#2406]
### Describe the bug

no matching manifest for linux/arm64/v8 in the manifest list entries

### To Reproduce

have a mac m1 with apple ship
run `docker pull ghcr.io/coqui-ai/tts-cpu`

> docker pull ghcr.io/coqui-ai/tts-cpu
> 
> Using default tag: latest
> latest: Pulling from coqui-ai/tts-cpu
> no matching manifest for linux/arm64/v8 in the manifest list entries

### Expected behavior

pull the image

### Environment

```shell
Mac with M1 apple ship
```

**Comment by mattcar15** [comment]
Also facing this, any suggestions?

**Comment by crisemcon** [comment]
same here

**Comment by ans1genie** [comment]
[abiosoft/Colima](https://github.com/abiosoft/colima ) could be a solution. If someone have some time can try it and give us the feedback;

**Comment by davidstaab** [comment]
> [abiosoft/Colima](https://github.com/abiosoft/colima) could be a solution. If someone have some time can try it and give us the feedback;

M2 Mac here. I installed and ran it:
```
➜  ~ colima start
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
INFO[0029] provisioning ...                              context=docker
INFO[0029] starting ...                                  context=docker
INFO[0035] done
```
Then ran `docker run --rm -it -p 5002:5002 --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu`

But still got this response
```
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

**Comment by ans1genie** [comment]
@stale reopen.

**Comment by gitsoft** [comment]
Still no progress on this?

**Comment by anton-codes** [comment]
docker pull ghcr.io/coqui-ai/tts-cpu --platform linux/amd64 pulls on MBP M3
