### ISSUE TITLE
[Bug] invalid load key with pickle 

### ISSUE THREAD

**Issue by agent87** [coqui-ai/TTS#2422]
### Describe the bug

# tts --text "Mwaramutseho" --model_path tts/model.pth --encoder_path tts/SE_checkpoint.pth.tar --encoder_config_path tts/config_se.json --config_path tts/config.json --speakers_file_path tts/speakers.pth --speaker_wav tts/conditioning_audio.wav --out_path tts/sounds/sound-1.wav
 > Using model: vits
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 316, in main
    synthesizer = Synthesizer(
  File "/usr/local/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 75, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/usr/local/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 117, in _load_tts
    self.tts_model.load_checkpoint(self.tts_config, tts_checkpoint, eval=True)
  File "/usr/local/lib/python3.10/site-packages/TTS/tts/models/vits.py", line 1692, in load_checkpoint
    state = load_fsspec(checkpoint_path, map_location=torch.device("cpu"), cache=cache)
  File "/usr/local/lib/python3.10/site-packages/TTS/utils/io.py", line 86, in load_fsspec
    return torch.load(f, map_location=map_location, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

### To Reproduce

When running the tts in the docker container under Fast API
https://github.com/agent87/RW-DEEPSPEECH-API.git deployment

### Expected behavior

I should get an output of voice audio

### Environment

```shell
# python collect_env_info.py
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.1+cu117",
        "TTS": "0.10.0",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.10.9",
        "version": "#1 SMP Tue Sep 13 07:51:46 UTC 2022"
    }
}
```

**Comment by Edresson** [comment]
Hi @agent87,

Looks like that your checkpoint "tts/model.pth" is corrupted.  Please try another checkpoint and let me know if the error persists.

**Comment by agent87** [comment]
Solved! Just loaded another checkpoint.
