### ISSUE TITLE
[Feature request] Fine-tuning a vocoder

### ISSUE THREAD

**Issue by XiangyiZhang** [coqui-ai/TTS#2423]
**🚀 Feature Description**

TTS currently allows us to fine-tune a TTS model but it it does not allow us to fine-tune the vocoders. I did not see any example that demonstrates vocders fine-tuning and it seems there is no way to restore a pretrained model before training from scratch. I wonder if there is any specific reason for that or is this a feature to add in the future.

**Solution**

To add the fine-tuning or transfer learning feature for the vocoders.

**Comment by erogol** [comment]
you can finetune vocoders as you finetune TTS models. They have the same API.
