### ISSUE TITLE
[Bug] Speaker manager missing in YourTTS recipe 

### ISSUE THREAD

**Issue by p0p4k** [coqui-ai/TTS#2446]
### Describe the bug

When using the default yourtts recipe for a multispeaker dataset, it wont work. We need to fix it by passing a speakermanager. 

### To Reproduce

run yourtts on multispk dataset.

### Environment

```shell
latest tts version,
py3.10
```

**Comment by erogol** [comment]
@Edresson can you check?

**Comment by p0p4k** [comment]
@Edresson ok thanks. I'll try again and report back.
