### ISSUE TITLE
[Bug] yourTTS Python API Portuguese (and French) not working

### ISSUE THREAD

**Issue by elhombrejd** [coqui-ai/TTS#2458]
### Describe the bug

Python API for yourTTS is not working for Portuguese (and also, it seems, French).  I used the exactly same example as the given one on readme.md.

It gives me a "KeyError: 'pt'"

### To Reproduce

from TTS.api import TTS
tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts")
tts.tts_to_file("Olá, tudo bem?", speaker_wav="teste.wav", language="pt", file_path="output.wav")

### Expected behavior

Generate output.wav with the standard given by speaker_wav.

### Logs

```shell
KeyError: 'pt'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3050 Laptop GPU"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu118",
        "TTS": "0.12.0",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.6",
        "version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021"
    }
```

**Comment by elhombrejd** [comment]
The complete log of the error:

 > Text splitted to sentences.
['Olá, tudo bem?']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/TTS/api.py", line 220, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav)
  File "/root/TTS/api.py", line 183, in tts
    wav = self.synthesizer.tts(
  File "/root/TTS/utils/synthesizer.py", line 253, in tts
    language_id = self.tts_model.language_manager.name_to_id[language_name]
KeyError: 'pt'

**Comment by erogol** [comment]
language code is `pt-br`
