### ISSUE TITLE
Bug in token of Chinese[Bug] 

### ISSUE THREAD

**Issue by ILG2021** [coqui-ai/TTS#2482]
### Describe the bug

I think the tokenize of Chinese language has bug. When I use tts_models/zh-CN/baker/tacotron2-DDC-GST model to synthesis text "你好，晚上好，很高兴认识你", The sound will be very strange. It generate a 12 seconds sound which play the last letter for 8 seconds. But when I give it a end punctuation in the sentence, which is "你好，晚上好，很高兴认识你。", it works ok, the tokenizer don't detect the end of the sentence, just detect by punctuations. I don't know if it has the same problem in other languages.

### To Reproduce

use https://huggingface.co/spaces/coqui/CoquiTTS to test it.
Input Text: "你好，很高兴认识你"
TTS model: tts_models/zh-CN/baker/tacotron2-DDC-GST

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1070 Ti"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu117",
        "TTS": "0.12.0",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.6",
        "version": "#39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2"
    }
}
```

**Comment by sctm002** [comment]
在后面加上中文句号就正常了，“你好，很高兴认识你。”这样。不知道是不是对字的编码的问题。

**Comment by erogol** [comment]
No one knows Chinese in the dev team. We need help for fixing this if there is a fix and a problem.

**Comment by dumengru** [comment]
> 

It's really a pity. Chinese is the most widely used language in the world.

**Comment by shawhu** [comment]
> No one knows Chinese in the dev team. We need help for fixing this if there is a fix and a problem.

i'll help you if you guys needed.
i know chinese and i'm a dev too

**Comment by dumengru** [comment]
> > No one knows Chinese in the dev team. We need help for fixing this if there is a fix and a problem.
> 
> i'll help you if you guys needed. i know chinese and i'm a dev too

Can you provide a demo or recipes for Chinese training?

**Comment by erogol** [comment]
@shawhu if you are up to help, these are the relevant files. 

https://github.com/coqui-ai/TTS/blob/56ba616a0356655ae78e9bfe5d93546bcf0fe46b/TTS/tts/utils/text/phonemizers/zh_cn_phonemizer.py

https://github.com/coqui-ai/TTS/blob/209ee40c8811e23a6e753d30627cf054f399532b/TTS/tts/utils/text/chinese_mandarin

You can also see the test here. But it has no test case.

https://github.com/coqui-ai/TTS/blob/724360d71a6c5ee9284ceb51682f7aa6a4f5cd6c/tests/text_tests/test_phonemizer.py#L212

**Comment by shawhu** [comment]
> @shawhu if you are up to help, these are the relevant files.
> 
> https://github.com/coqui-ai/TTS/blob/56ba616a0356655ae78e9bfe5d93546bcf0fe46b/TTS/tts/utils/text/phonemizers/zh_cn_phonemizer.py
> 
> https://github.com/coqui-ai/TTS/blob/209ee40c8811e23a6e753d30627cf054f399532b/TTS/tts/utils/text/chinese_mandarin
> 
> You can also see the test here. But it has no test case.
> 
> https://github.com/coqui-ai/TTS/blob/724360d71a6c5ee9284ceb51682f7aa6a4f5cd6c/tests/text_tests/test_phonemizer.py#L212

i'll take a look and see what i can do.

**Comment by shawhu** [comment]
> @shawhu I think a simple start would be just running the phonemizer and seeing if outputs make sense. If not then we can discuss what is the problem and try to fix it. Makes sense?

ok sure, i'll try and let you know the results

**Comment by erogol** [comment]
> 

sounds good. If it works then we can use a part of it in the test too.
