### ISSUE TITLE
[Bug] Voice synthesizing problem after comma in text

### ISSUE THREAD

**Issue by SerhanCeetin** [coqui-ai/TTS#2497]
### Describe the bug

I am trying to produce a sound using this sentence:
"Many of us fall victim to common time management mistakes such as procrastination, failing to prioritize effectively, and succumbing to distractions."

But after the "procrastination," word, it doesn't synthesize a sound.
If I change the comma's position from "procrastination," to another word or delete it, it works properly. I don't understand what the problem is.

### To Reproduce

The complete code to reproduce the problem:
```
from TTS.api import TTS
import IPython.display as ipd
tts = TTS("tts_models/en/ljspeech/tacotron2-DDC_ph")
wav = tts.tts("Many of us fall victim to common time management mistakes such as procrastination, failing to prioritize effectively, and succumbing to distractions.")
ipd.Audio(wav, rate=22050)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cpu",
        "TTS": "0.13.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel",
        "python": "3.9.16",
        "version": "10.0.22621"
    }
}
```

**Comment by erogol** [comment]
it is about the model. There is not much to do except training more and with better data.
