### ISSUE TITLE
[Bug] Cannot synthesize via API because of self.model_name None

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [coqui-ai/TTS#2525]
### Describe the bug

Hi, 

I trained a VITS model following the recipe. 

Now I try to synthesize speech via the API but it fails because `self.model_name` is None.
So 
https://github.com/coqui-ai/TTS/blob/e4c5c27854782bcda5ee0539dac32a7e4c8fa735/TTS/api.py#L306
cannot be evaluated.

### To Reproduce

Follow the readme part on inference via api on a VITS model.

### Environment

```shell
Latest coqui version (0.13.2)
```

**Comment by erogol** [comment]
this is fixed in the latest release
