### ISSUE TITLE
[Bug] Voice conversion with your_tts throws an error: AttributeError: 'NoneType' object has no attribute 'voice_conversion'

### ISSUE THREAD

**Issue by chigkim** [coqui-ai/TTS#2528]
### Describe the bug

Voice conversion with your_tts throws an error: AttributeError: 'NoneType' object has no attribute 'voice_conversion'

### To Reproduce

tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=False, gpu=True)
source = base+"/source.wav"
target = base+"/target.wav"
out = base+"/output.wav"
tts.voice_conversion_to_file(source_wav=source, target_wav=target, file_path=out)

### Expected behavior

Produce output.wav.

### Logs

```shell
/content/TTS/TTS/api.py
 in voice_conversion(self, source_wav, target_wav)
    591                 Path to the target wav file.
    592         """
--> 593         wav = self.voice_converter.voice_conversion(source_wav=source_wav, target_wav=target_wav)
    594         return wav
    595 
AttributeError: 'NoneType' object has no attribute 'voice_conversion'
```

### Environment

```shell
aColab with latest from git.
```

**Comment by rising-entropy** [comment]
Hello!
Able to reproduce the same. It's happening because there is no check in place that loads up a VC_model if not found already.
Preparing a PR for the same

**Comment by erogol** [comment]
This is not the intended use

```
tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=False, gpu=True)
source = base+"/source.wav"
target = base+"/target.wav"
out = base+"/output.wav"
tts.voice_conversion_to_file(source_wav=source, target_wav=target, file_path=out)
```

YourTTS is not a voice conversion model. It is a TTS model.

**Comment by chigkim** [comment]
Actually, YourTTS can do both TTS as well as voice conversion!
It just doesn't work through API.

"YourTTS: Towards Zero-Shot Multi-Speaker TTS and Zero-Shot Voice Conversion for everyone"

```
To use the 🐸 TTS released YourTTS model for voice conversion use the following command:
tts --model_name tts_models/multilingual/multi-dataset/your_tts  --speaker_wav target_speaker_wav.wav --reference_wav  target_content_wav.wav --language_idx "en"
Considering the "target_content_wav.wav" as the reference wave file to convert into the voice of the "target_speaker_wav.wav" speaker.
```

**Comment by gitmylo** [comment]
So i guess we'll need to do some manual steps to get it working?

**Comment by VietDo26** [comment]
> Hello! Able to reproduce the same. It's happening because there is no check in place that loads up a VC_model if not found already. Preparing a PR for the same



> Hello! Able to reproduce the same. It's happening because there is no check in place that loads up a VC_model if not found already. Preparing a PR for the same

Excuse me, How i can fix this in code ?

**Comment by VietDo26** [comment]
> Hello! Able to reproduce the same. It's happening because there is no check in place that loads up a VC_model if not found already. Preparing a PR for the same



> Hello! Able to reproduce the same. It's happening because there is no check in place that loads up a VC_model if not found already. Preparing a PR for the same

@rising-entropy excuse me, How I can fix this ?
