### ISSUE TITLE
[Bug] Microsoft C++ Build tools installed but not found during pip install

### ISSUE THREAD

**Issue by anphex** [coqui-ai/TTS#2546]
### Describe the bug

I try to run the very first installation command
`pip install TTS `

At some point this error is reached:

`  building 'TTS.tts.utils.monotonic_align.core' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`  

### To Reproduce

Trying to run 
`pip install TTS `
from Jupyter Notebook and terminal, both with same error while having a fresh install of the build tools.

### Expected behavior

Successful installation of TTS via pip.

### Logs

```shell
https://pastebin.com/2mnD1CDH
```

### Environment

```shell
Traceback (most recent call last):
  File "C:\Users\Constantin\collect_env_info.py", line 48, in <module>
    main()
  File "C:\Users\Constantin\collect_env_info.py", line 43, in main
    details = {"System": system_info(), "CUDA": cuda_info(), "Packages": package_info()}
  File "C:\Users\Constantin\collect_env_info.py", line 38, in package_info
    "TTS": TTS.__version__,
AttributeError: module 'TTS' has no attribute '__version__'
```

### Additional context

Environment: Anaconda with Python 3.9.16

**Comment by anphex** [comment]
I had Visual Studio Community 2022 installed but without Desktop Developement C++ Tools. 
I installed the Build Tools that are linked to in the error message but these don't work.
After some googling I ran the Visual Studio Installer, installed the Desktop Developement C++ Tools.
Then it worked via `pip install TTS`

**Comment by thorstenMueller** [comment]
Just in case it's useful for future. I've made a technical tutorial for Coqui TTS on Windows (incl. VS stuff 😉 ).
https://youtu.be/zRaDe08cUIk
