### ISSUE TITLE
[Bug] " No module named 'TTS.tts.utils.text.symbols"

### ISSUE THREAD

**Issue by beew** [coqui-ai/TTS#2574]
### Describe the bug

I am trying to run this note book https://github.com/coqui-ai/TTS/blob/dev/notebooks/ExtractTTSpectrogram.ipynb

and it failed in the first cell with 

" No module named 'TTS.tts.utils.text.symbols"

### To Reproduce

run the note book

### Expected behavior

It should run.

### Environment

```shell
TTs version 0.11.1

pytorch version 2.0.0+cpu

python 3.10.9

No cuda

OS Ubuntu 22.04
```

**Comment by erogol** [comment]
Notebooks are out of sync, unfortunately.
