### ISSUE TITLE
Unity 2022 Plugin

### ISSUE THREAD

**Issue by giorgosgs** [coqui-ai/TTS#2589]
Hi

I just found this project and it looks amazing. Both the TTS and the STT part.
There is only one thing missing to make this project the default choice for Unity Indie game creators and smaller sized companies.

1) A simple to use Unity plugin or Unity Package (through package manager) is needed here.
For both TTS and STT.
2) A license to use it in our games commercially.
3) The plugin must work in both desktops, consoles and mobiles.

Thanks

**Comment by erogol** [comment]
Do you have any pointers about how to do that?

**Comment by giorgosgs** [comment]
I suppose you first need .NET support for Unity. This would be much cleaner.
But as I remember there is a native Python Unity package: See here: https://docs.unity3d.com/Packages/com.unity.scripting.python@6.0/manual/index.html
So you could be able to run the plugin with this python package in unity. But I don't know if this can be done.

There is a small discussion about this at STT here: https://github.com/coqui-ai/STT/discussions/1802
In STT there is some progress here: https://bitbarrelmedia.wordpress.com/2021/09/19/coqui-stt-in-unity/

thanks for your quick answer

**Comment by erogol** [comment]
Thanks for the links. I'll take a look.

**Comment by giorgosgs** [comment]
Unity or Unreal engine full support is the way to make this project super popular.

**Comment by giorgosgs** [comment]
Did you take have a chanceto take a look?

**Comment by erogol** [comment]
not yet sorry

**Comment by giorgosgs** [comment]
Unity provides the ability to embed Python code directly into your C# scripts using the IronPython library. Can someone try and see if we can make this a unity plugin?

**Comment by giorgosgs** [comment]
If other Unity developers think that this kind of TTS library would be perfect as a unity plugin to use in our multiplatform games, open sourced and with no limitations, then we can gather here and hire some skilled developers to port it. What do you think?

**Comment by erogol** [comment]
Integrating TTS into Unity is a fantastic idea. Unfortunately, we are currently occupied with other tasks, we don't have the necessary time to dedicate to this. Nevertheless, if someone is willing to assist, I can provide guidance throughout the process.

**Comment by Bamboy** [comment]
I'm a long time unity/C# user. This is the first I have heard of python support in unity, but then again I don't keep a close eye on the latest unity features.
A unity plugin is really just a bunch of files that you import into your unity project subdirectory (packages are slightly different but the same idea)

Its been years and years since I did any python. Is it possible to compile into a DLL? If you can, that might be the easiest approach.

**Comment by giorgosgs** [comment]
If its compiled into a DLL will that work for multi-platforms in Unity?

**Comment by Bamboy** [comment]
Yes I think so.

**Comment by erogol** [comment]
Can we run the TTS as a local service and call it from Unity? Probably it'd be easier if possible.

**Comment by giorgosgs** [comment]
A guy has already run this in unity by importing and using python and running a python server. https://github.com/HardCodeDev777/UnityNeuroSpeech?tab=readme-ov-file
After 2 years we still need a clean unity c# solution..
