### ISSUE TITLE
Get word boundaries with TTS output

### ISSUE THREAD

**Issue by osolmaz** [coqui-ai/TTS#2593]
**🚀 Feature Description**

"Word boundaries" map positions in the input text string to time offsets in the synthesized speech output. For example, Azure TTS returns this information:

See for example: https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechsynthesiswordboundaryeventargs

I use this functionality in [Manim Voiceover](https://github.com/ManimCommunity/manim-voiceover) for getting the timing of words and triggering animations at a specific word.

I already implemented this functionality for a previous version of Coqui here: https://github.com/ManimCommunity/manim-voiceover/blob/0726b6909b98ec57c82318d85cacc5da749b6008/manim_voiceover/services/coqui/utils_synthesizer.py#L284-L353

Now that the Python API for Coqui is maturing, I would like to deprecate the custom Coqui logic in Manim Voiceover and depend on native functionalities.  

**Solution**

- [ ] TTS calls should output word boundary info alongside the generated audio.

The output schema and data that Azure TTS uses (see above) has been comprehensive enough for use in Manim Voiceover until now. I think if Coqui were to implement this feature, it should output using the same schema for the sake of interoperability.

A single word boundary looks like the following:

```json
{
  "audio_offset": 500000,
  "duration_milliseconds": 212,
  "text_offset": 0,
  "word_length": 4,
  "text": "This",
  "boundary_type": "Word"
}
```

> **Warning**
>
> Note that `audio_offset` is in 1e-7 seconds (or 1e-4 milliseconds), but `duration_milliseconds` is in milliseconds. `text_offset` is the distance from the beginning of the input string. `boundary_type` is an enum—check out Azure docs for more info.

See below example for how I store output from Azure in Manim Voiceover. You can see the input text, the array of multiple word boundaries and metadata related to TTS.

```json
{
  "input_text": "This circle is drawn as I speak.",
  "input_data": {
    "input_text": "This circle is drawn as I speak.",
    "ssml": "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\"\n    xmlns:mstts=\"https://www.w3.org/2001/mstts\" xml:lang=\"en-US\">\n    <voice name=\"en-US-AriaNeural\">\n        <mstts:express-as style=\"newscast-casual\">\n    This circle is drawn as I speak.\n</mstts:express-as>\n    </voice>\n</speak>\n        ",
    "service": "azure",
    "config": {
      "voice": "en-US-AriaNeural",
      "style": "newscast-casual",
      "output_format": "Audio48Khz192KBitRateMonoMp3",
      "prosody": null
    }
  },
  "ssml": "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\"\n    xmlns:mstts=\"https://www.w3.org/2001/mstts\" xml:lang=\"en-US\">\n    <voice name=\"en-US-AriaNeural\">\n        <mstts:express-as style=\"newscast-casual\">\n    This circle is drawn as I speak.\n</mstts:express-as>\n    </voice>\n</speak>\n        ",
  "word_boundaries": [
    {
      "audio_offset": 500000,
      "duration_milliseconds": 212,
      "text_offset": 0,
      "word_length": 4,
      "text": "This",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 2750000,
      "duration_milliseconds": 412,
      "text_offset": 5,
      "word_length": 6,
      "text": "circle",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 7000000,
      "duration_milliseconds": 125,
      "text_offset": 12,
      "word_length": 2,
      "text": "is",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 8375000,
      "duration_milliseconds": 350,
      "text_offset": 15,
      "word_length": 5,
      "text": "drawn",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 12000000,
      "duration_milliseconds": 100,
      "text_offset": 21,
      "word_length": 2,
      "text": "as",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 13125000,
      "duration_milliseconds": 125,
      "text_offset": 24,
      "word_length": 1,
      "text": "I",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 14500000,
      "duration_milliseconds": 512,
      "text_offset": 26,
      "word_length": 5,
      "text": "speak",
      "boundary_type": "Word"
    },
    {
      "audio_offset": 19750000,
      "duration_milliseconds": 100,
      "text_offset": 31,
      "word_length": 1,
      "text": ".",
      "boundary_type": "Punctuation"
    }
  ],
  "original_audio": "vermont-shade-finch-colorado.mp3",
  "final_audio": "vermont-shade-finch-colorado.mp3"
}
```

AFAIU [my previous implementation](https://github.com/ManimCommunity/manim-voiceover/blob/0726b6909b98ec57c82318d85cacc5da749b6008/manim_voiceover/services/coqui/utils_synthesizer.py#L284-L353) should be a good starting point. Let me know if you need further information from my side.

**Comment by erogol** [comment]
@osolmaz would you mind sending a PR for the new API?

**Comment by osolmaz** [comment]
@erogol can you elaborate?

I can try to adapt my implementation, but I'm not sure it will work out of the box with the current version (I had errors when I tried to use it with TTS v0.13.3)

I'm also not sure about the interface, like how the word boundaries should be returned, or whether they should be saved to a directory. How should it be according to the convention up until now?

**Comment by erogol** [comment]
what is the error when you use v0.13.3?

**Comment by Jameeehhhh** [comment]
Is there any update on this, since this seems like a really useful feature?

**Comment by osolmaz** [comment]
@Jameeehhhh I don't have any time to implement this, but maybe the devs will consider taking it on if more people advocated for it.

**Comment by erogol** [comment]
I don't think this will be something in our scope anytime soon. If anyone is willing to take on, happy to guide them.

**Comment by nise** [comment]
I am thinking about doing it. Could anyone tell me where and how to start?
