### ISSUE TITLE
[Bug] Docker image size

### ISSUE THREAD

**Issue by jangrewe** [coqui-ai/TTS#2594]
### Describe the bug

Hi, the Docker image you're creating is quite huge, and i noticed that you keep `/root/.cache/pip`, which contains a *2.6GB* file.

I'm pretty sure the pip cache can be deleted when building the image...

### To Reproduce

```
$ docker run --rm -it --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu:latest
root@30caa77e39b1:~# du -h /root/.cache/ | sort -h | tail -n1
2.7G    /root/.cache/pip
```

### Expected behavior

The pip cache is not baked into the image

### Environment

```shell
Current `latest` tag of the Docker image.
```

### Additional context
Add this into the Dockerfile after the last `pip install ...`
```
rm -r /root/.cache
```

**Comment by erogol** [comment]
fixed by #2600
