### ISSUE TITLE
[Bug] Error when trying to run tortoise v2 model

### ISSUE THREAD

**Issue by basel45rob** [coqui-ai/TTS#2623]
### Describe the bug

Hi, 
I am trying to run the Tortoise model in tts-server but get an error.

I installed coqui environment on windows 10. I tried using venv and conda (separate installations) , other models such as vits or tacotron are working.  If I am running CLI tts --model_name tts_models/en/multi-dataset/tortoise-v2 --text "This is a tortoise test string" --use_cuda True --out_path L:\test.wav it is working fine.

when running : tts-server --model_name tts_models/en/multi-dataset/tortoise-v2 --use_cuda true I get an error

My steps were:  (for venv) 

git clone coqui 
create venv
install requirements 
running tts with text sample for vits/tacotron/tortoise  - working
running tts-server with vits/tacotron - working 
running tts-server with tortoise - not working

no errors during installation. 

when running tts-server with tortoise I get the following error: 

```
(coqui) L:\coqui2>tts-server --model_name tts_models/en/multi-dataset/tortoise-v2 --use_cuda true
 > tts_models/en/multi-dataset/tortoise-v2 is already downloaded.
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "L:\coqui2\coqui\Scripts\tts-server.exe\__main__.py", line 4, in <module>
  File "L:\coqui2\coqui\lib\site-packages\TTS\server\server.py", line 104, in <module>
    synthesizer = Synthesizer(
  File "L:\coqui2\coqui\lib\site-packages\TTS\utils\synthesizer.py", line 89, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "L:\coqui2\coqui\lib\site-packages\TTS\utils\synthesizer.py", line 164, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "L:\coqui2\coqui\lib\site-packages\TTS\config\__init__.py", line 79, in load_config
    ext = os.path.splitext(config_path)[1]
  File "C:\Program Files\Python310\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I tried deleting the cache folder and redownloading, didnt work. 
Can you help me solve this please. 
Thank you.

### To Reproduce

Installing a fresh install. 
Running tts-server command for tortoise.

### Environment

```shell
TTS 0.14.0
python 3.10.2
pytorch 2.0.0 
cuda 11.7 
windows 10 
python venv
```

**Comment by erogol** [comment]
The server is not yet compatible. We'll drop the current server implementation. Try using the Python API or CLI
