### ISSUE TITLE
[Feature request] Direct Java access

### ISSUE THREAD

**Issue by madhephaestus** [coqui-ai/TTS#2630]
**🚀 Feature Description**

As a Java Developer, I would like access to this voice synthesis from within the JVM environment. There are many ways to accomplish this, and that is a good topic for discussion. In the meantime, I have worked up and tested a solution for anyone in the same boat as me. I was looking for a Java TTS engine using WaveNet technology, and came up short. My hope is that even if java support is not official added, then this issue can serve as a breaadcrumb trail for someone willing to work to get it working for themselves. 

**Solution**

I added com.github.dockerjava to my project as well as OkHTTP. I use the docker manager to load up a Dockerfile that extends the regular docker release with pre-caching the voice packs i intend to use, and changing the  starting conditions. 

https://github.com/Halloween2020TheChild/CoquiDocker/blob/main/Dockerfile

Then i wrote a small management class in Java to load the Docker image, and launch the server.py within the Docker, with the voice configurable by the user in Java. Then the TTS server is communicated with by OkHTTP to send the text and receive the audio. 

https://github.com/CommonWealthRobotics/bowler-script-kernel/blob/2f63daca4153e9cf97b5d31f534e5c051bad6720/src/main/java/com/neuronrobotics/bowlerstudio/CoquiDockerManager.java

**Alternative Solutions**

I was hoping to be able to load the network using the DeepJavaLibrary https://github.com/deepjavalibrary/djl to make the solution pure Java. Unfortunately that was more of a lift than i was able to muster for my project, and the Docker wrapping worked very well. I think it would be worthwhile to have a pure DJL implementation to make these voices accessible across all platforms. 

**Additional context**

For anyone interested, i am building a modern Zoltar fortune telling machine with the most advance neural nets i can get my hands on, check it out if your are interested: https://github.com/Halloween2020TheChild/Zoltar

This java layer that  i am putting up as a solution example is adding Coqui to BowlerStudio, a free, open source, robotics control engine: https://commonwealthrobotics.com/

**Comment by lexkoro** [comment]
You should be able to export the VITS model to onnx https://github.com/coqui-ai/TTS/pull/2563#issue-1686770580 
and then directly run it form JAVA using https://onnxruntime.ai/docs/get-started/with-java.html

**Comment by madhephaestus** [comment]
> You should be able to export the VITS model to onnx [#2563 (comment)](https://github.com/coqui-ai/TTS/pull/2563#issue-1686770580) and then directly run it form JAVA using https://onnxruntime.ai/docs/get-started/with-java.html

This is very exciting as an idea. I am at a loss for how to map the waveform sources to the result from processing the net. If someone who knows the Coqui stack could help with the data processing, i can build a project and publish it to Maven for all other JVM developers.
