### ISSUE TITLE
[Bug] Issue with Distributed training on 8 GPUs, empty logs

### ISSUE THREAD

**Issue by scape7575** [coqui-ai/TTS#2632]
### Describe the bug

So I have been trying to get distributed training working with Tacotron2, GlowTTS, VITS, and FastSpeech2, all to the same end. What happens is that It starts training as normal, but upon checking the trainer_1_log.txt there is nothing inside, while trainer_0_log.txt has logs. I am unsure if the this means that it is only training on one GPU or more, as all the other logs other than trainer_0_log.txt are empty. 

### To Reproduce

an example of one of the commands I use to run the training is: python3 -m trainer.distribute --gpus "5,6" --script train_ar_glow.py

### Expected behavior

Training starts on all gpus

### Logs

```shell
> Training Environment:
 | > Current device: 0
 | > Num. of GPUs: 2
 | > Num. of CPUs: 80
 | > Num. of Torch Threads: 40
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 > Start Tensorboard: tensorboard --logdir=/root/recipes/ljspeech/glow_tts/run-May-24-2023_12+29PM-0000000
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu118",
        "TTS": "0.14.0",
        "numpy": "1.23.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.6",
        "version": "#64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020"
    }
}
```

### Additional context

Upon using the nvidia-smi command, I can see that there is ram being taken by the training from all the gpus mentioned from the command

**Comment by littleGiant-28** [comment]
I am facing the same issue, can anyone provide closure on this issue? Thanks.
