### ISSUE TITLE
IndexError in train.py demo

### ISSUE THREAD

**Issue by guighub** [coqui-ai/TTS#2652]
### Describe the bug

I tried the train.py demo in Python 3.10 Ubuntu but I get this error:
```
line 59, in <module>
    train_samples, eval_samples = load_tts_samples(
IndexError: list index out of range
```

### To Reproduce

Run any training demo (example: recipes/ljspeech/vits-tts/train_vits.py

### Expected behavior

No error

### Environment

```shell
TTS Version: 1.14.0
Python 3.10.6
Ubuntu 22.04.2 LTS
```

**Comment by erogol** [comment]
are you sure you set the dataset correctly? I think you have an empty list of samples.

**Comment by guighub** [comment]
That would be defined in the .csv file right? I put the name of each file followed by the transcript separated by |.

**Comment by JagarYousef** [comment]
Shouldn't it be `text=cols[1]`:
![image](https://github.com/coqui-ai/TTS/assets/41321155/63cad4d9-c4f3-4536-bfcc-c1e9eeb7fff9)

**Comment by Edresson** [comment]
> Shouldn't it be `text=cols[1]`: ![image](https://user-images.githubusercontent.com/41321155/244962851-63cad4d9-c4f3-4536-bfcc-c1e9eeb7fff9.png)
> 
> https://github.com/coqui-ai/TTS/blob/2d967b786db36325f629228d7f350e0120b41c8c/TTS/tts/datasets/formatters.py#LL162C1-L163C1

LJ Speech has two text columns, cols[1] and cols[2]. Most of the LJSpeech data loader implementations use the second one that is already preprocessed and ready for most all model's training. The second column has numbers expanded for example (Line example: LJ001-0045|1469, 1470;|fourteen sixty-nine, fourteen seventy;).

@guighub You need to recreate your metadata file in the format "audio_name"| text | preprocessed_text" to be able to use the LJ Speech formatter. Feel free to write your own formatter or use others like "coqui" that receives a pandas-compatible TSV/CSV as input.
