### ISSUE TITLE
environment variable for tts home

### ISSUE THREAD

**Issue by xunxky** [coqui-ai/TTS#2680]
Hi I have noticed that `get_user_data_dir` will unceremoniously use the `.local/share/<appname>`  folder and similar "home"-folders on other platforms

**Solution**

     ans = os.getenv('COQUI_HOME_PREFIX')
     if ans is not None: 
         return Path(ans).joinpath(appname)

**Alternative Solutions**

**Additional context**

I simply would like to use a different folder for the models.

**Comment by reuben** [comment]
Instead of creating a new var, using [$XDG_DATA_HOME](https://pyxdg.readthedocs.io/en/latest/basedirectory.html#xdg.BaseDirectory.xdg_data_home) would allow customization while also conforming with standards.

**Comment by erogol** [comment]
I am ok with any solution above that would work on different platforms. Feel free to send a PR.

**Comment by TheFoxarmy** [comment]
Anyone working on a PR for this already? If not I might look into it?

**Comment by erogol** [comment]
@TheFoxarmy feel free to take on

**Comment by WeberJulian** [comment]
Closing as solved by this: https://github.com/coqui-ai/TTS/pull/2871
