### ISSUE TITLE
TTS Performance benchmark lacks information

### ISSUE THREAD

**Issue by ostwilkens** [coqui-ai/TTS#2706]
### Describe the bug

I spent a lot of time googling for the seemingly legendary TTS models "Jofish" and "Abe". 
Didn't find anything about them, but Judy is supposedly an "official" 🐸TTS model, but for some reason it's not in TTS.list_models(). 
After way too long I found https://github.com/coqui-ai/TTS/wiki/MOS-Results. 
Please make it clear that Jofish and Abe are not TTS directly in the readme. 

### To Reproduce

n/a

### Environment

```shell
n/a
```

**Comment by erogol** [comment]
you can send a or
