### ISSUE TITLE
[Bug] Tortoise tts doesn't work with Docker image on a cpu

### ISSUE THREAD

**Issue by springcoil** [coqui-ai/TTS#2716]
### Describe the bug

root@e901f80c5317:~# python3 TTS/server/server.py --model_name tts_models/en/multi-dataset/tortoise-v2
 > Downloading model to /root/.local/share/tts/tts_models--en--multi-dataset--tortoise-v2
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
Traceback (most recent call last):
  File "/root/TTS/server/server.py", line 104, in <module>
    synthesizer = Synthesizer(
  File "/root/TTS/utils/synthesizer.py", line 91, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/root/TTS/utils/synthesizer.py", line 181, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "/root/TTS/config/__init__.py", line 79, in load_config
    ext = os.path.splitext(config_path)[1]
  File "/usr/local/lib/python3.10/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Is what I get. 

### To Reproduce

docker run --rm -it -p 5002:5002 --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu
python3 TTS/server/server.py --list_models #To get the list of available models
python3 TTS/server/server.py --model_name tts_models/en/multi-dataset/tortoise-v2

### Expected behavior

I expected the moodel to run 

But might be better to run this on sagemaker

### Environment

```shell
Latest TTS version
```

**Comment by erogol** [comment]
Server doesn't support Tortoise. Also running Tortoise on cpu would take ages. FYI
