### ISSUE TITLE
[Bug] Bark model fails with Config for Bark not found

### ISSUE THREAD

**Issue by thefex** [coqui-ai/TTS#2722]
### Describe the bug

Using the most basic tts command - new Bark model fails - both using pip install and clean make from develop branch. It failed on Mac M1 and in **Google Codelabs env**. 
 
I looked at source code and it seems that register_config uses deprecated imp.find_module - maybe that is the reason?

### To Reproduce

 tts --model_name tts_models/multilingual/multi-dataset/bark --text "This is an example." --out_path "output.wav" --progress_bar True
 
 > tts_models/multilingual/multi-dataset/bark is already downloaded.
 > Model's license - MIT
 > Check https://choosealicense.com/licenses/mit/ for more info.
Traceback (most recent call last):
  File "/Users/..../opt/miniconda3/envs/coqui-tts/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/Users/..../tts-1/TTS/TTS/bin/synthesize.py", line 385, in main
    synthesizer = Synthesizer(
  File "/Users/..../tts-1/TTS/TTS/utils/synthesizer.py", line 107, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/Users/..../tts-1/TTS/TTS/utils/synthesizer.py", line 159, in _load_tts_from_dir
    config = load_config(os.path.join(model_dir, "config.json"))
  File "/Users/..../tts-1/TTS/TTS/config/__init__.py", line 94, in load_config
    config_class = register_config(model_name.lower())
  File "/Users/..../tts-1/TTS/TTS/config/__init__.py", line 47, in register_config
    raise ModuleNotFoundError(f" [!] Config for {model_name} cannot be found.")
ModuleNotFoundError:  [!] Config for bark cannot be found.

### Environment

```shell
- latest TTS version
- both Google Codelabs Linux and Mac M1
- Python 3.10.9 (conda create fresh enviornments)
```

**Comment by erogol** [comment]
what is latest tts version?

**Comment by thefex** [comment]
It's been using https://github.com/coqui-ai/TTS/commit/dfd8d313a2e8b3f7e2e2971578e7747deab5f68b commits - 1.5.1

**Comment by erogol** [comment]
0.15.2 should fix the issue 👍

**Comment by thefex** [comment]
Thank you for the expedited support.
