### ISSUE TITLE
[Bug] where is tts.model.bark?

### ISSUE THREAD

**Issue by acordova200** [coqui-ai/TTS#2724]
### Describe the bug

this file cannot be found

Traceback (most recent call last):
ModuleNotFoundError: No module named 'TTS.tts.models.bark'

### To Reproduce

from TTS.tts.models.bark import BarkAudioConfig

this file cannot be found

Traceback (most recent call last):
ModuleNotFoundError: No module named 'TTS.tts.models.bark'

### Logs

```shell
development
```

### Environment

```shell
this file cannot be found

Traceback (most recent call last):
ModuleNotFoundError: No module named 'TTS.tts.models.bark'
```

**Comment by erogol** [comment]
duplicate https://github.com/coqui-ai/TTS/issues/2722
