### ISSUE TITLE
[Feature request] Support the Wyoming protocol for easy integration with Home Assistant / rhasspy and other projects

### ISSUE THREAD

**Issue by bagobones** [coqui-ai/TTS#2729]
**🚀 Feature Description**

Run as a persistent service taking TTS requests via the Wyoming protocol to serve as a fully local TTS engine.

**Solution**

- Docker image supports starting as a specific trained model
- Docker image supports the [wyoming ](https://www.home-assistant.io/integrations/wyoming/) protocol allowing easy integration with the Home Assistant / rhasspy projects which are working on fully local voice assistants

**Alternative Solutions**

Provide a way to export / train a model to a new voice in Coqui and export it to be usable by [piper TTS](https://github.com/rhasspy/piper) in home assistant

**Additional context**

Mainly looking for a way to use coqui training / customization to have a unique voice for my home automations in Home Assistant.

**Comment by thorstenMueller** [comment]
Hi @bagobones, i like the idea 👍. You already can use Coqui TTS models in Home Assistant by using MaryTTS API compatibility. Just in case that's interesting for you if made a tutorial on that on my open voice tech Youtube channel:
https://youtu.be/vtZbGrJqoZU?t=422

**Comment by bagobones** [comment]
I will check it out, I have tried Mary and the various voices it has out of the box in HA in the past. Not sure if the quality is a limitation of Marry or the voices.

Still would like to see direct support so I is quick to build and use a voice directly.

It seems like the new protocol will be the preferred way provide a TTS voice to a HA voice pipeline going forward so it would be nice to see wider support.

**Comment by bagobones** [comment]
Commenting to keep alive. 

Have not yet looking Timor exporting to marry.

**Comment by thorstenMueller** [comment]
I still think that the idea is worth to be kept open. Maybe @synesthesiam has any thoughts on that.

**Comment by bagobones** [comment]
I am still interested.. I think by year end homeassistant is going to have a more complete local voice and speech system (HW and wake words are expected) so having a flexible / trainable voice that just plugs in would be great.

**Comment by mahimairaja** [comment]
I find the idea interesting... 
Are you actively working on this @bagobones?

**Comment by bagobones** [comment]
No, not currently working on it.

**Comment by bagobones** [comment]
Bumping again.
