### ISSUE TITLE
[Bug] Tortoise-TTS doesn't work, maybe is unable to load config.json properly for the model

### ISSUE THREAD

**Issue by SanguineSatan** [coqui-ai/TTS#2762]
### Describe the bug

Running under ubuntu 22, nvidia a5000, everything was properly installed, original tortoise implementation working from the box(weird lol) and is separated using conda. a relatively clean ubuntu installation.

### To Reproduce

run in python:

from TTS.api import TTS
tts = TTS("tts_models/en/multi-dataset/tortoise-v2")

input_text1="...How about... a bake-off?"

tts.tts_to_file(text=input_text1,
                file_path="/home/asd/Desktop/TTS_Outputs/output_a-3-30.wav",
                voice_dir="/home/asd/tortoise-tts/tortoise/voices/",
                speaker="lj",
                use_deterministic_seed=1,
                num_autoregressive_samples=3,
                diffusion_iterations=30)

### Expected behavior

to run the inference

### Logs

```shell
> tts_models/en/multi-dataset/tortoise-v2 is already downloaded.
 > Using model: tortoise
Traceback (most recent call last):
  File "/home/asd/TTS/TTS/test_seed.py", line 3, in <module>
    tts = TTS("tts_models/en/multi-dataset/tortoise-v2")
  File "/home/asd/TTS/TTS/api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/home/asd/TTS/TTS/api.py", line 391, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "/home/asd/TTS/TTS/utils/synthesizer.py", line 107, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/home/asd/TTS/TTS/utils/synthesizer.py", line 162, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "/home/asd/TTS/TTS/tts/models/tortoise.py", line 884, in load_checkpoint
    self.autoregressive.load_state_dict(checkpoint, strict=strict)
  File "/home/asd/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
        Missing key(s) in state_dict: "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.masked_bias".
```

### Environment

```shell
2023-07-11 01:13:03 (8.59 MB/s) - ‘collect_env_info.py’ saved [1067/1067]

{
    "CUDA": {
        "GPU": [
            "NVIDIA RTX A5000",
            "NVIDIA GeForce GTX 1070"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.15.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.9",
        "version": "#5-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  2 21:27:23 UTC 2023"
```

**Comment by erogol** [comment]
What version of `transformers` are you using?

**Comment by SanguineSatan** [comment]
transformers 4.29.2
i tried several versions, but i get the same error.
can you perhaps point me to the right direction so i can try to attempt solving this?
this is so weird, because the original tortoise is working fine.
is it the transformers version or can it be something else?

**Comment by SanguineSatan** [comment]
> transformers 4.29.2 i tried several versions, but i get the same error. can you perhaps point me to the right direction so i can try to attempt solving this? this is so weird, because the original tortoise is working fine. is it the transformers version or can it be something else?

after reinstalling ubuntu from scratch, everything works, the issue seems with conda, unable to separate dependencies properly. I believe that making installation instructions using conda will resolve the conflict.
