### ISSUE TITLE
[Bug] thorsten/tacotron2-DDC make the docker container crash

### ISSUE THREAD

**Issue by AlessioMTX** [coqui-ai/TTS#2773]
### Describe the bug

I created a simple server to run the following TTS model: tts_models/de/thorsten/tacotron2-DDC. 

The problem is that after few seconds that I run the webserver it crashes.

It happens only with this model.

```
import json
from TTS.api import TTS
from flask import Flask, request, Response, abort

app = Flask(__name__)
app.config['PROPAGATE_EXCEPTIONS'] = True

#it_tts = TTS(model_name="tts_models/it/mai_male/glow-tts", progress_bar=False, gpu=False)
#en_tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=False, gpu=False)
# model is broken
de_tts = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", progress_bar=False, gpu=False)


if __name__ == '__main__':
    app.run(port=8005,debug=True)
```

I run it in a docker container and this is the Dockerfile:
```
FROM python:3.10-slim

WORKDIR /app

# espeak is required by the german model
RUN apt-get update && apt-get install -y \
        espeak-ng && \
    apt-get clean

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8005

CMD ["python", "main.py"]
```

The docker image build finishes successfully, the docker run fine, but then gets killed with code 137 that means that it's using too many memory (I see both CPU and RAM ramping up).

### To Reproduce

Server has 3 vCPUs and 4GB RAM

### Expected behavior

After the initial downloading of the model the web server should be idle waiting for requests

### Environment

```shell
- Latest TTS
- Python 3.10
```

**Comment by AlessioMTX** [comment]
![image](https://github.com/coqui-ai/TTS/assets/1489571/b088e58f-eecf-4c58-9740-e86db69334f6)
from docker run to crash

Latest log lines
```
| > db_level:None
 | > stats_path:/root/.local/share/tts/vocoder_models--de--thorsten--hifigan_v1/scale_stats.npy
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 * Serving Flask app 'main'
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8005
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
```

**Comment by erogol** [comment]
What is the error traceback?

**Comment by AlessioMTX** [comment]
The issue was the low RAM amount on the machine. I went from 4 to 8 and it solved the issue. I didn't plan so much RAM.
