### ISSUE TITLE
[Bug] Tortoise example not working

### ISSUE THREAD

**Issue by DatboiiPuntai** [coqui-ai/TTS#2782]
### Describe the bug

Tortoise TTS example is broken on ubuntu 20.04. It is unable to load the keys_to_ignore list.

This line seems to be broken. 
`keys_to_ignore = self.autoregressive.gpt._keys_to_ignore_on_load_missing  # pylint: disable=protected-access`

Traceback (most recent call last):
  File "/home/datability/rvc-tts-webui/test/tortoise_test.py", line 2, in <module>
    tts = TTS("tts_models/en/multi-dataset/tortoise-v2")
  File "/home/datability/rvc-tts-webui/venv/lib/python3.10/site-packages/TTS/api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/home/datability/rvc-tts-webui/venv/lib/python3.10/site-packages/TTS/api.py", line 391, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "/home/datability/rvc-tts-webui/venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 107, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/home/datability/rvc-tts-webui/venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 162, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "/home/datability/rvc-tts-webui/venv/lib/python3.10/site-packages/TTS/tts/models/tortoise.py", line 879, in load_checkpoint
    for pat in keys_to_ignore:
TypeError: 'NoneType' object is not iterable

### To Reproduce

1. Install with pip on ubuntu server 20.04 in a python 3.10.11 venv
`pip install TTS`

2. Run the api example
```
from TTS.api import TTS
tts = TTS("tts_models/en/multi-dataset/tortoise-v2")

tts.tts_to_file(text="Hello, my name is Manmay , how are you?",
                file_path="output.wav")
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu118",
        "TTS": "0.15.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.11",
        "version": "#170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023"
    }
}
```

### Additional context

To fix it, I had to do this
```
keys_to_ignore = ["gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias"]
```

**Comment by erogol** [comment]
make sure you have the right transformers version

**Comment by Rajashekhar-Reddy** [comment]
I have solved this issue by installing  below transformers version
`pip install transformers==4.30.0`
