### ISSUE TITLE
[Bug] KeyError: 'use_phonemes'

### ISSUE THREAD

**Issue by MVR3S** [coqui-ai/TTS#2785]
### Describe the bug

I tried to train a vocoder model and I tried to utilize it with tts-server but this throws KeyError: 'use_phonemes'.
This is the full error that I get:

(venv) PS D:\GitHub\Coqui> tts-server --config_path D:\GitHub\Coqui\models\LJSpeech-1.1\config.json --model_path D:\GitHub\Coqui\models\LJSpeech-1.1\best_model.pth

D:\GitHub\Coqui\venv\lib\site-packages\torchaudio\compliance\kaldi.py:22: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  EPSILON = torch.tensor(torch.finfo(torch.float).eps)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\GitHub\Coqui\venv\Scripts\tts-server.exe\__main__.py", line 4, in <module>
  File "D:\GitHub\Coqui\venv\lib\site-packages\TTS\server\server.py", line 104, in <module>
    synthesizer = Synthesizer(
  File "D:\GitHub\Coqui\venv\lib\site-packages\TTS\utils\synthesizer.py", line 91, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "D:\GitHub\Coqui\venv\lib\site-packages\TTS\utils\synthesizer.py", line 182, in _load_tts
    if self.tts_config["use_phonemes"] and self.tts_config["phonemizer"] is None:
  File "D:\GitHub\Coqui\venv\lib\site-packages\coqpit\coqpit.py", line 614, in __getitem__
    return self.__dict__[arg]
KeyError: 'use_phonemes'

### To Reproduce

1. Run the command "tts-server --config_path config path --model_path model path"
2. error

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cpu",
        "TTS": "0.15.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD",
        "python": "3.10.11",
        "version": "10.0.22621"
    }
}
```

**Comment by fugaprascolinas** [comment]
I have this same error. Unfortunately it is hard to get any attention around here, because they want us to pay for Coqui Studio. If only there is an option there to clone non-english voices there...

**Comment by kegbo** [comment]
Experiencing this issue when I push code to Azure functions when performing voice conversion.

**Comment by Edresson** [comment]
Hi @MVR3S, 

Looks like you are providing the vocoder checkpoint and vocoder config respectly on  `--config_path` and `--model_path`, is it right?

You need to provide it on `--vocoder_path` and `--vocoder_config_path`. Also you need to provide the config and the checkpoint of the TTS model that you want to use with the vocoder (on `--config_path` and `--model_path`).
