### ISSUE TITLE
[Bug] TypeError: generate_text_semantic() got an unexpected keyword argument 'd_vector'

### ISSUE THREAD

**Issue by zzlgreat** [coqui-ai/TTS#2797]
### Describe the bug

I have install tts for dev. It work well in other functions. But when I use bark, it will happen:
```
 > tts_models/multilingual/multi-dataset/bark is already downloaded.
 > Using model: bark
 > Text splitted to sentences.
['Hello, my name is Manmay , how are you?']
Traceback (most recent call last):
  File "/DATA4T/video-retalking/bark_example.py", line 11, in <module>
    tts.tts_to_file(text="Hello, my name is Manmay , how are you?",
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/api.py", line 596, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/api.py", line 543, in tts
    wav = self.synthesizer.tts(
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 364, in tts
    outputs = self.tts_model.synthesize(
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 220, in synthesize
    outputs = self.generate_audio(text, history_prompt=history_prompt, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 153, in generate_audio
    x_semantic = self.text_to_semantic(
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 87, in text_to_semantic
    x_semantic = generate_text_semantic(
TypeError: generate_text_semantic() got an unexpected keyword argument 'd_vector'

```

### To Reproduce

1. Run the following command 'python bark_example.py'
2. bark_example.py: 
`from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/bark", gpu=True)
tts.tts_to_file(text="Hello, my name is Manmay , how are you?",
                file_path="1.wav",
                voice_dir="bark_voices/",
                speaker="ljspeech")
tts.tts_to_file(text="Hello, my name is Manmay , how are you?",
                file_path="1.wav",
                voice_dir="bark_voices/",
                speaker="ljspeech")
tts = TTS("tts_models/multilingual/multi-dataset/bark", gpu=True)
tts.tts_to_file("hello world", file_path="out.wav")`
3. ` File "/DATA4T/video-retalking/bark_example.py", line 11, in <module>
    tts.tts_to_file(text="Hello, my name is Manmay , how are you?",
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/api.py", line 596, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/api.py", line 543, in tts
    wav = self.synthesizer.tts(
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 364, in tts
    outputs = self.tts_model.synthesize(
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 220, in synthesize
    outputs = self.generate_audio(text, history_prompt=history_prompt, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 153, in generate_audio
    x_semantic = self.text_to_semantic(
  File "/root/anaconda3/envs/tts/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 87, in text_to_semantic
    x_semantic = generate_text_semantic(
TypeError: generate_text_semantic() got an unexpected keyword argument 'd_vector'`

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 4090",
            "NVIDIA GeForce RTX 4090",
            "NVIDIA GeForce RTX 4090",
            "NVIDIA GeForce RTX 4090"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.16.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#25-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 17:05:07 UTC 2023"
    }
}
```

**Comment by Sharrnah** [comment]
same issue.

haven't looked into the very detail, as it seems its called by some other function in some to me hidden way.

As a quick fix, you can edit the file `TTS/tts/layers/bark/inference_funcs.py`

find the function generate_text_semantic() and add the argument `d_vector=None` (even though its never used).

So it looks like this:
```py
def generate_text_semantic(
    text,
    model,
    history_prompt=None,
    temp=0.7,
    top_k=None,
    top_p=None,
    silent=False,
    min_eos_p=0.2,
    max_gen_duration_s=None,
    allow_early_stop=True,
    base=None,
    use_kv_caching=True,
    d_vector=None, # <-- This is added.
):
```

This is most likely not the way this is supposed to be fixed, so i won't make a pull-request. Probably someone with more Python and coqui-ai insight can fix this properly.

**Comment by zzlgreat** [comment]
> same issue.
> 
> haven't looked into the very detail, as it seems its called by some other function in some to me hidden way.
> 
> As a quick fix, you can edit the file `TTS/tts/layers/bark/inference_funcs.py`
> 
> find the function generate_text_semantic() and add the argument (even though its never used).`d_vector=None`
> 
> So it looks like this:
> 
> ```python
> def generate_text_semantic(
>     text,
>     model,
>     history_prompt=None,
>     temp=0.7,
>     top_k=None,
>     top_p=None,
>     silent=False,
>     min_eos_p=0.2,
>     max_gen_duration_s=None,
>     allow_early_stop=True,
>     base=None,
>     use_kv_caching=True,
>     d_vector=None, # <-- This is added.
> ):
> ```
> 
> This is most likely not the way this is supposed to be fixed, so i won't make a pull-request. Probably someone with more Python and coqui-ai insight can fix this properly.

It works, thanks a lot!

**Comment by erogol** [comment]
This should have fixed it. https://github.com/coqui-ai/TTS/pull/2822
