### ISSUE TITLE
[Bug] cannot install TTS from pip (Dependency lookup for OpenBLAS with method 'pkgconfig' failed)

### ISSUE THREAD

**Issue by vayvaychicken** [coqui-ai/TTS#2801]
### Describe the bug

When I run pip install TTS (on mac in vscode) I run into this error:
Found Pkg-config: NO
      Run-time dependency python found: YES 3.10
      Program cython found: YES (/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-build-env-422m5n95/overlay/bin/cython)
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 13.1.0 "GNU Fortran (Homebrew GCC 13.1.0) 13.1.0")
      Fortran linker for the host machine: gfortran ld64 650.9
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: NO
      Program pythran found: YES (/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-build-env-422m5n95/overlay/bin/pythran)
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency xsimd found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      pybind11-config found: YES (/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-build-env-422m5n95/overlay/bin/pybind11-config) 2.10.4
      Run-time dependency pybind11 found: YES 2.10.4
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried framework)
      
      ../../scipy/meson.build:159:9: ERROR: Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.
      
      A full log can be found at /private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37/.mesonpy-820un46a/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

### To Reproduce

pip install TTS
or
git clone https://github.com/coqui-ai/TTS
pip install -e .[all,dev,notebooks]  # Select the relevant extras

### Expected behavior

Supposed to install TTS

### Logs

```shell
pip install TTS
Collecting TTS
  Using cached TTS-0.15.6.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cython==0.29.30 (from TTS)
  Using cached Cython-0.29.30-py2.py3-none-any.whl (985 kB)
Collecting scipy>=1.4.0 (from TTS)
  Using cached scipy-1.11.1.tar.gz (56.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      + meson setup /private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37 /private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37/.mesonpy-820un46a/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37/.mesonpy-820un46a/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.0
      Source dir: /private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37
      Build dir: /private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37/.mesonpy-820un46a/build
      Build type: native build
      Project name: SciPy
      Project version: 1.11.1
      C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C linker for the host machine: cc ld64 650.9
      C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C++ linker for the host machine: c++ ld64 650.9
      Cython compiler for the host machine: cython (cython 0.29.36)
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Program python found: YES (/Library/Frameworks/Python.framework/Versions/3.10/bin/python3)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency python found: YES 3.10
      Program cython found: YES (/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-build-env-422m5n95/overlay/bin/cython)
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 13.1.0 "GNU Fortran (Homebrew GCC 13.1.0) 13.1.0")
      Fortran linker for the host machine: gfortran ld64 650.9
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: NO
      Program pythran found: YES (/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-build-env-422m5n95/overlay/bin/pythran)
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency xsimd found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      pybind11-config found: YES (/private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-build-env-422m5n95/overlay/bin/pybind11-config) 2.10.4
      Run-time dependency pybind11 found: YES 2.10.4
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried framework)
      
      ../../scipy/meson.build:159:9: ERROR: Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.
      
      A full log can be found at /private/var/folders/0y/kbqk5xzn5f397bmdxh0jt8h40000gn/T/pip-install-jmtiyxte/scipy_aaa7ee9f969b4a2984a0151a62db7a37/.mesonpy-820un46a/build/meson-logs/meson-log.txt
      [end of output]
```

### Environment

```shell
Python 3.10
```

**Comment by NouiliKh** [comment]
Experiencing the same error while trying to install `scikit-learn `

**Comment by erogol** [comment]
```
 Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.
 ```

**Comment by vayvaychicken** [comment]
That is the error message I received, is there any fix?

**Comment by vayvaychicken** [comment]
> ```
>  Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.
> ```
That is the error message I received, is there any fix?

**Comment by NouiliKh** [comment]
I am not sure if this will help but I had the exact same issue while trying to install some packages with pipenv. 
I had to downgrade it to `version 2022.9.4` for it to work.
