### ISSUE TITLE
[Feature request] Integrate Vocos (especially for Bark)

### ISSUE THREAD

**Issue by Sharrnah** [coqui-ai/TTS#2803]
**🚀 Feature Description**

Integrate the Vocos vocoder from here: https://github.com/charactr-platform/vocos

As it has a much better quality of Bark generated audio when used.

**Solution**

Integrate Vocos vocoder for Bark (specifically), or if useful maybe also for other TTS models.

**Additional context**

I made a Plugin for my application specific for Bark. When i stumbled over Vocos i used that as default Vocoder and the results are way better then using the original Bark vocoder.

**Comment by erogol** [comment]
As far as I know 🐸TTS is already in Vocos. If not, I think you should create the issue there.

**Comment by Sharrnah** [comment]
No. Bark is not using Vocos by default, and its a seperate Vocoder. Not sure if they plan in replacing the current one.
But it should not be difficult to have Bark in Coqui use Vocos.

**Comment by erogol** [comment]
Sorry, I confused things. You mean the vocoder. Yeah, it makes sense. I've seen it improve the results quite a bit. 

I just reopen, so feel free to send a PR anyone.
