### ISSUE TITLE
[Bug] Unable to Prompt Engineer in Tortoise 

### ISSUE THREAD

**Issue by SuyashVoid** [coqui-ai/TTS#2804]
### Describe the bug

So the [tortoise-tts-fast](https://github.com/152334H/tortoise-tts-fast) that is currently implemented in Coqui, for some reason, includes the text that is supposed to be redacted in the generated audio. In original words of tortoise's author:

> For example, you can evoke emotion by including things like "I am really sad," before your text. I've built an automated redaction system that you can use to take advantage of this. It works by attempting to redact any text in the prompt surrounded by brackets. For example, the prompt "[I am really sad,] Please feed me." will only speak the words "Please feed me" (with a sad tonality).

So the example I tried:

> [Horrified,] Brother, it's dark! It's, it's not coming back. Brother, I can't see. Brother, Help!

When using Tortoise through Coqui, it reads: "Horrified, Brother, it's dark! It's, it's not coming back. Brother, I can't see. Brother, Help!"
But when I separately pass this text to tortoise-fast, it only reads back (a little horrified intonations): "Brother, it's dark! It's, it's not coming back. Brother, I can't see. Brother, Help!"

Coqui's sentence splitting doesn't make the bracketed text its own sentence, so segmentation shouldn't be the problem. Since that is the case, my next conjecture is that coqui might be stripping away the square brackets at some point before it gets to tortoise. But I couldn't find something about it during my search, so here I am.

Thanks for looking into this.

### To Reproduce

Provide following text to Coqui tts_to_file on tortoise model (I used the TTS API, not CLI),
[Horrified,] Brother, it's dark! It's, it's not coming back. Brother, I can't see. Brother, Help!

### Expected behavior

Generated sound should only have the text (might or might not have the suggested horrified intonation):
Brother, it's dark! It's, it's not coming back. Brother, I can't see. Brother, Help!

### Environment

```shell
- TTS 0.15.6
- Pytorch 2.1.0
- Python 3.9.10
- Windows
```

**Comment by erogol** [comment]
Prompting does not do any good in my experience. Do we disabled it by default to save some runtime that is caused by reduct operation .

**Comment by SuyashVoid** [comment]
Ah, I see. Fair enough, I guess. Not much of an issue then. Thank you for looking into it.
