### ISSUE TITLE
[Bug] 0.16 version not on PyPI

### ISSUE THREAD

**Issue by gizmo84** [coqui-ai/TTS#2809]
### Describe the bug

0.16.0 version not on PyPI. Currently 0.15.6 is published.

### To Reproduce

See https://pypi.org/project/TTS/

### Expected behavior

Publish 0.16.0 on PyPI

### Environment

```shell
- TTS version: 0.16.0
```

**Comment by erogol** [comment]
just rerunning fixed it.
