### ISSUE TITLE
[Feature request] To update the HiFi-GAN vocoder

### ISSUE THREAD

**Issue by mllopartbsc** [coqui-ai/TTS#2810]
Hi, 

My request would be to update the HiFi-GAN vocoder to newer versions, such as V2.

The current version of HiFi-GAN used by coqui is the V1.

That would improve the performance in inference for models such as VITS.

Thank you.

**Comment by manmay-nakhashi** [comment]
@mllopartbsc I think hifigan-2 is for audio enhancement, which is not a vocoder.🤔

**Comment by mllopartbsc** [comment]
Hi @manmay-nakhashi,

Thank you for the prompt response. 

HiFi-GAN V1 is listed by Coqui as one of the available vocoder models: 

https://github.com/coqui-ai/TTS/blob/b739326503b6077c8662c0244b461ca75294384e/TTS/vocoder/models/hifigan_generator.py

And the VITS tts model uses it as such: 

https://github.com/coqui-ai/TTS/blob/b739326503b6077c8662c0244b461ca75294384e/TTS/tts/models/vits.py#L38C1-L38C1

**Comment by manmay-nakhashi** [comment]
@mllopartbsc yes but you can replace hifigan v1 with v2 because both of them are doing different things, one is for feature or spectrogram to audio , and second is for audio 2 audio enhancement.

**Comment by mllopartbsc** [comment]
> @mllopartbsc yes but you can replace hifigan v1 with v2 because both of them are doing different things, one is for feature or spectrogram to audio , and second is for audio 2 audio enhancement.

Sorry, you were meaning to say that you can't replace them right?

I was meaning to say the updated version of HiFi-GAN 1, not HiFi-GAN 2. 

The one using these configurations: 

https://github.com/jik876/hifi-gan/blob/master/config_v2.json

Kind Regards

**Comment by manmay-nakhashi** [comment]
These are just small, mid and big versions of hifigan you can change that in params of vits if you want to do that.

**Comment by mllopartbsc** [comment]
Have you thought about developing an option for the users to change between HiFi-GAN versions with just a parameter instead of having to manually change all the settings? It would be very useful because [the HiFi-GAN paper](https://arxiv.org/pdf/2010.05646.pdf) shows how changing from HiFi-GAN V1 to HiFi-GAN V2 can result in a minimum speedup for CPU inference of 8x and a minimum speedup for GPU inference of 5x. All of that with a very small loss in MOS of about 0.13. Here's the table with the results from the paper: 

![image](https://github.com/coqui-ai/TTS/assets/133785234/148e3a16-cf22-4c3b-91ff-c411eaff381a)

Let me know what you think of this possible addition.

References: 
[Kong, Jungil, Jaehyeon Kim, and Jaekyoung Bae. "Hifi-gan: Generative adversarial networks for efficient and high fidelity speech synthesis." Advances in Neural Information Processing Systems 33 (2020): 17022-17033.]

**Comment by Liujingxiu23** [comment]
Is there any script to finetune hifigan model in xtts v2?
