### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by MoreOwO** [coqui-ai/TTS#2815]
**🚀 Feature Description**
An integration of DML or OpenAL for faster training on non NVIDIA GPUs

**Solution**
I don't really know what library support non-CUDA acceleration, but something like torch-directml unfortunatly not yet available for torch 2.0.1.

**Comment by erogol** [comment]
You need to create this in PyTorch not here. We rely on it for training models.

**Comment by MoreOwO** [comment]
Pytorch has an integration of DirectML, however this needs some work of integration if you want to use it. Here is the documentation : [Documentation](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-wsl)

**Comment by erogol** [comment]
This doc is about TF not pytorch

**Comment by MoreOwO** [comment]
Oops, sorry wrong link [https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl)

**Comment by neonarc4** [comment]
> This doc is about TF not pytorch

hey bro any update for dml?
