### ISSUE TITLE
[Feature request] VITS 2 implementation 

### ISSUE THREAD

**Issue by mehrzadai** [coqui-ai/TTS#2828]
**🚀 Feature Description**

VITS2: Improving Quality and Efficiency of Single-Stage Text-to-Speech with Adversarial Learning and Architecture Design

+ Transformer Blocks in flow mechanism
+ Text Encoder conditioned on speaker embeddings

I even love you more with these modifications ! 
Soon ?

**Comment by manmay-nakhashi** [comment]
@mehrzadai can you post a paper link ?

**Comment by mehrzadai** [comment]
@manmay-nakhashi 
https://arxiv.org/abs/2307.16430

**Comment by erogol** [comment]
I think @p0p4k is working on it.

**Comment by S-Ali-Zaidi** [comment]
Hi! any updates on implementing VITS2?

**Comment by erogol** [comment]
I think @p0p4k gave up on that :(

**Comment by p0p4k** [comment]
@S-Ali-Zaidi Ill do it in this month, sorry for delay!

**Comment by erogol** [comment]
ok then reopened 👍

**Comment by S-Ali-Zaidi** [comment]
Yay, glad to hear it! Thank you both!

**Comment by andersmmg** [comment]
Someone is supposedly still working on it

**Comment by mrakotos** [comment]
Any update ?

**Comment by cod3r0k** [comment]
Any update?
