### ISSUE TITLE
[Bug] pip install TTS seems not to bring in required dependecies (mecab-python3 and unidic-lite)

### ISSUE THREAD

**Issue by JackNova** [coqui-ai/TTS#2839]
### Describe the bug

Trying the last version of TTS package on Google Colab it complains about missing dependencies, namely  mecab-python3 and unidic-lite
After installing those packages I've been able to initialize the application

### To Reproduce

!pip install TTS
from TTS.api import TTS

### Expected behavior

Initialization is expected not to fail, pip install of the package should bring in all required dependencies

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu118",
        "TTS": "0.16.1",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Fri Jun 9 10:57:30 UTC 2023"
    }
}
```

**Comment by erogol** [comment]
Addressed here #2843

**Comment by koernchen02** [comment]
I'm having the same problem when installing TTS in a docker container based on debian and wanted to try out "0.16.2" but PyPI states it is still 0.16.1... 
So I assume the releases you tag here aren't automatically published to the PyPI?!
Sorry for the off-topic question!

**Comment by erogol** [comment]
fixed here https://github.com/coqui-ai/TTS/pull/2843
