### ISSUE TITLE
Special character like ö, ä, ü not spoken [Bug] 

### ISSUE THREAD

**Issue by frixos25** [coqui-ai/TTS#2842]
### Describe the bug

The special character do not correct convertet to spoken text.

from TTS.api import TTS

def read_file_to_string(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
            return content
    except FileNotFoundError:
        print("Datei nicht gefunden.")
        return ""
    except Exception as e:
        print("Fehler beim Lesen der Datei:", e)
        return ""

file_content = read_file_to_string("text.txt")
print(file_content)
api = TTS(model_name="tts_models/de/thorsten/tacotron2-DCA", gpu=False)
api.tts_to_file(file_content, file_path="output.wav", encoding='utf-8')

The string file_content is in correct utf-8 format.

### To Reproduce

Run the code and check the output.wav.

### Expected behavior

Correct speaking with ö, ä, ü

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cpu",
        "TTS": "0.14.3",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD",
        "python": "3.8.17",
        "version": "10.0.22621"
    }
}
```

**Comment by erogol** [comment]
Maybe @thorstenMueller has an idea about that.

**Comment by frixos25** [comment]
It seems to be a problem from espeak-ng
https://github.com/thorstenMueller/Thorsten-Voice/issues/50

**Comment by thorstenMueller** [comment]
This might be as you're using Windows. Can you test and verify that eSpeak works better (in this case) than eSpeak-ng as mentioned in the linked issue.

**Comment by frixos25** [comment]
Yes, eSpeak works fine.

**Comment by thorstenMueller** [comment]
This probably means that Coqui TTS and their models can't solve it and eSpeak-ng has to fix it.

**Comment by erogol** [comment]
I don't think this is CoquiTTS or Espeak-NG since we were able to train many models with all kinds of characters.

Maybe the text cleaner is normalizing those to ascii versions.

@frixos25 Can you also check `tts_models/de/thorsten/tacotron2-DCA`?

**Comment by erogol** [comment]
Actually, I just passed a couple of sentences, and all the characters works fine. 

@frixos25 Can you share some samples?  I close it until then.

**Comment by frixos25** [comment]
It happens also with the tts_models/de/thorsten/tacotron2-DDC model. See atteched file.
Now i have deinstall eSpeak-ng and install eSpeak and change the enviroment path to eSpeak. (Windows)
[output.zip](https://github.com/coqui-ai/TTS/files/12329432/output.zip)

**Comment by MWRKUS** [comment]
This is an error that occurs because of the encoding of the command prompt set in Windows. I had the same error, which no longer occurs after changing the encoding to UTF-8. It is best to change it as described in the link, then it will read everything perfectly :-)

https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
