### ISSUE TITLE
[Feature request] Any model pretrained on Russian lang

### ISSUE THREAD

**Issue by BrasD99** [coqui-ai/TTS#2867]
As we know, there used to be such a model, it was trained on the Ruslan dataset, but then it was removed due to licensing violations. Maybe it's time to train the model on other data? I think the Russian language will be in demand.

**Comment by erogol** [comment]
There is Russian. You can follow this example https://github.com/coqui-ai/TTS#example-text-to-speech-using-fairseq-models-in-1100-languages-
