### ISSUE TITLE
[Bug] Sound too quick when synthesize one-word-speech like "hello"。

### ISSUE THREAD

**Issue by travisCxy** [coqui-ai/TTS#2884]
### Describe the bug

hello,I want to synthesize some speech only have one word, like "Hello". 
I try the model named "tts_models/en/ek1/tacotron2". I got the wav file but it sound so quickly that can not hear the word clearly. Any method can solve it?

### To Reproduce

tts --text "hello" --model_name  tts_models/en/ek1/tacotron2 --vocoder_name  vocoder_models/en/ek1/wavegrad  --out_path ./hello.wav

### Environment

```shell
-TTS 1.3.
```

**Comment by erogol** [comment]
This is not a dev issue.

**Comment by WeberJulian** [comment]
This is not a bug @travisCxy , this is an inherent issue with the model/data.
