### ISSUE TITLE
[Bug] TypeError: list_models() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by kegbo** [coqui-ai/TTS#2887]
### Describe the bug

I am unable to get the list of models using the python API. Executing the command `model_name = TTS.list_models()[0]` returns the error `TypeError: list_models() missing 1 required positional argument: 'self'`

### To Reproduce

1) Install  TTS using the pip command `pip install TTS`
2) Copy into editor the following line into a python script
` from TTS.api import TTS  `
` model_name = TTS.list_models() `
3) Execute the python script

### Expected behavior

Expected to see a list of models provided by TTS

### Logs

```shell
TypeError: list_models() missing 1 required positional argument: 'self'
```

### Environment

```shell
- TTS Version : 0.16.3
- Python : 3.9.0
- Conda : 23.1.0
- Torch : 1.7
- OS : Windows
- Pytorch installation done with pip
```

**Comment by sam1am** [comment]
Same issue here. The code in the readme didn't work. Try this instead: 

```
from TTS.api import TTS

# Instantiate the TTS class
tts_api = TTS()

# List available TTS models and choose the first one
model_name = tts_api.list_models()[0]

# Init TTS with the chosen model
tts = TTS(model_name)
```

**Comment by xinjiboy1234** [comment]
yeah, I have same issue

**Comment by erogol** [comment]
`TTS().list_models()[0]`

**Comment by guanwang19** [comment]
try the following?

from TTS.api import TTS
tts = TTS('tts_models/en/ljspeech/tacotron2-DDC')
lst = tts.list_models()
print(lst)

**Comment by xinjiboy1234** [comment]
> try the following?
> 
> from TTS.api import TTS tts = TTS('tts_models/en/ljspeech/tacotron2-DDC') lst = tts.list_models() print(lst)

TTS().list_models()[0]  it is works for me , thanks

**Comment by skyjiang** [comment]
I have the same issue
i fix it 
pip uninstall TTS
pip installl TTS==0.21.3

**Comment by e-olang** [comment]
**TTS()**.list_models() seems to work and prodcue the model list instead of **TTS**.list_models()

**Comment by sshu2017** [comment]
I still get this issue in version 0.22.0.

**Comment by eginhard** [comment]
You can use [our fork](https://github.com/idiap/coqui-ai-TTS) (available via `pip install coqui-tts`), the old behaviour with `TTS.list_models()` is restored there.
