### ISSUE TITLE
[Bug] UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf.

### ISSUE THREAD

**Issue by JET2001** [coqui-ai/TTS#2903]
### Describe the bug

Hi!
I am getting a warning and a related runtime error where it is unable to initialise NumPy and a related `NumPy` runtime error when doing any command related to this tts library.

What are the supported versions of numpy am I supposed to use?

Thank you so much for your help! 

### To Reproduce

The command  `tts --model_name tts_models/en/ek1/tacotron2 --list_speaker_idxs` gives the warning and error described below.

### Expected behavior

List the speakers for the downloaded model 

### Logs

```shell
Running: tts --model_name tts_models/en/ek1/tacotron2 --list_speaker_idxs

C:\...\lib\site-packages\torchaudio\compliance\kaldi.py:22: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)`
(The above warning occurs at every tts command that I run)

// log for loading the model has been left out.

`File "C:\Users\...\scoop\apps\python\current\Scripts\tts.exe\__main__.py", line 7, in <module>
  File "C:\Users\...\lib\site-packages\TTS\bin\synthesize.py", line 396, in main
    synthesizer = Synthesizer(
  File "C:\Users\...\lib\site-packages\TTS\utils\synthesizer.py", line 95, in __init__        
    self._load_vocoder(vocoder_checkpoint, vocoder_config, use_cuda)
  File "C:\Users\...\lib\site-packages\TTS\utils\synthesizer.py", line 221, in _load_vocoder  
    self.vocoder_model.load_checkpoint(self.vocoder_config, model_file, eval=True)
  File "C:\Users\...\lib\site-packages\TTS\vocoder\models\wavegrad.py", line 235, in load_checkpoint
    self.compute_noise_level(betas)
  File "C:\Users\...\lib\site-packages\TTS\vocoder\models\wavegrad.py", line 168, in compute_noise_level
    self.beta = torch.tensor(beta.astype(np.float32))        
**RuntimeError: Could not infer dtype of numpy.float32**
```

### Environment

```shell
I have the following dependencies:
- TTS==0.16.0
- torch==1.13.1
- torchaudio==0.13.1
- numba==0.56.4
- numpy==1.23.5
- Python==3.10.7
```

### Additional context

Windows 11 (64-bit)

**Comment by manmay-nakhashi** [comment]
Change np.float to normal float

**Comment by JET2001** [comment]
I have now a different error: 
File `C:\...\lib\site-packages\TTS\bin\synthesize.py", line 406, in main
    print(synthesizer.tts_model.speaker_manager.name_to_id)    
AttributeError: 'NoneType' object has no attribute 'name_to_id'`

Here's the snapshot of the code:
<img width="470" alt="image" src="https://github.com/coqui-ai/TTS/assets/91585955/45aa4561-a6c1-4f1a-9302-ffd8e5e4a8c5">

Do you know why `synthesizer.tts_model.speaker_manager` is returning `None`?

**Comment by Muhammad-Ali-Saqib** [comment]
I was doing
```
script  = 'hello this is the test audio.'
wav, alignment, _, _ = synthesis(model, script, C, "cuda" in str(next(model.parameters()).device), speaker_id=None, d_vector=target_emb, language_id=0).values()
```
and the error was 
```
AttributeError: 'NoneType' object has no attribute 'name_to_id'
```
I have resolved that by setting `language_id=None` the show command will be 
```
wav, alignment, _, _ = synthesis(model, script, C, "cuda" in str(next(model.parameters()).device), speaker_id=None, d_vector=target_emb, language_id=None).values()
```

you can get the generated audio by 
```
file_name = "inference/generative_audio.wav"
ap.save_wav(wav, file_name)
```

**Comment by agilebean** [comment]
> I have now a different error: File `C:\...\lib\site-packages\TTS\bin\synthesize.py", line 406, in main print(synthesizer.tts_model.speaker_manager.name_to_id) AttributeError: 'NoneType' object has no attribute 'name_to_id'`
> 
> Here's the snapshot of the code: <img alt="image" width="470" src="https://user-images.githubusercontent.com/91585955/264004166-45aa4561-a6c1-4f1a-9302-ffd8e5e4a8c5.png">
> 
> Do you know why `synthesizer.tts_model.speaker_manager` is returning `None`?

I can confirm the same error shows on MacOS 14.1 (Ventura), M2.
Would be great to fix it as @Muhammad-Ali-Saqib suggested
