### ISSUE TITLE
[Bug] Documentation for Simple Usage Not Working

### ISSUE THREAD

**Issue by jeremyblalock** [coqui-ai/TTS#2905]
### Describe the bug

Hi, I was attempting to setup and run TTS locally on my Macbook this morning, and I ran into what seems like a documentation issue. The README gives the following example for a single speaker ([link](https://github.com/coqui-ai/TTS#running-a-single-speaker-model)):

```python
# Init TTS with the target model name
tts = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", progress_bar=False).to(device)
...
```

When I run this locally with everything installed, and `device` set to `cpu`, I get the following error:

```
AttributeError: 'TTS' object has no attribute 'to'
```

Note the previous setup I've already run in the same file / session:

```python
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"
```

Is this an issue with the documentation? Or is this something to do with my setup or an error in the library? This seems like SUPER simple usage.

### To Reproduce

1. Install using `pip install TTS`, MacOS Ventura 13.4
2. Install `espeak` with `brew install espeak`
3. Run `python`
4. Run the following code:

    ```python
    from TTS.api import TTS
    device = 'cpu'
    tts = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", progress_bar=False).to(device)
    ```
5. Observe the error:

    ```
    AttributeError: 'TTS' object has no attribute 'to'
    ```

### Expected behavior

I'd expect this to load the model.

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1",
        "TTS": "0.14.3",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "i386",
        "python": "3.8.8",
        "version": "Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64"
    }
}
```

**Comment by akx** [comment]
On fead04f779c26b6bc99a608542ecea8d39f0fbc7, your example works fine on my Mac. The version on PyPI might be older.

**Comment by erogol** [comment]
If you update to the latest version that I just released, things should be fixed.
