### ISSUE TITLE
[Bug] Missing IPA characters in default set

### ISSUE THREAD

**Issue by SineSwiper** [coqui-ai/TTS#2916]
### Describe the bug

When I run the following in eSpeak's IPA processor, I get:

```
# espeak-ng --ipa "across the sky"
əkɹˌɒs ðə skˈaɪ
```

Running this phrase into the phenome cache generator gives me:

```
 [!] Character '̩' not found in the vocabulary. Discarding it.
```

The low vertical line (`\u02CC`) can also be expressed as `\u0329`, which is what appears in the "discarding" message.  That can be fixed with this line in `TTS/tts/utils/text/characters.py`:

```
_suprasegmentals = "\u0329\u02cc" + "ˈːˑ"
```

There are also smart quotes in the LJSpeech set (entry LJ020-0041) that gets untranslated by IPA and goes directly through the phenome processors.  This gives me:

```
 [!] Character '“' not found in the vocabulary. Discarding it.
 [!] Character '”' not found in the vocabulary. Discarding it.
```

I don't know if that's something that should be cleaned in the `phenome_cleaners` functions, but it sounds like it.

### To Reproduce

1. Train the LJSpeech set using the standard `train_tacotron_ddc.py` trainer.
2. Add in a `test_sentence` with the phrase "across the sky".
3. See discard warnings in run.

### Expected behavior

No warnings.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090 Ti"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu118",
        "TTS": "0.16.5",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

**Comment by SineSwiper** [comment]
Actually, you don't even need the `test_sentence`.  These suprasegmental phenomes appear in the base LJSpeech set.

**Comment by erogol** [comment]
You don't need those characters for a good model. You can ignore those warnings or update the characters in your model config.
