### ISSUE TITLE
[Bug] Fine-tuning broken for Tacotron2-DDC

### ISSUE THREAD

**Issue by SineSwiper** [coqui-ai/TTS#2917]
### Describe the bug

Taking the simplest test case possible, I cannot fine-tune the `en/ljspeech/tacotron2-DDC` model at all, using a single epoch and lowered `lr`.  All attempts at doing so results in garbled output.

Either the `restore_path` function is broken, or the recipe has the wrong data points.  The Tacotron2-DDC model is also the example used in the [documentation](https://tts.readthedocs.io/en/latest/finetuning.html).

Furthermore, swapping out the `config_path` parameter for the new model test with the original `tts_models--en--ljspeech--tacotron2-DDC` reveals a bunch of `state_dict` size mismatch errors, indicating that it didn't copy the model properly during the re-training process:

```
RuntimeError: Error(s) in loading state_dict for Tacotron2:
        Unexpected key(s) in state_dict: "coarse_decoder.prenet.linear_layers.0.linear_layer.weight", "coarse_decoder.prenet.linear_layers.1.linear_layer.weight", "coarse_decoder.attention_rnn.weight_ih", "coarse_decoder.attention_rnn.weight_hh", "coarse_decoder.attention_rnn.bias_ih", "coarse_decoder.attention_rnn.
bias_hh", "coarse_decoder.attention.query_layer.linear_layer.weight", "coarse_decoder.attention.inputs_layer.linear_layer.weight", "coarse_decoder.attention.v.linear_layer.weight", "coarse_decoder.attention.v.linear_layer.bias", "coarse_decoder.attention.location_layer.location_conv1d.weight", "coarse_decoder.attent
ion.location_layer.location_dense.linear_layer.weight", "coarse_decoder.decoder_rnn.weight_ih", "coarse_decoder.decoder_rnn.weight_hh", "coarse_decoder.decoder_rnn.bias_ih", "coarse_decoder.decoder_rnn.bias_hh", "coarse_decoder.linear_projection.linear_layer.weight", "coarse_decoder.linear_projection.linear_layer.bi
as", "coarse_decoder.stopnet.1.linear_layer.weight", "coarse_decoder.stopnet.1.linear_layer.bias".
        size mismatch for embedding.weight: copying a param with shape torch.Size([131, 512]) from checkpoint, the shape in current model is torch.Size([64, 512]).
        size mismatch for decoder.linear_projection.linear_layer.weight: copying a param with shape torch.Size([480, 1536]) from checkpoint, the shape in current model is torch.Size([80, 1536]).
        size mismatch for decoder.linear_projection.linear_layer.bias: copying a param with shape torch.Size([480]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for decoder.stopnet.1.linear_layer.weight: copying a param with shape torch.Size([1, 1504]) from checkpoint, the shape in current model is torch.Size([1, 1104]).
```

### To Reproduce

```
docker run --rm -it -p 5002:5002 --shm-size '2GB' --gpus all --volume '/var/tmp:/var/tmp' --entrypoint /bin/bash ghcr.io/coqui-ai/tts
python3 -c 'from TTS.utils.downloaders import download_ljspeech; download_ljspeech("recipes/ljspeech/");'
tts --model_name tts_models/en/ljspeech/tacotron2-DDC --text "Hi."

export TACOTRON_DDC_DIR=/root/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC
export HIFIGAN_V2_DIR=/root/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2

python3 recipes/ljspeech/tacotron2-DDC/train_tacotron_ddc.py --restore_path $TACOTRON_DDC_DIR/model_file.pth --config_path $TACOTRON_DDC_DIR/config.json --coqpit.run_name "LJS-finetune" --coqpit.lr 0.00001 --coqpit.epoch 1
# Wait 10 minutes for fine-tune

tts --text "This is a test of TTS." --model_path $TACOTRON_DDC_DIR/model_file.pth --config_path $TACOTRON_DDC_DIR/config.json --vocoder_path $HIFIGAN_V2_DIR/model_file.pth --vocoder_config_path $HIFIGAN_V2_DIR/config.json --out_path /var/tmp/orig.wav
# Good WAV
tts --text "This is a test of TTS." --model_path /root/recipes/ljspeech/tacotron2-DDC/LJS-finetune-*/best_model.pth --config_path /root/recipes/ljspeech/tacotron2-DDC/LJS-finetune-*/config.json --vocoder_path $HIFIGAN_V2_DIR/model_file.pth --vocoder_config_path $HIFIGAN_V2_DIR/config.json --out_path /var/tmp/LJS-finetune.wav
# Bad WAV
tts --text "This is a test of TTS." --model_path /root/recipes/ljspeech/tacotron2-DDC/LJS-finetune-*/best_model.pth --config_path $TACOTRON_DDC_DIR/config.json --vocoder_path $HIFIGAN_V2_DIR/model_file.pth --vocoder_config_path $HIFIGAN_V2_DIR/config.json --out_path /var/tmp/LJS-finetune-origconfig.wav
# state_dict errors
```

### Expected behavior

1. Both WAVs produced should be about the same output.
2. Swapping out the `config_path` parameter (last command) should not result in `state_dict` errors.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090 Ti"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu118",
        "TTS": "0.16.5",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

**Comment by erogol** [comment]
released model does not have the coarse decoder in it to save space and memory. If you want to finetune first you get good results with train_tacotron_ddc.py under ljspeech recipes. It is how we trained the initial model. 

If you think there is a bug, you need to provide some way for us to reproduce it. However, the model being not good is not really a bug.

**Comment by SineSwiper** [comment]
> released model does not have the coarse decoder in it to save space and memory.

Then why do the docs [recommend downloading the released model](https://tts.readthedocs.io/en/latest/finetuning.html#steps-to-fine-tune-a-tts-model) to work with fine-tuning?

> If you want to finetune first you get good results with train_tacotron_ddc.py under ljspeech recipes.

That's precisely what I referenced in the bug report.  I didn't even change the script in the example.  I just downloaded the LJSpeech set and ran the fine-tune with that exact script.

> If you think there is a bug, you need to provide some way for us to reproduce it.

Did you not even read the bug report?  The "To Reproduce" section shows the exact steps from start to finish on how to reproduce the bug.  I even spent the time re-running my commands to make sure they were consistently producing bad results.

> However, the model being not good is not really a bug.

If this is not documented and is, in fact, saying that it is appropriate to fine-tune with these models in the TTS documentation, then it most certainly is a bug in the documentation.

**Comment by codepharmer** [comment]
@SineSwiper I feel your pain. I've unsuccessfully been trying to fine-tune this model for way too long and facing the same problems. I agree with you that this is most definitely a bug.

**Comment by JacopoMangiavacchi** [comment]
Can we please reopen this issues and evaluate the best recipe for fine tuning Tacotron2-DDC.  I love this framework and thank you very much for your great work but I'm a bit confused and I see I'm probably not the only one.  

The finetunining.md guide line says "Whether you use one of the training scripts under recipes folder or the train_tts.py to start your training, you should use the --restore_path flag to specify the path to the pre-trained model." but the TTS/bin/train_tts.py has no restore_path parameter.

**Comment by JacopoMangiavacchi** [comment]
I think I found how TrainerArgs with restore_path is passed in other model scripts and I'll try training again

**Comment by iovoovoi** [comment]
hiya, I used train_tacotron_ddc.py under ljspeech recipes, but still received the size mismatch error...I'm using the model_name: tts_models/en/ljspeech/tacotron2-DDC. anything missed?
