### ISSUE TITLE
[Bug] Unable to run tts-server or server/server.py with Bark

### ISSUE THREAD

**Issue by aindilis** [coqui-ai/TTS#2927]
### Describe the bug

Hi,

Thank you for making such excellent software.

However, maybe due to my lack of familiarity with Docker and Python, I am running into the following errors. I ran:

`docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash ghcr.io/coqui-ai/tts`

`python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/bark --use_cuda true`

I observed an error when doing this, similar to the first large error text below. After I ran the above commands, I noticed it downloaded tens of gigabytes of files, plus used the `--rm`, which made me think it would delete the image and try to redownload them when I reran it. (Maybe it's not so good an idea to suggest to include the `--rm` in this case? I don't know, I don't know docker very well. Maybe it caches them?).  So I searched how to save a container that was run with --rm. I followed the instructions and quit the terminal with `Ctrl-P Ctrl-Q`, and then ran `docker commit <CONTAINERID> tts-bark.`

When I start the container again:

`andrewdo@ai2:~$ docker run -i --gpus all -p 5002:5002  --entrypoint='/bin/bash' -t 50a9973597d3`

and when trying to run the server, I get the results below. I'm pretty sure that it's not related to my commiting to an image, since I observed the first error when initially running that command before commiting.

```
  root@98e9ad432209:~# python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/bark --use_cuda true
  > tts_models/multilingual/multi-dataset/bark is already downloaded.
  Traceback (most recent call last):
  File "/root/TTS/server/server.py", line 104, in <module>
  synthesizer = Synthesizer(
  File "/root/TTS/utils/synthesizer.py", line 93, in __init__
  self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/root/TTS/utils/synthesizer.py", line 183, in _load_tts
  self.tts_config = load_config(tts_config_path)
  File "/root/TTS/config/__init__.py", line 79, in load_config
  ext = os.path.splitext(config_path)[1]
  File "/usr/lib/python3.10/posixpath.py", line 118, in splitext
  p = os.fspath(p)
  TypeError: expected str, bytes or os.PathLike object, not NoneType
  root@98e9ad432209:~#
```

```
  root@98e9ad432209:~# tts-server --model_name "tts_models/multilingual/multi-dataset/bark" --use_cuda true
  > tts_models/multilingual/multi-dataset/bark is already downloaded.
  Traceback (most recent call last):
  File "/usr/local/bin/tts-server", line 33, in <module>
  sys.exit(load_entry_point('TTS', 'console_scripts', 'tts-server')())
  File "/usr/local/bin/tts-server", line 25, in importlib_load_entry_point
  return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
  module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/TTS/server/server.py", line 104, in <module>
  synthesizer = Synthesizer(
  File "/root/TTS/utils/synthesizer.py", line 93, in __init__
  self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/root/TTS/utils/synthesizer.py", line 183, in _load_tts
  self.tts_config = load_config(tts_config_path)
  File "/root/TTS/config/__init__.py", line 79, in load_config
  ext = os.path.splitext(config_path)[1]
  File "/usr/lib/python3.10/posixpath.py", line 118, in splitext
  p = os.fspath(p)
  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any idea how to get the TTS (w/Bark) server working? I haven't changed the config as far as I remember.

I did note that this did work:

`tts --text "This is a test" --model_name "tts_models/multilingual/multi-dataset/bark" --use_cuda true --out_path "/tmp/example.wav"`

However, I'm trying to get Bark to work with Rhasspy as a Local Command (or Remote HTTP) TTS server, so I need some kind of server functionality.

Thanks,

Andrew

### To Reproduce

docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash ghcr.io/coqui-ai/tts
python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/bark --use_cuda true

### Environment

```shell
python3 ./TTS/bin/collect_env_info.py
{
  "CUDA": {
    "GPU": [
      "NVIDIA GeForce RTX 3090"
    ],
    "available": true,
    "version": "11.8"
  },
  "Packages": {
    "PyTorch_debug": false,
    "PyTorch_version": "2.0.1+cu118",
    "TTS": "0.16.6",
    "numpy": "1.22.0"
  },
  "System": {
    "OS": "Linux",
    "architecture": [
      "64bit",
      ""
    ],
    "processor": "x86_64",
    "python": "3.10.12",
    "version": "#1 SMP Debian 5.10.140-1 (2022-09-02)"
  }
}
```

**Comment by aindilis** [comment]
Btw, forgot to mention I noticed the error was similar to this: https://github.com/coqui-ai/TTS/issues/2716

**Comment by aindilis** [comment]
I managed to figure it out. 

This was probably the same error: https://github.com/coqui-ai/TTS/issues/2913

I needed to supply more CLI options to the server.py. 

```python3 ./TTS/server/server.py --model_name "tts_models/multilingual/multi-dataset/bark" --model_path /root/.local/share/tts/tss_models--multilingual--multi-dataset--bark/ --debug true --config_path /root/.local/share/tts/tts_models--multilingual--multi-dataset--bark/config.json --use_cuda true```

But now I'm getting an error that ends with

```File "/root/TTS/tts/layers/bark/inference_funcs.py", line 64, in load_voice
   paths = voices[voice]
KeyError: ''```

If I run:

```tts --model_name "tts_models/multilingual/multi-dataset/bark" --list_speaker_idxs```

Gives an errors that ends:

```File "/root/TTS/bin/synthesize.py", line 421, in main
  print(synthesizer.tts_model.speaker_manager.name_to_id)
AttributeError: 'NoneType' object has no attribute 'name_to_id'```

I think I need to create a speaker. I tried creating a bark_voices/pizza/pizza.webm but am now confused how to create a voice.  It seems to need a transcript of the audio clip (i may have to change it to a .wav), and it needs to generate into a speaker idx file or something. Cannot remember the extension name.

I would also want to expand my question to include asking for help on programmatically querying the server via some host/port, i.e. 0.0.0.0:5002.

**Comment by aindilis** [comment]
I figured out how to create an npx file, from docs/source/models/bark.md , but now cannot figure out how to load that particular npx file.

**Comment by erogol** [comment]
the server does not support Bark and Tortoise. It is not a bug but I'll let it stay open if someone wants to help add those to the server.

**Comment by darkzbaron** [comment]
How about xTTS on the server?

**Comment by the-homeless-god** [comment]
Any updates here?

**Comment by eginhard** [comment]
[Our fork](https://github.com/idiap/coqui-ai-TTS) now supports all Coqui TTS models in the server. Specifying a `speaker_wav` file is not possible yet, this is tracked in https://github.com/idiap/coqui-ai-TTS/issues/254.
