### ISSUE TITLE
[Bug] Cannot load Coqui studio model in python

### ISSUE THREAD

**Issue by xinghua-qu** [coqui-ai/TTS#2938]
### Describe the bug

Hi, I am trying to use python code loading Coqui studio model.

Based on instruction, I have to set a api token, which I did as follows.
```
os.environ["COQUI_STUDIO_TOKEN"] = 'TOKEN DETAILS'
```

Then I use the following code to do speech synthesis.
```
tts = TTS(model_name="coqui_studio/en/Torcull Diarmuid/coqui_studio", progress_bar=False)
# Run TTS
tts.tts_to_file(text="This is a test.", file_path=OUTPUT_PATH)
```

However, I got the following error.
`TypeError: TTS.__init__() got an unexpected keyword argument 'model_name'`
Could anyone point out the misunderstanding or providing an example of successfully doing so?

### To Reproduce

```
os.environ["COQUI_STUDIO_TOKEN"] = 'TOKEN DETAILS'
tts = TTS(model_name="coqui_studio/en/Torcull Diarmuid/coqui_studio", progress_bar=False)
# Run TTS
tts.tts_to_file(text="This is a test.", file_path=OUTPUT_PATH)
```

### Expected behavior

successfully load the model from Coqui studio

### Logs

```shell
`   tts_model = TTS(model_name="coqui_studio/en/Torcull Diarmuid/coqui_studio", progress_bar=False)
TypeError: TTS.__init__() got an unexpected keyword argument 'model_name'`
```

### Environment

```shell
- TTS version 0.16.6
```

### Additional context

NAN

**Comment by erogol** [comment]
Can't reproduce on the latest version.

**Comment by erogol** [comment]
maybe retry by updating TTS. You can reopen if the error persists.
