### ISSUE TITLE
[Bug] Audio Length error in dataset.py - Training on custom dataset.

### ISSUE THREAD

**Issue by Rakshasv18** [coqui-ai/TTS#2942]
### Describe the bug

In the line 316 - TTS/tts/datasets/dataset.py

if length < min_len or length > max_len:
    #             ignore_idx.append(idx)  )  has to be changed to (  
 if length > min_len and length < max_len:
                keep_idx.append(idx) )

variables defined: 
        min_audio_len: int = 0,
        max_audio_len: int = float("inf")

Else every time i run the on custom dataset it always returns empty list for keep_idx and all the idx are ignored.

### To Reproduce

  # @staticmethod
    # def filter_by_length(lengths: List[int], min_len: int, max_len: int):
    #     idxs = np.argsort(lengths)  # ascending order
    #     ignore_idx = []
    #     keep_idx = []
    #     for idx in idxs:
    #         length = lengths[idx]
    #         if length < min_len or length > max_len:
    #             ignore_idx.append(idx)
    #             #print(ignore_idx, "-0-0-0-0-0-0-0-0-0")
    #         else:
    #             keep_idx.append(idx)
    #     return ignore_idx, keep_idx

### Expected behavior

keep_idx should have all the index 

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A100-PCIE-40GB",
            "NVIDIA A100-PCIE-40GB",
            "NVIDIA A100-PCIE-40GB"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu117",
        "TTS": "0.16.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.0",
        "version": "#1 SMP Thu May 18 10:27:05 EDT 2023"
    }
}
```

### Additional context

How much of space if required to run 1000 epochs on custom data ?

**Comment by Edresson** [comment]
Hi @Rakshasv18 ,

I think the current implemented logic is right.

I belief that the issue is on the way that the audio length is get here: https://github.com/coqui-ai/TTS/blob/747f688dc374a571e47f2c40358883c7ea11fa32/TTS/tts/datasets/dataset.py#L298C28-L298C96 It was implemented thinking about 16bit waveform audio files. What file format are you using?
But yeah I think we need to implement a more general approach.

**Comment by Rakshasv18** [comment]
Hey even the audios i used are 16 bit only

@Edresson 
<img width="998" alt="Screenshot 2024-01-26 at 9 57 17 PM" src="https://github.com/coqui-ai/TTS/assets/42600473/b53af54e-8e85-4c95-a08c-1b8732cce751">
