### ISSUE TITLE
[Feature request] AND 

### ISSUE THREAD

**Issue by Zacharybinx34** [coqui-ai/TTS#2953]
AMD gpu support would be appreciated.

**Comment by loupzeur** [comment]
Hello, a recent patch support torch devices, so it appear you can use `tts('...').to('opencl')` if you want to use AMD gpu.
On a mac I tried with `TTS('...').to('mps')` and it kinda work (some functions are still not being supported)

**Comment by maxime-fleury** [comment]
Is AMD gpu supported with XTTS ?

**Comment by erogol** [comment]
this is to ask Pytorch not TTS.
