### ISSUE TITLE
[Bug] Text input via cat and multiple lines

### ISSUE THREAD

**Issue by domasofan** [coqui-ai/TTS#2957]
### Describe the bug

When feeding multiple lines of text using cat into the tts command line tool, tts creates long pauses after a line break.

### To Reproduce

1. Write some text with line breaks into demo.txt
2. Execute tts --text "$(cat demo.txt)" --out_path demo.wav --model_name whatever/model

### Expected behavior

It shouldn't make a pause when just a simple line break is found.

### Environment

```shell
Windows 10 64 bit using WSL 2 and Ubuntu 23.04. coqui tts 0.17.2 and Python 3.11.
```

**Comment by WeberJulian** [comment]
You mean when the line break is in the middle of a sentence?

**Comment by domasofan** [comment]
Hi @WeberJulian,

Yes.
