### ISSUE TITLE
[Bug] Text input via cat and long lines get cut off

### ISSUE THREAD

**Issue by domasofan** [coqui-ai/TTS#2958]
### Describe the bug

When feeding long text lines into tts using cat, the lines get cut off and the text isn't spoken after this limit.

### To Reproduce

1. write some text into demo.txt with long lines and no line breaks.
2. pipe it into tts. 
$ tts --text "$(cat demo.txt)" --model_name whatever/model --out_path demo.wav

### Expected behavior

It should also speak the text of the too long lines as well. Maybe internally splitting the lines if they are too long to handle.

### Environment

```shell
Windows 10 64 bit, WSL 2 with Ubuntu 23.04 and Coqui 0.17.2 with Python 3.11.
```

**Comment by WeberJulian** [comment]
There is already a sentence spliter in TTS. Could you share your text file so we can reproduce please?

**Comment by domasofan** [comment]
Hi @WeberJulian,

Attached is the demo text file. 
Let's see if attaching it this way works. 
[langtext.txt](https://github.com/coqui-ai/TTS/files/12680252/langtext.txt)

**Comment by qrdrop** [comment]
Simply crashing on \n and \r. Sanitize your input.
