### ISSUE TITLE
[Bug] Long text via cat makes the voice stutter after 3 minutes of speaking

### ISSUE THREAD

**Issue by domasofan** [coqui-ai/TTS#2959]
### Describe the bug

When piping 4-5 kb of text using cat, after a while the tts engine starts mumbling and stuttering. Sometimes it is able to recover itself after 5 seconds into the stuttering. Sometimes it also exits and doesn't create a wave file.

### To Reproduce

1. Paste some text with around 3000-4000 characters. maybe also 5000. Thats around 3-4 minutes of speaking into a text file.
2. pipe this into tts
$ tts --text "(cat demo.txt)" --model_name whatever/model --out_path demo.wav

### Expected behavior

Expected would be that it would read the text without any problems. Great would be if we can find a possibility to make it read texts that have more than 100000 characters.
I often split texts at around 60000 characters. that would be around 1 hour of speaking.

### Environment

```shell
Windows 10 64 bit, wsl 2 with ubuntu 23.04, coqui 0.17.2 and python 3.11
```

**Comment by lexkoro** [comment]
This is rather a limitation to the architecture of the TTS systems or the data they were trained with than a bug.
A simple solution would be to synthesize each sentence separately.

**Comment by domasofan** [comment]
Hi @lexkoro,

So that might be more of a feature request than a bug report.
So if I understand you right the tts command line tool would  need to split the contents of the cat stream into small pices where the sentence ends with a .
Then piping it into the synthesizing pipeline and into the wav file or raw audio output stream if supported by the tts tool.

**Comment by 0965970018** [comment]
> ### Describe the bug
> When piping 4-5 kb of text using cat, after a while the tts engine starts mumbling and stuttering. Sometimes it is able to recover itself after 5 seconds into the stuttering. Sometimes it also exits and doesn't create a wave file.
> 
> ### To Reproduce
> 1. Paste some text with around 3000-4000 characters. maybe also 5000. Thats around 3-4 minutes of speaking into a text file.
> 2. pipe this into tts
>    $ tts --text "(cat demo.txt)" --model_name whatever/model --out_path demo.wav
> 
> ### Expected behavior
> Expected would be that it would read the text without any problems. Great would be if we can find a possibility to make it read texts that have more than 100000 characters. I often split texts at around 60000 characters. that would be around 1 hour of speaking.
> 
> ### Logs
> _No response_
> 
> ### Environment
> ```shell
> Windows 10 64 bit, wsl 2 with ubuntu 23.04, coqui 0.17.2 and python 3.11
> ```
> 
> ### Additional context
> _No response_

Hi

**Comment by 0965970018** [comment]
Help

**Comment by 0965970018** [comment]
Belam

**Comment by lexkoro** [comment]
@domasofan the tts cli should actually already segment a text into separate sentences. What language are you trying it with?

**Comment by domasofan** [comment]
Hi @lexkoro,

I was using German.
I used the model tts_models/de/thorsten/tacotron2-DDC

Greetings,
Simon
