### ISSUE TITLE
Upgrade and Optimize TTS Code in extractttsspectrogram.ipynb

### ISSUE THREAD

**Issue by anupammaurya6767** [coqui-ai/TTS#2967]
**Description**:
I am seeking to upgrade and optimize my Text-to-Speech (TTS) codebase to improve efficiency, maintainability, and performance. This issue outlines a series of changes and enhancements I plan to make in my codebase.

**Proposed Changes**:
1. Refactor the code to use command-line arguments for configuration, making it more flexible and user-friendly.
2. Implement proper logging to track progress and errors during code execution.
3. Utilize multiprocessing to parallelize data loading and processing for improved efficiency.
4. Organize the code into modular functions and classes to enhance readability and maintainability.
5. Implement GPU support for faster computation when available.
6. Add error handling and graceful exception handling to prevent crashes.
7. Optimize file operations, including asynchronous I/O for improved performance.
8. Utilize PyTorch's memory management functions to minimize memory usage.
9. Implement unit tests for critical code sections to ensure correctness.
10. Document the code, functions, and classes for better understanding and maintenance.

**Reason for Changes**:
The current codebase lacks flexibility, is hard to maintain, and does not take full advantage of available resources, including GPUs. These changes aim to address these issues and make the codebase more robust and efficient.

**Additional Context**:
This upgrade will improve the overall performance of my TTS system and make it easier to manage and extend in the future. It will also enhance collaboration among team members.

**Labels**:
- Enhancement
- Optimization
- Code Refactoring

**Comment by erogol** [comment]
if you plan to contribute, proper logging would be a nice start. There is a lot to take on here.

**Comment by anupammaurya6767** [comment]
@erogol pls check out the pull request

**Comment by erogol** [comment]
isn't it merged already?
