### ISSUE TITLE
[Bug] error when loading xtts model

### ISSUE THREAD

**Issue by taalua** [coqui-ai/TTS#2976]
### Describe the bug

Error when model.load_state_dict(checkpoint['model']):
```

RuntimeError: Error(s) in loading state_dict for Xtts:
	Unexpected key(s) in state_dict: "gpt.gpt_inference.transformer.h.0.ln_1.weight", "gpt.gpt_inference.transformer.h.0.ln_1.bias", "gpt.gpt_inference.transformer.h.0.attn.c_attn.weight", "gpt.gpt_inference.transformer.h.0.attn.c_attn.bias", "gpt.gpt_inference.transformer.h.0.attn.c_proj.weight", "gpt.gpt_inference.transformer.h.0.attn.c_proj.bias",
```

### To Reproduce

git clone https://github.com/coqui-ai/TTS
pip install -e . all

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A40"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.17.4",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Wed Aug 09 15:22:17 UTC 2022"
    }
}
```

**Comment by WeberJulian** [comment]
Hello, run `pip install transformers==4.33.1` and try again.

**Comment by OlegXio** [comment]
@WeberJulian I received 
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.18.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
I have entered these two commands and the error remains the same

**Comment by gorkemgoknar** [comment]
If anyone experiencing issue even after transformers, check if model files exists on xtts_v1 folder 

This should print path check inside and if there is no file in it delete the folder  xtts_v1
```
import os 
from TTS.utils.generic_utils import get_user_data_dir
model_path = os.path.join(get_user_data_dir("tts"), "tts_models--multilingual--multi-dataset--xtts_v1")
print(model_path)
```

Then after deleting xtts_v1 folder (if its contents are empty!) you can download model within code with this
```
import os 
os.environ["COQUI_TOS_AGREED"] = "1"
from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1") 
```



https://huggingface.co/coqui/XTTS-v1/discussions/8#651dc7be3cc79d62e6a9b864

**Comment by erogol** [comment]
I close this due to inactivity.
