### ISSUE TITLE
There Is No way to install three of the required dependencies on M1 and M2 Mac [Bug] 

### ISSUE THREAD

**Issue by Hamish-Leahy** [coqui-ai/TTS#2978]
### Describe the bug

Hello 
I have been having syntax errors printing when i have been trying to clone your repo and boot it 
this is an issue i believe to be related to the M1 and M2 hardware compatibility layers.
So sorry to disturb you and if this is a stupid question then my bad just trying to get it working

### To Reproduce

Git Clone (Repo Link Here)

Error that printed:
Syntax Error Unable To Contact Host

### Expected behavior

To just Git clone like usual as i have done before

### Environment

```shell
- tts version 1 
- Git Clone
- Syntax Error Logs
```

**Comment by erogol** [comment]
no enough info to reprduce
