### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by furqan4545** [coqui-ai/TTS#2984]
### Describe the bug

<img width="1074" alt="image" src="https://github.com/coqui-ai/TTS/assets/50285664/43d0f200-315f-4026-92e2-35d4e41d9f6c">

It doesn't have any builtin speaker voice because the array is always empty.So, just wanna ask does xtts come with any builtin voice library that user can use right away? if yes, where to find it and how to use it?

### To Reproduce

issue above

### Expected behavior

issue above

### Logs

```shell
issue above
```

### Environment

```shell
issue above
```

### Additional context

issue above

**Comment by WeberJulian** [comment]
Nope sorry, no built in speakers. Only voice cloning.
