### ISSUE TITLE
[Bug] metadata-generation-failed

### ISSUE THREAD

**Issue by mriamnobody** [coqui-ai/TTS#2987]
### Describe the bug

After downloading the `TTS` from release section section, I ran `pip install -r requirements.txt` and the following error occurred. I never installed `pytorch` (usually I first try to install a repository with the default packages/dependencies to check whether it is running or having some conflict. When there are no conflicts then I proceed with installing `pytorch` (if the repo needs it).

As I was getting error "Comment is too long (maximum is 65536 characters): 

![Screenshot (2604)](https://github.com/coqui-ai/TTS/assets/14347205/7e9ee11d-93d0-4eee-9649-bbdc7f3251fb)

I have pasted the whole log on Pastebin and here is the link for the log: [https://pastebin.com/kurdhNkf](url)

### To Reproduce

To reproduce the problem run the command `pip install -r requirements.txt`

### Expected behavior

All dependencies should be installed without any conflict

### Environment

```shell
TTS Version: V0.17.4
Python: V3.10.7
OS: Windows 11
Cuda: V11.8
Cudnn version: 8.9
GPU Model: Nvidia 3090
How you installed Pytorch: never installed pytorch instead I `pip install -r requirements.txt`
```

**Comment by mriamnobody** [comment]
something similar is happening at https://github.com/coqui-ai/TTS/issues/2986.

**Comment by CreeperCatcherD** [comment]
Same error here. I tried on different machines with no luck.
```
Desktop:
Python: 3.10.9
OS: Windows 10
GPU Model: 3060 Ti
```
```
Laptop:
Python: 3.10.9
OS: Windows 10
GPU: None
```

In both, ```pip install TTS``` is successful for most of the install process until it throws an error:
```Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [782 lines of output]
```

miramnobody's Pastebin link does not work for me, so here is a link to the error that I am getting: https://pastebin.com/dN7q8tVS

**Comment by WilliamKeating** [comment]
I'm getting the same error when cloning the GitHub and building 
`git clone https://github.com/coqui-ai/TTS
pip install -e .[all,dev,notebooks]  # Select the relevant extras` 

Tried both on M1 MacbookAir and Google Colab 
`error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

**Comment by erogol** [comment]
duplicate #2986
