### ISSUE TITLE
[Bug]Training using multiple GPU's

### ISSUE THREAD

**Issue by 18Raksha** [coqui-ai/TTS#2997]
### Describe the bug

RuntimeError:  [!] 2 active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`.

But i cannot find distribute.py in that location also distribute.py is in TTS/utils/distribute.py

I am trying use multiple GPU for training on custom data, but i face the above error when i start the training.

### To Reproduce

python train.py

### Expected behavior

Training should start 

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A100-PCIE-40GB",
            "NVIDIA A100-PCIE-40GB",
            "NVIDIA A100-PCIE-40GB"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu117",
        "TTS": "0.16.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.0",
        "version": "#1 SMP Thu Aug 31 10:29:22 EDT 2023"
    }
}
```

**Comment by erogol** [comment]
What's the error?

**Comment by 18Raksha** [comment]
@erogol the error :

RuntimeError: [!] 2 active GPUs. Define the target GPU by CUDA_VISIBLE_DEVICES. For multi-gpu training use TTS/bin/distribute.py.

**Comment by erogol** [comment]
"Define the target GPU by CUDA_VISIBLE_DEVICES"

**Comment by VafaKnm** [comment]
i have same problem. can you fix it @18Raksha ?

**Comment by r666ay** [comment]
I define CUDA_VISIBLE_DEVICES, but it doesn't work at all.
