### ISSUE TITLE
[Bug] pip install TTS failing, related to sentencepiece==0.1.91

### ISSUE THREAD

**Issue by arbudiman** [coqui-ai/TTS#2998]
### Describe the bug

I tried installing TTS but I got an error. The error occurred after I reinstalled Ubuntu. I tried downgrading the TTS version to 0.16.6 but the error still persists. Error that appears when collecting sentence pieces from transformers. The installation process stopped after failing to collect sentencespiece from transformer. Before the latest version of TTS appeared, TTS installation had no problems and was normal. So far I have not found a way to fix this and TTS cannot be installed.

### To Reproduce

update conda
update setuptools
still can't install tts, error is still in the same process in collecting sentencepiece from transformers

### Logs

```shell
Collecting sentencepiece==0.1.91 (from transformers->TTS==0.16.6)
  Using cached sentencepiece-0.1.91.tar.gz (500 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'sentencepiece' found
      Failed to find sentencepiece pkgconfig
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Environment

```shell
TTS 0.17.4 and try TTS 0.16.6
python : 3.9
conda : 23.7.4
pip : 23.2.1
GPU : RTX 3060 12 Gb
OS : ubuntu 18.04
Cuda : 11.7
cudnn : 8.5.0
```

**Comment by WeberJulian** [comment]
Can you please try `pip install TTS==0.17.5`

**Comment by arbudiman** [comment]
I tried pip install TTS=0.17.5 but it still failed. I finally tried to install using Ubuntu 20.04 and Python 3.10 was successfully installed. I think python3.9 doesn't support sentencespiece 0.1.91.

**Comment by arbudiman** [comment]
and now I run TTS 0.17.5 normally using ubuntu 20.04 and python3.10

**Comment by WeberJulian** [comment]
Weird, our CI test 3.9 and could install TTS just fine. I'm gonna close for now, please feel free to reopen if you keep having issues.
