### ISSUE TITLE
[Bug] AttributeError: 'VoiceBpeTokenizer' object has no attribute 'preprocess'

### ISSUE THREAD

**Issue by Lenos500** [coqui-ai/TTS#3000]
### Describe the bug

When I execute the hugging face demo (https://huggingface.co/spaces/Olivier-Truong/XTTS_V1_CPU_working) on my local pc it loads the model fine and it opens a web gui on localhost. However, when I select an audio and type some text and click on the submit button to start the voice cloning process. The demo shows processing for few seconds then gives an attribute error . (I'm trying to run XTTS V1).

### To Reproduce

1. python3 app.py ( The hugging face space app script)
2. Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/test/XTTS_V1_CPU_working/app.py", line 49, in predict
    tts.tts_to_file(
  File "/home/test/.local/lib/python3.9/site-packages/TTS/api.py", line 390, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "/home/test/.local/lib/python3.9/site-packages/TTS/api.py", line 337, in tts
    wav = self.synthesizer.tts(
  File "/home/test/.local/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 375, in tts
    outputs = self.tts_model.synthesize(
  File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 428, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 450, in inference_with_config
    return self.inference(text, ref_audio_path, language, **settings)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 529, in inference
    text_tokens = torch.IntTensor(self.tokenizer.encode(text, lang=language)).unsqueeze(0).to(self.device)
  File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 274, in encode
    if self.preprocess:
AttributeError: 'VoiceBpeTokenizer' object has no attribute 'preprocess'

### Environment

```shell
Python version = 3.10.3
Tts = 0.17. 5
Pytorch version = latest
transformers and numpy versions = latest
Ram available is 16gb ram
GPU is gtx 1050 ti which has 4gb Vram
It's an intel i7 7th gen laptop (I'm running this as CPU only on a kali Linux machine in virtualbox with 14gb ram. Your_TTS runs very well on this same machine. 
```

**Comment by premg16** [comment]
I am getting the issue. Did it solved?

**Comment by Lenos500** [comment]
> I am getting the issue. Did it solved?

No, no one told me how to solve it. I'm waiting for help.

**Comment by Lenos500** [comment]
> ### Describe the bug
> When I execute the hugging face demo (https://huggingface.co/spaces/Olivier-Truong/XTTS_V1_CPU_working) on my local pc it loads the model fine and it opens a web gui on localhost. However, when I select an audio and type some text and click on the submit button to start the voice cloning process. The demo shows processing for few seconds then gives an attribute error . (I'm trying to run XTTS V1).
> 
> ### To Reproduce
> 1. python3 app.py ( The hugging face space app script)
> 2. Traceback (most recent call last):
>    File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
>    output = await app.get_blocks().process_api(
>    File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1431, in process_api
>    result = await self.call_function(
>    File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1103, in call_function
>    prediction = await anyio.to_thread.run_sync(
>    File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 33, in run_sync
>    return await get_asynclib().run_sync_in_worker_thread(
>    File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
>    return await future
>    File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
>    result = context.run(func, *args)
>    File "/usr/local/lib/python3.9/dist-packages/gradio/utils.py", line 707, in wrapper
>    response = f(*args, **kwargs)
>    File "/home/test/XTTS_V1_CPU_working/app.py", line 49, in predict
>    tts.tts_to_file(
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/api.py", line 390, in tts_to_file
>    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/api.py", line 337, in tts
>    wav = self.synthesizer.tts(
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 375, in tts
>    outputs = self.tts_model.synthesize(
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 428, in synthesize
>    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 450, in inference_with_config
>    return self.inference(text, ref_audio_path, language, **settings)
>    File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>    return func(*args, **kwargs)
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 529, in inference
>    text_tokens = torch.IntTensor(self.tokenizer.encode(text, lang=language)).unsqueeze(0).to(self.device)
>    File "/home/test/.local/lib/python3.9/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 274, in encode
>    if self.preprocess:
>    AttributeError: 'VoiceBpeTokenizer' object has no attribute 'preprocess'
> 
> ### Expected behavior
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Environment
> ```shell
> Python version = 3.10.3
Tts = 0.17. 5
> Pytorch version = latest
> transformers and numpy versions = latest
> Ram available is 16gb ram
> GPU is gtx 1050 ti which has 4gb Vram
> It's an intel i7 7th gen laptop (I'm running this as CPU only on a kali Linux machine in virtualbox with 14gb ram. Your_TTS runs very well on this same machine. 
> ```
> 
> ### Additional context
> _No response_

**Comment by erogol** [comment]
duplicate #3005
