### ISSUE TITLE
[Bug] compute_attention_masks.py doesn't work

### ISSUE THREAD

**Issue by akx** [coqui-ai/TTS#3002]
### Describe the bug

`TTS/bin/compute_attention_masks.py` doesn't work due to what I assume are imports that have been moved around.

My PyCharm highlights

```
from TTS.tts.datasets.TTSDataset import TTSDataset
from TTS.tts.utils.text.characters import make_symbols, phonemes, symbols
```

as missing imports.

### To Reproduce

```
$ python TTS/bin/compute_attention_masks.py
Traceback (most recent call last):
  File "/Users/akx/build/coqui-tts/TTS/bin/compute_attention_masks.py", line 12, in <module>
    from TTS.tts.datasets.TTSDataset import TTSDataset
ModuleNotFoundError: No module named 'TTS.tts.datasets.TTSDataset'
```

### Expected behavior

Not an ImportError.

### Environment

```shell
TTS version: 0b95b88f138b58982fe078b13ab56efcb0f751f0
```

**Comment by erogol** [comment]
I don't think we'll touch this until we need this internally. But if someone is willing to fix it, help is here.

**Comment by Nagispace** [comment]
You can use mozilla's [symbols.py](https://github.com/mozilla/TTS/blob/master/TTS/tts/utils/text/symbols.py) and change the imports. For the TTSDataset you just need to point to its right location
```
from TTS.tts.datasets.dataset import TTSDataset
from TTS.tts.utils.text.symbols import make_symbols, phonemes, symbols
```
