### ISSUE TITLE
[Bug] XTTS can't set length_penalty

### ISSUE THREAD

**Issue by davtoro** [coqui-ai/TTS#3023]
### Describe the bug

I see in XTTS config that length_penalty can be set but I'm getting this:

UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `0.6` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.

But when running with num_beams higher than 1 I'm getting:
```
Traceback (most recent call last):
...
    next_tokens = torch.multinomial(probs, num_samples=2 * num_beams)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

### To Reproduce

```
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

config = XttsConfig()
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_dir="/home/sssss.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v1/", eval=True)
model.cuda()

config.length_penalty=0.6

outputs = model.synthesize(
   "something",
    config,
    speaker_wav="/path/to/wav",
    language="en",
)
```

### Expected behavior

length_penalty working

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.0+cu117",
        "TTS": "0.17.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2"
    }
}
```

**Comment by erogol** [comment]
@Edresson can you look at this?

**Comment by Edresson** [comment]
Hi @davtoro,

It is not really a bug. As default, currently, XTTS is using multinomial sampling by calling [sample()](https://huggingface.co/docs/transformers/v4.18.0/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.sample) because num_beams=1 and do_sample=True. See details here: https://huggingface.co/docs/transformers/v4.18.0/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin


You can control length_penalty  by setting num_beams to > 1. Example:

```


from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

config = XttsConfig()
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_dir="~/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v1/", eval=True)
model.cuda()

config.length_penalty=0.65

model.gpt_batch_size = 1

outputs = model.synthesize(
   "Text",
    config,
    speaker_wav="/raid/edresson/dev/ref.wav",
    language="en",
    num_beams=6,
    temperature=0.9,
)

```

**Comment by davtoro** [comment]
Hello @Edresson 
Thanks, indeed changing temperature fixed the issue.
One more thing, what could be a reason for the model returning input (speaker wav) in the output? I am facing this issue not only locally but also when using your Hugging Face demo. The output is returned as around first 3 seconds of the input, or a few seconds of the input are added to the beginning or end of the output. I can reproduce that on the same text and speaker every time.
