### ISSUE TITLE
[Feature request] Add Finetuning to XTTS Model

### ISSUE THREAD

**Issue by muhi-zatar** [coqui-ai/TTS#3026]
**🚀 Feature Description**

Excited for XTTS output for Arabic language since it is the first Arabic TTS released by Coqui TTS. However it does not offer fine-tuning or further training, which we could use to enhance the Arabic pronunciation with diacratization.

Thank you

**Comment by adhikjoshi** [comment]
Training script to add new languages +++

**Comment by erogol** [comment]
@muhi-zatar if you point out what we should do for diacratization, we can try internally.

**Comment by Edresson** [comment]
XTTS GPT training code will be available soon. You can see the progress on the PR https://github.com/coqui-ai/TTS/pull/3086

**Comment by Edresson** [comment]
It was already added in the latest :frog: TTS version: https://tts.readthedocs.io/en/dev/models/xtts.html#training
