### ISSUE TITLE
[Bug] XTTS output. 

### ISSUE THREAD

**Issue by Lenos500** [coqui-ai/TTS#3032]
### Describe the bug

70% of the times of using xtts in hugging face leads to an output audio which is just the same input audio all over again instead of the input text being converted to new cloned speech. Sometimes the output contains words from the input audio and some new cloned words from the input text. 

### To Reproduce

Use the hugging face demo or record an audio in any language other than English and try to produce an output in Arabic for example. 

### Environment

```shell
Coqui Xtts hugging face public space demo
```

**Comment by Selectorrr** [comment]
Same problem. It really makes this model useless

**Comment by Lenos500** [comment]
> Same problem. It really makes this model useless

Well actually when it works, the results are really impressive, but most cases repeat the input audio either partially or fully.

**Comment by erogol** [comment]
next release will make the model less useless. Should be this week.

**Comment by Lenos500** [comment]
> next release will make the model less useless. Should be this week.

When will xtts v2 be released?

**Comment by Lenos500** [comment]
> next release will make the model less useless. Should be this week.

Is the new XTTS model still releasing this week?

**Comment by erogol** [comment]
Probably

**Comment by Selectorrr** [comment]
@erogol Thank you so much! The hallucinations are gone! I think we can close the bug.

**Comment by Lenos500** [comment]
> @erogol Thank you so much! The hallucinations are gone! I think we can close the bug.

Did they release a new fixed model or fix something within the scripts of tts itself?

**Comment by Selectorrr** [comment]
@erogol This bug is reproduced after fine Fine-tuning model by this [recipes](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/xtts_v1/train_gpt_xtts.py)
Should we reopen the bug?

**Comment by Lenos500** [comment]
> @erogol This bug is reproduced after Fine-tuning model by this [recipes](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/xtts_v1/train_gpt_xtts.py) Should we reopen the bug?

How did you fix it at first place?

**Comment by Selectorrr** [comment]
xtts_v1 experiences the same problems (appearance of the source audio in the inference) that we get after fine-tune xtts_v1.1.
@erogol  Can you please tell me what has changed in model training between xtts_v1 and xtts_v1.1 ? @WeberJulian  Maybe this difference should be specified in [recipes](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/xtts_v1/train_gpt_xtts.py)

**Comment by Lenos500** [comment]
> I opened a new bug because apparently the problem is related to model training: #3122

But the hugging face demo no longer shows this problem, can I know please how you're reproducing it?
