### ISSUE TITLE
[Bug] xtts fine tune error

### ISSUE THREAD

**Issue by deryaguler95** [coqui-ai/TTS#3063]
### Describe the bug

I got this error : AttributeError: 'Xtts' object has no attribute 'get_criterion'
 in this line : trainer = Trainer(....)
I try to fine tune xtts with my data. Please can you help me?

### To Reproduce

 same

### Expected behavior

 training

### Logs

```shell
AttributeError: 'Xtts' object has no attribute 'get_criterion'
```

### Environment

```shell
TTS/bin/train_tts.py
```

### Additional context

 no

**Comment by lexkoro** [comment]
You can't finetune xtts yet.

**Comment by lexkoro** [comment]
You can't finetune xtts yet.

**Comment by CHIHHSIANGLI** [comment]
> You can't finetune xtts yet.

I just tried to finetune xtts and met this problem. What model can be finetuned now?  Your_tts? Other models are not as good as XTTS...

**Comment by deryaguler95** [comment]
I tried to your tts but I got other problems. I tried glowtts but results are include just noise. Therefore, I could not find model that can be finetune.

**Comment by debbagh185** [comment]
Me too I tried to finetune this model, but I had the same problem!

**Comment by todochenxi** [comment]
I'm also experiencing this problem, if there is a solution, please @ me, thank you very much!

**Comment by mshbaita-jo** [comment]
I'm also experiencing this problem , did anyone solve this problem?

**Comment by aibot8113-lab** [comment]
bro use glow_tts for fine tuning
