### ISSUE TITLE
[Feature request] xTTS server configuration example

### ISSUE THREAD

**Issue by darkzbaron** [coqui-ai/TTS#3075]
**🚀 Feature Description**

Not sure xTTS is supported in the server but in case it is could you please provide model and server config example? 

**Solution**

model configutation example for multi speaker models to implement in server in the documentation or in the repository

**Comment by gorkemgoknar** [comment]
there is a streaming server implementation available here, you can modify it for non-streaming too

https://github.com/coqui-ai/xtts-streaming-server
