### ISSUE TITLE
[Feat] :  Multilingual Support for Tacotron2

### ISSUE THREAD

**Issue by Parvezkhan0** [coqui-ai/TTS#3077]
**🚀 Feature Description**

The Tacotron2 model is a powerful tool for text-to-speech synthesis, but it currently lacks built-in support for multiple languages. Adding multilingual capabilities would significantly enhance its utility for a global user base.

**Solution**

Implement a mechanism to support multiple languages in the Tacotron2 model. This could involve adapting the model architecture, incorporating language embeddings, and providing tools for data preprocessing in different languages.

**Alternative Solutions**

One alternative approach to achieving multilingual support is to explore the possibility of using a language-agnostic pre-trained model as a starting point. This could involve fine-tuning the model with data from different languages to adapt it to various linguistic contexts.

**Additional context**

Adding multilingual support to Tacotron2 is an important step towards making the TTS library more versatile and globally accessible. It will empower users from diverse linguistic backgrounds to leverage the capabilities of Tacotron2 for speech synthesis in their respective languages. Your contributions to this enhancement will play a significant role in expanding the reach and impact of the TTS library. We look forward to your insights and expertise!

**Comment by Edresson** [comment]
Hi @Parvezkhan0,

I guess that the most interesting multilingual  Tacotron2  model is https://arxiv.org/abs/2008.00768 . However, we already have YourTTS and XTTS that are both multilingual models that in general achieved better quality than multilingual Tacotron2.
Do you still think that it is needed? Do you have a specific use case that YourTTS and XTTS can be used that a Tacotron 2 model can?
