### ISSUE TITLE
[Bug] Docker - No Matching Manifest (Apple M1 Pro 13.6)

### ISSUE THREAD

**Issue by stevebanik** [coqui-ai/TTS#3095]
### Describe the bug

For Mac M1 chipset there is no matching manifest for linux/arm64/v8 in the manifest list entries.

### To Reproduce

% docker run --rm -it -p 5002:5002 --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu
Unable to find image 'ghcr.io/coqui-ai/tts-cpu:latest' locally
latest: Pulling from coqui-ai/tts-cpu
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.

### Expected behavior

Expected the image to be found and pulled.

### Environment

```shell
Apple M1 Pro 13.6 (22G120)
```

**Comment by cherfia** [comment]
Try run docker with `--platform linux/amd64`. Your command would be: 
`docker run -platform linux/amd64 --rm -it -p 5002:5002 --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu`

**Comment by farzad-845** [comment]
> Try run docker with `--platform linux/amd64`. Your command would be: `docker run -platform linux/amd64 --rm -it -p 5002:5002 --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu`

There is a small issue with this, you should put two `-` before the platform argument.
The command should be:
` docker run --platform linux/amd64 --rm -it -p 5002:5002 --entrypoint /bin/bash ghcr.io/coqui-ai/tts-cpu`
