### ISSUE TITLE
Bug: Typo in code

### ISSUE THREAD

**Issue by pepetikesavasiddhardha** [coqui-ai/TTS#3113]
### Describe the bug

https://github.com/coqui-ai/TTS/blob/dev/TTS/tts/models/forward_tts.py in this file at line 225  
self.encoder = Encoder(
            self.args.hidden_channels,
            self.args.hidden_channels,
            self.args.encoder_type,
            self.args.encoder_params,
            self.embedded_speaker_dim,
        )
But self.args.hidden_channels, is accidentally typed 2 times instead the correct code should be 
self.encoder = Encoder(
            self.args.out_channels,
            self.args.hidden_channels,
            self.args.encoder_type,
            self.args.encoder_params,
            self.embedded_speaker_dim,
        )
I think it might be a typo.Please look into it and resolve it so the performance can be improved

### To Reproduce

I think above explination is understandable and just 1 word needs to be changed

### Environment

```shell
Latest version
```

**Comment by erogol** [comment]
the number of input and output channels should be the same for that model. It's intentional.
