### ISSUE TITLE
[Feature request]  Support voice clone on more languages, like zh-CN

### ISSUE THREAD

**Issue by dongwangdw** [coqui-ai/TTS#3119]
**🚀 Feature Description**

Hi I try to clone a voice in zh-CN. But the exceptions show:
```
Language zh-CN is not in the available languages: dict_keys(['en', 'fr-fr', 'pt-br']).
```

How can I enable it then? Any directions will be appreciated if I can help contribute.

**Comment by WeberJulian** [comment]
We already support voice cloning with that model: `tts_models/multilingual/multi-dataset/xtts_v1`
