### ISSUE TITLE
XTTS update: FIne-tuning decoder (hifigan) & Phoneme-based Model

### ISSUE THREAD

**Issue by KyeongJoong** [coqui-ai/TTS#3152]
**🚀 Feature Description**

Really impressive work! 

Is there any hifigan (vocoder) fine tuning code upon gpt latent output on XTTS? If so, it is really helpful to encourage the voice quality via fine-tuning

Also, it's still based on BPE tokenizers so that if we need to add the languages, we need to keep increase the number of tokens which influence the model architecture also. Do you have any specific reasons behind where you only apply bpe tokenizer?

**Comment by erogol** [comment]
There is no support for this. However, the Hifigan code is there as a separate vocoder. You can hack your own solution. We'll consider releasing it sometime future.
