### ISSUE TITLE
[Bug] Fine-error in trainer

### ISSUE THREAD

**Issue by cycham0** [coqui-ai/TTS#3162]
### Describe the bug

Cannot fine-tune glowTTS model.

edit 2023.11.08:
I also face this issuse when I try to use tacotron2-DDC

### To Reproduce

Fine tuning with dataset in ljspeech format with GlowTTS

```
CUDA_VISIBLE_DEVICES="0" python /<mypath>/TTS/recipes/ljspeech/glow_tts/train_glowtts.py \
    --restore_path  /<mypath>/data/tts/tts_models--en--ljspeech--glow-tts/model_file.pth
```

### Logs

```shell
> Traceback (most recent call last):
  File "<mypath>/TTS/recipes/ljspeech/glow_tts/train_glowtts.py", line 79, in <module>
    trainer = Trainer(
              ^^^^^^^^
  File "<mypath>/anaconda3/envs/KristyTTS/lib/python3.11/site-packages/trainer/trainer.py", line 400, in __init__
    config, new_fields = self.init_training(args, coqpit_overrides, config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mypath>/anaconda3/envs/KristyTTS/lib/python3.11/site-packages/trainer/trainer.py", line 738, in init_training
    new_fields["github_branch"] = get_git_branch()
                                  ^^^^^^^^^^^^^^^^
  File "<mypath>/anaconda3/envs/KristyTTS/lib/python3.11/site-packages/trainer/generic_utils.py", line 44, in get_git_branch
    current = next(line for line in out.split("\n") if line.startswith("*"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

Using conda enviroment with python 3.11
```

### Environment

```shell
return torch._C._cuda_getDeviceCount() if nvml_count < 0 else nvml_count
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.20.1",
        "numpy": "1.24.3"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.11.5",
        "version": "#1 SMP Wed Feb 23 16:47:03 UTC 2022"
    }
}
```

**Comment by loganhart02** [comment]
I wasn't able to replicate using the same env. maybe the version of the trainer is mismatched. Try installing the newest version of TTS.

**Comment by ghost** [comment]
This is a problem with `TTS/utils/generic_utils.py` in `get_git_branch()` function.


```python
out = subprocess.check_output(["git", "branch"]).decode("utf8")
current = next(line for line in out.split("\n") if line.startswith("*"))
```


If the output from `git branch` is an empty string, it never finds the `*` and sends nothing to `next`, so it raises `StopIteration` error. The solution is to also handle `StopIteration` errors.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Hi, I'm still facing this issue how can I solve it? and why does the trainer even need to get the branch name?

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
I found a solution using clude but I don't know if it does damage anything else or not:

from trainer.trainer import Trainer as BaseTrainer

class CustomTrainer(BaseTrainer):
    def init_training(self, args, coqpit_overrides, config):
        new_fields = {}
        if args.continue_path:
            new_fields["continue_path"] = args.continue_path
        if args.restore_path:
            new_fields["restore_path"] = args.restore_path
        # We simply skip the github_branch line that was causing the error
        return config, new_fields
```
# Then use CustomTrainer instead of Trainer in your code
trainer = CustomTrainer(
    TrainerArgs(
        restore_path=None,
        skip_train_epoch=False,
        start_with_eval=START_WITH_EVAL,
        grad_accum_steps=GRAD_ACUMM_STEPS,
    ),
    config,
    output_path=OUT_PATH,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples,
)
trainer.fit()
```

**Comment by eginhard** [comment]
@Aml-Hassan-Abd-El-hamid This is fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), which you can install with `pip install coqui-tts`. This repo is not maintained anymore.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
I didn't know that!
Thanks a lot @eginhard 
I have one final question: should I un-install the current package before installing yours?

**Comment by eginhard** [comment]
@Aml-Hassan-Abd-El-hamid Yes.
