### ISSUE TITLE
[Feature request] CLI file input

### ISSUE THREAD

**Issue by Martinligabue** [coqui-ai/TTS#3175]
**🚀 Feature Description**

I can't input a txt file, only direct text via --text, that is limited in number of characters.
**Solution**

A file parameter would be nice.
**Alternative Solutions**

The only way I can do something for now is to split manually the sentences and feed them one by one, maybe it can be automated, but it's still not thebest way.
**Additional context**

**Comment by WeberJulian** [comment]
You can load the text file with python and feed it all to the API https://github.com/coqui-ai/TTS/blob/dev/README.md#running-a-multi-speaker-and-multi-lingual-model

**Comment by shahbaz9221** [comment]
I have created a pull request for this feature. It's my first contribution to open source.
I am not sure what to do next. This PR addresses the CLI file input for extensive text.
Link: [PR](https://github.com/coqui-ai/TTS/pull/3195)
