### ISSUE TITLE
[Bug] KeyError: 'xtts_v2'

### ISSUE THREAD

**Issue by KKOSGPT** [coqui-ai/TTS#3181]
### Describe the bug

by using:

tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

### To Reproduce

 KeyError: 'xtts_v2'

### Expected behavior

download the model

### Logs

```shell
Traceback (most recent call last):
  File "F:\project\TTS-dev\xtts_test.py", line 12, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
  File "F:\project\TTS-dev\TTS\api.py", line 81, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "F:\project\TTS-dev\TTS\api.py", line 179, in load_tts_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(
  File "F:\project\TTS-dev\TTS\api.py", line 142, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "F:\project\TTS-dev\TTS\utils\manage.py", line 377, in download_model
    model_item, model_full_name, model, md5sum = self._set_model_item(model_name)
  File "F:\project\TTS-dev\TTS\utils\manage.py", line 295, in _set_model_item
    model_item = self.models_dict[model_type][lang][dataset][model]
KeyError: 'xtts_v2'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080 Ti"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu118",
        "TTS": "0.19.1",
        "numpy": "1.26.1"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
        "python": "3.10.11",
        "version": "10.0.17763"
    }
}
```

### Additional context

{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080 Ti"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu118",
        "TTS": "0.19.1",
        "numpy": "1.26.1"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
        "python": "3.10.11",
        "version": "10.0.17763"
    }
}

**Comment by Lenos500** [comment]
Why don't you update TTS to the latest verison? However, even if you do so I guess you might encounter the handle error I encountered, but I guess you should try it.

**Comment by WeberJulian** [comment]
The solution is indeed to update TTS like so `pip install -U TTS`
