### ISSUE TITLE
AttributeError: 'TTS' object has no attribute 'is_multi_speaker'[Bug] 

### ISSUE THREAD

**Issue by lucasjinreal** [coqui-ai/TTS#3187]
### Describe the bug

 pip list  | grep TTS                                 
TTS                                0.20.2

### To Reproduce

 pip list  | grep TTS                                 
TTS                                0.20.2

### Environment

```shell
pip list  | grep TTS                                 
TTS                                0.20.2
```

**Comment by mayi203** [comment]
me too ....

**Comment by bank010** [comment]
+1

**Comment by vitaliy-sharandin** [comment]
+1

**Comment by khoa-nguyendang** [comment]
same for version
0.20.1, 0.20.2, 0.20.3

**Comment by xxm1668** [comment]
me too

**Comment by Ratelsun** [comment]
这个问题到现在还没有解决吗？我也遇到了。

**Comment by bigcash** [comment]
也遇到了这个问题，经过查看代码分析后，解决了。
因为从huggingface上下载模型较慢，所以我的模型是指定的本地路径，即tts = TTS(模型路径)，但这个路径中并不包含"tts_models"或者"coqui_studio"，所以导致tts对象中的is_multi_speaker在对象实例创建时从方法转成attribute时出错。如果你也是这样出错的，可以这样修改：
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2")
手动创建目录.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2，并创建config.json,dvae.pth,hash.md5,mel_stats.pth,model.pth,vocab.json等文件的软链接。这样应该就解决了。

**Comment by erogol** [comment]
@bigcash thanks

**Comment by seetimee** [comment]
> 也遇到了这个问题，经过查看代码分析后，解决了。 因为从huggingface上下载模型较慢，所以我的模型是指定的本地路径，即tts = TTS(模型路径)，但这个路径中并不包含"tts_models"或者"coqui_studio"，所以导致tts对象中的is_multi_speaker在对象实例创建时从方法转成attribute时出错。如果你也是这样出错的，可以这样修改： tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2") 手动创建目录.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2，并创建config.json,dvae.pth,hash.md5,mel_stats.pth,model.pth,vocab.json等文件的软链接。这样应该就解决了。
> 
> 或者也可以直接将模型路径中增加“tts_models”字符串，应该也可以，不过这样改我没测试。

正解,但是我现在 TTS' object has no attribute 'speakers'  列不出speakers诶,但是用官网的speaker="Ana Florence"又可以找到这个speaker,有啥方案么老哥
