### ISSUE TITLE
TTS/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual     for regex, replacement in _abbreviations[lang]: KeyError: 'zh-cn'[Bug] 

### ISSUE THREAD

**Issue by lucasjinreal** [coqui-ai/TTS#3189]
### Describe the bug

TTS/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'

### To Reproduce

TTS/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'

### Expected behavior

TTS/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'

### Logs

```shell
TTS/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'
```

### Environment

```shell
TTS/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
    for regex, replacement in _abbreviations[lang]:
KeyError: 'zh-cn'
```

**Comment by douhaohaode** [comment]
If zh-cn and zh represent Chinese, it is recommended to use one.

**Comment by lucasjinreal** [comment]
I think the tokenizer these map's keys should be consistent with language codes.

**Comment by AIFSH** [comment]
before offical fix
```
pip uninstall TTS
pip install TTS==0.20.2
```
work!

**Comment by jbang2004** [comment]
> If zh-cn and zh represent Chinese, it is recommended to use one.
> 
> 如果想运行可以手动先更改TTS文件下tokenizer.py中118行和283行 zh改为zh-cn

可以啊兄弟，对了，兄弟知道怎么保存说话人的潜在特征和嵌入，使用这些特征生成多段对话吗？现在每次都要先生成特征，再推理，效率很低

**Comment by lucasjinreal** [comment]
@jbang2004 可以，但是官方似乎压根没有考虑这个问题

**Comment by jbang2004** [comment]
> @jbang2004 可以，但是官方似乎压根没有考虑这个问题

研究了一个上午，官方文档里有个直接从模型提取特征，然后用torchaudio生成wav的方法，这个可以一直沿用相同的特征进行转换，不过这种方法生成的效果比使用api差一些，不知道为什么

**Comment by lucasjinreal** [comment]
@jbang2004 方便分享一下代码吗

**Comment by genglinxiao** [comment]
I think there are 2 places that the key code used for Chinese language are inconsistent:
The model uses "zh-cn" for the Chinese (simplifed) language. However, the key defined in the _abbreviations and the _symbols_multilingual for Chinese language is "zh". These 2 structures are used in expand_abbreviations_multilingual() and expand_symbols_multilingual() respectively, resulting in key errors.

In my case, I changed the key from "zh-cn" to "zh" inside these 2 functions by adding the following lines to the functions.
```
    if lang=="zh-cn":
        lang="zh"
```

But I think there ought to be a cleaner solution.
