### ISSUE TITLE
[Bug] Total eval samples after filtering: 0

### ISSUE THREAD

**Issue by Scralius** [coqui-ai/TTS#3198]
### Describe the bug

When i start TTS/recipes/ljspeech/xtts_v2/train_gpt_xtts.py (that i modify to use my dataset according to the documentation) i have this :  
python /home/theo/coqui/TTS/recipes/ljspeech/xtts_v2/train_gpt_xtts_My_training.py
>> DVAE weights restored from: /home/theo/coqui/TTS/recipes/ljspeech/xtts_v2/run/training/XTTS_v2.0_original_model_files/dvae.pth
 | > Found 525 files in /home/theo/coqui/datasets/My_dataset
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 16
 | > Num. of Torch Threads: 1
 | > Torch seed: 1
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=/home/theo/coqui/TTS/recipes/ljspeech/xtts_v2/run/training/GPT_XTTS_v2.0_LJSpeech_FT-November-11-2023_05+08PM-0000000

 > Model has 517360175 parameters

 > EPOCH: 0/1000
 --> /home/theo/coqui/TTS/recipes/ljspeech/xtts_v2/run/training/GPT_XTTS_v2.0_LJSpeech_FT-November-11-2023_05+08PM-0000000
 > Filtering invalid eval samples!!
 > Total eval samples after filtering: 0
 ! Run is removed from /home/theo/coqui/TTS/recipes/ljspeech/xtts_v2/run/training/GPT_XTTS_v2.0_LJSpeech_FT-November-11-2023_05+08PM-0000000
Traceback (most recent call last):
  File "/home/theo/anaconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/home/theo/anaconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1762, in _fit
    self.eval_epoch()
  File "/home/theo/anaconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1610, in eval_epoch
    self.get_eval_dataloader(
  File "/home/theo/anaconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 976, in get_eval_dataloader
    return self._get_loader(
  File "/home/theo/anaconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 900, in _get_loader
    len(loader) > 0
AssertionError:  ❗ len(DataLoader) returns 0. Make sure your dataset is not empty or len(dataset) > 0.

### To Reproduce

Create a conda env with python 3.10 follow the instrallation guide.
Modify the traning script (/TTS/recipes/ljspeech/xtts_v2/train_gpt_xtts.py) to use your dataset and start the training.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.20.3",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.13",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

### Additional context

I try on windows, google colab and wsl (ubuntu 20.04.6LTS) and I have the same error.
I check how many eval_samples I have, and i have 5 samples not 0 so i don't know where the problem comes from!

**Comment by AIFSH** [comment]
same error，what's wrong!

**Comment by AIFSH** [comment]
> same error，what's wrong! 

fault by self, wrong dataset format

**Comment by Scralius** [comment]
I find what was wrong with my dataset! I had just put .wav at the end of my file name for my wav file ("audio1.wav|This is my sentence.|This is my sentence." instead of "audio1|This is my sentence.|This is my sentence.")
