### ISSUE TITLE
[Bug] Strange noises at the end of the generation after fine-tuning the XTTS model.

### ISSUE THREAD

**Issue by brambox** [coqui-ai/TTS#3204]
### Describe the bug

I'm getting strange noises at the end of the generation after fine-tuning the XTTS model. It is 
happening with both versions 1.1 and 2.0. It sounds like it's saying 'A' or some random mumbling.

### To Reproduce

Im using the inference example in docs 

https://tts.readthedocs.io/en/dev/models/xtts.html

import os
import torch
import torchaudio
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

# Add here the xtts_config path
CONFIG_PATH = "recipes/ljspeech/xtts_v1/run/training/GPT_XTTS_LJSpeech_FT-October-23-2023_10+36AM-653f2e75/config.json"
# Add here the vocab file that you have used to train the model
TOKENIZER_PATH = "recipes/ljspeech/xtts_v1/run/training/XTTS_v2_original_model_files/vocab.json"
# Add here the checkpoint that you want to do inference with
XTTS_CHECKPOINT = "recipes/ljspeech/xtts_v1/run/training/GPT_XTTS_LJSpeech_FT/best_model.pth"
# Add here the speaker reference
SPEAKER_REFERENCE = "LjSpeech_reference.wav"

# output wav path
OUTPUT_WAV_PATH = "xtts-ft.wav"

print("Loading model...")
config = XttsConfig()
config.load_json(CONFIG_PATH)
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_path=XTTS_CHECKPOINT, vocab_path=TOKENIZER_PATH, use_deepspeed=False)
model.cuda()

print("Computing speaker latents...")
gpt_cond_latent, speaker_embedding = model.get_conditioning_latents(audio_path=[SPEAKER_REFERENCE])

print("Inference...")
out = model.inference(
    "It took me quite a long time to develop a voice and now that I have it I am not going to be silent.",
    "en",
    gpt_cond_latent,
    speaker_embedding,
    temperature=0.7, # Add custom parameters here
)
torchaudio.save(OUTPUT_WAV_PATH, torch.tensor(out["wav"]).unsqueeze(0), 24000)

### Environment

```shell
TTS v0.20.3
Python 3.10
```

**Comment by AIFSH** [comment]
same case

**Comment by erogol** [comment]
This is something we recognized. @Edresson is working on a fix. We belive there is a bug in the code somewhere.

**Comment by ukemamaster** [comment]
i am getting same noises

**Comment by FurkanGozukara** [comment]
Do you see vram usage increae during training?

Mine is like using only cpu

Can you share your venv pip freeze and config please

@brambox @AIFSH @ukemamaster

**Comment by ukemamaster** [comment]
@FurkanGozukara I am training with a single GPU, and i don't have RAM or CPU usage issues.

**Comment by stlohrey** [comment]
I observed this to mostly happen when there is a full stop in the end, can you confirm?

**Comment by ukemamaster** [comment]
@stlohrey Exactly.

**Comment by brambox** [comment]
There are still now like door cracks or something like that in end of generation.

**Comment by stlohrey** [comment]
Unfortunately, the Issue persists. Also, sometimes the punctuation in the end is actually spoken.

**Comment by carinae** [comment]
Yes, it seems to pronouce a kind of "point", shame because the result is pretty good for French.
[answer to question about atoms in french](https://drive.proton.me/urls/252QSFXQS0#tLXSZgucCSZol)
The trick is to replace by ',' or add it after the point -> xxx.','

**Comment by Nanshanelectrician** [comment]
Yes, I also have noise. How can I optimize it

**Comment by fcrescio** [comment]
I confirm that punctuation is problematic also in italian. It's spoken "... punto" and it also produce incertitudes and strange noise. It's actually amusing, like hearing a real human not very good at reading, but I suppose this is not the intended behaviour.

**Comment by danielmzak** [comment]
In Czech (xtts_v2 model) try replacing "." with ";\n" - this will make the ends of sentences sound more natural.

**Comment by staltux** [comment]
Why is it closed if it's still happening?

**Comment by revelnode** [comment]
I just tested myself, and I have the same thing... depending on the voice, it either sounds like "Eh" or "Ugh" at the full stop of a sentence.

**Comment by ffleader1** [comment]
Yeah can confirm it is still happening in 2026
So the trick is
Never use full stop I guess
