### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pyh007** [coqui-ai/TTS#3220]
### Describe the bug

复刻声音的时候报错
import torch
from TTS.api import TTS

tts = TTS("tts_models/de/thorsten/tacotron2-DDC")
tts.tts_with_vc_to_file(
    "我在马路边捡到一分钱",
    speaker_wav="enhanced.wav",
    file_path="output.wav" 
)

### To Reproduce

import torch
from TTS.api import TTS

tts = TTS("tts_models/de/thorsten/tacotron2-DDC")
tts.tts_with_vc_to_file(
    "我在马路边捡到一分钱",
    speaker_wav="enhanced.wav",
    file_path="output.wav" 
)

### Logs

```shell
Traceback (most recent call last):
  File "/root/TTS/1.py", line 5, in <module>
    tts.tts_with_vc_to_file(
  File "/root/TTS/TTS/api.py", line 488, in tts_with_vc_to_file
    wav = self.tts_with_vc(text=text, language=language, speaker_wav=speaker_wav)
  File "/root/TTS/TTS/api.py", line 465, in tts_with_vc
    self.load_vc_model_by_name("voice_conversion_models/multilingual/vctk/freevc24")
  File "/root/TTS/TTS/api.py", line 160, in load_vc_model_by_name
    model_path, config_path, _, _, _ = self.download_model_by_name(model_name)
  File "/root/TTS/TTS/api.py", line 142, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "/root/TTS/TTS/utils/manage.py", line 410, in download_model
    output_model_path, output_config_path = self._find_files(output_path)
  File "/root/TTS/TTS/utils/manage.py", line 433, in _find_files
    raise ValueError(" [!] Model file not found in the output
```

### Environment

```shell
absl-py                   2.0.0                    pypi_0    pypi
accelerate                0.24.1                   pypi_0    pypi
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyascii                  0.3.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
astroid                   2.7.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
babel                     2.13.1                   pypi_0    pypi
bangla                    0.0.2                    pypi_0    pypi
black                     23.11.0                  pypi_0    pypi
blinker                   1.7.0                    pypi_0    pypi
bnnumerizer               0.0.2                    pypi_0    pypi
bnunicodenormalizer       0.1.6                    pypi_0    pypi
bokeh                     1.4.0                    pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
clean-fid                 0.1.35                   pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
clip-anytorch             2.5.2                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
coqpit                    0.0.17                   pypi_0    pypi
coverage                  7.3.2                    pypi_0    pypi
cutlet                    0.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.30                  pypi_0    pypi
dateparser                1.1.8                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
encodec                   0.1.1                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flask                     2.3.3                    pypi_0    pypi
fonttools                 4.44.0                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
fugashi                   1.3.0                    pypi_0    pypi
g2pkk                     0.1.2                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
google-auth               2.23.4                   pypi_0    pypi
google-auth-oauthlib      1.1.0                    pypi_0    pypi
grpcio                    1.59.2                   pypi_0    pypi
gruut                     2.2.3                    pypi_0    pypi
gruut-ipa                 0.13.0                   pypi_0    pypi
gruut-lang-de             2.0.0                    pypi_0    pypi
gruut-lang-en             2.0.0                    pypi_0    pypi
gruut-lang-es             2.0.0                    pypi_0    pypi
gruut-lang-fr             2.0.2                    pypi_0    pypi
hangul-romanize           0.1.0                    pypi_0    pypi
huggingface-hub           0.19.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.32.0                   pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
inflect                   5.6.2                    pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaconv                    0.3.4                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonlines                 1.2.0                    pypi_0    pypi
jsonmerge                 1.9.2                    pypi_0    pypi
jsonschema                4.19.2                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
k-diffusion               0.0.16                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.0                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
lazy-object-proxy         1.9.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libffi                    3.3                  he6710b0_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
librosa                   0.10.0                   pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
llvmlite                  0.40.1                   pypi_0    pypi
markdown                  3.5.1                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mecab-python3             1.0.6                    pypi_0    pypi
mojimoji                  0.0.12                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.7                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
networkx                  2.8.8                    pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
nose2                     0.14.0                   pypi_0    pypi
num2words                 0.5.13                   pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.52                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pillow                    10.0.1                   pypi_0    pypi
pip                       23.3             py39h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
platformdirs              4.0.0                    pypi_0    pypi
pooch                     1.8.0                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pylint                    2.10.2                   pypi_0    pypi
pynndescent               0.5.10                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pypinyin                  0.49.0                   pypi_0    pypi
pysbd                     0.3.4                    pypi_0    pypi
python                    3.9.0                hdb3f193_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
python-crfsuite           0.9.9                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
referencing               0.30.2                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resize-right              0.0.2                    pypi_0    pypi
rpds-py                   0.12.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scikit-image              0.22.0                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
sentry-sdk                1.35.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.3.7                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
sympy                     1.12                     pypi_0    pypi
tbb                       2021.10.0                pypi_0    pypi
tensorboard               2.15.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.9.26                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     2.1.0                    pypi_0    pypi
torchaudio                2.1.0                    pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchsde                  0.2.6                    pypi_0    pypi
torchvision               0.16.0                   pypi_0    pypi
tornado                   6.3.3                    pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
trainer                   0.0.31                   pypi_0    pypi
trampoline                0.1.2                    pypi_0    pypi
transformers              4.33.3                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
tts                       0.20.4                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tzlocal                   5.2                      pypi_0    pypi
umap-learn                0.5.4                    pypi_0    pypi
unidecode                 1.3.7                    pypi_0    pypi
unidic-lite               1.0.8                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
wandb                     0.16.0                   pypi_0    pypi
wcwidth                   0.2.10                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.4.2                h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
```

### Additional context

absl-py                   2.0.0                    pypi_0    pypi
accelerate                0.24.1                   pypi_0    pypi
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyascii                  0.3.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
astroid                   2.7.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
babel                     2.13.1                   pypi_0    pypi
bangla                    0.0.2                    pypi_0    pypi
black                     23.11.0                  pypi_0    pypi
blinker                   1.7.0                    pypi_0    pypi
bnnumerizer               0.0.2                    pypi_0    pypi
bnunicodenormalizer       0.1.6                    pypi_0    pypi
bokeh                     1.4.0                    pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
clean-fid                 0.1.35                   pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
clip-anytorch             2.5.2                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
coqpit                    0.0.17                   pypi_0    pypi
coverage                  7.3.2                    pypi_0    pypi
cutlet                    0.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.30                  pypi_0    pypi
dateparser                1.1.8                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
encodec                   0.1.1                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flask                     2.3.3                    pypi_0    pypi
fonttools                 4.44.0                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
fugashi                   1.3.0                    pypi_0    pypi
g2pkk                     0.1.2                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
google-auth               2.23.4                   pypi_0    pypi
google-auth-oauthlib      1.1.0                    pypi_0    pypi
grpcio                    1.59.2                   pypi_0    pypi
gruut                     2.2.3                    pypi_0    pypi
gruut-ipa                 0.13.0                   pypi_0    pypi
gruut-lang-de             2.0.0                    pypi_0    pypi
gruut-lang-en             2.0.0                    pypi_0    pypi
gruut-lang-es             2.0.0                    pypi_0    pypi
gruut-lang-fr             2.0.2                    pypi_0    pypi
hangul-romanize           0.1.0                    pypi_0    pypi
huggingface-hub           0.19.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.32.0                   pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
inflect                   5.6.2                    pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaconv                    0.3.4                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonlines                 1.2.0                    pypi_0    pypi
jsonmerge                 1.9.2                    pypi_0    pypi
jsonschema                4.19.2                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
k-diffusion               0.0.16                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.0                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
lazy-object-proxy         1.9.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libffi                    3.3                  he6710b0_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
librosa                   0.10.0                   pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
llvmlite                  0.40.1                   pypi_0    pypi
markdown                  3.5.1                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mecab-python3             1.0.6                    pypi_0    pypi
mojimoji                  0.0.12                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.7                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
networkx                  2.8.8                    pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
nose2                     0.14.0                   pypi_0    pypi
num2words                 0.5.13                   pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.52                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pillow                    10.0.1                   pypi_0    pypi
pip                       23.3             py39h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
platformdirs              4.0.0                    pypi_0    pypi
pooch                     1.8.0                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pylint                    2.10.2                   pypi_0    pypi
pynndescent               0.5.10                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pypinyin                  0.49.0                   pypi_0    pypi
pysbd                     0.3.4                    pypi_0    pypi
python                    3.9.0                hdb3f193_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
python-crfsuite           0.9.9                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
referencing               0.30.2                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resize-right              0.0.2                    pypi_0    pypi
rpds-py                   0.12.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scikit-image              0.22.0                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
sentry-sdk                1.35.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.3.7                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
sympy                     1.12                     pypi_0    pypi
tbb                       2021.10.0                pypi_0    pypi
tensorboard               2.15.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.9.26                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     2.1.0                    pypi_0    pypi
torchaudio                2.1.0                    pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchsde                  0.2.6                    pypi_0    pypi
torchvision               0.16.0                   pypi_0    pypi
tornado                   6.3.3                    pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
trainer                   0.0.31                   pypi_0    pypi
trampoline                0.1.2                    pypi_0    pypi
transformers              4.33.3                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
tts                       0.20.4                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tzlocal                   5.2                      pypi_0    pypi
umap-learn                0.5.4                    pypi_0    pypi
unidecode                 1.3.7                    pypi_0    pypi
unidic-lite               1.0.8                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
wandb                     0.16.0                   pypi_0    pypi
wcwidth                   0.2.10                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.4.2                h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main

**Comment by WeberJulian** [comment]
The `de` in the model name is for german. It won't work for chinese inference. You can use XTTSv2 for chinese inference.
