### ISSUE TITLE
[Bug] While finetune tts_models--multilingual--multi-dataset--xtts_v2, but error happen,how to fix it? Thanks in advance! 

### ISSUE THREAD

**Issue by jackyin68** [coqui-ai/TTS#3222]
### Describe the bug

Traceback (most recent call last):
File "D:\Projects\TTS\TTS\bin\train_tts.py", line 71, in
main()
File "D:\Projects\TTS\TTS\bin\train_tts.py", line 58, in main
trainer = Trainer(
File "D:\Projects\TTS\venv\lib\site-packages\trainer\trainer.py", line 502, in init
self.criterion = self.get_criterion(self.model)
File "D:\Projects\TTS\venv\lib\site-packages\trainer\trainer.py", line 2077, in get_criterion
criterion = model.get_criterion()
File "D:\Projects\TTS\venv\lib\site-packages\torch\nn\modules\module.py", line 1695, in getattr
raise AttributeError(f"'{type(self).name}' object has no attribute '{name}'")
AttributeError: 'Xtts' object has no attribute 'get_criterion'

### To Reproduce

[config.json](https://github.com/coqui-ai/TTS/files/13362242/config.json)

### Expected behavior

fine tune one person model using   tts_models--multilingual--multi-dataset--xtts_v2

### Environment

```shell
"Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cpu",
        "TTS": "0.20.4",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 63 Stepping 2, GenuineIntel",
        "python": "3.9.13",
        "version": "10.0.22000"
    }
}
```

**Comment by WeberJulian** [comment]
Please use the example recipe and don't FT the model directly: https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/xtts_v2/train_gpt_xtts.py

**Comment by jackyin68** [comment]
Many thanks to you, I shall try and feedback.
