### ISSUE TITLE
[Feature request] Finnish language support

### ISSUE THREAD

**Issue by mikkorantalainen** [coqui-ai/TTS#3225]
It seems that there is no open source solution for high quality speech synthesis in Finnish.

**Solution**

I'm volunteering to implement this. I can record audio samples and maybe train the model if it doesn't require too much VRAM. I only have an old GTX 1060 with 3 GB RAM if I need to run some CUDA programs.

I'd be glad to publish the recordings and results with MPL 2.0 license.

**Additional context**

I'd need pointers about how to add a new language instead of simply fine-tuning existing language. I would also want to have some idea how much audio I would need to record to have usable quality output.

**Comment by erogol** [comment]
We are working on Finnish. In the data collection stage. If you have data ping me on Discord -> erogol

**Comment by AsmoKoskinen** [comment]
I want to join this. My intention is to record my voice for a datset from the beginning of the year. I'll ping when I have enough audio files to test.

I plan to use Piper Recording Studio.

My intention is to follow the Thorsten-Voice guide to recordings:

LJSpeech file and directory structure
22.668 recorded phrases (wav files)
More than 23 hours of pure audio
Sample rate 22.050Hz
Mono
Normalized to -24dB
Phrase length (min/avg/max): 2 / 52 / 180 chars
No silence at beginning/end
Avg spoken chars per second: 14
Sentences with question mark: 2.780
Sentences with exclamation mark: 1.840

How much good quality audio data is needed? 24 hours?

**Comment by Arthil** [comment]
@erogol Amazing to hear that. Are you able to give any estimate on when this might get released?
