### ISSUE TITLE
Slow deep voice after Vits training

### ISSUE THREAD

**Issue by o3web** [coqui-ai/TTS#3235]
### Describe the bug

Hi,

I'm trying to train a model with my own voice. I recorded 150 samples with studio quality (44100Hz), which I reduced for training to 22050Hz. After 10000 epochs, I get a slow, deep voice far from the original voice.

What do I need to change to get a nearly original voice render?

Here is an example of the render with best_model_80000.pth after 10000 epochs with "Vous écoutez COQUI" (You listen to [COQUI)

https://github.com/coqui-ai/TTS/assets/62831563/c165133d-e443-4e68-804f-a7e161eb53c8

```
config = VitsConfig(
    batch_size=15,
    eval_batch_size=10,
    num_loader_workers=4,
    num_eval_loader_workers=4,
    run_eval=True,
    test_delay_epochs=-1,
    epochs=10000,
    save_step=1000,
    text_cleaner="french_cleaners",
    use_phonemes=True,
    phoneme_language="fr-fr",
    phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
    compute_input_seq_cache=True,
    print_step=25,
    print_eval=True,
    mixed_precision=True,
    output_path=output_path,
    characters=characters_config,
    datasets=[dataset_config],
    audio=audio_config,
    cudnn_benchmark=True,
    test_sentences=[
    ["Vous écouter COQUI"]
    ]
)
```

**Comment by manmay-nakhashi** [comment]
Check your downsampled samples , looks like a resampling issue.

**Comment by o3web** [comment]
Ok I used ffmpeg to convert stereo to mono and resample. I need to try with 44.1 ?

**Comment by manmay-nakhashi** [comment]
Post your audio config and downsampled audio.

**Comment by o3web** [comment]
```
audio_config = VitsAudioConfig(
    sample_rate=22050, win_length=1024, hop_length=256, num_mels=80, mel_fmin=0, mel_fmax=None
)
```
Audio sample
https://github.com/coqui-ai/TTS/assets/62831563/fd7efb08-3181-4f54-b361-aa661cd97989

**Comment by o3web** [comment]
If you want a much longer sentence, here it is "Les plats traditionnels sont délicieux" : Traditional dishes are delicious

https://github.com/coqui-ai/TTS/assets/62831563/1f090423-5a9c-47c5-8aa2-1f3aa710eb10

**Comment by WeberJulian** [comment]
Both samples you shared are still 44khz, either train a 44khz model or downsample your dataset to match the config sr.
