### ISSUE TITLE
[Feature request] Could add a switch to disabled the remote config check that in check_if_configs_are_equal function in TTS/utils/manage.py file

### ISSUE THREAD

**Issue by listeng** [coqui-ai/TTS#3246]
Sometimes in Intranet which could not connect to Internet, the **check_if_configs_are_equal** function (in TTS/utils/manage.py file) check the local config version and the remote config version will failed and halt on so much time. Would it be possible to add a parameter setting to enable or disable this version of the check? Thanks.

**Comment by WeberJulian** [comment]
It's in a try catch, so maybe the better options is a shorter timeout like 2-4s.
