### ISSUE TITLE
[Feature request] Passing speaker ID to server to enable use of multi-speaker models with MaryTTS

### ISSUE THREAD

**Issue by BVollmerhaus** [coqui-ai/TTS#3256]
**🚀 Feature Description**

Coqui's [built-in server](https://github.com/coqui-ai/TTS/blob/dev/TTS/server/server.py) offers [basic compatibility with the MaryTTS API](https://tts.readthedocs.io/en/dev/marytts.html) schema. However, this is currently limited to using single-speaker models, as the MaryTTS API does not specify a `speaker_idx` parameter (specific to Coqui) that could normally be used to select a voice. As such, the compatibility API returns a 500 error for all requests when started with a multi-speaker `--model_name`.

[The documentation](https://tts.readthedocs.io/en/dev/marytts.html#how-it-works-and-limitations) states "Since we only have one active model and always want to return a WAV-file, we currently ignore all other processing parameters except `INPUT_TEXT`. [...] We think that this is an acceptable compromise, since users are often only interested in one specific voice anyways". I'd agree with this; however, this is not just a limitation to using a single model – it also prevents one from using any of the multi-speaker models, even if just for one voice.

**Solution**

I'd assume most use cases would, in fact, be covered with just a single voice. If `server.py` would allow pre-selecting a particular speaker like `tts` does (i.e. via a `--speaker_idx` argument), users could also use voices from multi-speaker models with MaryTTS-only integrations (e.g. through Home Assistant).

**Alternative Solutions**

Since MaryTTS-compatible applications send a `VOICE` parameter at most, perhaps this could be used to select a speaker as well. It may even allow for selecting both a model and speaker (e.g. as `<model>#<speaker>`), although, as stated before, one model likely covers most use cases.

**Comment by eginhard** [comment]
This is now supported in [our fork](https://github.com/idiap/coqui-ai-TTS) (available via `pip install coqui-tts`). For more details: https://coqui-tts.readthedocs.io/en/latest/marytts.html#multi-speaker-models
