### ISSUE TITLE
[Bug] Doesn't work with python 3.12

### ISSUE THREAD

**Issue by frozencemetery** [coqui-ai/TTS#3257]
### Describe the bug

In the README, it states that "🐸TTS is tested on Ubuntu 18.04 with python >= 3.9, < 3.12.." but I don't see a tracker for 3.12 support, so opening this.

### To Reproduce

```
frozencemetery@llawan:~$ python3 --version
Python 3.12.0
frozencemetery@llawan:~$ cat /etc/fedora-release 
Fedora release 39 (Thirty Nine)
frozencemetery@llawan:~$ rpm -qv python3
python3-3.12.0-1.fc39.x86_64
frozencemetery@llawan:~$ virtualenv ttsenv
created virtual environment CPython3.12.0.final.0-64 in 120ms
  creator CPython3Posix(dest=/home/frozencemetery/ttsenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(extra_search_dir=/usr/share/python-wheels,download=False, pip=bundle, via=copy, app_data_dir=/home/frozencemetery/.local/share/virtualenv)
    added seed packages: pip==23.2.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
frozencemetery@llawan:~$ source ttsenv/bin/activate
(ttsenv) frozencemetery@llawan:~$ pip install TTS
ERROR: Ignored the following versions that require a different python version: 0.0.10.2 Requires-Python >=3.6.0, <3.9; 0.0.10.3 Requires-Python >=3.6.0, <3.9; 0.0.11 Requires-Python >=3.6.0, <3.9; 0.0.12 Requires-Python >=3.6.0, <3.9; 0.0.13.1 Requires-Python >=3.6.0, <3.9; 0.0.13.2 Requires-Python >=3.6.0, <3.9; 0.0.14.1 Requires-Python >=3.6.0, <3.9; 0.0.15 Requires-Python >=3.6.0, <3.9; 0.0.15.1 Requires-Python >=3.6.0, <3.9; 0.0.9 Requires-Python >=3.6.0, <3.9; 0.0.9.1 Requires-Python >=3.6.0, <3.9; 0.0.9.2 Requires-Python >=3.6.0, <3.9; 0.0.9a10 Requires-Python >=3.6.0, <3.9; 0.0.9a9 Requires-Python >=3.6.0, <3.9; 0.1.0 Requires-Python >=3.6.0, <3.10; 0.1.1 Requires-Python >=3.6.0, <3.10; 0.1.2 Requires-Python >=3.6.0, <3.10; 0.1.3 Requires-Python >=3.6.0, <3.10; 0.10.0 Requires-Python >=3.7.0, <3.11; 0.10.1 Requires-Python >=3.7.0, <3.11; 0.10.2 Requires-Python >=3.7.0, <3.11; 0.11.0 Requires-Python >=3.7.0, <3.11; 0.11.1 Requires-Python >=3.7.0, <3.11; 0.12.0 Requires-Python >=3.7.0, <3.11; 0.13.0 Requires-Python >=3.7.0, <3.11; 0.13.1 Requires-Python >=3.7.0, <3.11; 0.13.2 Requires-Python >=3.7.0, <3.11; 0.13.3 Requires-Python >=3.7.0, <3.11; 0.14.0 Requires-Python >=3.7.0, <3.11; 0.14.2 Requires-Python >=3.7.0, <3.11; 0.14.3 Requires-Python >=3.7.0, <3.11; 0.15.0 Requires-Python >=3.9.0, <3.12; 0.15.1 Requires-Python >=3.9.0, <3.12; 0.15.2 Requires-Python >=3.9.0, <3.12; 0.15.4 Requires-Python >=3.9.0, <3.12; 0.15.5 Requires-Python >=3.9.0, <3.12; 0.15.6 Requires-Python >=3.9.0, <3.12; 0.16.0 Requires-Python >=3.9.0, <3.12; 0.16.1 Requires-Python >=3.9.0, <3.12; 0.16.3 Requires-Python >=3.9.0, <3.12; 0.16.4 Requires-Python >=3.9.0, <3.12; 0.16.5 Requires-Python >=3.9.0, <3.12; 0.16.6 Requires-Python >=3.9.0, <3.12; 0.17.0 Requires-Python >=3.9.0, <3.12; 0.17.1 Requires-Python >=3.9.0, <3.12; 0.17.2 Requires-Python >=3.9.0, <3.12; 0.17.4 Requires-Python >=3.9.0, <3.12; 0.17.5 Requires-Python >=3.9.0, <3.12; 0.17.6 Requires-Python >=3.9.0, <3.12; 0.17.7 Requires-Python >=3.9.0, <3.12; 0.17.8 Requires-Python >=3.9.0, <3.12; 0.17.9 Requires-Python >=3.9.0, <3.12; 0.18.0 Requires-Python >=3.9.0, <3.12; 0.18.1 Requires-Python >=3.9.0, <3.12; 0.18.2 Requires-Python >=3.9.0, <3.12; 0.19.0 Requires-Python >=3.9.0, <3.12; 0.19.1 Requires-Python >=3.9.0, <3.12; 0.2.0 Requires-Python >=3.6.0, <3.10; 0.2.1 Requires-Python >=3.6.0, <3.10; 0.2.2 Requires-Python >=3.6.0, <3.10; 0.20.0 Requires-Python >=3.9.0, <3.12; 0.20.1 Requires-Python >=3.9.0, <3.12; 0.20.2 Requires-Python >=3.9.0, <3.12; 0.20.3 Requires-Python >=3.9.0, <3.12; 0.20.4 Requires-Python >=3.9.0, <3.12; 0.20.5 Requires-Python >=3.9.0, <3.12; 0.20.6 Requires-Python >=3.9.0, <3.12; 0.3.0 Requires-Python >=3.6.0, <3.10; 0.3.1 Requires-Python >=3.6.0, <3.10; 0.4.0 Requires-Python >=3.6.0, <3.10; 0.4.1 Requires-Python >=3.6.0, <3.10; 0.4.2 Requires-Python >=3.6.0, <3.10; 0.5.0 Requires-Python >=3.6.0, <3.10; 0.6.0 Requires-Python >=3.6.0, <3.10; 0.6.1 Requires-Python >=3.6.0, <3.10; 0.6.2 Requires-Python >=3.6.0, <3.10; 0.7.0 Requires-Python >=3.7.0, <3.11; 0.7.1 Requires-Python >=3.7.0, <3.11; 0.8.0 Requires-Python >=3.7.0, <3.11; 0.9.0 Requires-Python >=3.7.0, <3.11
ERROR: Could not find a version that satisfies the requirement TTS (from versions: none)
ERROR: No matching distribution found for TTS

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
```

### Expected behavior

Working TTS (on Fedora 39).

### Logs

```shell
(see above)
```

### Environment

```shell
- TTS Version: pip
- PyTorch Version: pop
- Python version: 3.12
- OS: Fedora 39
- How you installed PyTorch: pip
```

**Comment by theoparis** [comment]
bad bot

**Comment by theoparis** [comment]
L stale bot. 

Honestly the stale bot should be removed as it's causing this important issue to almost be closed for no reason. It also means I have to keep commenting for no reason....

**Comment by jp-x-g** [comment]
This would seem like a rather urgent issue. I am not sure what the status of this project is (Coqui shut down, see https://twitter.com/_josh_meyer_/status/1742522906041635166 ) and according to Discord it's not clear who is supposed to be in charge of maintaining the repository at this point. @theoparis In the meantime do you think it might be worth throwing together a PR to address the issue? I suspect it might be very simple; see https://github.com/coqui-ai/TTS/blob/dev/setup.py#L35

Also line 120, and one should be added after 127 probably to include 3.12 for the test build, then we see where that breaks

There's literally a line that throws an error during setup and exits if python version is 3.12, probably the first place to start would be commenting that out and seeing where (if anywhere) an error actually pops during execution.

**Comment by sammcj** [comment]
This still seems to be an issue

**Comment by theoparis** [comment]
I made a WIP PR #3660 but I noticed https://github.com/coqui-ai/trainer needs to be updated as well... Not sure if I should use this fork which should fix the issue: https://github.com/eginhard/coqui-Trainer/tree/py312

**Comment by eginhard** [comment]
> I made a WIP PR #3660 but I noticed https://github.com/coqui-ai/trainer needs to be updated as well... Not sure if I should use this fork which should fix the issue: https://github.com/eginhard/coqui-Trainer/tree/py312

Hey @theoparis, thanks for looking into this! If you'd like, you can make a PR to [our lab's fork](https://github.com/idiap/coqui-ai-TTS) from where we can release a new package as well. You can change the `trainer` requirement to `coqui-tts-trainer`, which I've already [released](https://pypi.org/project/coqui-tts-trainer/) with 3.12 support.

**Comment by Norman742** [comment]
Hi I added support to be able to use tts on Python 3.12 update from @theoparis to new trainer coqui-tts-trainer use this command pip install git+https://github.com/Norman742/ttspython312.git   , repository https://github.com/Norman742/ttspython312.git

**Comment by kaisch13** [comment]
> Hi I added support to be able to use tts on Python 3.12 update from @theoparis to new trainer coqui-tts-trainer use this command pip install git+https://github.com/Norman742/ttspython312.git , repository https://github.com/Norman742/ttspython312.git

New to git- just getting into things. I tried installing "pip install git+https://github.com/Norman742/ttspython312.git" with git bash on win10. got the following error: 
Failed to build TTS pandas
ERROR: Could not build wheels for TTS, pandas, which is required to install pyproject.toml-based projects

any idea why this is?

**Comment by Norman742** [comment]
> > Hi I added support to be able to use tts on Python 3.12 update from @theoparis to new trainer coqui-tts-trainer use this command pip install git+https://github.com/Norman742/ttspython312.git , repository https://github.com/Norman742/ttspython312.git
> 
> New to git- just getting into things. I tried installing "pip install git+https://github.com/Norman742/ttspython312.git" with git bash on win10. got the following error: Failed to build TTS pandas ERROR: Could not build wheels for TTS, pandas, which is required to install pyproject.toml-based projects
> 
> any idea why this is?

You could try this https://stackoverflow.com/questions/75003495/error-could-not-build-wheels-for-prophet-which-is-required-to-install-pyprojec. Maybe prophet issue or need to have Microsoft Visual C++ 14.0 or greater

**Comment by eginhard** [comment]
Python 3.12 is now supported in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by LucBerge** [comment]
Having the same issue

**Comment by eginhard** [comment]
@LucBerge This repository is unlikely to get updated. You can use [our fork](https://github.com/idiap/coqui-ai-TTS) (`pip install coqui-tts`) if you need Python 3.12 support.

**Comment by paboum** [comment]
> Python 3.12 is now supported in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

Still not fixed. The official documentation says "pip install TTS" everywhere, not making differentiation for `python3.12`.

**Comment by skewty** [comment]
This repo is more-or-less dead / abandoned..  Many have moved over to [idiap/coqui-ai-TTS fork](https://github.com/idiap/coqui-ai-TTS) successfully. The fork is likely where future development will continue to take place.

**Comment by eginhard** [comment]
@paboum You can find the new docs for the fork here: https://coqui-tts.readthedocs.io/en/latest/ There's nobody to update the original ones.

**Comment by paboum** [comment]
> This repo is more-or-less dead / abandoned.. Many have moved over to [idiap/coqui-ai-TTS fork](https://github.com/idiap/coqui-ai-TTS) successfully. The fork is likely where future development will continue to take place.

Is it too much to expect a friendly "This repository was archived by the owner on ... It is now read-only." message? Or in docu: "This documentation site is for the versions of ... maintained by ... Since version ..., ... is now maintained by ... under ..."

**Comment by skewty** [comment]
> Is it too much to expect a friendly "This repository was archived by the owner on ... It is now read-only." message? Or in docu: "This documentation site is for the versions of ... maintained by ... Since version ..., ... is now maintained by ... under ..."

It would seem all the people who are able don't care to or they have perhaps somehow lost that ability. The situation is like getting a dead person to sign over authority.. good luck
