### ISSUE TITLE
[Bug] Cuda 10.1 will not install for Windows 11 so test_cuda.py fails, can't run train.bat

### ISSUE THREAD

**Issue by brentjohnston** [coqui-ai/TTS#3259]
### Describe the bug

The windows user guide seems a bit outdated, cuda reports false on the test_cuda.py file. I checked the nvidia installer and it all says "not installed" with an error. Can't figure it out. It's the last step I'm on. Can I use a newer version of Cuda on Windows 11 and this will still work?

### To Reproduce

Try to install Cuda 10.1 with nvidia installer on windows 11.

### Expected behavior

Installer fails, need workaround.

### Logs

```shell
Windows, VENV
```

### Environment

```shell
None
```

### Additional context

None

**Comment by brentjohnston** [comment]
Could I avoid all of this if I just do install Ubuntu on WSL2 on Windows 11?

**Comment by erogol** [comment]
win is not a platform we officially support. Hope someone here can comment on this.
