### ISSUE TITLE
[Feature request] Minimum substring length

### ISSUE THREAD

**Issue by kanttouchthis** [coqui-ai/TTS#3261]
**🚀 Feature Description**

When generating voice from text, TTS automatically splits the text in to shorter subtexts based on punctuation. This makes sense, however, when the substring is short (like "Hey!"), the models don't perform very well and it just doesn't sound great.

**Solution**

Add an optional minimum length parameter to ensure short sentences aren't cut off.
from 
`["Hey!", "How are you?", "I'm doing great!"]`
to 
`["Hey! How are you?", "I'm doing great!"]`

You might be worried that having two sentences in the same string could cause problems with tts but from my testing it sounds a lot better than having too short of a string. And you could change the min length at any time if you do not like it.

**Comment by erogol** [comment]
We add an option to disable sentence splitting. So you cah apply any splitting logic you want before passing it to the model.
