### ISSUE TITLE
[Bug] server.py crashes on systems with IPv6 disabled

### ISSUE THREAD

**Issue by Phr33d0m** [coqui-ai/TTS#3269]
### Describe the bug

`server.py` is statically configured to use IPv6. On systems with IPv6 disabled - this causes a crash when starting the server (bare metal or Docker)

### To Reproduce

1. On a Linux host as an example, disable ipv6 (sysctl):

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

2. Try to start the server
3. ???

### Expected behavior

`server.py` should not rely on `::` by default

### Logs

```shell
> initialization of speaker-embedding layers.
 > initialization of language-embedding layers.
 * Serving Flask app 'server'
 * Debug mode: off
Traceback (most recent call last):
  File "/root/TTS/server/server.py", line 258, in <module>
    main()
  File "/root/TTS/server/server.py", line 254, in main
    app.run(debug=args.debug, host="::", port=args.port)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 612, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 1077, in run_simple
    srv = make_server(
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 917, in make_server
    return ThreadedWSGIServer(
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 737, in __init__
    super().__init__(
  File "/usr/lib/python3.10/socketserver.py", line 448, in __init__
    self.socket = socket.socket(self.address_family,
  File "/usr/lib/python3.10/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

### Environment

```shell
irrelevant
```

### Additional context

I was able to easily fix this on my local environment by just modifying https://github.com/coqui-ai/TTS/blob/29dede20d336c8250810575fcdcdbbcad8c40a44/TTS/server/server.py#L254 to look like:

```python
app.run(debug=args.debug, host="0.0.0.0", port=args.port)
```

**Comment by buzzy** [comment]
Thanks for this! I got the same error. ipv6 disabled on my box.

**Comment by erogol** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=56373

**Comment by buzzy** [comment]
> https://forums.raspberrypi.com/viewtopic.php?t=56373

Why is this issue closed? If your system does not support ipv6, listening on "::" will fail. Why is the script using that instead of 0.0.0.0 in the first place? Every system supports ipv4, but not all supports ipv6.
