### ISSUE TITLE
[Bug] ValueError: Model is not multi-lingual but `language` is provided.

### ISSUE THREAD

**Issue by JJun-Guo** [coqui-ai/TTS#3280]
### Describe the bug

I got the "ValueError: Model is not multi-lingual but `language` is provided." when i used XTTSv2 

### To Reproduce

import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

# Run TTS
# ❗ Since this model is multi-lingual voice cloning model, we must set the target speaker_wav and language
# Text to speech list of amplitude values as output
wav = tts.tts(text="Hello world!", speaker_wav="my/cloning/audio.wav", language="en")
# Text to speech to a file
tts.tts_to_file(text="Hello world!", speaker_wav="my/cloning/audio.wav", language="en", file_path="output.wav")

### Environment

```shell
Environment u provided
```

**Comment by jackyin68** [comment]
I just commented out parameter check line, and waiting for fix.

**Comment by ANK789** [comment]
em, the same question,waiting

**Comment by yhyu13** [comment]
![Code_awUrXJBd9I](https://github.com/coqui-ai/TTS/assets/19365678/0a06f033-a6d3-4091-8520-6ae0cab34d9a)

I encountered the same error msg when loading from local model checkpoint, 

turns out you need to input the model name for xtts to be recognized as multilingual.

But since you guys load from model name instead of loading from a given local model checkpoint, xtts2 should be fine with multilingual, this is strange

**Comment by Edresson** [comment]
Hi @JJun-Guo @jackyin68 @yhyu13 @ANK789,

It was fixed on https://github.com/coqui-ai/TTS/pull/3273. Please try to update your :frog:  TTS version to the latest one :).

**Comment by JJun-Guo** [comment]
> Hi @JJun-Guo @jackyin68 @yhyu13 @ANK789,
> 
> It was fixed on #3273. Please try to update your 🐸 TTS version to the latest one :).

But i got the other bug "  File "./TTS/TTS/tts/layers/xtts/tokenizer.py", line 653, in encode
    return self.tokenizer.encode(txt).ids
AttributeError: 'NoneType' object has no attribute 'encode'"
