### ISSUE TITLE
[Feature request] In non-English models stress could be assigned incorrectly

### ISSUE THREAD

**Issue by DmitryVN** [coqui-ai/TTS#3282]
Fix it plz https://github.com/coqui-ai/TTS/issues/3039
The problem persists and because of this, normal correct use is not possible. Also at the moment it kind of breaks off the phrase at the end of each sentence and it turns out a jerky reading.

**Comment by Tessory** [comment]
@DmitryVN I see you also met that issue. Stress syllable often wrong in Russian, but Russian have a lot of word with same writting, but different spelling (different stress syllable).
Also moment with dots "." . I see TTS split sentence on separate generating parts, and pronounce strange word something like "ponto" between these sentence/parts. I only found solution in changing all dots to periods ("." -> ","), then it pronounce phrases fine.

**Comment by carinae** [comment]
Same issue with dot in french.

**Comment by brambox** [comment]
Well adding some kind of way to force stress will probably be biggest and most important feature. My guess is it will need alot of work and maybe break stuff. 

Also problem with the gpt xtts is it sometimes decide on its own and put stress in diferent placess on multiple generations. So someways of hard force need to be exist for better accuracy.

**Comment by DmitryVN** [comment]
Without this function, the meaning is lost in many places, it just turns out to be an incorrect synthesis.

**Comment by DmitryVN** [comment]
Is it possible to implement some kind of solution in the future?

**Comment by Tessory** [comment]
> Is it possible to implement some kind of solution in the future?

I don't know how working TTS, and hope author will give answer.
But in xVASynth/Trainer stress realise via through individual vowel phonemes.
For example, phonemes for two words may look like:

phonemes - word
Z AA1 M OW0 K - зАмок (castle)
Z AA0 M OW1 K - замОк (lock)

For AI these stressed and not stressed vowels (AA0 and AA1, or OW0 and OW1) just look like absolutely different phonemes. 

Also I know Sylero have marks for stress vowels like: з+амок and зам+ок , but how it look like at phonemes level I don't know.

I think we also can add something here, somehow separate stressed vowels and retrain... or maybe fineturn will be enough?
I just want to tell, that for us - humans    stressed "А" and not stressed "А" - are same vowels. But for AI it's may look like absolutelly different vowels, like AA1 and AA0 phonemes. And maybe some of these tricks can be using there too.

**Comment by skalp2020** [comment]
I confirm that there is a problem, please add this function.

**Comment by AIG-Livny** [comment]
A slightly helpful way is to remove the competing vowel. For example: “вОзрАст” -> “вОзрст” (age)
