### ISSUE TITLE
[Bug]could not create a primitive descriptor for a matmul primitive

### ISSUE THREAD

**Issue by zhhxiang05** [coqui-ai/TTS#3284]
### Describe the bug

tts-server raised an error 

### To Reproduce

//bash code 
tts --text "hello" --out_path ./01.wav
or 
tts-server 

//output 
the output error is the same 

File "/home/anth/.local/pipx/venvs/tts/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: could not create a primitive descriptor for a matmul primitive

### Expected behavior

Is it a hardware problem 
or 
Is this package not successfully installed 

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1",
        "TTS": "0.20.6",
        "numpy": "1.26.2"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.11.6",
        "version": "#1 SMP Debian 6.1.38-1 (2023-07-14)"
    }
}
```

### Additional context

//my operating system information 
//macbook 
//parallels-desktop debian sid 

pipx install tts 
tts-server 
firefox http://localhost:5002 
//nothing more has done to this package 

I have read lots of articles 
It is supposed to be a CPU problem 
Is it possible for me to deal this in macbook m2 ?

**Comment by timgreen** [comment]
I'm facing the same issue on the aarch64 machine (others are fine). So I guess it might relate to the CPU architecture.

**Comment by zhhxiang05** [comment]
This issue is fixed. So I closed it. There are two problems. 

1. download model again to fix broken model 
2. give virtual machine more RAM. Limited RAM memory may cause error without a clear warning .

**Comment by stevenygd** [comment]
I encountered this issue.

**Comment by elyxlz** [comment]
bump, on asahi linux
