### ISSUE TITLE
StyleTTS2 support?

### ISSUE THREAD

**Issue by itsPreto** [coqui-ai/TTS#3290]
How feasible is it to add support for https://github.com/yl4579/StyleTTS2

**Comment by RootingInLoad** [comment]
I agree. Considering how crisp and good StyleTTS2 sounds like. Having the ability to easily clone a voice and having it sound more natural at the same time would be a killer feature.

**Comment by eginhard** [comment]
See #3272

**Comment by platform-kit** [comment]
Bumping this

**Comment by prassanna-ravishankar** [comment]
bump
