### ISSUE TITLE
Indicate whether TTS model supports voice cloning

### ISSUE THREAD

**Issue by eginhard** [coqui-ai/TTS#3293]
It would be useful to check in tts_with_vc() whether the underlying model supports voice cloning directly and direct users to tts_to_file(..., speaker_wav="...") in that case to avoid issues like in https://github.com/coqui-ai/TTS/issues/3067. Is there some way to check this easily?

> most of the models needs speaker_manager if they voice clone but I don't think it applies them all. We should probably attribute them in the model classes.

_Originally posted by @erogol in https://github.com/coqui-ai/TTS/issues/3275#issuecomment-1823596669_

**Comment by DrewThomasson** [comment]
Actually yeah it's if the model has multi-dataset in the name of the model when you make it print out all of the tts models , in python it's print(TTS().list_models())

**Comment by eginhard** [comment]
> I thought it was if the model has multi-dataset in the name of the model when you make it print out all of the tts models?

How many datasets a model was trained on is unrelated to whether it supports voice cloning, it's just a coincidence if that heuristic works for the currently available pre-trained models.
