### ISSUE TITLE
[Bug] Fine-Tuned xtts2 model not recognized as multi-lingual model

### ISSUE THREAD

**Issue by Okohedeki** [coqui-ai/TTS#3305]
### Describe the bug

After finetuning the xtts2 model I passed it into the TTS with the model_path and config_path arguments for inference. When trying to save the model I get

`ValueError: Model is not multi-lingual but `language` is provided.` 

However, when I remove the language arguments and try running it again I get the following error:

`AssertionError:  ❗ Language None is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn', 'hu', 'ko', 'ja']`

So I can neither pass the language or not pass the language argument when using the `tts_to_file ` function since both fail. 

### To Reproduce

```
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"
tts = TTS(model_path = path_to_finetuned_xtts2_model_in_xtts_v2/run/training,
config_path = path_to_finetuned_xtts2_config_in_xtts_v2/run/training).to(device)

text = """ 
Hello World
"""

#The below returns ValueError: Model is not multi-lingual but `language` is provided.
tts.tts_to_file(text=text, speaker_wav=r"E:\test\output.wav", language="en", file_path="test2.wav")

#The below returns AssertionError:  ❗ Language None is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn', 'hu', 'ko', 'ja']
tts.tts_to_file(text=text, speaker_wav=r"E:\test\output.wav", file_path="test2.wav")
```

### Expected behavior

The wav file gets saved on the system correctly WAV

### Logs

```shell
#Trackback when passing in the language parameter:
Traceback (most recent call last):
  File "E:\Test\Test.py", line 140, in <module>
    tts.tts_to_file(text=text, speaker_wav=r"E:\Test\output.wav", language="en", file_path="Test.wav")
  File "E:\Test\TTS\TTS\api.py", line 391, in tts_to_file
    self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "E:\Test\TTS\TTS\api.py", line 242, in _check_arguments
    raise ValueError("Model is not multi-lingual but `language` is provided.")
ValueError: Model is not multi-lingual but `language` is provided.

#Traceback when not passing in the language parameter 
Traceback (most recent call last):
  File "E:\Test\Test.py", line 141, in <module>
    tts.tts_to_file(text=text, speaker_wav=r"E:\Test\output.wav", file_path="Test.wav")
  File "E:\Test\TTS\TTS\api.py", line 403, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "E:\Test\TTS\TTS\api.py", line 341, in tts
    wav = self.synthesizer.tts(
  File "E:\Test\TTS\TTS\utils\synthesizer.py", line 374, in tts
    outputs = self.tts_model.synthesize(
  File "E:\Test\TTS\TTS\tts\models\xtts.py", line 392, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "E:\Test\TTS\TTS\tts\models\xtts.py", line 399, in inference_with_config
    "zh-cn" if language == "zh" else language in self.config.languages
AssertionError:  ❗ Language None is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn', 'hu', 'ko', 'ja']
```

### Environment

```shell
$ python collect_env_info.py
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1+cpu",
        "TTS": "0.20.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 165 Stepping 5, GenuineIntel",
        "python": "3.10.13",
        "version": "10.0.19045"
    }
}
```

**Comment by Okohedeki** [comment]
And looking closer I also noticed that this function here:

```

    @property
    def is_multi_lingual(self):
        # Not sure what sets this to None, but applied a fix to prevent crashing.
        if isinstance(self.model_name, str) and "xtts" in self.model_name:
            return True
        if hasattr(self.synthesizer.tts_model, "language_manager") and self.synthesizer.tts_model.language_manager:
            return self.synthesizer.tts_model.language_manager.num_languages > 1
        return False
```

looks like an attempt to correct this issue but simply checking if the model_name is like xtts but since its a finetuned model the name does not appear in list_models so I cannot use this attribute.

**Comment by elix1er** [comment]
same error using
!tts --text "Moon rocket launched. Deploying." \
--model_name "tts_models/multilingual/multi-dataset/xtts_v2" \
--out_path output.wav

**Comment by Edresson** [comment]
> And looking closer I also noticed that this function here:
> 
> ```
> 
>     @property
>     def is_multi_lingual(self):
>         # Not sure what sets this to None, but applied a fix to prevent crashing.
>         if isinstance(self.model_name, str) and "xtts" in self.model_name:
>             return True
>         if hasattr(self.synthesizer.tts_model, "language_manager") and self.synthesizer.tts_model.language_manager:
>             return self.synthesizer.tts_model.language_manager.num_languages > 1
>         return False
> ```
> 
> looks like an attempt to correct this issue but simply checking if the model_name is like xtts but since its a finetuned model the name does not appear in list_models so I cannot use this attribute.

Hi @Okohedeki, 

You are right it was the issue. It is already fixed. You should try to update your :frog:  TTS version.

**Comment by Edresson** [comment]
> same error using !tts --text "Moon rocket launched. Deploying." --model_name "tts_models/multilingual/multi-dataset/xtts_v2" --out_path output.wav

@elix1er You need to provide `--language_idx`. Check here the docs for XTTS inference: https://tts.readthedocs.io/en/dev/models/xtts.html#id1
