### ISSUE TITLE
[Bug] torch `weight_norm` issue

### ISSUE THREAD

**Issue by saiakarsh193** [coqui-ai/TTS#3308]
### Describe the bug

In some of the model files, we use the `weight_norm` function which is imported as follows
```python
from torch.nn.utils.parametrizations import weight_norm
```
which is giving me the error:
```
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (/data/saiakarsh/envs/coqui/lib/python3.10/site-packages/torch/nn/utils/parametrizations.py)
```

but by changing it to
```python
from torch.nn.utils import weight_norm
```
the issue is solved.

I checked the commit history and found out that `parametrizations` was added in this commit #3176 recently. 
So considering it was intentional, am I missing something here? Like any torch update that's necessary?

### To Reproduce

for example you can go to [hifigan_generator.py](https://github.com/coqui-ai/TTS/blob/dev/TTS/vocoder/models/hifigan_generator.py), and check:
```python
from torch.nn.utils.parametrizations import weight_norm
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A100 80GB PCIe",
            "NVIDIA A100 80GB PCIe",
            "NVIDIA A100 80GB PCIe",
            "NVIDIA A100 80GB PCIe"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.20.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.13",
        "version": "#97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023"
    }
}
```

**Comment by WeberJulian** [comment]
You need to update to pytorch 2.1+ as in the requirement file.

**Comment by illtellyoulater** [comment]
I'm getting the same issue with torch==2.2.0 and Python 3.10.13.
