### ISSUE TITLE
[Bug] newer models performs much worse 

### ISSUE THREAD

**Issue by ttio2tech** [coqui-ai/TTS#3309]
### Describe the bug

The updated version requires re-download of the checkpoints. However, they gives much worse voice cloning/synthesis than previous versions. 

The same issue also mentioned in the Huggingface community discussion: https://huggingface.co/coqui/XTTS-v2/discussions/16 

Is it possible to use the previous model checkpoints or use local downloaded model? 
The model loading of the package seems strange. I do not see any options to do so. 

### To Reproduce

import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

# Run TTS
# ❗ Since this model is multi-lingual voice cloning model, we must set the target speaker_wav and language
# Text to speech list of amplitude values as output
wav = tts.tts(text="Hello world!", speaker_wav="my/cloning/audio.wav", language="en")

### Environment

```shell
TTS 0.21.1
Python 3.10.11
Pytorch 2.1.0+cu121
Ubuntu 22.04
```

**Comment by ttio2tech** [comment]
update: I saw it's possible to load from local model:
TTS/api.py 
Example loading a model from a path:
            >>> tts = TTS(model_path="/path/to/checkpoint_100000.pth", config_path="/path/to/config.json", progress_bar=False, gpu=False)
            >>> tts.tts_to_file(text="Ich bin eine Testnachricht.", file_path="output.wav")

**Comment by thibault-roux** [comment]
I thought that my local model was corrupted and I deleted so now, I can't use it it anymore. Hope this problem will be solved soon.

**Comment by ttio2tech** [comment]
> I thought that my local model was corrupted and I deleted so now, I can't use it it anymore. Hope this problem will be solved soon.

you can try to git clone the hf model and checkout the old commit

**Comment by Clad3815** [comment]
The best way actually, create a folder named `model` at your script location and put these files inside:

https://huggingface.co/coqui/XTTS-v2/raw/v2.0.2/config.json
https://huggingface.co/coqui/XTTS-v2/resolve/v2.0.2/model.pth?download=true
https://huggingface.co/coqui/XTTS-v2/raw/v2.0.2/vocab.json

And in your code load the TTS like that:
```
model = TTS(model_path="model/", config_path="model/config.json").to(device)
``

**Comment by emmendoza2794** [comment]
I have the same problem, I applied @Clad3815  solution but I am getting the following error
`ValueError: Model is not multi-lingual but `language` is provided.`
I am using TTS with the Spanish language, Any solution? thank you so much

**Comment by Clad3815** [comment]
> I have the same problem, I applied @Clad3815 solution but I am getting the following error `ValueError: Model is not multi-lingual but `language` is provided.` I am using TTS with the Spanish language, Any solution? thank you so much

That's strange, I'm using it with French without any trouble

```
model = TTS(model_path="model/tts_models--multilingual--multi-dataset--xtts_v2", config_path="model/tts_models--multilingual--multi-dataset--xtts_v2/config.json").to(device)   
model.tts_to_file(text=text_prompt, speaker_wav=speaker_wav, language=language, file_path=unique_filename) 
```

**Comment by Qualzz** [comment]
Oh ! So that's explain why suddenly I have really bad result ( but really worse, giberrish, weird accents, inventing words etc ) 
Also for some reason it redownload the model every time I generate something 'model has changed so it needs to be downloaded again" something along those lines. 

I hope this will be fixed soon, it's unusable rn

**Comment by Okohedeki** [comment]
> > I have the same problem, I applied @Clad3815 solution but I am getting the following error `ValueError: Model is not multi-lingual but `language` is provided.` I am using TTS with the Spanish language, Any solution? thank you so much
> 
> That's strange, I'm using it with French without any trouble
> 
> ```
> model = TTS(model_path="model/tts_models--multilingual--multi-dataset--xtts_v2", config_path="model/tts_models--multilingual--multi-dataset--xtts_v2/config.json").to(device)   
> model.tts_to_file(text=text_prompt, speaker_wav=speaker_wav, language=language, file_path=unique_filename) 
> ```

I have been getting this same error . Not sure why sometimes with xtts_v2 this happens

**Comment by thibault-roux** [comment]
> > > I have the same problem, I applied @Clad3815 solution but I am getting the following error `ValueError: Model is not multi-lingual but `language` is provided.` I am using TTS with the Spanish language, Any solution? thank you so much
> > 
> > 
> > That's strange, I'm using it with French without any trouble
> > ```
> > model = TTS(model_path="model/tts_models--multilingual--multi-dataset--xtts_v2", config_path="model/tts_models--multilingual--multi-dataset--xtts_v2/config.json").to(device)   
> > model.tts_to_file(text=text_prompt, speaker_wav=speaker_wav, language=language, file_path=unique_filename) 
> > ```
> 
> I have been getting this same error . Not sure why sometimes with xtts_v2 this happens

Same for me. But I was using french!

**Comment by erogol** [comment]
Thanks for the flag. This is already been discussed in various places including in issues. Closing this one as being duplicate and not dev related.

from discord 

> all models are available on HF branches for each version. You can download the version you want and use it manually. See the docs for how. 
> 
> Adding a new language cause model to fallback a little. More training hopefully will help. Currently we are training the models on a kettle. 
> 
> Let me know if you can provide more compute. 
> 
> Unless you let us train the model on your voices we can’t promise to keep the voices the same between releases. Also DM me if you want to provide data too.

**Comment by Ph0rk0z** [comment]
"sound the same" is amusing.. all of my speakers have UK accents now. But in terms of clicks, breaths, and other tortoise-isms the model is better.

**Comment by barghavanii** [comment]
hi I have a question I try to train XTTS_v2 for Persian which is not included in supported languages I revised vocab.json and add Persian tokens  also revised xtts_config.py and tokenizer.py according to your advice but for training I can't use checkpoint because of torch.size mismatch as I extended the vocab.json file and have to start my training from the beginning is there any way to  use the check point ? @erogol

**Comment by Lenos500** [comment]
> The best way actually, create a folder named `model` at your script location and put these files inside:
> 
> https://huggingface.co/coqui/XTTS-v2/raw/v2.0.2/config.json https://huggingface.co/coqui/XTTS-v2/resolve/v2.0.2/model.pth?download=true https://huggingface.co/coqui/XTTS-v2/raw/v2.0.2/vocab.json
> 
> And in your code load the TTS like that:
> 
> ```
> model = TTS(model_path="model/", config_path="model/config.json").to(device)
> ``
> ```

I tried running 2.0.2 in colab using the file links you provided however I'm getting JSONDecoder errors sometimes, state_dict errors. I don't know if it's an issue with the tts version or if the config file you provided isn't compatible with the model.pth file. Can you please tell me how to load or correctly?

**Comment by erogol** [comment]
We updated the version checkpoint. It should be now on par with the earlier version 

You can access all the versions by version name now. You don't need to do things manually. See the docs for details.

**Comment by Lenos500** [comment]
> We updated the version checkpoint. It should be now on par with the earlier version
> 
> You can access all the versions by version name now. You don't need to do things manually. See the docs for details.

I didn't find any instructions on running older versions in the docs page. It would be appreciated if you could share a direct link to the instructions page related to loading older versions.

**Comment by Lenos500** [comment]
> We updated the version checkpoint. It should be now on par with the earlier version
> 
> You can access all the versions by version name now. You don't need to do things manually. See the docs for details.

Can you kindly link that page in documentations I can't find any instructions on running older versions for xtts like v2.0.2.
