### ISSUE TITLE
[Bug] Cracks and click at end of generation xtts2

### ISSUE THREAD

**Issue by brambox** [coqui-ai/TTS#3311]
### Describe the bug

I'm getting very often random cracks and clicks sounds on end of generation using xtts finetuned models.
It is specially more often when using cuda. With cpu its not so much but still happens.

### To Reproduce

It happens when generating audio.

### Environment

```shell
Python 3.9
Python 3.10.10
```

**Comment by erogol** [comment]
I don’t think it’s a bug. Check your data if it has such samples and remove those.

**Comment by brambox** [comment]
There are no such a samples for sure. Also it happens more with cuda than cpu like 10 to 1. And it happens far more with the new versions of TTS and model 2.0.3.;

**Comment by dwang3142** [comment]
@brambox did you find a solution? I'm also getting the clicks at the end of sentences
