### ISSUE TITLE
[Bug] OSError: torchaudio 

### ISSUE THREAD

**Issue by rkuo2000** [coqui-ai/TTS#3313]
### Describe the bug

import TTS cause OSError 

### To Reproduce

https://www.kaggle.com/code/rkuo2000/coqui-tts

import torch
from TTS.api import TTS

### Expected behavior

OSError: /opt/conda/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

### Environment

```shell
Kaggle.com
TTS-0.21.1
torch-2.1.1
torchaudio-2.0.1
```

**Comment by Okohedeki** [comment]
#https://github.com/intel/intel-extension-for-pytorch/issues/317

**Comment by Okohedeki** [comment]
https://github.com/intel/intel-extension-for-pytorch/issues/317

Not a bug with TTS. How did you install torch?

**Comment by rkuo2000** [comment]
Yes, after I rerun it with 
pip install -U torch torchaudio

import TTS works！
