### ISSUE TITLE
[Bug] Core dumped on windows WSL2

### ISSUE THREAD

**Issue by Zibri** [coqui-ai/TTS#3322]
### Describe the bug

$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from TTS.api import TTS
>>> tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to("cpu")
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
Segmentation fault (core dumped)

### To Reproduce

$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from TTS.api import TTS
>>> tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to("cpu")
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
Segmentation fault (core dumped)

### Expected behavior

a normal behaviour like on latest ubuntu.

### Environment

```shell
$ python3 collect_env_info.py
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1+cu121",
        "TTS": "0.21.1",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#3570-Microsoft Fri Sep 29 17:00:00 PST 2023"
    }
```

**Comment by erogol** [comment]
It is impossible to debug. Reopen when you have more context.
