### ISSUE TITLE
Support pandas 2

### ISSUE THREAD

**Issue by Harmon758** [coqui-ai/TTS#3330]
**🚀 Feature Description**

Currently, the pandas requirement is constrained to >=1.4,<2.0:
https://github.com/coqui-ai/TTS/blob/11ec9f7471620ebaa57db7ff5705254829ffe516/requirements.txt#L26

[Pandas 2.0.0 was released in April](https://github.com/pandas-dev/pandas/releases/tag/v2.0.0), so this will start to result in dependency conflicts with other libraries that require pandas >= 2.0.

**Solution**

Loosen pandas requirement to support pandas 2

**Comment by korodarn** [comment]
Experiencing this now with downstream application text-generation-webui., to add support for the open issue.  Is causing problems with interop with other extensions on linux.

**Comment by Harmon758** [comment]
This issue is still relevant.

**Comment by Solsboer** [comment]
up

**Comment by eginhard** [comment]
We've completely dropped the dependency on Pandas in our fork, which should allow you to avoid such conflicts: https://github.com/idiap/coqui-ai-TTS (PyPI package: [coqui-tts](https://pypi.org/project/coqui-tts))
