### ISSUE TITLE
[Bug] xtts_v2 finetune abnormal ending

### ISSUE THREAD

**Issue by evelynyhc** [coqui-ai/TTS#3331]
### Describe the bug

when I fine-tune xtts_v2, generate wavs from fine-tune model may cause abnormal ending，What causes it？

### To Reproduce

finetune xtts_v2 cause annormal ending

### Environment

```shell
python xtts_infer_streaming.py
```

**Comment by ukemamaster** [comment]
Could you please upload a few examples as well as the corresponding exact texts?
