### ISSUE TITLE
[Bug] Performance decay in XTTS-v2

### ISSUE THREAD

**Issue by Lenos500** [coqui-ai/TTS#3335]
### Describe the bug

I noticed a significant decrease in quality and audio similarity when using the hugging space demo for xtts v2.0.3 before that version the quality and similarly between input and output audios was miles better. 

### To Reproduce

Use hugging face space to compare xtts 2.0.3 with older versions. 

### Environment

```shell
Hugging face demo for xtts v2.0.3
```

**Comment by plumface-gcc** [comment]
See https://github.com/coqui-ai/TTS/issues/3309#issue-2010577124

**Comment by Edresson** [comment]
Now it is easier to load a previous XTTS versions here is an example: https://tts.readthedocs.io/en/dev/models/xtts.html#multiple-references
