### ISSUE TITLE
[Bug] Error in comments - mixup between VITS generator and discriminator

### ISSUE THREAD

**Issue by nicemanis** [coqui-ai/TTS#3338]
### Describe the bug

From the `get_criterion` method we see that 0 is discriminator loss and 1 is generator loss:
https://github.com/coqui-ai/TTS/blob/11ec9f7471620ebaa57db7ff5705254829ffe516/TTS/tts/models/vits.py#L1688-L1696

However, in the `get_optimizer` method, comments state that `optimizer0` is for generator and `optimizer1` is for discriminator, which creates confusion:
https://github.com/coqui-ai/TTS/blob/11ec9f7471620ebaa57db7ff5705254829ffe516/TTS/tts/models/vits.py#L1652-L1665

The same error can be seen in the comments for `train_step` method - `optimizer_idx: 0` calculates discriminator loss and `optimizer_idx: 1` calculates generator loss; however, the comments state otherwise.
https://github.com/coqui-ai/TTS/blob/11ec9f7471620ebaa57db7ff5705254829ffe516/TTS/tts/models/vits.py#L1230-L1331

### To Reproduce

Issue is in the comments

### Environment

```shell
TTS - v0.21.1
```

**Comment by erogol** [comment]
I don't think there is an error. There is only a misleading comment `# select generator parameters `

**Comment by erogol** [comment]
comment is also wrong. If you check the code 0 is for discriminator.
