### ISSUE TITLE
[Bug] Segmentation Fault (core dumped) happened when trying XTTS* models

### ISSUE THREAD

**Issue by treya-lin** [coqui-ai/TTS#3339]
### Describe the bug

I met this issue (Segmentation fault (core dumped)) when I was trying xtts_v1.1 and xtts_v2.  So I can't find a way to use these models. I environment should have met the requirements.

### To Reproduce

I am following the instruction here. https://huggingface.co/coqui/XTTS-v2
You can run the following codes after replacing the xtts modeldir and speaker wav to your local path.
```
import os
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

modeldir = '/home/user/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/'
# modeldir = '/home/user/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v1.1'
config = XttsConfig()
config.load_json(os.path.join(modeldir,'config.json'))
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_dir=modeldir, eval=True)
model.cuda()

outputs = model.synthesize(
    "It took me quite a long time to develop a voice and now that I have it I am not going to be silent.",
    config,
    speaker_wav="speaker.wav",
    gpt_cond_len=3,
    language="en",
)

```

### Expected behavior

It will not print out anything except 
> Segmentation fault (core dumped)

### Logs

```shell
Segmentation fault (core dumped)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti",
            "NVIDIA GeForce GTX 1080 Ti"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu118",
        "TTS": "0.21.1",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.10.13",
        "version": "#202209281119 SMP Wed Sep 28 12:39:10 UTC 2022"
    }
}
```

**Comment by maociao** [comment]
I am also getting segmentation faults using latest xtts_v2 with Oobabooga's text-generation-webui on AMD 7900xt graphics card, but only after some time of use.  It works fine initially and for a while, but eventually it will core dump during TTS conversion.

**Comment by Edresson** [comment]
Hi @treya-lin @maociao,

I could not replicate this error on my side. 

How much RAM do you guys have available on the computer that you are trying to use XTTS? I think it might be related.

**Comment by maociao** [comment]
Might be. I have an AMD 7900XT 20GB and I'm running a 13B parameter llama model which uses 15GB plus xtts.  I notice that firefox is also using ~1.5 gb :face_exhaling:  As a workaround I just removed the device parameter so that it would run on cpu memory instead. That's working just fine for me.

@@ -74,7 +74,7 @@ Synthesizer.split_into_sentences = new_split_into_sentences
 
 
 def load_model():
-    model = TTS(params["model_name"]).to(params["device"])
+    model = TTS(params["model_name"])
     return model

**Comment by zhangyue678** [comment]
I am also getting segmentation faults. That's working just fine for me.
```
export PATH=/usr/local/cuda-***/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-***/lib64:$LD_LIBRARY_PATH
```
