### ISSUE TITLE
[Bug] Can't inference after finetuning

### ISSUE THREAD

**Issue by CHIHHSIANGLI** [coqui-ai/TTS#3356]
### Describe the bug

I just finetuned xttsv2 and can't do the inference. 

### To Reproduce

import os
import torch
import torchaudio
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

# Add here the xtts_config path
CONFIG_PATH = "/home/kendricklee/TTS/recipes/ljspeech/xtts_v2/run/training/Trump1/config.json"
# Add here the vocab file that you have used to train the model
TOKENIZER_PATH = "/home/kendricklee/TTS/recipes/ljspeech/xtts_v2/run/training/XTTS_v2_original_model_files/vocab.json"
# Add here the checkpoint that you want to do inference with
XTTS_CHECKPOINT = "/home/kendricklee/TTS/recipes/ljspeech/xtts_v2/run/training/Trump1/checkpoint_24000.pth"
# Add here the speaker reference
SPEAKER_REFERENCE = "/home/kendricklee/TTS/Trump_newdataset/wavs/Trump_0001.wav"

# output wav path
OUTPUT_WAV_PATH = "xtts-ft.wav"

print("Loading model...")
config = XttsConfig()
config.load_json(CONFIG_PATH)
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_path=XTTS_CHECKPOINT, vocab_path=TOKENIZER_PATH, use_deepspeed=False)
model.cuda()

print("Computing speaker latents...")
gpt_cond_latent, speaker_embedding = model.get_conditioning_latents(audio_path=[SPEAKER_REFERENCE])

print("Inference...")
out = model.inference(
    "Look, I have always believed in the power of our democratic process. However, it's no secret that there were some irregularities in the last election. We need to ensure the integrity of our elections, so that every American can have confidence in the results. That I can tell you.",
    "en",
    gpt_cond_latent,
    speaker_embedding,
    temperature=0.7, # Add custom parameters here
)
torchaudio.save(OUTPUT_WAV_PATH, torch.tensor(out["wav"]).unsqueeze(0), 24000)

### Logs

```shell
(newxtts) kendricklee@DESKTOP-02HRD4O:~/TTS/recipes/ljspeech/xtts_v2$ python inference.py 
Loading model...
Computing speaker latents...
Inference...
[!] Warning: The text length exceeds the character limit of 250 for language 'en', this might cause truncated audio.
Traceback (most recent call last):
  File "/home/kendricklee/TTS/recipes/ljspeech/xtts_v2/inference.py", line 56, in <module>
    out = model.inference(
  File "/home/kendricklee/miniconda3/envs/newxtts/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kendricklee/TTS/TTS/tts/models/xtts.py", line 536, in inference
    text_tokens = torch.IntTensor(self.tokenizer.encode(text, lang=language)).unsqueeze(0).to(self.device)
  File "/home/kendricklee/TTS/TTS/tts/layers/xtts/tokenizer.py", line 591, in encode
    return self.tokenizer.encode(txt).ids
AttributeError: 'NoneType' object has no attribute 'encode'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 4090"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.20.4",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.13",
        "version": "#1 SMP Thu Oct 5 21:02:42 UTC 2023"
    }
}
```

**Comment by Edresson** [comment]
Hi @CHIHHSIANGLI,
 This error means that the tokenizer was not initialized. It can happens if the tokenizer file (in your case "/home/kendricklee/TTS/recipes/ljspeech/xtts_v2/run/training/XTTS_v2_original_model_files/vocab.json") does not exist.
The model.load_checkpoint load the tokenizer, but when the file does not exists the tokenizer loading is ignored: https://github.com/coqui-ai/TTS/blob/dev/TTS/tts/models/xtts.py#L755-L756

**Comment by Leemax0904** [comment]
Thanks for replying! I have solved this issue!

**Comment by DrewThomasson** [comment]
@CHIHHSIANGLI 

How did you manage to solve the issue on your end?

I'm running into the same issue here when trying to load a custom model

**Comment by xxx** [comment]
For anyone else running into this, you can get around it by using [manual inference](https://docs.coqui.ai/en/latest/models/xtts.html#manual-inference), and passing `vocab_path` to the `load_checkpoint` call. I just used the `vocab.json` from the original xtts model files that are downloaded for training.

```python
model.load_checkpoint(config, checkpoint_dir='path/to/finetuned/model', use_deepspeed=True, vocab_path='path/to/vocab.json')
```
