### ISSUE TITLE
[Bug] LLVM ERROR: Symbol not found: __svml_cosf8_ha

### ISSUE THREAD

**Issue by dragonm4n** [coqui-ai/TTS#3359]
### Describe the bug

Im getting this error when I want to enable coqui the 1st time and want to restart and apply changes to the webui. Using windows. What I already tried: find the svml file in system32 folder and delete it (file not there); update librosa; installed icc_rt. Im using intel processor.

### To Reproduce

check coqui_tts box on web UI and hit Apply and restart

### Environment

```shell
TTS v0.21.3
Python 3.10
```

**Comment by themucha** [comment]
I'm running into the same issue when I import XTTS config
`from TTS.tts.configs.xtts_config import XttsConfig
`

**Comment by themucha** [comment]
Here is a solution that might work to solve this issue. It worked on one of my PCs.

https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093

**Comment by nothingness6** [comment]
> Here is a solution that might work to solve this issue. It worked on one of my PCs.
> 
> [lmcinnes/umap#702 (comment)](https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093)

Hi, themucha.
I encountered the similar issue and the error message is "LLVM ERROR: Symbol not found: __svml_cosf8_ha" instead.
I looked into the solution. However, there is no such a file, svml_dispmd.dll. 
Could you tell me if you solve the issue?
Cheers!

**Comment by dragonm4n** [comment]
I found a solution for myself. As I have Intel processor, the error was because it was expecting to find the svml_dispmd.dll on my system32 folder. So I manually placed the missing DLL file on the folder, and it fixed the issue.

Solution that worked for me (I have Intel):
Download (https://www.dll-files.com/svml_dispmd.dll.html) and paste svml_dispmd.dll into system32 folder

**Comment by dexterhuh** [comment]
> I found a solution for myself. As I have Intel processor, the error was because it was expecting to find the svml_dispmd.dll on my system32 folder. So I manually placed the missing DLL file on the folder, and it fixed the issue.
> 
> Solution that worked for me (I have Intel): Download (https://www.dll-files.com/svml_dispmd.dll.html) and paste svml_dispmd.dll into system32 folder

It works for me. The problem was resolved after I copied the svml_dispmd.dll file into the system32 folder (C:\Windows\System32). Thank you very much.

I strongly suspect that the **issue arose because** numba was somehow using the Intel SVML located in the system32 folder instead of the version provided by the library. However, the system32 folder did not have the svml_dispmd.dll file. Therefore, **the solution** was to copy the svml_dispmd.dll file into the system32 folder.

**Comment by ryantavan** [comment]
> I found a solution for myself. As I have Intel processor, the error was because it was expecting to find the svml_dispmd.dll on my system32 folder. So I manually placed the missing DLL file on the folder, and it fixed the issue.
> 
> Solution that worked for me (I have Intel): Download (https://www.dll-files.com/svml_dispmd.dll.html) and paste svml_dispmd.dll into system32 folder

After many hours of struggling, your solution worked for me. Thank You!

**Comment by SolarWindRider** [comment]
numba version incompatible. Try older numba.

**Comment by leo19941227** [comment]
I find that numba<=0.58.0 works.

**Comment by MetAIvisuals** [comment]
> > I found a solution for myself. As I have Intel processor, the error was because it was expecting to find the svml_dispmd.dll on my system32 folder. So I manually placed the missing DLL file on the folder, and it fixed the issue.
> > Solution that worked for me (I have Intel): Download (https://www.dll-files.com/svml_dispmd.dll.html) and paste svml_dispmd.dll into system32 folder
> 
> After many hours of struggling, your solution worked for me. Thank You!

for me too!

**Comment by Pytheas54** [comment]
[dragonm4n](https://github.com/dragonm4n) solution also worked for me: running spyder after updating anaconda. Thks !
