### ISSUE TITLE
Is there any plan to release expressive TTS like SeamlessExpressive model from Meta? 

### ISSUE THREAD

**Issue by furqan4545** [coqui-ai/TTS#3363]
**🚀 Feature Description**
Hi is there any plan to release expressive TTS like SeamlessExpressive model from Meta? 
The model which can keep the underlying tonality, breaks, and expressions of the speaker in the generated output. I think it will be great if you can build any model like that or atleast provide some training code which we can use to train our own model.

**Comment by Zibri** [comment]
this would be great... like in tts_v2  it would be great to use 2 types of speaker_wavs  1 for tone and voiceprint, and another for cadence, speed and emotion. This will allow to ua a voice to "dub" another.
Something similar to this: https://www.respeecher.com/
