### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by yyi016100** [coqui-ai/TTS#3371]
### Describe the bug

when i installing TTS, it couldn't build wheels.
![image](https://github.com/coqui-ai/TTS/assets/145563206/5615a8a0-9f39-4bd5-be6b-ca9ce544f686)

### To Reproduce

pip install TTS

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1+cpu",
        "TTS": "0.21.3",
        "numpy": "1.26.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "python": "3.11.5",
        "version": "10.0.22621"
    }
}
```

**Comment by MichaelFitzurka** [comment]
I'm getting a similar issue (minus the problem with mojimoji) on Win 10, Python 3.11.
Output similar to https://github.com/scrapinghub/python-crfsuite/issues/155

**Comment by brambox** [comment]
you guys need to install visual studio build tools  and then go and check install the c++ development

**Comment by MichaelFitzurka** [comment]
Can't speak for OP & I will open new issue if desired/preferred.

I have Visual Studio Build Tool 2022 ver 17.8.3 with "Desktop development with C++" checked.
Windows 10 Home 22H2 OS Build: 19045.3693
Python 3.11.6
Pip 23.3.1

I did a 'pip cache purge' and then 'pip install TTS'
eventually getting:

      running build_ext
      building 'TTS.tts.utils.monotonic_align.core' extension
      creating build
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\TTS
      creating build\temp.win-amd64-cpython-311\Release\TTS\tts
      creating build\temp.win-amd64-cpython-311\Release\TTS\tts\utils
      creating build\temp.win-amd64-cpython-311\Release\TTS\tts\utils\monotonic_align
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mfitz\AppData\Local\Temp\pip-build-env-cdvziwyn\overlay\Lib\site-packages\numpy\core\include -IC:\Users\mfitz\AppData\Local\Programs\Python\Python311\include -IC:\Users\mfitz\AppData\Local\Programs\Python\Python311\Include /TcTTS/tts/utils/monotonic_align/core.c /Fobuild\temp.win-amd64-cpython-311\Release\TTS/tts/utils/monotonic_align/core.obj
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TTS

followed by:

  Building wheel for python-crfsuite (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for python-crfsuite (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pycrfsuite
      copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-cpython-311\pycrfsuite
      copying pycrfsuite\_logparser.py -> build\lib.win-amd64-cpython-311\pycrfsuite
      copying pycrfsuite\__init__.py -> build\lib.win-amd64-cpython-311\pycrfsuite
      running build_ext
      building 'pycrfsuite._pycrfsuite' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\crfsuite
      creating build\temp.win-amd64-cpython-311\Release\crfsuite\lib
      creating build\temp.win-amd64-cpython-311\Release\crfsuite\lib\cqdb
      creating build\temp.win-amd64-cpython-311\Release\crfsuite\lib\cqdb\src
      creating build\temp.win-amd64-cpython-311\Release\crfsuite\lib\crf
      creating build\temp.win-amd64-cpython-311\Release\crfsuite\lib\crf\src
      creating build\temp.win-amd64-cpython-311\Release\crfsuite\swig
      creating build\temp.win-amd64-cpython-311\Release\liblbfgs
      creating build\temp.win-amd64-cpython-311\Release\liblbfgs\lib
      creating build\temp.win-amd64-cpython-311\Release\pycrfsuite
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -IC:\Users\mfitz\AppData\Local\Programs\Python\Python311\include -IC:\Users\mfitz\AppData\Local\Programs\Python\Python311\Include /Tccrfsuite/lib/cqdb/src/cqdb.c /Fobuild\temp.win-amd64-cpython-311\Release\crfsuite/lib/cqdb/src/cqdb.obj
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-crfsuite
Successfully built gruut encodec umap-learn bnnumerizer bnunicodenormalizer jieba docopt gruut-ipa gruut-lang-de gruut-lang-en gruut-lang-es gruut-lang-fr
Failed to build TTS python-crfsuite
ERROR: Could not build wheels for TTS, python-crfsuite, which is required to install pyproject.toml-based projects

**Comment by aedocw** [comment]
I'm getting the same thing. I do have all the microsoft tools installed. Both "pip install TTS" and the following result in the same error.
from clone of TTS repo:
pip install -r requirements.txt (successful)
python setup.py install
fails with:
```
creating temp_build\TTS\vocoder\utils
copying TTS\vocoder\utils\__init__.py -> temp_build\TTS\vocoder\utils
copying TTS\vocoder\utils\distribution.py -> temp_build\TTS\vocoder\utils
copying TTS\vocoder\utils\generic_utils.py -> temp_build\TTS\vocoder\utils
running build_ext
building 'TTS.tts.utils.monotonic_align.core' extension
error: [WinError 2] The system cannot find the file specified
```

**Comment by aedocw** [comment]
I am no longer able to recreate the problem - installation went fine today.

**Comment by loveoverflowdev** [comment]
![image](https://github.com/coqui-ai/TTS/assets/113291130/a83d1dae-a806-4c9c-8499-7ae14f00d93d)
I have encountered a similar error, and don't have any solution yet

**Comment by loveoverflowdev** [comment]
Oh, I did install C++ Desktop Development and it works now
