### ISSUE TITLE
Voice conversion is not getting done properly with voice conversion model

### ISSUE THREAD

**Issue by AnushkaTyagi26** [coqui-ai/TTS#3376]
### Describe the bug

Hello team,

I have tried to convert the Sunny Deol voice into Amitabh Bachan voice but it doesn't work at all. I have attached the zip file of the audio of both actors and also their results. Please check it and please explain me what I am doing wrong.

Thank You.

[sunnyamitabh.zip](https://github.com/coqui-ai/TTS/files/13595480/sunnyamitabh.zip)

### To Reproduce

tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=False).to("cuda")
tts.voice_conversion_to_file(source_wav="my/source.wav", target_wav="my/target.wav", file_path="output.wav")

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1650"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu118",
        "TTS": "0.21.3",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel",
        "python": "3.10.11",
        "version": "10.0.19045"
    }
}
```

**Comment by erogol** [comment]
It is the public model released by the FreeVC author. You should probably train a better one. Closing it as it is not dev related.

**Comment by ewwink** [comment]
hi @erogol how to train voice conversion model?
