### ISSUE TITLE
[Bug] xtts ft demo does not work with Japanese KeyError 'ja"

### ISSUE THREAD

**Issue by Egoblin** [coqui-ai/TTS#3384]
### Describe the bug

xtts ft demo does not work with Japanese KeyError: 'ja'

### To Reproduce

run xtts_demo.py 
upload wav
dataset language: ja

### Expected behavior

TTS-0.21.3\TTS\demos\xtts_ft_demo\xtts_demo.py", line 215, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, target_language=language, out_path=out_path, gradio_progress=progress)
TTS-0.21.3\TTS\demos\xtts_ft_demo\utils\formatter.py", line 107, in format_audio_list
    sentence = multilingual_cleaners(sentence, target_language)
TTS-0.21.3\TTS\tts\layers\xtts\tokenizer.py", line 558, in multilingual_cleaners
    text = expand_numbers_multilingual(text, lang)
TTS-0.21.3\TTS\tts\layers\xtts\tokenizer.py", line 538, in expand_numbers_multilingual
    text = re.sub(_ordinal_re[lang], lambda m: _expand_ordinal(m, lang), text)
KeyError: 'ja'

### Logs

```shell
TTS-0.21.3\TTS\demos\xtts_ft_demo\xtts_demo.py", line 215, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, target_language=language, out_path=out_path, gradio_progress=progress)
TTS-0.21.3\TTS\demos\xtts_ft_demo\utils\formatter.py", line 107, in format_audio_list
    sentence = multilingual_cleaners(sentence, target_language)
TTS-0.21.3\TTS\tts\layers\xtts\tokenizer.py", line 558, in multilingual_cleaners
    text = expand_numbers_multilingual(text, lang)
TTS-0.21.3\TTS\tts\layers\xtts\tokenizer.py", line 538, in expand_numbers_multilingual
    text = re.sub(_ordinal_re[lang], lambda m: _expand_ordinal(m, lang), text)
KeyError: 'ja'
```

### Environment

```shell
TTS Version 0.21.3
pytorch Version 2.1.1+cu118
python Version 3.9.13
OS windows
CUDA/cuDNN version 11.8
Pytorch install method pip
```

### Additional context

other languages work fine, google collab has the same issue, ja reqs already installed as well

**Comment by gjin10969** [comment]
how to resolve this?
