### ISSUE TITLE
[Bug] xtts ft demo don't have option for Hindi language

### ISSUE THREAD

**Issue by akshay1728** [coqui-ai/TTS#3387]
### Describe the bug

I am using xtts ft demo for fine tuning with collab. There is no option of hindi language in gradio dropdown select option 

### To Reproduce

run xtts_demo.py
open gradio link
go the the select language option

### Expected behavior

'hi' i.e. hindi language option needs to be there in the drop down

### Environment

```shell
TTS Version 0.21.3
```

**Comment by akshay1728** [comment]
Also hindi is missing from tokenizer.py present in /layer/xtts folder

**Comment by Priyanshu-Dholu** [comment]
Yes, the option is available on demo at huggingface but not in this project

**Comment by CLICKEARNER** [comment]
needed

**Comment by eginhard** [comment]
Thanks for spotting this. I've enabled Hindi in the fine-tuning demo and tokenizer in our fork: https://github.com/idiap/coqui-ai-TTS
