### ISSUE TITLE
[Bug] XTTS v2 cond_idxs missing a 'for' loop for training

### ISSUE THREAD

**Issue by asr-pub** [coqui-ai/TTS#3388]
### Describe the bug

https://github.com/coqui-ai/TTS/blob/c99e885cc8a35639ca124a6cad9573bb23f06764/TTS/tts/layers/xtts/gpt.py#L543-L546
I think is there lack a for loop?
```python
        if cond_idxs is not None:
            for idx in range(cond_idxs.size(0)):
                cond_start = cond_idxs[idx, 0]
                cond_end = cond_idxs[idx, 1]
                mel_targets[idx, cond_start:cond_end] = -1
```

### To Reproduce

empty

### Environment

```shell
dev branch
```

**Comment by aaron-lii** [comment]
I debugged this part of codes just now.
```python
print(cond_latents.shape, cond_mels.shape, mel_emb.shape, mel_targets.shape, cond_idxs)

# ignore the loss for the segment used for conditioning
# coin flip for the segment to be ignored
if cond_idxs is not None:
    cond_start = cond_idxs[idx, 0]
    cond_end = cond_idxs[idx, 1]
    mel_targets[idx, cond_start:cond_end] = -1
```
I guess the author is trying to ignore a part of loss of the last data in every batch. So we don't need a ‘for’ here.
But there might be a bug here. I find that cond_idxs may not match the index of segment used for conditioning. I might fix it later.

**Comment by asr-pub** [comment]
@erogol Could u confirm it? a feature or a bug ?
