### ISSUE TITLE
[Bug] long text generation doesnt work

### ISSUE THREAD

**Issue by unifirer** [coqui-ai/TTS#3395]
### Describe the bug

try to generate anything beyond 250 words and it says 

max token of 400

seems like the text splitter is not working

### To Reproduce

try to generate anything beyond 250 words and it says 

### Expected behavior

text splitter splits it into segments of less than 250 and then recombine them

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1+cu118",
        "TTS": "0.21.1",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
        "python": "3.10.11",
        "version": "10.0.19045"
    }
}
```

**Comment by aitechlab1** [comment]
Any update on this? Came across a similar issue ..
Also, does XTTS_v2 support long audio generations in general? How is the performance?

**Comment by unifirer** [comment]
Its fixed

 it takes 1 hour on a high end GPU to produce 2 hours. So very slow

Please inform me of interesting jobs and opportunities

________________________________
