### ISSUE TITLE
[Feature request] Changing the reading speed for xTTS v2

### ISSUE THREAD

**Issue by bropines** [coqui-ai/TTS#3396]
**🚀 Feature Description**
In certain situations, TTS is required to adhere to certain strict voice acting boundaries. This is acceptable when dubbing an SRT file.
Of course, you can simply add a neuron or write an algorithm that cuts and speeds up itself, but this is stupid. I would like the XTTS python api to have a speed setting, or better yet, we pass the timing (start - end) and everything else as an argument

**Solution**
You could just do a calculation of the acceleration factor based on file length. So the file is dubbed, we run it through acceleration one more time. If the file is already almost the desired length (+- 1 second), then do not touch it. 

**Alternative Solutions**

**Additional context**

**Comment by FlorianEagox** [comment]
This is something I've been toying with in my repo. right now, I'm just time-stretching audio files, but I'd like to get something more sophisticated soon.

**Comment by platform-kit** [comment]
Seconding this. I have mentioned to @erogol and co elsewhere, and they seem to imply that the `speed` setting of the TTS api will work with XTTS, but my experience has been contrary.

**Comment by FlorianEagox** [comment]
So ideally, we would be able to set not just speed, but speaking rate as in words per minute, but I don't know if that's possible

**Comment by bropines** [comment]
> So ideally, we would be able to set not just speed, but speaking rate as in words per minute, but I don't know if that's possible

I assumed that you could just make a track and then apply a deceleration and acceleration coefficient, but this is a terrible crutch. You could simply add speed as a parameter in training or generation, and train the data already on slow and fast phrases

**Comment by lixikun** [comment]
There is speed parameter in the model.inference interface, the following is the explaination.

` speed:  The speed rate of the generated audio. Defaults to 1.0. (can produce artifacts if far from 1.0)`

but when I test this parameter, Its results are not very accurate. sometime it is longer or shorter than the length that I want. 
Can somebody have a new solution?

**Comment by ajayarora1235** [comment]
Also super interested in this... feels like most generations are way too slow speaking wise and sound nothing like a natural conversation. Any immediate solutions I can try?

**Comment by jp-x-g** [comment]
The most obvious thing is to just take the WAV output and tempo-shift it using some other utility (this can even be done without loss fo samples if you're trying to speed it up rather than slow it down).

**Comment by platform-kit** [comment]
@jp-x-g do you have an example of that?

**Comment by jp-x-g** [comment]
If I recall correctly “sox”, “ffmpeg”, and “soundstretch” can all do this from the command line, audacity is the GUI application I'm most familiar with, all are open-sores (there's also "rubberband" for all you proprietaryheads out there who like paying $20 for software for no reason, although if you have the money to spare I could use twenty bucks and tell you to use audacity)

**Comment by kaveenkumar** [comment]
I have a similar requirement with tempo variation.
Currently I use this script to achieve the same:

`"""borrowed from - https://stackoverflow.com/a/43438143/12584995"""

import wave
from pydub import AudioSegment

def speed_change_pydub(wav, speed=1.0):
    wav = AudioSegment.from_wav(wav)
    # Manually override the frame_rate. This tells the computer how many samples to play per second
    sound_with_altered_frame_rate = wav._spawn(wav.raw_data, overrides={
        "frame_rate": int(wav.frame_rate * speed)
    })

    return sound_with_altered_frame_rate.set_frame_rate(wav.frame_rate)

def speed_change_wave(wav, speed=1.0):
    spf = wave.Wave_read(wav)
    fr = spf.getframerate()  # frame rate
    signal = spf.readframes(-1)

    wf = wave.Wave_write(wav)
    wf.setframerate(fr * speed)
    wf.writeframes(signal)
    wf.close()

audio_file = AudioSegment.from_file("sample.wav")
slow_sound = speed_change_pydub(audio_file, 0.75)
fast_sound = speed_change_pydub(audio_file, 2.0)
`

**Comment by kaveenkumar** [comment]
I have a similar requirement with tempo variation.
Currently I use this script to achieve the same:

"""borrowed from - https://stackoverflow.com/a/43438143/12584995"""

```
import wave
from pydub import AudioSegment

def speed_change_pydub(wav, speed=1.0):
    wav = AudioSegment.from_wav(wav)
    # Manually override the frame_rate. This tells the computer how many samples to play per second
    sound_with_altered_frame_rate = wav._spawn(wav.raw_data, overrides={
        "frame_rate": int(wav.frame_rate * speed)
    })

    return sound_with_altered_frame_rate.set_frame_rate(wav.frame_rate)

def speed_change_wave(wav, speed=1.0):
    spf = wave.Wave_read(wav)
    fr = spf.getframerate()  # frame rate
    signal = spf.readframes(-1)

    wf = wave.Wave_write(wav)
    wf.setframerate(fr * speed)
    wf.writeframes(signal)
    wf.close()

audio_file = AudioSegment.from_file("sample.wav")
slow_sound = speed_change_pydub(audio_file, 0.75)
fast_sound = speed_change_pydub(audio_file, 2.0)
```

**Comment by AI-Guru** [comment]
This would be a really neat feature!

**Comment by bropines** [comment]
Reopen?

**Comment by gameveloster** [comment]
Has this feature been implemented? If not, what is the best workaround right now?

**Comment by manmay-nakhashi** [comment]
```
def deterministic_state(seed=None):
    """
    Sets the random seeds that tortoise uses to the current time() and returns that seed so results can be
    reproduced.
    """
    seed = int(time()) if seed is None else seed
    torch.manual_seed(seed)
    random.seed(seed)
    # Can't currently set this because of CUBLAS. TODO: potentially enable it if necessary.
    # torch.use_deterministic_algorithms(True)

    return seed
```
generate first time with random seed get this in a return statement from inference 
fix the seed with this while doing second inference with speed param i.e. speed=0.8 speed=1.2 etc
to fix the seed call 
```
deterministic_state(seed=first_gen_seed)
```

**Comment by manmay-nakhashi** [comment]
why speed is not working currently is becasue of random seed 
every time generation is random so for example
if you generate a first time your wav len is 5 sec. second time your wav len can be 5.5 , but you passed speed=1.1 and it'll shrink it down to agin 5 sec. 
if you fix seed then generation will be always 5 sec. hance deterministic  and you can apply speed to change the waveform.

**Comment by h-oneohone** [comment]
> why speed is not working currently is becasue of random seed every time generation is random so for example if you generate a first time your wav len is 5 sec. second time your wav len can be 5.5 , but you passed speed=1.1 and it'll shrink it down to agin 5 sec. if you fix seed then generation will be always 5 sec. hance deterministic and you can apply speed to change the waveform.

@manmay-nakhashi  Could you share how to fix it :<

**Comment by pocakka** [comment]
In xtts.py you can set any speed you want.

/tts_env/lib/python3.x/site-packages/TTS/tts/models/xtts.py

Also, with tts = initialize_tts_model you can override xtts.py speed setting.
