### ISSUE TITLE
Every Time I run the model, the model is downloaded again

### ISSUE THREAD

**Issue by PatricioFernandezF** [coqui-ai/TTS#3397]
### Describe the bug

Hello, every time i try to run a simple code of tts like this one:

```python
from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
                file_path="output.wav",
                speaker_wav="/path/to/target/speaker.wav",
                language="en")
```
Python force me to download AGAIN the model again. Im doing something wrong?
![image](https://github.com/coqui-ai/TTS/assets/26440958/c5153006-2b3d-4d15-82d2-5e66655a23c0)
Regards

### To Reproduce

Run the following code:
```python
from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
                file_path="output.wav",
                speaker_wav="/path/to/target/speaker.wav",
                language="en")
```

### Environment

```shell
Latest Version
```

**Comment by ihmily** [comment]
## reason
The problem may be that the model and related files you downloaded are incomplete. The error message prompted appears on the following lines of the TTS source code
```
                md5sum_file = os.path.join(output_path, "hash.md5")
                if os.path.isfile(md5sum_file):
                    with open(md5sum_file, mode="r") as f:
                        if not f.read() == md5sum:
                            print(f" > {model_name} has been updated, clearing model cache...")
                            self.create_dir_and_download_model(model_name, model_item, output_path)
                        else:
                            print(f" > {model_name} is already downloaded.")
                else:
                    print(f" > {model_name} has been updated, clearing model cache...")      
 ```
It checks whether the hash.md5 file exists in the root directory of the project and compares its md5 hash value with the md5 hash value of the latest model file. If the file does not exist or the hash value is not equal, it will download the latest model again

code line：https://github.com/coqui-ai/TTS/blob/c99e885cc8a35639ca124a6cad9573bb23f06764/TTS/utils/manage.py#L412C17-L421C88

## resolution
First, please update TTS to the latest version
```
pip install --upgrade pip
pip install --upgrade TTS
```

Then, ensure that the downloaded files are the latest version, correct and complete. Perhaps you can download the latest version from huggingface
```
git lfs install
git clone https://huggingface.co/coqui/XTTS-v2
```
Sure it includes the hash.md5 file.

**Comment by PatricioFernandezF** [comment]
Working, next to do the resolution i moved XTTS-v2 content to my model folder and works.

**Comment by leomeow33** [comment]
> ## reason
> The problem may be that the model and related files you downloaded are incomplete. The error message prompted appears on the following lines of the TTS source code
> 
> ```
>                 md5sum_file = os.path.join(output_path, "hash.md5")
>                 if os.path.isfile(md5sum_file):
>                     with open(md5sum_file, mode="r") as f:
>                         if not f.read() == md5sum:
>                             print(f" > {model_name} has been updated, clearing model cache...")
>                             self.create_dir_and_download_model(model_name, model_item, output_path)
>                         else:
>                             print(f" > {model_name} is already downloaded.")
>                 else:
>                     print(f" > {model_name} has been updated, clearing model cache...")      
> ```
> 
> It checks whether the hash.md5 file exists in the model directory and compares its md5 hash value with the md5 hash value of the latest model file. If the file does not exist or the hash value is not equal, it will download the latest model again
> 
> code line：https://github.com/coqui-ai/TTS/blob/c99e885cc8a35639ca124a6cad9573bb23f06764/TTS/utils/manage.py#L412C17-L421C88
> 
> ## resolution
> First, please update TTS to the latest version
> 
> ```
> pip install --upgrade pip
> pip install --upgrade TTS
> ```
> 
> Then, ensure that the downloaded files are the latest version, correct and complete. Perhaps you can download the latest version from huggingface
> 
> ```
> git lfs install
> git clone https://huggingface.co/coqui/XTTS-v2
> ```
> 
> Sure it includes the hash.md5 file.



> ## reason
> The problem may be that the model and related files you downloaded are incomplete. The error message prompted appears on the following lines of the TTS source code
> 
> ```
>                 md5sum_file = os.path.join(output_path, "hash.md5")
>                 if os.path.isfile(md5sum_file):
>                     with open(md5sum_file, mode="r") as f:
>                         if not f.read() == md5sum:
>                             print(f" > {model_name} has been updated, clearing model cache...")
>                             self.create_dir_and_download_model(model_name, model_item, output_path)
>                         else:
>                             print(f" > {model_name} is already downloaded.")
>                 else:
>                     print(f" > {model_name} has been updated, clearing model cache...")      
> ```
> 
> It checks whether the hash.md5 file exists in the model directory and compares its md5 hash value with the md5 hash value of the latest model file. If the file does not exist or the hash value is not equal, it will download the latest model again
> 
> code line：https://github.com/coqui-ai/TTS/blob/c99e885cc8a35639ca124a6cad9573bb23f06764/TTS/utils/manage.py#L412C17-L421C88
> 
> ## resolution
> First, please update TTS to the latest version
> 
> ```
> pip install --upgrade pip
> pip install --upgrade TTS
> ```
> 
> Then, ensure that the downloaded files are the latest version, correct and complete. Perhaps you can download the latest version from huggingface
> 
> ```
> git lfs install
> git clone https://huggingface.co/coqui/XTTS-v2
> ```
> 
> Sure it includes the hash.md5 file.

same question, thanks for the solution!

**Comment by testter21** [comment]
@ihmily, quick question.

What to start first, to perform the updates:
pip install --upgrade pip
pip install --upgrade TTS
for specifically pinokio and/or xtts within it?

I assume, that the terminal has to run something first in order to execute these commands? (sorry, I'm fresh to mac)

I'm not programmer/developer, I just use pinokio and apps within it. I have the same problem of redownloading model per each pinokio start.
