### ISSUE TITLE
correctly reading

### ISSUE THREAD

**Issue by scronge** [coqui-ai/TTS#3398]
I tried it with the following expression

$\int_{b}^{a} f(x) dx = F(b)-F(a)$ 

Result was terrible and included some sort of jungle scream, it should have read :

"the riemann integral from a to b of f of x with respect to x is equal to the difference between the antiderivative evaluated at the upper limit and the antiderivative at the lower limit"

**Comment by lexkoro** [comment]
That's not supported, you would have to preprocess it yourself.
