### ISSUE TITLE
[Bug] Unable to use TTS api for models like Bark, Tortoise

### ISSUE THREAD

**Issue by rj-7** [coqui-ai/TTS#3411]
### Describe the bug

Http connection error when trying to download bark or tortoise models via the TTS API
Error message:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='app.coqui.ai', port=443): Max retries exceeded with url: /tts_model/autoregressive.pth (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x781363678850>: Failed to resolve 'app.coqui.ai' ([Errno -2] Name or service not known)"))
 

### To Reproduce

Run the examples as it is from the docs - https://tts.readthedocs.io/en/latest/models/tortoise.html

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla T4"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu118",
        "TTS": "0.21.3",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Wed Aug 30 11:19:59 UTC 2023"
    }
}
```

**Comment by rli-taveres** [comment]
[They took it down](https://news.ycombinator.com/item?id=38437743)
