### ISSUE TITLE
Emotion parameter does not work at all

### ISSUE THREAD

**Issue by dilerbatu** [coqui-ai/TTS#3425]
### Describe the bug

Hi, I am trying to add emotion to my voice but emotion argument does not work. 

Speed parameter also does not work.

### To Reproduce

` self.tts.tts_to_file(text="I am a robot so I dont have any feelings but If you need to help about something you can always ask me ", 
                                     language ="en", 
                                     speaker_wav = "dataset/Could-you-type-ur.wav" , 
                                     emotion="angry", 
                                     speed= 1,  
                                     file_path="generated_dataset/generated{}.wav".format(generated_data_count))`

### Environment

```shell
Python 3.9.18
TTS 0.22.0
```

**Comment by Edresson** [comment]
Hi @dilerbatu, 

Emotion argument only works for 🐸 Studio model. Also, it is deprecated now because the :frog: Studio does not exist anymore.

**Comment by Wladastic** [comment]
The emotion parameter was just forgotten to pass to the tts() function.
tts_to_wav() does accept the emotion param and doesnt enter it into tts() at all.
When using tts only and then making a wav yourself, emotion works again, I think.
