### ISSUE TITLE
[Bug] unable to use TTS().list_models()

### ISSUE THREAD

**Issue by T0L0ve** [coqui-ai/TTS#3429]
### Describe the bug

when I use tts0.22.0
`print(TTS().list_models()[0])`
I get `TypeError: 'ModelManager' object is not subscriptable`
but in tts0.21.3 this is ok

### To Reproduce

print(TTS().list_models()[0])
` print(TTS().list_models()[0])
TypeError: 'ModelManager' object is not subscriptable`

### Environment

```shell
-TTs 0.22.0
-torch 2.1.1
```

**Comment by fuomag9** [comment]
Same issue on 0.22.0, only fix was downgrading. Why was this closed?

**Comment by hadariru** [comment]
To monkeypatch the issue change the part from the TTS library. TTS/api.py
```

    def list_models(self):
        return ModelManager(models_file=TTS.get_models_file_path(), progress_bar=False, verbose=False).list_models()

```

I do hope this will be added in the later version for TTS

**Comment by ChebliAlamiAhmed** [comment]
> Same issue on 0.22.0, only fix was downgrading. Why was this closed?

downgrading for which version

**Comment by eginhard** [comment]
This has been fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by ChebliAlamiAhmed** [comment]
> This has been fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

thank you, it works
