### ISSUE TITLE
[Feature request] CLI or importable script for generating dataset & fine-tuning XTTS

### ISSUE THREAD

**Issue by platform-kit** [coqui-ai/TTS#3433]
**🚀 Feature Description**

Right now (and correct me if I'm wrong) it seems that the [collab](https://colab.research.google.com/drive/1GiI4_X724M8q2W-zZ-jXo7cWTV7RfaH-?usp=sharing#scrollTo=zd2xo_7a8wyj) is the only way to fine-tune XTTS from zero (i.e. no dataset) 

I would love to see the code from this collab extracted / separated from Gradio and Collab so that it can be used via CLI or imported into a custom script.

Ideally this would involve one function/CLI command that takes 1 or more audio files as input and generates the dataset (with some kind of optional config, so we can specify format, etc?) from that, then another to train based on that dataset.

**Comment by Yaodada12** [comment]
> **🚀 Feature Description**
> 
> Right now (and correct me if I'm wrong) it seems that the [collab](https://colab.research.google.com/drive/1GiI4_X724M8q2W-zZ-jXo7cWTV7RfaH-?usp=sharing#scrollTo=zd2xo_7a8wyj) is the only way to fine-tune XTTS from zero (i.e. no dataset)
> 
> I would love to see the code from this collab extracted / separated from Gradio and Collab so that it can be used via CLI or imported into a custom script.
> 
> Ideally this would involve one function/CLI command that takes 1 or more audio files as input and generates the dataset (with some kind of optional config, so we can specify format, etc?) from that, then another to train based on that dataset.

I can't download the finetune dataset，do you have it？Can you share it？Thanks

**Comment by platform-kit** [comment]
@Yaodada12  

Check out these repos
https://github.com/daswer123/xtts-finetune-webui
https://github.com/Haurrus/xtts-trainer-no-ui-auto

**Comment by Yaodada12** [comment]
> @Yaodada12
> 
> Check out these repos https://github.com/daswer123/xtts-finetune-webui https://github.com/Haurrus/xtts-trainer-no-ui-auto

Thank you so much！
