### ISSUE TITLE
SSML input not working for xtts_v2

### ISSUE THREAD

**Issue by trivikramak** [coqui-ai/TTS#3436]
### Describe the bug

<break time="2.0s" /> tag isn't working. I've read that ssml isn't supported yet. Is there any other way to achieve required pauses?

### To Reproduce

Add <break time="2.0s" /> tag in text

### Expected behavior

Pause in the audio at the location of the tag.

### Environment

```shell
- xtts_v2
```

**Comment by lexkoro** [comment]
There is no ssml support

**Comment by trivikramak** [comment]
Is there any other way to achieve required pauses?
