### ISSUE TITLE
[Feature request] Please Make an spacial android release for persian deafs

### ISSUE THREAD

**Issue by mablue** [coqui-ai/TTS#3447]
**🚀 Feature Description**
Persian Deafs need your help to can speak with others.
we have not voice functionality in persian in apps like google translate and need your help to make an spacial model to persian language as android offline app.

**Solution**
I hope we have at the end an android app that we can load prebuild models for example for persian and than use it to generate persian voice from persian text
also we need an spacial model for persian language 

**Alternative Solutions**

**Additional context**
persian deaf need your help them cant speak and be social please help them.thanks

**Comment by csukuangfj** [comment]
The android app is available now for Persian. Please see
https://github.com/coqui-ai/TTS/discussions/2306#discussioncomment-8123201
