### ISSUE TITLE
Can the code and model be used commercially?

### ISSUE THREAD

**Issue by dizhenx** [coqui-ai/TTS#3448]
You can purchase a commcerial XTTS license from Coqui: licensing@coqui.ai. Otherwise, this demo is for non-commercial purposes only.

I saw the above information on the demo page. Can the code and model be used commercially?

**Comment by EvarDion** [comment]
As I understand it each model has its own license so it depends which model you want to use.

for example when you run the VITS model you get the Apache 2.0 license.

```
root@4ddedd4ba97e:~# python3 TTS/server/server.py --model_name tts_models/en/vctk/vits
 > Downloading model to /root/.local/share/tts/tts_models--en--vctk--vits
 > Model's license - apache 2.0
```

If you run the XTTS model it will ask you to confirm that you purchased a valid license.

The code itself should be covered by the [MPL-2.0 license](https://github.com/coqui-ai/TTS?tab=MPL-2.0-1-ov-file#) on the GitHub page.

If this information is not correct then someone else can correct me and update the doco.
