### ISSUE TITLE
A better plan for Chinese polyphonic characters

### ISSUE THREAD

**Issue by alin995** [coqui-ai/TTS#3455]
# G2PW

there are many polyphonic characters in Chinese, and 'pypinyin' does not handle them well.

for example: '盛了一碗米饭' in pinyin should be

```
cheng2 le5 yi1 wan3 mi3 fan4
```

but pypinyin.pinyin() outputs

```
sheng4 le5 yi1 wan3 mi3 fan4
```

'cheng2' is incorrectly translated as 'sheng4'.

package g2pW performs well in handling this convenience.

this is my code

> TTS/tts/layers/xtts/tokenizer.py

```
from g2pw import G2PWConverter

conv = G2PWConverter(style='pinyin', enable_non_tradional_chinese=True)

def chinese_transliterate(text):
    return "".join(conv(text)[0])
```

**Comment by Yaodada12** [comment]
可以的，大佬

**Comment by stormcenter** [comment]
关注一下，这个feature的进展

**Comment by OswaldoBornemann** [comment]
But that would cause a multiprocessing problem.
