### ISSUE TITLE
我想让生成的语音带有情感和正常人说话的节奏，有什么改进方案吗

### ISSUE THREAD

**Issue by pyh007** [coqui-ai/TTS#3465]
我想让生成的语音带有情感和正常人说话的节奏，有什么改进方案吗

**Comment by molakds** [comment]
maybe ENGLISH

**Comment by pyh007** [comment]
中文没有办法了吗

**Comment by Yaodada12** [comment]
> 中文没有办法了吗

他的意思应该是让你说英文？

**Comment by wang7521** [comment]
我想问下 实际操作下来 可以克隆自己的声音来读文章是行得通吗

**Comment by Yaodada12** [comment]
> 我想问下 实际操作下来 可以克隆自己的声音来读文章是行得通吗

可以的，自己玩一下没什么问题。
