### ISSUE TITLE
[Bug] Loosing your progress

### ISSUE THREAD

**Issue by kalaspuffar** [coqui-ai/TTS#3486]
### Describe the bug

If you are not careful when you resume a workload you might loose it all if you ever want to pause your training.

Lets say that you run this command everything is fine and dandy and your progress is saved.
```
python3 TTS/bin/train_tts.py --continue_path output
```

But if you happen to change the command to 
```
python3 TTS/bin/train_tts.py --continue_path output/
```

Which your system is so helpful to do you will loose everything. This is due to the glob function not finding any models in your root folder.

```
def remove_experiment_folder(experiment_path):
    """Check folder if there is a checkpoint, otherwise remove the folder"""
    fs = fsspec.get_mapper(experiment_path).fs
    checkpoint_files = fs.glob(experiment_path + "/*.pth")
    if not checkpoint_files:
        if fs.exists(experiment_path):
            fs.rm(experiment_path, recursive=True)
            print(" ! Run is removed from {}".format(experiment_path))
    else:
        print(" ! Run is kept in {}".format(experiment_path))
```

So this is not the best
```
fs.glob("output//*.pth")
```

Best regards 
Daniel

### To Reproduce

Run a training operation ending your continue_path with a slash

### Expected behavior

I get to keep my progress.

### Logs

```shell
> Saving model before exiting...

 > CHECKPOINT : output/checkpoint_306837.pth
 ! Run is kept in output
```

``` 
> Saving model before exiting...

 > CHECKPOINT : output/checkpoint_306907.pth
 ! Run is removed from output/
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080 Ti"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2+cu121",
        "TTS": "0.22.0",
        "numpy": "1.26.2"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.11.6",
        "version": "#14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023"
    }
}
```

**Comment by AAS-Crypt** [comment]
It's because code doesn't check if you have slash at end of your path but rather add another slash and searches for checkpoint it 'path/to/model//checkpoint' rather than 'path/to/model/checkpoint'.
Solution is to remove the last slash at path or modify the checking file.

**Comment by ATtendev** [comment]
same issue. any update?

**Comment by ATtendev** [comment]
python3 TTS/bin/train_tts.py --continue_path output/
just remove the slash of output
rewrite : python3 TTS/bin/train_tts.py --continue_path output

**Comment by eginhard** [comment]
@kalaspuffar I can't reproduce this and `fs.glob("output//*.pth")` and `fs.glob("output/*.pth")` return the same result for me.

**Comment by ipdan4ik** [comment]
I faced this bug today and lost folder with my progress.

How to reproduce it:
1. Created this file structure:
```
test
|ab.pth
run.py
```

2. In run.py:
```
import fsspec

fs = fsspec.get_mapper('test/').fs
print(fs.glob('test/*.pth'))
```
it returns `['<ROOT_PATH>/test/ab.pth']`

3. But if I change it to this:
```
import fsspec

fs = fsspec.get_mapper('test/').fs
print(fs.glob('test//*.pth'))
```
it returns `[]`

**Comment by eginhard** [comment]
@ipdan4ik Thank you for providing this minimal example! I was able to reproduce it.

I've released a fix in [our Coqui trainer fork](https://github.com/idiap/coqui-ai-Trainer) version 0.1.3. If you're already using [our TTS fork](https://github.com/idiap/coqui-ai-TTS) (PyPI package `coqui-tts`) you can simply update the Trainer with: `pip install -U coqui-tts-trainer`

If you're using the original TTS package, I'd recommend to switch to the fork (`pip install coqui-tts`) to also benefit from other bug fixes.
