### ISSUE TITLE
[Bug] package installation methods not working

### ISSUE THREAD

**Issue by cagrikumas** [coqui-ai/TTS#3496]
### Describe the bug

pip install and other package installing methods not working on ubuntu 20.04 lts

I think I have tried every way. I would appreciate it if you could help me see what I can't see about where I made a mistake.

### To Reproduce

pip install tts
,
,
,
,

  Using cached pandas-0.25.1.tar.gz (12.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-0.25.0.tar.gz (12.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Expected behavior

_No response_

### Logs

_No response_

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A100-SXM4-40GB"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2",
        "TTS": "0.22.0",
        "numpy": "1.26.3"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.11.0",
        "version": "#74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023"
    }
}
```


### Additional context

I think I have tried every way. I would appreciate it if you could help me see what I can't see about where I made a mistake.

**Comment by AAS-Crypt** [comment]
Have you tried to install from source?

**Comment by cagrikumas** [comment]
> Have you tried to install from source?

Thanks for your answer

When you say source, do you mean requirements.txt in the repo, make install or here https://pypi.org/project/TTS/#files

Which source exactly?


@AAS-Crypt

**Comment by AAS-Crypt** [comment]
Source as in GitHub repository.
You can install it using following commands
git clone https://github.com/coqui-ai/TTS
pip install -e .[all,dev,notebooks]

пн, 8 янв. 2024 г., 21:50 Çağrı Kumaş ***@***.***>:

**Comment by cagrikumas** [comment]
@AAS-Crypt 

Yes, I tried many different methods but it didn't work.

my python version meets the requirements but claims to be a lower version

`pip install -e .[all,dev,notebooks]
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
Obtaining file:///home/ubuntu/cagri/TTS
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-m_8upe28/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-m_8upe28/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-m_8upe28/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-m_8upe28/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-m_8upe28/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
      RuntimeError: TTS requires python >= 3.9 and < 3.12 but your Python version is 3.8.10 (default, Nov 14 2022, 12:59:47)
      [GCC 9.4.0]
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by Permafacture** [comment]
"my python version meets the requirements but claims to be a lower version"

You are in fact using python 3.8. If you run `pip --version` you'll see that. You might have a higher version of python also installed somewhere, but that's not what;s being used.

Use a virtual environment to solve this. like

```
python3.9 -m venv .env-tts
source .env-tts/bin/activate
python --version  # should say 3.9
pip install whatever
```
