### ISSUE TITLE
[Bug]  Windows Installation Guide not working at step # 11

### ISSUE THREAD

**Issue by Nikanoru** [coqui-ai/TTS#3498]
### Describe the bug

Following this guide: 
https://stackoverflow.com/questions/66726331/how-can-i-run-mozilla-tts-coqui-tts-training-with-cuda-on-a-windows-system

I get an error output at step 11 which requires me to do the following:

11. Run the following command (this differs from the command you get from [the PyTorch website](https://pytorch.org/get-started/locally/) because of [a known issue](https://github.com/pytorch/pytorch/issues/54172)): 

.\Scripts\pip install torch==1.8.0+cu101 torchvision==0.9.0+cu101 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

The following error will occur:

![image](https://github.com/coqui-ai/TTS/assets/83954293/9cd47c4e-d596-4230-84bd-d88765435747)

PS D:\AI\TTS> pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu101 (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu113, 1.11.0+cu115, 1.12.0, 1.12.0+cpu, 1.12.0+cu113, 1.12.0+cu116, 1.12.1, 1.12.1+cpu, 1.12.1+cu113, 1.12.1+cu116, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118, 2.1.0, 2.1.0+cpu, 2.1.0+cu118, 2.1.0+cu121, 2.1.1, 2.1.1+cpu, 2.1.1+cu118, 2.1.1+cu121, 2.1.2, 2.1.2+cpu, 2.1.2+cu118, 2.1.2+cu121)
ERROR: No matching distribution found for torch==1.8.1+cu101

What should I do?

### To Reproduce

run .\Scripts\pip install torch==1.8.0+cu101 torchvision==0.9.0+cu101 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

### Environment

```shell
using what is recommended in https://stackoverflow.com/questions/66726331/how-can-i-run-mozilla-tts-coqui-tts-training-with-cuda-on-a-windows-system
```

**Comment by Wuzzooy** [comment]
The guide is outdated, TTS works fine on windows with cuda 11.8 or 12.1
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
https://pytorch.org/get-started/locally/

This repo make the installation easy.

https://github.com/daswer123/xtts-webui
