### ISSUE TITLE
got error when using fairseq

### ISSUE THREAD

**Issue by uyplayer** [coqui-ai/TTS#3501]
### Describe the bug

```


from TTS.api import TTS


tts = TTS(model_name="tts_models/eng/fairseq/vits", progress_bar=False, gpu=True)
tts.tts_to_file("This is a test.", file_path="output.wav")

```

### To Reproduce

got following error 

```
D:\Software\anaconda3\envs\freqtrade310\python.exe C:\Users\uyplayer\Downloads\uig-script_arabic\model.py 
D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py:70: UserWarning: `gpu` will be deprecated. Please use `tts.to(device)` instead.
  warnings.warn("`gpu` will be deprecated. Please use `tts.to(device)` instead.")
Traceback (most recent call last):
  File "C:\Users\uyplayer\Downloads\uig-script_arabic\model.py", line 5, in <module>
    tts = TTS(model_name="tts_models/eng/fairseq/vits", progress_bar=False, gpu=True)
  File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py", line 74, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py", line 171, in load_tts_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(
  File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py", line 129, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\utils\manage.py", line 385, in download_model
    model_item, model_full_name, model, md5sum = self._set_model_item(model_name)
  File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\utils\manage.py", line 304, in _set_model_item
    model_full_name = f"{model_type}--{lang}--{dataset}--{model}"
UnboundLocalError: local variable 'dataset' referenced before assignment

Process finished with exit code 1
```

### Environment

```shell
Sys: Windows11
Python : 3.10
TTS : 0.22.0
Torch : 2.1.2
```

### Additional context
i saw other issues and said  this was fixed , but i still got this error

**Comment by akgupta1337** [comment]
i think the variables are not defined in manager.py
let me see if i can fix this, I am new to it tho.

**Comment by Dhruv16S** [comment]
Hi @uyplayer. I encountered a similar issue recently, and I guess you are referring to the fix as mentioned [here] (https://github.com/coqui-ai/TTS/pull/3502). If you have used the command `pip install TTS`, prior to using this model, this change has not been reflected yet for some reason.
Instead, you can modify the manage.py file at the location where you installed the TTS package. Simple add the line `model_type, lang, dataset, model = model_name.split("/")` as mentioned in the following [snippet](https://github.com/coqui-ai/TTS/pull/3502/files). For instance, in my local environment, I performed the updates at env/lib/site-packages/TTS/utils/manage.py, and it solved the problem for me.

**Comment by Dhruv16S** [comment]
> ### Describe the bug
> ```
> 
> 
> from TTS.api import TTS
> 
> 
> tts = TTS(model_name="tts_models/eng/fairseq/vits", progress_bar=False, gpu=True)
> tts.tts_to_file("This is a test.", file_path="output.wav")
> ```
> 
> ### To Reproduce
> got following error
> 
> ```
> D:\Software\anaconda3\envs\freqtrade310\python.exe C:\Users\uyplayer\Downloads\uig-script_arabic\model.py 
> D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py:70: UserWarning: `gpu` will be deprecated. Please use `tts.to(device)` instead.
>   warnings.warn("`gpu` will be deprecated. Please use `tts.to(device)` instead.")
> Traceback (most recent call last):
>   File "C:\Users\uyplayer\Downloads\uig-script_arabic\model.py", line 5, in <module>
>     tts = TTS(model_name="tts_models/eng/fairseq/vits", progress_bar=False, gpu=True)
>   File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py", line 74, in __init__
>     self.load_tts_model_by_name(model_name, gpu)
>   File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py", line 171, in load_tts_model_by_name
>     model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(
>   File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\api.py", line 129, in download_model_by_name
>     model_path, config_path, model_item = self.manager.download_model(model_name)
>   File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\utils\manage.py", line 385, in download_model
>     model_item, model_full_name, model, md5sum = self._set_model_item(model_name)
>   File "D:\Software\anaconda3\envs\freqtrade310\lib\site-packages\TTS\utils\manage.py", line 304, in _set_model_item
>     model_full_name = f"{model_type}--{lang}--{dataset}--{model}"
> UnboundLocalError: local variable 'dataset' referenced before assignment
> 
> Process finished with exit code 1
> ```
> 
> ### Expected behavior
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Environment
> ```shell
> Sys: Windows11
> Python : 3.10
> TTS : 0.22.0
> Torch : 2.1.2
> ```
> 
> ### Additional context
> i saw other issues and said this was fixed , but i still got this error

Hi @uyplayer. I encountered a similar issue recently, and I guess you are referring to the fix as mentioned [here](https://github.com/coqui-ai/TTS/pull/3502). If you have used the command `pip install TTS`, prior to using this model, this change has not been reflected yet for some reason.
Instead, you can modify the manage.py file at the location where you installed the TTS package. Simply add the line `model_type, lang, dataset, model = model_name.split("/")` as mentioned in the following [snippet](https://github.com/coqui-ai/TTS/pull/3502/files). For instance, in my local environment, I performed the updates at env/lib/site-packages/TTS/utils/manage.py, and it solved the problem for me.

**Comment by rainloha** [comment]
Please make those change to this file TTS/utils/manage.py

ligne 263

        #model_type = "tts_models"
        #lang = model_name.split("/")[1]
        model_type, lang, dataset, model = model_name.split("/")
regards

**Comment by eginhard** [comment]
This is fixed in our fork: https://github.com/idiap/coqui-ai-TTS
