### ISSUE TITLE
[Bug] impossible to resume train_gpt_xtts training

### ISSUE THREAD

**Issue by KukumavMozolo** [coqui-ai/TTS#3510]
### Describe the bug

When resuming training with train_gpt_xtts.py the GPTArgs in the saved config,json is deserialized incorretly as its parent XttsArgs, therefore not containing all required files.

### To Reproduce

Try resuming from checkpoint via setting continue_path

### Expected behavior

It trains

### Logs

```shell
No time
```

### Environment

```shell
--
```

**Comment by KukumavMozolo** [comment]
Can be fixed by modifying GPTTrainerConfig to overwrite model_args and audio like below
```
@dataclass
class GPTTrainerConfig(XttsConfig):
    lr: float = 5e-06
    training_seed: int = 1
    optimizer_wd_only_on_weights: bool = False
    weighted_loss_attrs: dict = field(default_factory=lambda: {})
    weighted_loss_multipliers: dict = field(default_factory=lambda: {})
    test_sentences: List[dict] = field(default_factory=lambda: [])
    model_args: GPTArgs = field(default_factory=GPTArgs)
    audio: XttsAudioConfig = field(default_factory=XttsAudioConfig)
```

**Comment by shivaio** [comment]
yes it works
