### ISSUE TITLE
Value Error : target loss not found[Bug] 

### ISSUE THREAD

**Issue by Hafiz-ATHAR** [coqui-ai/TTS#3519]
### Describe the bug

Hi!
I am trying to train a MultibandMelGAN model. I am using thorsten_de_v03 dataset. When epoch is finished, i get a warning 
"UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`."
Then evaluation happens and
After that :
" ValueError:  [!] Target loss not found in the keep_avg_target. You might be exiting the training loop before it is computed or set the target_loss in the model config incorrectly. "

I used thorsten's multiband mel gan recipe code. This issue also occurs with univnet.

### To Reproduce

I ran :
recipes/thorsten_DE/multiband_melgan/train_multiband_melgan.py

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090 Ti"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2+cu121",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023"
    }
}
```

### Additional context

I used dockerfile from dev branch but changed cuda image to cuda:12.2.2-base-ubuntu22.04.

**Comment by Amith5970** [comment]
did you resolved this error?

**Comment by Naminwang** [comment]
The default target_loss is loss_0, loss_0 is discriminator loss, but default steps_to_start_discriminator is 200000 in UnivnetConfig and MultibandMelganConfig, so target loss not found error appear.
And set target_loss='loss_1' in the UnivnetConfig or MultibandMelganConfig can avoid this error.

**Comment by Amith5970** [comment]
Are you able to run multiband melgan successfully ,because iam facing issues while saving the checkpoint

**Comment by mightmay** [comment]
HI, are you able to fix the issue?
I am facing same issue,
