### ISSUE TITLE
[Feature request] Add Libtashkeel for Arabic Diacritization

### ISSUE THREAD

**Issue by mush42** [coqui-ai/TTS#3532]
**🚀 Feature Description**

The Arabic text diacritization method currently used by XTTS provides very low-quality output, reducing the naturalness of generated speech.

**Solution**

Add [libtashkeel](https://github.com/mush42/libtashkeel) for Arabic text diacritization  to **XTTS**, which can benefit grately from libtashkeel's high-quality diacritization. 

**Alternative Solutions**

Diacritizing the text manually before input to the model, which is very inefficient, and many Arabic speakers are not familiar with it.

**Additional context**

Libtashkeel is a totally free and open-source tool that have both Python and C/C++ bindings, it is written in Rust, and it provides a **Single** function for diacritizing Arabic text.

**Comment by cod3r0k** [comment]
Do you have any updates? can you guide me about this note in Xtts for Arabic? @mush42
