### ISSUE TITLE
Numpy 1.22.0 and 1.24.3 Problem with TTS 0.22.0 and Librosa 0.10.0 and 0.10.1

### ISSUE THREAD

**Issue by OrbitPeppermint** [coqui-ai/TTS#3538]
Hello everyone, 
I'm working as a scientistic assistance on Linux and we had a compatibility problem with TTS 0.22.0, Librosa 0.10.0 and Numpy 1.22.0 after an TTS Update from 0.11.0 to 0.22.0. 
With these updates we got the following traceback:
```
Traceback (most recent call last):
  File "/project/translate_lecture.py", line 195, in <module>
    main(
  File "/project/translate_lecture.py", line 96, in main
    speaker.speak(use_gpu=use_cuda)
  File "/project/src/speaker.py", line 49, in speak
    self._add_text(segment=segment, use_gpu=use_gpu)
  File "/project/src/speaker.py", line 110, in _add_text
    file_handler.adjust_audio_length(
  File "/project/utils/file_handler.py", line 122, in adjust_audio_length
    short_y = librosa.effects.time_stretch(y=y, rate=factor)
  File "/opt/conda/lib/python3.10/site-packages/librosa/effects.py", line 245, in time_stretch
    stft_stretch = core.phase_vocoder(
  File "/opt/conda/lib/python3.10/site-packages/librosa/core/spectrum.py", line 1457, in phase_vocoder
    d_stretch[..., t] = util.phasor(phase_acc, mag=mag)
  File "/opt/conda/lib/python3.10/site-packages/librosa/util/utils.py", line 2602, in phasor
    z = _phasor_angles(angles)
  File "/opt/conda/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py", line 190, in __call__
    return super().__call__(*args, **kws)
numpy.core._exceptions._UFuncNoLoopError: ufunc '_phasor_angles' did not contain a loop with signature matching types <class 'numpy.dtype[float32]'> -> None
```

After this I was looking inside of the requirements of TTS 0.22.0 to search for the numpy compatibility:
```
# core deps
numpy==1.22.0;python_version<="3.10"
numpy>=1.24.3;python_version>"3.10"
librosa>=0.10.0
...
```
and Librosa 0.10.1:
```
install_requires =
    audioread >= 2.1.9
    numpy >= 1.20.3, != 1.22.0, != 1.22.1, != 1.22.2
...
```
With this knowledge I updated from python 3.10 (uninstalled) to python 3.11 and defined ``numpy==1.24.3`` in our requirements, because I thought it needs the next higher compatible version, as read in the TTS requirements. But, while building, the compiler said:
```
#17 12.18 The conflict is caused by:
#17 12.18     The user requested numpy==1.24.3
#17 12.18     tts 0.22.0 depends on numpy==1.22.0; python_version <= "3.10"
#17 12.18
```
I already tried to install numpy, librosa and tts without an version tag, but I got again the 1.22.0 numpy version with librosa 0.10.0 and tts 0.22.0 with the error at the beginning.

Why does the compiler stops at the first requirement validation and doesn't run through to the next one? Does anyone has an idea to fix it? install python 3.10 and 3.11?

_Originally posted by @OrbitPeppermint in https://github.com/coqui-ai/TTS/discussions/3537_

**Comment by Ph0rk0z** [comment]
Consider editing the deps.

**Comment by OrbitPeppermint** [comment]
I have updated the deps where I negate the numpy versions 1.22.0 , 1.22.1 and 1.22.2 , defined tts <= 0.22.0 and librosa without any definitions. In the end I got the versions • Librosa: 0.10.0.post2
• TTS: 0.14.3
• Numpy: 1.23.5
and it‘s running but only on TTS 0.14.3 with limited functions in comparision with todays version of tts 0.22.0.
If anyone has the time for an tts update to get it running with a new numpy version, I would be really thankful :)
Cheers

**Comment by Ph0rk0z** [comment]
I don't remember having issues with 1.23.5 and new TTS. I run XTTS and numpy keeps getting upgraded. I did upgrade librosa to the latest.

**Comment by eginhard** [comment]
This is fixed in our fork: https://github.com/idiap/coqui-ai-TTS Thanks for pointing it out.
