### ISSUE TITLE
speak only normal text not *thoughts*

### ISSUE THREAD

**Issue by kalle07** [coqui-ai/TTS#3564]
speak only normal text not *thoughts*

if i have a character i wrote under Greeting:
*Laura strides into the room with a warm but serious smile on her face. Her eyes are full of kindness as he greets you with a handshake.* Hello Joe

so all text is convert into audio not only "helle Joe"

so may option or suppress all audio for toughts

maybe an option for a little faster or slower audio ...

**Comment by Shlabadee** [comment]
Why not just omit the narration when sending it to the program?

**Comment by kalle07** [comment]
i use text-generation-webui, i cant send anything extra  ^^

**Comment by rose07** [comment]
This website is also owned by Microsoft. You can give it a try

https://tts.byylook.com/ai/text-to-speech

**Comment by 78Alpha** [comment]
Sillytavern has a feature that lets you omit those thoughts. You can still use textgenwebui as the backend.
