### ISSUE TITLE
Chinese speech synthesis does not have good sentence breaks

### ISSUE THREAD

**Issue by fanghaiquan1** [coqui-ai/TTS#3583]
### Describe the bug

When fine-tuning is completed, it is not good to break sentences when inferring Chinese text. Is there any good solution？

### To Reproduce

import os
import torch
import torchaudio
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

# Add here the xtts_config path
CONFIG_PATH = "recipes/ljspeech/xtts_v2/run/training/GPT_XTTS_v2.0_LJSpeech_FT-February-16-2024_03+59AM-0000000/config.json"
# Add here the vocab file that you have used to train the model
TOKENIZER_PATH = "recipes/ljspeech/xtts_v2/run/training/XTTS_v2.0_original_model_files/vocab.json"
# Add here the checkpoint that you want to do inference with
XTTS_CHECKPOINT = "recipes/ljspeech/xtts_v2/run/training/GPT_XTTS_v2.0_LJSpeech_FT-February-16-2024_03+59AM-0000000/best_model.pth"
# Add here the speaker reference
SPEAKER_REFERENCE = r"/home/TTS-dev/recipes/ljspeech/xtts_v2/LJSpeech-1.1/wavs/000005.wav"

# output wav path
OUTPUT_WAV_PATH = "yu202403.wav"

print("Loading model...")
config = XttsConfig()
config.load_json(CONFIG_PATH)
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_path=XTTS_CHECKPOINT, vocab_path=TOKENIZER_PATH, use_deepspeed=False)
model.cuda()

print("Computing speaker latents...")
gpt_cond_latent, speaker_embedding = model.get_conditioning_latents(audio_path=[SPEAKER_REFERENCE])

print("Inference...")
out = model.inference(
    "过年，在中国人心中有着特殊的意义，中国人也总是用最隆重、最充满仪式感的方式欢度新春佳节。贴春联、除夕夜守岁、拜大年，中国的年俗文化源远流长。在绵延数千年的传承发展中，全国各地衍生出丰富多彩的过年习俗。",
    "zh-cn",
    gpt_cond_latent,
    speaker_embedding,
    temperature=0.7, # Add custom parameters here
    length_penalty=1.0,
    repetition_penalty=10.0,
    top_k=50,
    top_p=0.85,
    do_sample=True,
    num_beams=1,
    speed=1.0,
    enable_text_splitting=True,
)
torchaudio.save(OUTPUT_WAV_PATH, torch.tensor(out["wav"]).unsqueeze(0), 24000)

### Environment

```shell
docker
```

**Comment by SMK1311** [comment]
请问您解决了吗，我也遇到这种问题
