### ISSUE TITLE
xttsv2 model sometimes（almost 10%）produce extra noise.[Bug] 

### ISSUE THREAD

**Issue by seetimee** [coqui-ai/TTS#3598]
### Describe the bug

For example,If it generates a 30-second audio, for the first 15 seconds it generates normal audio, and for the last 15 seconds it generates noise

### To Reproduce

tts_to_file(text=text,
                             language=lang_code,
                             speaker_wav=speaker_wav,
                             speed=speed,
                             file_path=temp_file
                             ,split_sentences=split_sentences)

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2+cu118",
        "TTS": "0.22.0",
        "numpy": "1.23.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.8",
        "version": "#148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022"
    }
}
```

**Comment by TangHaitao1994** [comment]
training data default length is about 15 seconds

**Comment by seetimee** [comment]
Is my training reference audio too long?（lower than 5 minutes will be better）

**Comment by kaveenkumar** [comment]
Most often occurs in FR language than others.

You synthesize 10 samples of a "text" for a given "voice", 2-3 out of those 10 samples contain the "text" + "some other blabbering"

**Comment by Sharrnah** [comment]
same with german.
English seems fine, so my guess is the training for some languages resulted in these issues.

For german, i think i sometimes could hear sentences like `Punkt. Neues Kapitel` or similar.
So maybe the training data included some verbose audio the readers added and the AI "learned" this for these languages.

(just some guessing here)

**Comment by seetimee** [comment]
keep watching

**Comment by Sharrnah** [comment]
i think something that confirms my guess.
In Italian, if you add a `.` (dot) at the end of a sentence, it very often speaks that dot "punkto".

it should not pronounce punctuation marks in my opinion.

**Comment by CRochaVox** [comment]
I also have a problem with noise after punctuations and in long sentences it is common for him to say the 'ponto' for the period in Portuguese

Does anyone know if it is possible to reduce this by finetunning the model?

**Comment by DrewThomasson** [comment]
Does this issue only occur in xttsv2? or also the original xtts?

**Comment by seetimee** [comment]
I haven't test it in  the original xtts
