### ISSUE TITLE
How to increase the 250 token limits for TTS

### ISSUE THREAD

**Issue by billdevmaster** [coqui-ai/TTS#3618]
Hello,
Now I am using TTS v2 for my tts server.
But this keeps to cut the whole text, because of the error of 250 token limits.
![image](https://github.com/coqui-ai/TTS/assets/83673245/3a69f782-37c5-4849-b122-a9f892275a99)

So I have updated /TTS/TTS/layers/xtts/tokenizer.py to set 400 limits
![image](https://github.com/coqui-ai/TTS/assets/83673245/c1d6edb9-8f3c-4e25-bc6d-379b1c173818)

it seems not to updated text limit.
it keeps cutting text as before.
how to resolve this?

**Comment by andrewginns** [comment]
There's a parameter called `enable_text_splitting` that automatically handles and splits text longer than the `char_limits`. I've passed it to the `synthesize` function call to avoid the error.

e.g.
```
    model, config = load_tts_model(
        config_path="./XTTS-v2/config.json", checkpoint_dir="./XTTS-v2/"
    )

    reference_audios = [reference_file]

    outputs = model.synthesize(
        text_to_speak,
        config,
        speaker_wav=reference_audios,
        gpt_cond_len=3,
        language="en",
        enable_text_splitting=True,
    )
```

**Comment by YodaGitMaster** [comment]
> There's a parameter called `enable_text_splitting` that automatically handles and splits text longer than the `char_limits`. I've passed it to the `synthesize` function call to avoid the error.
> 
> e.g.
> 
> ```
>     model, config = load_tts_model(
>         config_path="./XTTS-v2/config.json", checkpoint_dir="./XTTS-v2/"
>     )
> 
>     reference_audios = [reference_file]
> 
>     outputs = model.synthesize(
>         text_to_speak,
>         config,
>         speaker_wav=reference_audios,
>         gpt_cond_len=3,
>         language="en",
>         enable_text_splitting=True,
>     )
> ```

Thank you!
