### ISSUE TITLE
Please update to be able to use with Python 3.12

### ISSUE THREAD

**Issue by Aphexus** [coqui-ai/TTS#3627]
RuntimeError: TTS requires python >= 3.9 and < 3.12 but your Python version is 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

This happens even with trying to install using 
pip3 install --ignore-requires-python TTS

**Comment by eanon** [comment]
Same for me: `RuntimeError: TTS requires python >= 3.9 and < 3.12 but your Python version is 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]`

**Comment by sanjuhs** [comment]
guys +1 here does not work with python 3.12 , is there a way to update it manually ?

**Comment by eginhard** [comment]
See #3257

**Comment by Norman742** [comment]
Hi I added support to be able to use tts on Python 3.12  use this command pip install git+https://github.com/Norman742/ttspython312.git   , repository https://github.com/Norman742/ttspython312.git

**Comment by eginhard** [comment]
Python 3.12 is now supported in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by qq894617385** [comment]
thx,for everybody help

**Comment by errornullvoid** [comment]
> Python 3.12 is now supported in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

Your Readme instructions need to be updated, because the instructions plainly state to "pip install tts" not "pip install coqui-tts"
