### ISSUE TITLE
Question: Why is the model size different when trained using train_gpt_xtts.py in xtts_v2 compared to the baseline model?

### ISSUE THREAD

**Issue by MPQZF** [coqui-ai/TTS#3640]
### Describe the bug

When I train the train_gpt_xtts.py in recipes/ljspeech/xtts_v2 folder, the trained model size is 5.3G, but the baseline model size is 1.8G.
![image](https://github.com/coqui-ai/TTS/assets/30284344/11a9cad0-642b-4488-b7ae-b81b26e9d38e)
![image](https://github.com/coqui-ai/TTS/assets/30284344/0964df34-94d6-403e-b21f-67d0a7b15e6d)

### To Reproduce

I only made the following modifications in the recipes/ljspeech/xtts_v2/train_gpt_xtts.py in order to be able to execute it:
the "path" and "meta_file_train" in the BaseDatasetConfig input parameters and 
the path of the LJ001-0002.wav in "SPEAKER_REFERENCE". 
I think it has nothing to do with this.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla T4"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2",
        "TTS": "0.22.0",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.11.7",
        "version": "#60~20.04.1-Ubuntu SMP Thu Feb 22 15:49:52 UTC 2024"
    }
}
```

**Comment by phvaha1** [comment]
@MPQZF 
I got same issue as you. Did you solve the problem?

**Comment by eginhard** [comment]
This is normal. The pretrained model is smaller because it only includes the parts needed for inference.
