### ISSUE TITLE
[Bug] Time taken to run TTS command far greater than actual processing time

### ISSUE THREAD

**Issue by Vesper-Works** [coqui-ai/TTS#3642]
### Describe the bug

When running any command using tts <arguments> there's a long period of time before anything is actually done. I believe it is the same length of time independent of what arguments are used, even with invalid arguments this delay is present.

### To Reproduce

On Windows 10 machine run pip install tts --use-deprecated=legacy-resolver (legacy resolver else it'll download every single dependency version to try and match them...) without a virtual environment. Then try and use the library.

Sorry I can't be more descriptive since I don't use Python very much

### Expected behavior

The commands should be run instantly surely? 

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.1+cpu",
        "TTS": "0.14.3",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD",
        "python": "3.8.10",
        "version": "10.0.19045"
    }
}
```

### Additional context

I'm using this library to generate speech in real-time through the use of Process in C#, and this delay isn't acceptable for my use-case.
I'm sorry this is a vague issue, but I'm quite lost to be honest! Happy to answer all questions.

**Comment by Manamama** [comment]
The models are quite large. It takes time to fully download them to RAM, simply. You can monitor the process via python -v, of via resource monitor, the default GUI ones in Windows etc will do.

**Comment by Vesper-Works** [comment]
But the delay is present regardless of whether I'm synthesising speech. Even if I'm simply doing tts -h the delay is the same length of time. I can see using my resource manager that the resources are only allocated after this delay period, and are allocated almost instantaneously.

**Comment by Manamama** [comment]
Also the memory hard faults  may be to blame, especially on e.g. Droids. 

I wrote a snippet to monitor just that:
```

pidstat_while() {
  echo
  pidstat -r | awk 'NR<=3 {print $0}'
  echo
  while true; do
    pidstat -r | awk 'NR>3 {print $0}' | sort -k8nr -k5nr | head -n 1
    sleep 2
  done
}
```



It is a function that you can run by typing  `pidstat_while`  after pasting the above. 
It even runs in Termux, but in prooted Debian. 
In very short, it shows you the most memory intensive process, and the hard faults. If you have too many (say, over 50 per seconds) - the model is being memory mapped (aka loaded) from disk, now and then. (Excuse my maybe naive and non-IT explanation of the root cause... )

**Comment by Vesper-Works** [comment]
I'm away from my PC for the next week, I'll run this and see what it says once I have access to it again, thanks!

**Comment by Vesper-Works** [comment]
I didn't really understand what you were talking about and asked a friend, they said because I'm on Windows I won't be able to run what you've sent

**Comment by eginhard** [comment]
First of all, you're using a very outdated TTS version (you need at least Python 3.9 to get the latest). Then, making separate CLI calls will always be slow because you have to load the model every time, so e.g. use the server: https://docs.coqui.ai/en/latest/inference.html#on-the-demo-server-tts-server

**Comment by Vesper-Works** [comment]
Ah okay, thanks! I had no idea I was outdated, I tried installing on Python 3. something greater than 8 and it told me I needed Python 8. I'm going to assume there must have been some user error there, once I'm able I'll try a fresh reinstall and look into creating the server.

**Comment by Vesper-Works** [comment]
Yep, the server runs faaar faster! Thanks, the first line of the server part of the wiki tells you to not use it in real-time applications so I avoided looking into it further, there was my mistake! Maybe this could be made clearer? Thanks!
