### ISSUE TITLE
[Bug] Unable to use xtts_v2 with mps device on Apple Silicon

### ISSUE THREAD

**Issue by vesper8** [coqui-ai/TTS#3649]
### Describe the bug

I have a M1 Max with 32 cores and 64 gb of unified memory. So if MPS is meant to work, it should work quite fast. But currently it doesn't work at all, it just hangs.

I'm running it this way: `tts --device mps --model_name "tts_models/multilingual/multi-dataset/xtts_v2" --speaker_idx 'Daisy Studious' --language_idx en --text "Hello world" --out_path ./output/speech.wav`

If I change the device to cpu then it works just fine and rather quickly. If I change it to mps, it just hangs until I Ctrl-C

I also have this info:

```
PyTorch version: 2.2.2
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps
```

Am I missing something?

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.2",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "arm",
        "python": "3.10.10",
        "version": "Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000"
    }
}
```

**Comment by Panquesito0** [comment]
Hey. I've been searching for a way to use mps, but this is what I found. Using the following  Python code:
```
import torch
from TTS.api import TTS
AUDIO_INPUT = './Input.mp3'
AUDIO_OUTPUT = './Output.wav'
TEXT = '''Hello'''
# Get device
device = "cuda" if torch.cuda.is_available() else 'mps' # "mps"
# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
# Text to speech to a Tile
tts.tts_to_file(text=TEXT, speaker_wav=AUDIO_INPUT,language="en",file_path=AUDIO_OUTPUT) 

```
The next message is shown:
`The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.`

After searching for this error message on internet I've found this https://github.com/pytorch/pytorch/issues/116392. It appears to be more related to pytorch than to TTS itself. In the link it is mentioned that they are working to implement the use of MPS on this models. So I guess we have to wait.

**Comment by DrewThomasson** [comment]
I'm pretty sure Ive gotten xtts to run on mps on my M1 pro,
But I don't seem to see any speedup when I use it on mps anyway

and running on a python 3.10 env in conda

I got it working by doing these pips
```bash
pip install tensorflow-macos 
# Optional
pip install tensorflow-metal
```

**Comment by Panquesito0** [comment]
By using latest PyTorch, using CPU is faster than MPS for some reason. For 4:30 min on MPS using CPU gives me 30s. I'm using a MacBook Air M1

**Comment by DrewThomasson** [comment]
very interesting... thats even weirder cause I barley see a change on my side lol

**Comment by DrewThomasson** [comment]
lol well now its not working on my computer but anyway


## but also related to your error of 

`The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.`



Considering the xtts model is based on tortoise tts I found something on people trying to run tortoise it on mps, 

https://github.com/neonbjb/tortoise-tts/discussions/115


leading to this merge with the tortoise repo
https://github.com/neonbjb/tortoise-tts/pull/550

It appears there isn't support for stuff like `aten::_fft_r2c` and such so yeah as you previous statment does, I guess we just wait lol.

lol so were just back to where we started with this comment here lol
 https://github.com/coqui-ai/TTS/issues/3649#issuecomment-2372232656

**Comment by DrewThomasson** [comment]
# Yup seems that loading on `mps` is slower than `cpu` rn 😞 

```bash
(newtts_test) drew@wmughal-CN4D09397T Downloads % export PYTORCH_ENABLE_MPS_FALLBACK=1
python test.py

Generating on CPU...
Generation time on CPU: 2.40 seconds
Generating on mps...
Generation time on mps: 5.57 seconds

Time difference: -3.17 seconds
```

## Details on how I got it to kind of work [here](https://github.com/idiap/coqui-ai-TTS/issues/65#issuecomment-2444936395) on the fork of coqui that's still being updated
