### ISSUE TITLE
[Feature request] Language Support ("Hindi") missing in XTTS on local machine.

### ISSUE THREAD

**Issue by ghost** [coqui-ai/TTS#3655]
*Title

On XTTS site (i.e https://huggingface.co/coqui/XTTS-v2), Hindi language is already supported and it's working perfect on demo site. But, the problem is when I install XTTS on my local machine, error appears that 'hi' is not supported. 

Language hi is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn', 'hu', 'ko', 'ja']

Possible solution might be adding 'hi' index in languages. Since afaik, XTTS on local machine import the dataset as on the online demo website. Also, for fine tuning XTTS (used colab notebook from this video - https://www.youtube.com/watch?v=8tpDiiouGxc), Hindi language option isn't available as a option. It would be helpful to add support plus able to fine tune XTTS for that language.

Thanks!

**Comment by eginhard** [comment]
Thanks for spotting this. I've enabled Hindi in the fine-tuning demo and tokenizer in our fork: https://github.com/idiap/coqui-ai-TTS

**Comment by ghost** [comment]
Hi, thanks for the fork repo link, I noticed keyerror='hi' type of errors when I tried to fine tune model, however I've added some 'hi' tags/attributes in some function located in tokenizer.py and now it's works perfectly.

**Comment by jiten634** [comment]
> Hi, thanks for the fork repo link, I noticed keyerror='hi' type of errors when I tried to fine tune model, however I've added some 'hi' tags/attributes in some function located in tokenizer.py and now it's works perfectly.

Can you share the files, where you have added hindi tags/att ? because I am still stuck at there. Please help... I am facing the same issue in xtts v1.1

**Comment by ghost** [comment]
Install the Coqui TTS, then,
Download the selected tokenizer.py and put it in TTS/tts/layers/xtts folder
https://drive.google.com/file/d/1cAW8b-JTttyVLST3_PIYGJbvs4gQQMzc/view?usp=drivesdk

**Comment by jiten634** [comment]
> Install the Coqui TTS, then, Download the selected tokenizer.py and put it in TTS/tts/layers/xtts folder https://drive.google.com/file/d/1cAW8b-JTttyVLST3_PIYGJbvs4gQQMzc/view?usp=drivesdk

Thanks for the link. I am also facing one more problem in **XTTS V2**, when I am making hindi voice, in the **end of the audio file**, sometimes it **cut the word**, or sometimes it speak a **different hallucination** type voice. is there any solution for this?

**Comment by ghost** [comment]
It's the known issue of XTTS V2, there's no fix for this issue because as far as I know XTTS is proprietary TTS engine(not open source).
