### ISSUE TITLE
[Bug] Unable to install Coqui TTS

### ISSUE THREAD

**Issue by WarpWing** [coqui-ai/TTS#3685]
### Describe the bug

Could not install out of the box Coqui TTS due to missing setup tools command.

### To Reproduce

```bash
git clone https://github.com/coqui-ai/TTS
pip install -e .[all,dev,notebooks] -error here
```

### Expected behavior

Successful installation.

### Logs

```shell
Collecting sudachipy!=0.6.1,>=0.5.2
  Using cached SudachiPy-0.6.8.tar.gz (161 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 16, in <module>
          from setuptools_rust import Binding, RustExtension
        File "/tmp/pip-build-env-s44a2r7s/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-s44a2r7s/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 22, in <module>
          from setuptools.command.build import build as CommandBuild
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.0",
        "TTS": "0.22.0",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "aarch64",
        "python": "3.10.12",
        "version": "#55-Ubuntu SMP Mon Nov 20 19:53:49 UTC 2023"
    }
}
```

**Comment by anurag12-webster** [comment]
@WarpWing Try to install it Git LFS before installing the TTS

**Comment by WarpWing** [comment]
> @WarpWing Try to install it Git LFS before installing the TTS

That worked! thank you

**Comment by Jems5767** [comment]
I tried installing git-lfs but it still failed for me. Here is how i installed git-lfs. I updated the existing apt-get install command and added git-lfs to the list.

```
RUN apt-get install -y --no-install-recommends \
    gcc g++ \
    make \
    git-lfs \
    python3 python3-dev python3-pip python3-venv python3-wheel \
    espeak-ng libsndfile1-dev \
    && rm -rf /var/lib/apt/lists/*
```

This is the error that I am facing now.
```
213.6   Installing build dependencies: started
215.3   Installing build dependencies: finished with status 'done'
215.3   Getting requirements to build wheel: started
215.4   Getting requirements to build wheel: finished with status 'error'
215.4   error: subprocess-exited-with-error
215.4   
215.4   × Getting requirements to build wheel did not run successfully.
215.4   │ exit code: 1
215.4   ╰─> [22 lines of output]
215.4       Traceback (most recent call last):
215.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
215.4           main()
215.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
215.4           json_out['return_val'] = hook(**hook_input['kwargs'])
215.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
215.4           return hook(config_settings)
215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
215.4           return self._get_build_requires(
215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
215.4           self.run_setup()
215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
215.4           super(_BuildMetaLegacyBackend,
215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
215.4           exec(compile(code, __file__, 'exec'), locals())
215.4         File "setup.py", line 16, in <module>
215.4           from setuptools_rust import Binding, RustExtension
215.4         File "/tmp/pip-build-env-ct9ucovm/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
215.4           from .build import build_rust
215.4         File "/tmp/pip-build-env-ct9ucovm/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 22, in <module>
215.4           from setuptools.command.build import build as CommandBuild
215.4       ModuleNotFoundError: No module named 'setuptools.command.build'
215.4       [end of output]
215.4   
215.4   note: This error originates from a subprocess, and is likely not a problem with pip.
215.4 error: subprocess-exited-with-error
215.4 
215.4 × Getting requirements to build wheel did not run successfully.
215.4 │ exit code: 1
215.4 ╰─> See above for output.
215.4 
215.4 note: This error originates from a subprocess, and is likely not a problem with pip.
------
```

I am using a macbook M3 pro as a host.

**Comment by WarpWing** [comment]
> I tried installing git-lfs but it still failed for me. Here is how i installed git-lfs. I updated the existing apt-get install command and added git-lfs to the list.
> 
> ```
> RUN apt-get install -y --no-install-recommends \
>     gcc g++ \
>     make \
>     git-lfs \
>     python3 python3-dev python3-pip python3-venv python3-wheel \
>     espeak-ng libsndfile1-dev \
>     && rm -rf /var/lib/apt/lists/*
> ```
> 
> This is the error that I am facing now.
> ```
> 213.6   Installing build dependencies: started
> 215.3   Installing build dependencies: finished with status 'done'
> 215.3   Getting requirements to build wheel: started
> 215.4   Getting requirements to build wheel: finished with status 'error'
> 215.4   error: subprocess-exited-with-error
> 215.4   
> 215.4   × Getting requirements to build wheel did not run successfully.
> 215.4   │ exit code: 1
> 215.4   ╰─> [22 lines of output]
> 215.4       Traceback (most recent call last):
> 215.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
> 215.4           main()
> 215.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
> 215.4           json_out['return_val'] = hook(**hook_input['kwargs'])
> 215.4         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
> 215.4           return hook(config_settings)
> 215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
> 215.4           return self._get_build_requires(
> 215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
> 215.4           self.run_setup()
> 215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
> 215.4           super(_BuildMetaLegacyBackend,
> 215.4         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
> 215.4           exec(compile(code, __file__, 'exec'), locals())
> 215.4         File "setup.py", line 16, in <module>
> 215.4           from setuptools_rust import Binding, RustExtension
> 215.4         File "/tmp/pip-build-env-ct9ucovm/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
> 215.4           from .build import build_rust
> 215.4         File "/tmp/pip-build-env-ct9ucovm/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 22, in <module>
> 215.4           from setuptools.command.build import build as CommandBuild
> 215.4       ModuleNotFoundError: No module named 'setuptools.command.build'
> 215.4       [end of output]
> 215.4   
> 215.4   note: This error originates from a subprocess, and is likely not a problem with pip.
> 215.4 error: subprocess-exited-with-error
> 215.4 
> 215.4 × Getting requirements to build wheel did not run successfully.
> 215.4 │ exit code: 1
> 215.4 ╰─> See above for output.
> 215.4 
> 215.4 note: This error originates from a subprocess, and is likely not a problem with pip.
> ------
> ```
> 
> I am using a macbook M3 pro as a host.

You can install setup tools via pip to fix the issue.

**Comment by Jems5767** [comment]
Tried that but that also didn't worked
> You can install setup tools via pip to fix the issue.

**Comment by swaipdev** [comment]
Same problem on Windows 11:

Traceback (most recent call last):
        File "C:\AIKU\experiments\coqui\TTS\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\AIKU\experiments\coqui\TTS\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\AIKU\experiments\coqui\TTS\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\carlo\AppData\Local\Temp\pip-build-env-c8o3a0bc\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\carlo\AppData\Local\Temp\pip-build-env-c8o3a0bc\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\carlo\AppData\Local\Temp\pip-build-env-c8o3a0bc\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "C:\Users\carlo\AppData\Local\Temp\pip-build-env-c8o3a0bc\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\carlo\AppData\Local\Temp\pip-build-env-c8o3a0bc\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by eginhard** [comment]
@swaipdev Try installing [our fork](https://github.com/idiap/coqui-ai-TTS) with `pip install coqui-tts`, it has prebuilt wheels for Windows. This repo is not maintained anymore.

**Comment by swaipdev** [comment]
Hi, seems to work thanks !

Do you know if there's any way to speak multiple phrases with a voice cloned loaded like this :

audio_data = tts.tts("my phrase", speaker_wav="my_audio.mp3", language="en")


without reloading each time the speaker_wav? This should result in a faster generation of the subsequent phrases hopefully.

Thanks !

On 10/9/2024 10:51:59 PM, Enno Hermann ***@***.***> wrote:
@swaipdev [https://github.com/swaipdev] Try installing our fork [https://github.com/idiap/coqui-ai-TTS] with pip install coqui-tts, it has prebuilt wheels for Windows. This repo is not maintained anymore.

**Comment by eginhard** [comment]
@swaipdev You can store and reuse the latents, see https://coqui-tts.readthedocs.io/en/latest/models/xtts.html#id5
