### ISSUE TITLE
starting from best_model is not the best option when --continue_training

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#369]
@gerazov based on this https://github.com/mozilla/TTS/issues/679 starting from the last best_model looks confusing for people, and sometimes I found myself removing the best model to continue from the last checkpoint. 

I suggest reverting this to the old behavior that we pick the last checkpoint.

**Comment by gerazov** [comment]
Training should continue from last checkpoint or best model whatever has the latest step stamp as found by https://github.com/coqui-ai/TTS/blob/f24d48c245c3381db99f3f9f16dda574ad1df3c5/TTS/utils/arguments.py#L70. Is this not working?

When is the `config.json` updated as pointed out by  mozilla/TTS#679 ? Is it after restarting training?

**Comment by erogol** [comment]
Ok then we have a bug :beetle:  since model continues from the last best model regardless of the step number

**Comment by Sadam1195** [comment]
This hasn't been fixed yet.
