### ISSUE TITLE
[Bug] Voice lag and pronounce punctuation

### ISSUE THREAD

**Issue by Razatator** [coqui-ai/TTS#3701]
### Describe the bug

When I create a model to imitate a voice for dubbing it comes out with stutters as if the character had Down syndrome sometimes and it pronounces 'point' at the end of sentences in French. On other imitations, there were Japanese voices in the background. Since installing the V2 model
I went back to version 0.21 and 0.22 as explained but still the bugs.

### To Reproduce

https://colab.research.google.com/github/R3gm/SoniTranslate/blob/main/SoniTranslate_Colab.ipynb

### Logs

```shell
anaconda3/TTS/bin/collect_env_info.py dont work
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1060 with Max-Q Design"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.2",
        "TTS": "0.22.0",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.14",
        "version": "#13-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 16 00:01:45 UTC 2024"
    }
}
```

### Additional context

I use TTS in this environment https://github.com/R3gm/SoniTranslate in anaconda3

**Comment by Ca-ressemble-a-du-fake** [comment]
This also happens to me but I don't know how to reproduce it. I am using the `from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)

tts.tts_to_file(text="Ma phrase en français.",
                file_path="output.wav",
                speaker_wav=["/path/to/target/speaker2.wav"],
                language="fr",
                split_sentences=True
                )` as shown in https://docs.coqui.ai/en/latest/models/xtts.html#id2.

So what happens is that it literally says the period : "Ma phrase en français POINT", where it should be "Ma phrase en français". 

Yet it happens inconsistently  ~~and only for some speakers (ie speaker_wav). So same sentence from another speaker does not trigger it~~. The problem can happen differently (not the same artifacts are generated) with other speaker_wav, but it can also not happen for the same sentence and same speaker_wav but after a different context (ie the sentence that was said just beforehand).

One workaround is to add a space before like `Ma phrase en français .` but this sometimes add an artifact (like breathing or long bizarre slow hearing sound or another short sound like "euh").

**Comment by Ca-ressemble-a-du-fake** [comment]
Using [manual inference ](https://docs.coqui.ai/en/latest/models/xtts.html#id5) with a low temperature (0.1) tends to decrease this phenomenon (but sentences get sometimes truncated).
