### ISSUE TITLE
[Feature request] Run in the browser?

### ISSUE THREAD

**Issue by flatsiedatsie** [coqui-ai/TTS#3714]
**🚀 Feature Description**

It would be wonderful if it were possible to generate voices in a webbrowser. E.g. through Transformers.js or something similar?

**Solution**

I don't know. Perhaps a WASM version could be made through emscriptem?

**Alternative Solutions**

- Transformers.js supports a T5 model, but it's quality is not on the same level.
- Web browser come with built-in TTS, with very low quality. Yet a lot of visually impaired people rely on these low quality voices for interaction.

**Comment by JabariHolder** [comment]
@flatsiedatsie, @rvuyyuru2, @jlucaso1 (and anyone else who is interested)

[Sherpa ONNX](https://github.com/k2-fsa/sherpa-onnx) has a few coqui models integrated in it.
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

You can demo the coqui models here by selecting them from the list. They all start with (vits-coqui-xx):
https://huggingface.co/spaces/k2-fsa/text-to-speech

Quickest way to get started once you know what model you want:
https://huggingface.co/spaces/k2-fsa/web-assembly-tts-sherpa-onnx-en/tree/main

**Comment by jlucaso1** [comment]
It's possible to get xtts from coqui with audio reference and multi language support in onnx?
