### ISSUE TITLE
[Bug] xtts_v2, AttributeError: 'TTS' object has no attribute 'speakers'

### ISSUE THREAD

**Issue by chigkim** [coqui-ai/TTS#3742]
### Describe the bug

If I run tts.speakers after loading xtts_v2, it throws an error: 'TTS' object has no attribute 'speakers'.

### To Reproduce

import torch
from TTS.api import TTS
device = "cuda" if torch.cuda.is_available() else "cpu"
model = "tts_models/multilingual/multi-dataset/xtts_v2"
tts = TTS(model).to(device)
tts.speakers

### Expected behavior

It should list all the speaker names.

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>.venv\Lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TTS' object has no attribute 'speakers'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.3.0+cpu",
        "TTS": "0.22.0",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel",
        "python": "3.11.9",
        "version": "10.0.19045"
    }
}
```

### Additional context

Other multi speaker models like vctk/vits work fine using the same method.

**Comment by eginhard** [comment]
This is fixed by https://github.com/eginhard/coqui-tts/pull/8 in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by chigkim** [comment]
Thanks@eginhard! Had no idea this repo was abandoned.

**Comment by jamesob** [comment]
Thanks @eginhard. This repo should probably be marked as read-only/archive by its owners.

**Comment by Asrithapenmetsa** [comment]
Hi, @chigkim 
Have you finetuned the vits model with your own dataset?
Because I am encountering this error AttributeError: 'TTS' object has no attribute 'get_model' while I am tryng to finetune the model?

**Comment by chigkim** [comment]
It's a bug, and it's fixed in another fork.
https://github.com/idiap/coqui-ai-TTS

**Comment by Asrithapenmetsa** [comment]
But in this fork I've tried this line in my code . But it didn't work. Can
you please help me in the process of fine tuning vits model.Here is the
code:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from dataset import CustomDataset
from TTS.api import TTS
import warnings

def train_model(model, train_loader, val_loader, criterion, optimizer,
scheduler, num_epochs=10000, device='cuda'):
    model.to(device)  # Move the model to the specified device (e.g. GPU)

    for epoch in range(num_epochs):
        model.train()  # Set the model to training mode
        running_loss = 0.0
        for i, (waveform, transcript) in enumerate(train_loader):
            waveform = waveform.to(device)
            transcript = transcript.to(device)  # Move transcript to device
if necessary

            optimizer.zero_grad()  # Zero the parameter gradients

            # Forward pass
            outputs = model(waveform)  # Make sure this line aligns with
your model's forward method
            # Compute loss
            loss = criterion(outputs, transcript)

            # Backward pass and optimization
            loss.backward()
            optimizer.step()
            scheduler.step()

            running_loss += loss.item()
            if (i + 1) % 10 == 0:
                print(f'Epoch [{epoch + 1}/{num_epochs}], Step [{i + 1}/{len
(train_loader)}], Loss: {running_loss / 10:.4f}')
                running_loss = 0.0

        # Validation
        model.eval()  # Set the model to evaluation mode
        with torch.no_grad():
            val_loss = 0.0
            for waveform, transcript in val_loader:
                waveform = waveform.to(device)
                transcript = transcript.to(device)  # Move transcript to
device if necessary

                outputs = model(waveform)
                loss = criterion(outputs, transcript)
                val_loss += loss.item()

        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Loss: {val_loss
/ len(val_loader):.4f}')

    print('Training finished.')

def main():
    # Suppress the FutureWarning for this example
    warnings.filterwarnings("ignore", category=FutureWarning, module="torch"
)

    # Configuration
    metadata_file_train = 'C:\\TTS\\vits\\Dataset\\train_filelist.csv'
    metadata_file_val = 'C:\\TTS\\vits\\Dataset\\val_filelist.csv'
    audio_dir = 'C:\\TTS\\vits\\Dataset\\audio'
    batch_size = 2
    learning_rate = 1e-5

    # Load dataset and dataloader
    train_dataset = CustomDataset(metadata_file=metadata_file_train,
audio_dir=audio_dir)
    val_dataset = CustomDataset(metadata_file=metadata_file_val, audio_dir=
audio_dir)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=
True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=
False)

    # Initialize TTS model
    model = TTS('tts_models/en/ljspeech/vits').to(device)

# Use the appropriate method to retrieve the model
    # Define criterion, optimizer, and scheduler
    criterion = nn.CTCLoss()  # Replace with appropriate loss function
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, betas=(0.8,
0.99), eps=1e-09, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=
0.999875, last_epoch=-1)

    # Start training
    train_model(model, train_loader, val_loader, criterion, optimizer,
scheduler)

if __name__ == '__main__':
    main()


Thanks

**Comment by eginhard** [comment]
@Asrithapenmetsa Placing code between triple backticks would make it easier to read... Could you also share the full error trace, not just the last line?

**Comment by Asrithapenmetsa** [comment]
Hi,
But in this fork I've tried this line in my code . But it didn't work. Can you please help me in the process of fine tuning vits model.Here is the code:
'''import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from dataset import CustomDataset
from TTS.api import TTS
import warnings

def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler, num_epochs=10000, device='cuda'):
    model.to(device)  # Move the model to the specified device (e.g. GPU)

    for epoch in range(num_epochs):
        model.train()  # Set the model to training mode
        running_loss = 0.0
        for i, (waveform, transcript) in enumerate(train_loader):
            waveform = waveform.to(device)
            transcript = transcript.to(device)  # Move transcript to device if necessary

            optimizer.zero_grad()  # Zero the parameter gradients

            # Forward pass
            outputs = model(waveform)  # Make sure this line aligns with your model's forward method
            # Compute loss
            loss = criterion(outputs, transcript)
            
            # Backward pass and optimization
            loss.backward()
            optimizer.step()
            scheduler.step()

            running_loss += loss.item()
            if (i + 1) % 10 == 0:
                print(f'Epoch [{epoch + 1}/{num_epochs}], Step [{i + 1}/{len(train_loader)}], Loss: {running_loss / 10:.4f}')
                running_loss = 0.0

        # Validation
        model.eval()  # Set the model to evaluation mode
        with torch.no_grad():
            val_loss = 0.0
            for waveform, transcript in val_loader:
                waveform = waveform.to(device)
                transcript = transcript.to(device)  # Move transcript to device if necessary

                outputs = model(waveform)
                loss = criterion(outputs, transcript)
                val_loss += loss.item()

        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Loss: {val_loss / len(val_loader):.4f}')

    print('Training finished.')

def main():
    # Suppress the FutureWarning for this example
    warnings.filterwarnings("ignore", category=FutureWarning, module="torch")

    # Configuration
    metadata_file_train = 'C:\\TTS\\vits\\Dataset\\train_filelist.csv'
    metadata_file_val = 'C:\\TTS\\vits\\Dataset\\val_filelist.csv'
    audio_dir = 'C:\\TTS\\vits\\Dataset\\audio'
    batch_size = 2
    learning_rate = 1e-5

    # Load dataset and dataloader
    train_dataset = CustomDataset(metadata_file=metadata_file_train, audio_dir=audio_dir)
    val_dataset = CustomDataset(metadata_file=metadata_file_val, audio_dir=audio_dir)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    # Initialize TTS model
    model = TTS('tts_models/en/ljspeech/vits').to(device)

# Use the appropriate method to retrieve the model
    # Define criterion, optimizer, and scheduler
    criterion = nn.CTCLoss()  # Replace with appropriate loss function
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, betas=(0.8, 0.99), eps=1e-09, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.999875, last_epoch=-1)

    # Start training
    train_model(model, train_loader, val_loader, criterion, optimizer, scheduler)

if __name__ == '__main__':
    main()'''

And I got this error

AttributeError:'TTS' object has no attribute 'device'

**Comment by Asrithapenmetsa** [comment]
Sure thing.

I have posted the comment in github.Please Check it out.

Thanks

**Comment by Asrithapenmetsa** [comment]
Hi,
But in this fork I've tried this line in my code . But it didn't work. Can you please help me in the process of fine tuning vits model.Here is the code:

`import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from dataset import CustomDataset
from TTS.api import TTS
import warnings

def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler, num_epochs=10000, device='cuda'):
    model.to(device)  # Move the model to the specified device (e.g. GPU)

    for epoch in range(num_epochs):
        model.train()  # Set the model to training mode
        running_loss = 0.0
        for i, (waveform, transcript) in enumerate(train_loader):
            waveform = waveform.to(device)
            transcript = transcript.to(device)  # Move transcript to device if necessary

            optimizer.zero_grad()  # Zero the parameter gradients

            # Forward pass
            outputs = model(waveform)  # Make sure this line aligns with your model's forward method
            # Compute loss
            loss = criterion(outputs, transcript)
            
            # Backward pass and optimization
            loss.backward()
            optimizer.step()
            scheduler.step()

            running_loss += loss.item()
            if (i + 1) % 10 == 0:
                print(f'Epoch [{epoch + 1}/{num_epochs}], Step [{i + 1}/{len(train_loader)}], Loss: {running_loss / 10:.4f}')
                running_loss = 0.0

        # Validation
        model.eval()  # Set the model to evaluation mode
        with torch.no_grad():
            val_loss = 0.0
            for waveform, transcript in val_loader:
                waveform = waveform.to(device)
                transcript = transcript.to(device)  # Move transcript to device if necessary

                outputs = model(waveform)
                loss = criterion(outputs, transcript)
                val_loss += loss.item()

        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Loss: {val_loss / len(val_loader):.4f}')

    print('Training finished.')

def main():
    # Suppress the FutureWarning for this example
    warnings.filterwarnings("ignore", category=FutureWarning, module="torch")

    # Configuration
    metadata_file_train = 'C:\\TTS\\vits\\Dataset\\train_filelist.csv'
    metadata_file_val = 'C:\\TTS\\vits\\Dataset\\val_filelist.csv'
    audio_dir = 'C:\\TTS\\vits\\Dataset\\audio'
    batch_size = 2
    learning_rate = 1e-5

    # Load dataset and dataloader
    train_dataset = CustomDataset(metadata_file=metadata_file_train, audio_dir=audio_dir)
    val_dataset = CustomDataset(metadata_file=metadata_file_val, audio_dir=audio_dir)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    # Initialize TTS model
    model = TTS('tts_models/en/ljspeech/vits').to(device)

# Use the appropriate method to retrieve the model
    # Define criterion, optimizer, and scheduler
    criterion = nn.CTCLoss()  # Replace with appropriate loss function
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, betas=(0.8, 0.99), eps=1e-09, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.999875, last_epoch=-1)

    # Start training
    train_model(model, train_loader, val_loader, criterion, optimizer, scheduler)

if __name__ == '__main__':
    main()`

And I am getting the error like

AttributeError:'TTS' has no attribute 'device'

**Comment by Asrithapenmetsa** [comment]
Hi
model="tts_models/en/ljspeech/vits"
**Logs**
```Traceback (most recent call last):
  File "C:\Users\siren\AppData\Local\tts\tts_models--en--ljspeech--vits\finetune.py", line 82, in <module>
    main()
  File "C:\Users\siren\AppData\Local\tts\tts_models--en--ljspeech--vits\finetune.py", line 70, in main
    model = TTS('tts_models/en/ljspeech/vits').to(device)
NameError: name 'device' is not defined```
**Here is the complete code:**
```import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from dataset import CustomDataset
from TTS.api import TTS
import warnings

def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler, num_epochs=10000, device='cuda'):
    model.to(device)  # Move the model to the specified device (e.g. GPU)

    for epoch in range(num_epochs):
        model.train()  # Set the model to training mode
        running_loss = 0.0
        for i, (waveform, transcript) in enumerate(train_loader):
            waveform = waveform.to(device)
            transcript = transcript.to(device)  # Move transcript to device if necessary

            optimizer.zero_grad()  # Zero the parameter gradients

            # Forward pass
            outputs = model(waveform)  # Make sure this line aligns with your model's forward method
            # Compute loss
            loss = criterion(outputs, transcript)
            
            # Backward pass and optimization
            loss.backward()
            optimizer.step()
            scheduler.step()

            running_loss += loss.item()
            if (i + 1) % 10 == 0:
                print(f'Epoch [{epoch + 1}/{num_epochs}], Step [{i + 1}/{len(train_loader)}], Loss: {running_loss / 10:.4f}')
                running_loss = 0.0

        # Validation
        model.eval()  # Set the model to evaluation mode
        with torch.no_grad():
            val_loss = 0.0
            for waveform, transcript in val_loader:
                waveform = waveform.to(device)
                transcript = transcript.to(device)  # Move transcript to device if necessary

                outputs = model(waveform)
                loss = criterion(outputs, transcript)
                val_loss += loss.item()

        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Loss: {val_loss / len(val_loader):.4f}')

    print('Training finished.')

def main():
    # Suppress the FutureWarning for this example
    warnings.filterwarnings("ignore", category=FutureWarning, module="torch")

    # Configuration
    metadata_file_train = 'C:\\TTS\\vits\\Dataset\\train_filelist.csv'
    metadata_file_val = 'C:\\TTS\\vits\\Dataset\\val_filelist.csv'
    audio_dir = 'C:\\TTS\\vits\\Dataset\\audio'
    batch_size = 2
    learning_rate = 1e-5

    # Load dataset and dataloader
    train_dataset = CustomDataset(metadata_file=metadata_file_train, audio_dir=audio_dir)
    val_dataset = CustomDataset(metadata_file=metadata_file_val, audio_dir=audio_dir)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    # Initialize TTS model
    model = TTS('tts_models/en/ljspeech/vits').to(device)

# Use the appropriate method to retrieve the model
    # Define criterion, optimizer, and scheduler
    criterion = nn.CTCLoss()  # Replace with appropriate loss function
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, betas=(0.8, 0.99), eps=1e-09, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.999875, last_epoch=-1)

    # Start training
    train_model(model, train_loader, val_loader, criterion, optimizer, scheduler)

if __name__ == '__main__':
    main()```
**Environment** 

```{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz   4.20 GHz",
        "python": "3.10.9",
        "version": "22H2"
    }
}```

**Comment by eginhard** [comment]
Your error message
```python
    model = TTS('tts_models/en/ljspeech/vits').to(device)
NameError: name 'device' is not defined
```
tells you that the variable `device` is not defined. So add a line that defines it before, e.g.
```python
device = "cuda" if torch.cuda.is_available() else "cpu"
```

**Comment by Asrithapenmetsa** [comment]
Thank you so much .
 It got fixed.
Thanks
