### ISSUE TITLE
UnboundLocalError: local variable 'dataset' referenced before assignment [Bug] 

### ISSUE THREAD

**Issue by qyum** [coqui-ai/TTS#3744]
### Describe the bug

i got the error from following code
# TTS with on the fly voice conversion
![bug](https://github.com/coqui-ai/TTS/assets/45398575/0c0af403-a46d-45f5-b235-6377dc0f1796)

api = TTS("tts_models/ben/fairseq/vits")

### To Reproduce

![bug](https://github.com/coqui-ai/TTS/assets/45398575/7e89991e-88c9-4d17-8b20-d954cf2f0f6f)

### Logs

```shell
TTS.utils.manage.ModelManager object at 0x7d4d9a33d3f0>
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-10-d1f358930bab> in <cell line: 3>()
      1 print(TTS().list_models())
      2 # TTS with on the fly voice conversion
----> 3 api = TTS("tts_models/ben/fairseq/vits")

4 frames
/usr/local/lib/python3.10/dist-packages/TTS/utils/manage.py in _set_model_item(self, model_name)
    302             model_item["model_type"] = model_type
    303 
--> 304         model_full_name = f"{model_type}--{lang}--{dataset}--{model}"
    305         md5hash = model_item["model_hash"] if "model_hash" in model_item else None
    306         model_item = self.set_model_url(model_item)

UnboundLocalError: local variable 'dataset' referenced before assignment
```

### Environment

```shell
Use google colab
```

**Comment by eginhard** [comment]
This is fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by HardikJain02** [comment]
@qyum any workaround?

**Comment by eginhard** [comment]
@HardikJain02 This repo is not maintained anymore. But it's fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`
