### ISSUE TITLE
[Bug] DDP not actually working

### ISSUE THREAD

**Issue by hscspring** [coqui-ai/TTS#3748]
### Describe the bug

see https://github.com/coqui-ai/Trainer/issues/144

### To Reproduce

see https://github.com/coqui-ai/Trainer/issues/144

### Environment

```shell
see https://github.com/coqui-ai/Trainer/issues/144
```

**Comment by hscspring** [comment]
ok, guys, i've fixed this issue ~

**Comment by JinYuanZhang999** [comment]
@hscspring Would you mind sharing how you solved it?
