### ISSUE TITLE
[Bug] Anyway to run this as docker-compose ?

### ISSUE THREAD

**Issue by PeterTucker** [coqui-ai/TTS#3754]
### Describe the bug

Anyway to run this as docker-compose ?

### To Reproduce

Anyway to run this as docker-compose ?

### Expected behavior

Anyway to run this as docker-compose ?

### Logs

```shell
Anyway to run this as docker-compose ?
```

### Environment

```shell
Anyway to run this as docker-compose ?
```

### Additional context

Anyway to run this as docker-compose ?

**Comment by eginhard** [comment]
Duplicate of https://github.com/coqui-ai/TTS/issues/3745

**Comment by PeterTucker** [comment]
@eginhard correct.
