### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by thanhlong1997** [coqui-ai/TTS#3802]
Hi, I want to train your XTTS-v2 in distributed mode since my data is too large. How can I do that ? thank you!!!

**Comment by NikitaKononov** [comment]
> Hi, I want to train your XTTS-v2 in distributed mode since my data is too large. How can I do that ? thank you!!!

python -m trainer.distribute --script recipes/ljspeech/xtts_v2/train_gpt_xtts.py --gpus 0,1,2,3,4,5

But xtts scripts or Trainer framework is laggy and it doesn't work properly< you can check my issue

**Comment by NikitaKononov** [comment]
tried num_workers=0, >0, MP_THREADS_NUM and so on, nothing helps
lots of ram and shared memory

**Comment by JinYuanZhang999** [comment]
@thanhlong1997 May I ask if you successfully managed to use distributed training for XTTSv2 in the end?
