### ISSUE TITLE
[Bug] Training XTTSv2 with DDP leads to weird training lags

### ISSUE THREAD

**Issue by NikitaKononov** [coqui-ai/TTS#3807]
### Describe the bug

Hello, training XTTSv2 leads to weird training lags with using DDP - training gets stuck with no errors
x6 RTX a6000 and 512GB RAM

Here is monitoring GPU load graph. Purple - gpu0, green - gpu1 (all the rest GPUs behave like gpu1)

![image](https://github.com/coqui-ai/Trainer/assets/69078939/22fc5734-4ae5-4723-b171-e3f96499d7d3)

With 2 or 4 GPU situation remains the same

I think there's some kind of error in Trainer or in xtts scripts maybe
my dataset is kinda large, 2000hrs of 1 language

### To Reproduce

python -m trainer.distribute --script recipes/ljspeech/xtts_v2/train_gpt_xtts.py --gpus 0,1,2,3,4,5

### Expected behavior

training must not get stuck

### Environment

```shell
tts version: latest
```

**Comment by NikitaKononov** [comment]
tried num_workers=0, >0, MP_THREADS_NUM and so on, nothing helps
lots of ram and shared memory

**Comment by JinYuanZhang999** [comment]
@NikitaKononov May I ask if you managed to resolve this issue in the end?
