### ISSUE TITLE
Support offline mobile

### ISSUE THREAD

**Issue by boxabirds** [coqui-ai/TTS#381]
This repository is really great! Decent samples too. 

I see a huge opportunity for this to be extended to support mobile. 

There are a number of obstacles to this of course, including running on TF-Lite. 

If you ported it to Dart you could transpile it to iOS and Android.

**Comment by erogol** [comment]
Thx !  We also plan to expand :frog: TTS's use in offline and low-compute devices. 

Currently, some models we release are already real-time using simply the torch back-end. 

Targeting the mobile, we can make use of Torch Script, ONNX or TF-Lite export. So one step at a time we plan to get there. 

Actually you can already run the vanilla Tacotron on TF-Lite.  A bit of documentation is here https://github.com/coqui-ai/TTS/wiki/Converting-Torch-Tacotron-to-TF-2.0

**Comment by Dmole** [comment]
There are currently 3 FOSS TTSEs for Mobile https://search.f-droid.org/?q=tts+engine&lang=en
A coqui-ai.apk could improve that short list.
