### ISSUE TITLE
Coqui XTTS-V2 Quantization?

### ISSUE THREAD

**Issue by yukiarimo** [coqui-ai/TTS#3819]
Hello! I’ve seen LLaMA and even Whisper models quantized in GGUF/GGML. Is it possible to quantize Coqui XTTS-V2 model?

**Comment by DrewThomasson** [comment]
I think I've gotten at least pruning quantization to work for xtts

details can be found on my repo where I'm documenting my progress and trying to turn it into an easy to use tool for others lol

https://github.com/DrewThomasson/Quantize_xtts/tree/main

**Comment by shashankb-cc** [comment]
> Hello! I’ve seen LLaMA and even Whisper models quantized in GGUF/GGML. Is it possible to quantize Coqui XTTS-V2 model?

even i am looking for the same , quantized  GGUF/GGML model  of Coqui XTTS-V2.
