### ISSUE TITLE
window 11 pip install TTS,Display installation successful，But I can't quote it

### ISSUE THREAD

**Issue by hjj-lmx** [coqui-ai/TTS#3822]
### Describe the bug

![1720769949(1)](https://github.com/user-attachments/assets/c7c6b330-1566-4955-8377-5b3058ee4e09)
Dependent environment has only one folder

### To Reproduce

![1720770049(1)](https://github.com/user-attachments/assets/8fae3185-dd5a-4d6b-8770-a10ec7edcd1a)

### Environment

```shell
windows11
pip==24.1
TTS==0.22.0
```

**Comment by eginhard** [comment]
How did you install it and what error do you get?
