### ISSUE TITLE
[Bug]  Can not install the library inside Docker container

### ISSUE THREAD

**Issue by kostas2370** [coqui-ai/TTS#3844]
### Describe the bug

I have an issue on installing TTS library in my dockerfile , I add TTS in my requirements.txt , i use python 3:9 and trying to install the latest version . 

When i remove TTS the requirements are installed fine

### To Reproduce

try putting TTS in requirements.txt and pip install inside a dockerfile

### Expected behavior

it would have to download the TTS module.

### Logs

```shell
File "<string>", line 43, in <module>
662.6       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qh9b5us8/tts_c659be9d18984acca728629e9ac1c5fe/requirements.txt'
662.6       [end of output]
662.6
662.6   note: This error originates from a subprocess, and is likely not a problem with pip.
662.6 error: subprocess-exited-with-error
```

### Environment

```shell
wget https://raw.githubusercontent.com/coqui-ai/TTS/main/TTS/bin/collect_env_info.py
python collect_env_info.py
```

### Additional context

[docker_requirements.txt](https://github.com/user-attachments/files/16442924/docker_requirements.txt)
[docker-compose.txt](https://github.com/user-attachments/files/16442964/docker-compose.txt)
[Dockerfile.txt](https://github.com/user-attachments/files/16442953/Dockerfile.txt)

(dockerfile remove.txt)
docker-compose(add .yml)

**Comment by eginhard** [comment]
It complains about a missing `requirements.txt` file, but no idea why. You could try installing [our fork](https://github.com/idiap/coqui-ai-TTS) (package `coqui-tts` instead of `TTS`), which got rid of that file and is still maintained, so maybe it works.

**Comment by kostas2370** [comment]
Hello eginhard ! I used your fork for my project and it worked fine ! ( Ned to work a bit more with requirements). Thank you !
