### ISSUE TITLE
[Feature request] Upgrade to Python3.12

### ISSUE THREAD

**Issue by CorrM** [coqui-ai/TTS#3848]
Conceder upgrading to Python3.12

```
The current project's supported Python range (>=3.12,<3.13) is not compatible with some of the required packages Python requirement:
  - tts requires Python >=3.9.0, <3.12, so it will not be satisfied for Python >=3.12,<3.13

Because shortgpt depends on tts (0.22.0) which requires Python >=3.9.0, <3.12, version solving failed.
```

**Comment by Vectorrent** [comment]
Bump. Just tried to install this lib, and it fails with Python 3.12.

**Comment by eginhard** [comment]
This repo is not updated anymore. You can use [our fork](https://github.com/idiap/coqui-ai-TTS) (available via `pip install coqui-tts`), which supports Python 3.12 and has other bug fixes.

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech
