### ISSUE TITLE
Please provide german voice

### ISSUE THREAD

**Issue by davidak** [coqui-ai/TTS#385]
The quality of the english examples is already very good. What's missing to be useful for me is a model for a german voice.

You can use this issue for related discussions and documenting progress creating it.

**Comment by svenha** [comment]
Has anybody tried the German model listed on https://github.com/coqui-ai/TTS/wiki/Released-Models ?

**Comment by erogol** [comment]
If @thorstenMueller sends his models we are more than happy to include in the list and make it available with the ```tts``` end-point and server.  But I guess he uses a different text processing procedure.
