### ISSUE TITLE
[Feature request] How should I use the server API in the source code?

### ISSUE THREAD

**Issue by durantgod** [coqui-ai/TTS#3851]
My requirement is to call the API based on parameters such as timbre and source text, and then obtain the path to the converted WAV.

![1](https://github.com/user-attachments/assets/a575d0c5-5170-416a-b93a-8a368af6c374)

I followed the steps above and found the following error
ModuleNotFoundError: No module named 'TTS'

![2](https://github.com/user-attachments/assets/1b118ec2-1f9c-4bfb-ac51-0764e02b25ed)

**Comment by eginhard** [comment]
You have to install the package first.

**Comment by durantgod** [comment]
I have already done it, but it doesn't work. Is my install command incorrect?
`.\venv\Scripts\pip install -r .\requirements.txt `

But, I can run the demo I wrote myself。like this:
`python -m venv venv `

`.\venv\Scripts\pip install torch==2.2.0+cu118 torchvision==0.17.0+cu118 torchaudio==2.2.0  https://download.pytorch.org/whl/torch_stable.html`

`.\venv\Scripts\pip install -r .\requirements.txt`
 
`.\venv\Scripts\python.exe .\train.py`

**Comment by eginhard** [comment]
You only installed the requirements, you also have to install the package afterwards: `pip install -e .`

**Comment by durantgod** [comment]
It works , many thanks, bro~
