### ISSUE TITLE
[Bug] Illegal Instruction (core dump) when running on Ubuntu 22.04 LTS on Raspberry Pi 4 hardware

### ISSUE THREAD

**Issue by fury88** [coqui-ai/TTS#3857]
### Describe the bug

Following the directions in the READ.ME allows for TTS to be compiled fine but when I go to run it I get the immediate core dump. The particular board/chip in this Raspberry Pi is aarch64. I'm guessing there is an issue with that?

### To Reproduce

```pi_server:~/Projects/TTS$ tts --list_models```
Illegal instruction (core dumped)

### Expected behavior

List the models available. 

### Logs

```shell
collect_env_info.py fails also when run to collect environment
```

### Environment

```shell
TTS Version is whatever the latest is here. I cloned the repo

Linux <host> 5.15.0-1059-raspi #62-Ubuntu SMP PREEMPT Tue Jul 16 20:54:13 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

Linux version 5.15.0-1059-raspi (buildd@bos03-arm64-034) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #62-Ubuntu SMP PREEMPT Tue Jul 16 20:54:13 UTC 2024

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

description: Computer
    product: Raspberry Pi 4 Model B Rev 1.5
    width: 64 bits
    capabilities: smp cp15_barrier setend swp tagged_addr_disabled
```

**Comment by ChristianFariolen** [comment]
I've managed to run this on a raspberry pi 4B, using whisper.cpp STT and Conqui TTS as a combine service with a specially crafted bash and python scripts together :) I might have a solution for your concern but I need a more detailed error or the actual output on your terminal.
