### ISSUE TITLE
[Bug] ValueError:  [!] Model file not found in the output path

### ISSUE THREAD

**Issue by hubingkang** [coqui-ai/TTS#3968]
### Describe the bug

Previously, I ran tts --text "你好" --model_name "tts_models/zh-CN/baker/tacotron2-DDC-GST" --out_path ./audio.wav, and it started downloading the model. I interrupted the download midway. When I tried to run it again later, it indicated that tacotron2-DDC-GST was already downloaded, but it encountered an error when running. The tts --list_models command also shows it as downloaded, but in reality, the download was canceled halfway through. Now I can't re-download this model and run it.

<img width="762" alt="image" src="https://github.com/user-attachments/assets/58971169-90b9-4798-81d8-f5418e23ec10">

### To Reproduce

tts --text "你好" --model_name "tts_models/zh-CN/baker/tacotron2-DDC-GST" --out_path ./audio.wav

### Expected behavior

-

### Environment

```shell
0.22.0
```

**Comment by eginhard** [comment]
If you delete the model folder the files will be redownloaded the next time you run it.

**Comment by hubingkang** [comment]
I found the model storage path to be '/Users/XXXX/Library/Application\ Support/tts'. Deleting the specific model from this location should solve the issue.

**Comment by hubingkang** [comment]
I think some optimizations could be made for the case of interrupted downloads.
