### ISSUE TITLE
[Bug] TTS.trainer isn't working

### ISSUE THREAD

**Issue by Bowulf** [coqui-ai/TTS#3984]
### Describe the bug

TTS.trainer module is not working, it is showing that no module name TTS.trainer

### To Reproduce

from TTS.config import load_config
from TTS.trainer import Trainer

config_path = "config.json"
config = load_config(config_path)
trainer = Trainer(config=config)
trainer.fit()

### Environment

```shell
TTS version - 0.22.0
python version - 3.10.14
OS - MACBOOK M1
```

**Comment by eginhard** [comment]
The second line should just be `from trainer import Trainer`
