### ISSUE TITLE
[Feature request] singing voice synthesis

### ISSUE THREAD

**Issue by funmolde** [coqui-ai/TTS#4012]
Hello, I'd like to suggest adding a text-to-singing voice synthesis feature. 
Thank you -_-

**Comment by FrontierDK** [comment]
If I had to guess, it would take a lot of new training data to be able to do this.

If in a rush, try looking at these:

**Commercial solutions**
https://www.vocaloid.com/en
https://dreamtonics.com

**Open source solutions**
https://alternativeto.net/software/vocaloid-3/?license=opensource

**Comment by funmolde** [comment]
there already are : https://github.com/topics/singing-voice-synthesis

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech
