### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Eyobs-droid** [coqui-ai/TTS#4069]
### Describe the bug

from TTS.trainer import Trainer, TrainerArgs says, "No module named 'TTS.Trainer"

### To Reproduce

https://colab.research.google.com/drive/1n7rnrHHBPEjVhl2i1xKQ5lbu85DGPhTs#scrollTo=k-6PhSIi9o32

### Environment

```shell
TTS- 0.22.0
Pytorch- 2.5.1
OS- Linux mint cinnamon
Python- 3.10.12
```

**Comment by eginhard** [comment]
It should be: `from trainer import Trainer, TrainerArgs`
