### ISSUE TITLE
[Bug] model_path is not considered when downloading the model in TTS constructor

### ISSUE THREAD

**Issue by DanielRossi1** [coqui-ai/TTS#4084]
### Describe the bug

Coqui constructor accept a parameter named model_path. The logic within the constructor does not make sense (in my opinion) because if a model name is provided,  basically it will try to download the weight and other stuff. Later, if model_path is provided, it will try to load the model.

```
if model_name is not None and len(model_name) > 0:
    if "tts_models" in model_name:
        self.load_tts_model_by_name(model_name, gpu)
    elif "voice_conversion_models" in model_name:
        self.load_vc_model_by_name(model_name, gpu)
    else:
        self.load_model_by_name(model_name, gpu)

if model_path:
    self.load_tts_model_by_path(
        model_path, config_path, vocoder_path=vocoder_path, vocoder_config=vocoder_config_path, gpu=gpu
    )
```

In my opinion:
1) check if the model is already downloaded in the model_path provided
1.1) if model exists, then load
1.2) if model does not exists, download it and then load
In the load method you can then check the model name

the issue is that now, in the download method, the model_path provided by the user is not considered.

Additionally, I would consider to add a markdown file or a section within the readme listing all available models

### To Reproduce
```
# run the program at least twice
Coqui("voice_conversion_models/multilingual/vctk/freevc24", model_path="/home/user")
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "12.4"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.5.1+cu124",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024"
    }
}
```

**Comment by eginhard** [comment]
It's meant to be used differently, you should specify either `model_name` or `model_path`, not both.

When you run the following code the first time, it will download the model. But subsequent calls will load it from a local cache folder.
```python
from TTS.api import TTS
api = TTS("voice_conversion_models/multilingual/vctk/freevc24")
```

`model_path` is not the path where the model should be downloaded (for that see https://coqui-tts.readthedocs.io/en/latest/faq.html#where-does-coqui-store-downloaded-models), it is to load trained or fine-tuned from different locations. You don't need `model_name` in that case.

You can run `tts --list_models` to list all available models, there are too many to show in the readme.

**Comment by DanielRossi1** [comment]
okay, thanks for the clarification. 

Anyway, I am sorry but I still do not understand the reason of adopting this logic with the constructor parameters. If `model_path` is used to load trained or fine-tuned models, it should also be able to load pre-trained models. I mean model_path as the file system directory containing the model weights, because since TTS uses PyTorch these will always have the extension such as `.pt` or `.pth`, thus the model filename can be automatically retrieved. The behavior I am looking for is already implemented in the code (`os.environ["TTS_HOME"] = self.model_path`), however using an environment variable may be useful when working with multiple models, if you only intend to use one model, this approach can become an unnecessary overhead.

Since this is not the case, I would expect an assertion error to be thrown when trying to pass both `model_name` and `model_path`, but actually the code tryies to do stuff and then crashes.

**Comment by eginhard** [comment]
> If `model_path` is used to load trained or fine-tuned models, it should also be able to load pre-trained models.

Oh yes, that works fine (with the caveat that `voice_conversion_models` can only be loaded by name at the moment when using the high-level `TTS()` API):
```python
from TTS.api import TTS

# Downloads the model if necessary
xtts = TTS("tts_models/multilingual/multi-dataset/xtts_v2")

# Once it's downloaded, this also works (with the default download paths on Linux)
xtts = TTS(model_path="~/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/model.pth", config_path="~/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/config.json")
```

> I would expect an assertion error to be thrown when trying to pass both `model_name` and `model_path`, but actually the code tryies to do stuff and then crashes.

That would probably make sense, yes. I'll add that to [our fork](https://github.com/idiap/coqui-ai-TTS) (this repo is not maintained anymore).
