### ISSUE TITLE
[Feature request] Pass config values to Tensorboars

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#418]
**Is your feature request related to a problem? Please describe.**
It is hard to compare models with different configurations by just looking at Tensorboard. 

**Describe the solution you'd like**
We can pass the configuration fields to the tensorboard.

**Comment by thorstenMueller** [comment]
Nice addition @erogol . Top 👍

**Comment by thorstenMueller** [comment]
Just tried it with latest dev commit. Works like a charm. Thanks @erogol 

<img width="935" alt="Bildschirmfoto 2021-04-07 um 22 11 15" src="https://user-images.githubusercontent.com/9558265/113927918-65bfa080-97ee-11eb-946d-8252808f019e.png">
