### ISSUE TITLE
[Bug] Not able to install 

### ISSUE THREAD

**Issue by ishandutta2007** [coqui-ai/TTS#421]
```pip install TTS```

> Failed to build TTS ERROR: Could not build wheels for TTS which use PEP 517 and cannot be installed directly

Adding more details about the state of my machine. I am on Windows 10.
I am using `python 3.8.0` installed via `pyenv`. Here are my current package versions under python 3.8.0 environment:

```pip list```

> Package                Version
> ---------------------- ------------
> absl-py                0.12.0
> appdirs                1.4.4
> argon2-cffi            20.1.0
> astor                  0.8.1
> astunparse             1.6.3
> async-generator        1.10
> attrs                  20.3.0
> audioread              2.1.9
> backcall               0.2.0
> bar-chart-race         0.1.0
> black                  20.8b1
> bleach                 1.5.0
> cachetools             4.2.1
> certifi                2020.12.5
> cffi                   1.14.5
> chardet                4.0.0
> click                  7.1.2
> colorama               0.4.4
> cycler                 0.10.0
> decorator              5.0.5
> defusedxml             0.7.1
> dill                   0.3.3
> entrypoints            0.3
> flatbuffers            1.12
> gast                   0.3.3
> google-auth            1.28.0
> google-auth-oauthlib   0.4.4
> google-pasta           0.2.0
> grpcio                 1.32.0
> gTTS                   2.2.2
> h5py                   2.10.0
> html5lib               0.9999999
> idna                   2.10
> inflect                5.3.0
> ipykernel              5.5.3
> ipython                7.22.0
> ipython-genutils       0.2.0
> ipywidgets             7.6.3
> jedi                   0.18.0
> Jinja2                 2.11.3
> joblib                 1.0.1
> jsonpatch              1.32
> jsonpointer            2.1
> jsonschema             3.2.0
> jupyter                1.0.0
> jupyter-client         6.1.13
> jupyter-console        6.4.0
> jupyter-core           4.7.1
> jupyterlab-pygments    0.1.2
> jupyterlab-widgets     1.0.0
> Keras-Applications     1.0.8
> Keras-Preprocessing    1.1.2
> kiwisolver             1.3.1
> librosa                0.8.0
> llvmlite               0.36.0
> Markdown               3.3.4
> MarkupSafe             1.1.1
> matplotlib             3.3.3
> mistune                0.8.4
> multiprocess           0.70.11.1
> mypy-extensions        0.4.3
> nbclient               0.5.3
> nbconvert              6.0.7
> nbformat               5.1.3
> nest-asyncio           1.5.1
> notebook               6.3.0
> numba                  0.53.1
> numpy                  1.19.3
> oauthlib               3.1.0
> opt-einsum             3.3.0
> packaging              20.9
> pandas                 1.2.3
> pandocfilters          1.4.3
> parso                  0.8.2
> pathspec               0.8.1
> pep517                 0.10.0
> pickleshare            0.7.5
> Pillow                 8.2.0
> pip                    21.0.1
> pooch                  1.3.0
> prometheus-client      0.10.0
> prompt-toolkit         3.0.18
> protobuf               3.15.7
> pyasn1                 0.4.8
> pyasn1-modules         0.2.8
> pycparser              2.20
> Pygments               2.8.1
> pynndescent            0.5.2
> pyparsing              2.4.7
> PyQt5                  5.15.4
> PyQt5-Qt5              5.15.2
> PyQt5-sip              12.8.1
> pyrsistent             0.17.3
> python-dateutil        2.8.1
> pytz                   2021.1
> pywin32                300
> pywinpty               0.5.7
> pyzmq                  22.0.3
> qtconsole              5.0.3
> QtPy                   1.9.0
> regex                  2021.4.4
> requests               2.25.1
> requests-oauthlib      1.3.0
> resampy                0.2.2
> rsa                    4.7.2
> scikit-learn           0.24.1
> scipy                  1.6.2
> Send2Trash             1.5.0
> setuptools             54.2.0
> six                    1.15.0
> sounddevice            0.4.1
> SoundFile              0.10.3.post1
> tensorboard            1.14.0
> tensorboard-plugin-wit 1.8.0
> tensorflow             1.14.0
> tensorflow-estimator   1.14.0
> tensorflow-hub         0.11.0
> tensorflow-tensorboard 1.5.1
> termcolor              1.1.0
> terminado              0.9.4
> testpath               0.4.4
> threadpoolctl          2.1.0
> toml                   0.10.2
> torch                  1.8.1+cpu
> torchaudio             0.8.1
> torchfile              0.1.0
> torchvision            0.9.1+cpu
> tornado                6.1
> tqdm                   4.60.0
> traitlets              5.0.5
> typed-ast              1.4.2
> typing-extensions      3.7.4.3
> umap-learn             0.5.1
> Unidecode              1.2.0
> urllib3                1.26.4
> visdom                 0.1.8.9
> wcwidth                0.2.5
> webencodings           0.5.1
> websocket-client       0.58.0
> Werkzeug               1.0.1
> wheel                  0.36.2
> widgetsnbextension     3.5.1
> wrapt                  1.12.1

**Comment by erogol** [comment]
windows is not officially supported. But @GuyPaddock might help you with that.

**Comment by erogol** [comment]
BTW previously I was able to install using Conda.

**Comment by GuyPaddock** [comment]
I've actually not had any issues installing wheels on Windows 10, neither in WSL nor directly on Windows itself.

**Comment by erogol** [comment]
This also might help. If not feel free to reopen

https://github.com/pydata/bottleneck/issues/281#issuecomment-560030902

**Comment by IMJONEZZ** [comment]
In contrast, I have had only errors installing wheels on Windows 10, both in WSL and directly on Windows itself. Python 3.6, 3.8, and 3.10.

**Comment by ipdan4ik** [comment]
> In contrast, I have had only errors installing wheels on Windows 10, both in WSL and directly on Windows itself. Python 3.6, 3.8, and 3.10.

I am also on WSL and this was fixed for me by installing wheel and python3-dev packages.
`pip install --upgrade pip setuptools wheel python3-dev`
