### ISSUE TITLE
[Bug] Trainning using --restore_path fails with param 'initial_lr' not specified message.

### ISSUE THREAD

**Issue by freds0** [coqui-ai/TTS#425]
**Describe the bug**
Trainning using --restore_path fails with param 'initial_lr' not specified message.

**To Reproduce**
1. python TTS/bin/train_tacotron.py --config_path config.json  --restore_path best_model.pth.tar 
3. See error: 
  File "TTS/bin/train_tacotron.py", line 664, in <module>
    main(args)
  File "TTS/bin/train_tacotron.py", line 580, in main
    scheduler = NoamLR(optimizer,
  File "/root/TTS/TTS/utils/training.py", line 94, in __init__
    super(NoamLR, self).__init__(optimizer, last_epoch)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 39, in __init__
    raise KeyError("param 'initial_lr' is not specified "
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu Docker 18.04.4 LTS
- **PyTorch or TensorFlow version (use command below)**: torch=1.8.1+cu111
- **Python version**: 3.8.3
- **CUDA/cuDNN version**: 11
- **GPU model and memory**: V100

**Comment by erogol** [comment]
can you also post your config file ?

**Comment by freds0** [comment]
We trained the model using the same config, and now I want to do transfer learning to another speaker.

Here is my config:

https://file.io/klUZA2VuO0DS

**Comment by erogol** [comment]
file is deleted

**Comment by freds0** [comment]
Sorry! Try here:

https://drive.google.com/file/d/1DDnhtWWnPjTlw4w2SNecAoTWqt8yQ_kt/view?usp=sharing

**Comment by freds0** [comment]
Solved! It's only set noam_schedule=false.

**Comment by erogol** [comment]
Happy that you solved the problem but it is actually a bug that needs to be fixed. So I reopen it.
