### ISSUE TITLE
Google Lyra as the vocoder

### ISSUE THREAD

**Issue by NTT123** [coqui-ai/TTS#426]
Google open source lyra (https://github.com/google/lyra), a version of waveRNN vocoder recently, I wonder if any of you think of using this Lyra version as the vocoder for TTS.

The benefit of this approach is that we have a well-engineered real-time vocoder on mobile devices (and hopefully, a high quality vocoder).

The unknown here is that, we don't know if Lyra is fitted for TTS. From reading google's papers, they use quantized 160-dimension mel-spectrogram as the the conditional features with only one frame look ahead.

The source code of this real-time wavegru vocoder can be really helpful anyway!

**Comment by erogol** [comment]
Thanks for the pointer but I think it'd be hard to use it under TTS. However, we already have WaveRNN implemented under TTS. Maybe at some point, we can export the weights to use it with Lyra. But I don't know how feasible it is.

**Comment by NTT123** [comment]
Thanks for your comments, I'll close this issue for now.
