### ISSUE TITLE
[Bug] fix windows support (audio lambda function)

### ISSUE THREAD

**Issue by WeberJulian** [coqui-ai/TTS#439]
I think we've established that windows support is broken since that commit https://github.com/coqui-ai/TTS/commit/e0b3008c3156c6dd9fd69449be9f215d71a00af9 .
I suspect that it's due to the exp/log function stored in the class.
I would suggest to replace the log_func in the constructor by a `exp_log_base`, and only store that number in the class. Then I propose using `math.log(x, exp_log_base)` and `exp_log_base**x` since np.log doesn't allow to pass a base argument. But if we need np because of speed, we can define a function:

``` python
def np_log_base(x, base):
    return np.log(x) / np.log(base)
```

would that fix be ok ?

**Comment by erogol** [comment]
is it possible to verity that the problem is about that commit before we make any change? 

BTW this code is 3 times slower than just calling np.log.

```python
In [3]: %timeit np_log_base(9999, 10)
3.26 µs ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit np.log10(9999)
1.45 µs ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by WeberJulian** [comment]
Of course, I'm gonna run the tests and try on windows before doing a PR

For performance, I think it's a non issue. You could very well do this, you keep performance, windows compatibility and you can have new bases without changing the code:

``` python
def np_log_base(x, base):
    if base == 10:
        return np.log(x)
    if base == math.e: # I'm not sure how to do this cleanly 
        return np.log10(x)
    return np.log(x) / np.log(base)
```

**Comment by erogol** [comment]
maybe just call log if not base is specified since it is hard to define ```e``` as the base. 
 
Let's just use the one you have right now and verify if it fixes the issue on Windows.
