### ISSUE TITLE
[Feature request] add stopnet delay argument to synthesis function (tacotron)

### ISSUE THREAD

**Issue by WeberJulian** [coqui-ai/TTS#440]
Sometimes synthesis for some sentences are cut short at the last word. I know (think) that it's indicative that something is amiss in the model or the dataset, either not trained long enough, audio parameters could be tuned further (trim_db ?) or just dataset quality. But taking time to fix that issue, debugging and training many models is a luxury that some people can't afford (maybe even more if it's a low ressource language).

I would gladly do a PR to propose the feature but I'm not sure how to go about the implementation.
Would adding a stopnet delay (delaying from n steps the stop signal) solve this issue ?

**Comment by erogol** [comment]
do you think it would solve the problem for all the occurrences? 

Then you might need to tune that delay per sample. 

In general, there are two tricks I also use:

1. stopnet delay. Maybe delay longer than it needs and trim the silence. 
2. Don't use stopnet but look at the attention map and signal `stop` when the attention reaches the last token.

**Comment by WeberJulian** [comment]
> Then you might need to tune that delay per sample.

I was thinking that in the worst scenario it would add half a second of silence at the end of the sample (but I never actually tried)

> Don't use stopnet but look at the attention map and signal stop when the attention reaches the last token.

That approach sounds interesting, is it implemented yet ?

**Comment by erogol** [comment]
> That approach sounds interesting, is it implemented yet?

implemented once a long ago but don't know now where :)

**Comment by WeberJulian** [comment]
> implemented once a long ago but don't know now where :)

Haha ok, I'm gonna look for it and try both approaches
