### ISSUE TITLE
[Feature request] Unlimited Decoder Steps

### ISSUE THREAD

**Issue by MohamedAliRashad** [coqui-ai/TTS#472]
We need a TTS with unlimited decoding steps for parsing long texts, Is it possible?

**Comment by thorstenMueller** [comment]
If you need a higher max_decoder_step for your situation you can increase value here in tacotron2.py:
https://github.com/coqui-ai/TTS/blob/b00b1d46808649032cd5b96381ec2f9f3b7024a9/TTS/tts/layers/tacotron/tacotron2.py#L165

Don't forget to run `python3 ./setup.py install` afterwards.

**Comment by erogol** [comment]
unlimited by default would break systems with OOM. So it is better to do what is suggested above.
