### ISSUE TITLE
[Bug] KeyError: 'default_vocoder' for all hifigan_v2 models

### ISSUE THREAD

**Issue by krisgesling** [coqui-ai/TTS#473]
**Describe the bug**
Running any of the HiFiGAN models fails with a KeyError for the default_vocoder.

**To Reproduce**
1. Install from PyPI (or dev branch using pip)
2. Run `tts-server --list_models | grep hifigan` to get the list of HiFiGAN models
3. Attempt to run any eg `tts-server --use_cuda=true --model_name vocoder_models/en/sam/hifigan_v2`
4. See error:
```
Traceback (most recent call last):
  File "/home/gez/Projects/coqui-tts/.venv/bin/tts-server", line 6, in <module>
    from TTS.server.server import main
  File "/home/gez/Projects/coqui-tts/.venv/lib/python3.8/site-packages/TTS/server/server.py", line 86, in <module>
    args.vocoder_name = model_item["default_vocoder"] if args.vocoder_name is None else args.vocoder_name
KeyError: 'default_vocoder'
```

**Expected behavior**
Presumably `model_item` should always have a `default_vocoder`, or it should be checked and handled gracefully.

**Environment (please complete the following information):**
- **Python version**: 3.8.3

**Comment by krisgesling** [comment]
Just realised these are the vocoder models, not the TTS models. 

So perhaps this ticket should instead be something like:
"inform user if they attempt to use the wrong type of model :smile: "

Closing this as it's not a bug.

**Comment by erogol** [comment]
The config management is quite loose right now. But working on a better solution. Sorry for the hardship until then.
