### ISSUE TITLE
[Feature request] Use warning for Python 3.9

### ISSUE THREAD

**Issue by Ivan-Kouznetsov** [coqui-ai/TTS#486]
Currently it is not possible to install this package for use with Python 3.9, unless there are specific breaking changes in Python 3.9 which the team knows will prevent the use of this package, you should consider replacing the version check with a warning indicating to the user that the package is not tested under Python 3.9.

Blocking the installation of this package under the current version of Python simply out of an abundance of caution may needlessly restrict access to it for users that cannot use pyenv (which does not work with the latest version of gcc for example) and precludes people volunteering to test this package under Python 3.9.

**Comment by avaer** [comment]
Which are the python versions that work? I've been playing version darts trying to get a build and I couldn't figure out what is a legitimate error and what should work.

**Comment by Ivan-Kouznetsov** [comment]
@avaer 
> TTS is tested on Ubuntu 18.04 with python >= 3.6, < 3.9.

**Comment by X-m7** [comment]
Should this be merged with #570, since both are about Python 3.9 support?

**Comment by erogol** [comment]
3.9 will be there once the trainer API is merged. You can start using that branch,

**Comment by erogol** [comment]
I close this one and follow #570
