### ISSUE TITLE
[Feature request] Problem running example on jupyter notebook 

### ISSUE THREAD

**Issue by Doctorspeppers** [coqui-ai/TTS#507]
Hi, I was testing some examples on the site and noticed that the example "English - LJSpeech - Tacotron2 with Dynamic Convolutional Attention and Universal Fullband-MelGAN" has a permission failure in the "config_vocoder.json" file.

1. Run the notebook located in [Here](https://colab.research.google.com/drive/1uV2CD1hWx5FGUrcIQjdZfI717AMj8-kP?usp=sharing)

**Comment by erogol** [comment]
don't use the notebooks and try using the `tts` or `tts-server` for running models. Notebooks are soon to be deprecated.
