### ISSUE TITLE
[Bug] Cannot synthesize audio from text

### ISSUE THREAD

**Issue by tranquangchung** [coqui-ai/TTS#509]
We install your project based on your guide
1. git clone https://github.com/coqui-ai/TTS
2. pip install -e .[all]

Then we run the following command:
` tts --text "Text for TTS"    --model_name tts_models/en/ljspeech/tacotron2-DDC     --out_path wav_output/output.wav `

However, we receive **a error** as below
`assert os.path.exists(c[name]), f' [!] path for {name} ("{c[name]}") does not exist.'`
![image](https://user-images.githubusercontent.com/19748790/119767431-fb1f0d00-bee0-11eb-858d-1f31a83999c4.png)

Please tell me how to solve this problem, thank you.

**Another  the question**, In file "https://github.com/coqui-ai/TTS/blob/main/TTS/tts/configs/shared_configs.py#L83"
I don't understand why you pass "**characters**" in the check_argument function
![image](https://user-images.githubusercontent.com/19748790/119767344-d7f45d80-bee0-11eb-8363-0f3ca0891913.png)

**Comment by erogol** [comment]
Try removing the downloaded models, then  `pip install -U coqpit` and try again?

it checks if the right set of characters are defined in the model config. Each model must have its target characters defined in the config.

**Comment by tranquangchung** [comment]
I have just removed the downloaded models, however I still got this error.

**Comment by erogol** [comment]
it's a bug. I am on it.

**Comment by erogol** [comment]
can you try now ?

**Comment by SamuelBroughton** [comment]
I had the error and just tested your update, works for me thanks!

**Comment by SamuelBroughton** [comment]
Although I thought I would just note, I was using the multispeaker vctk ddc tacotron2 model which i believe has been trained using phonemes, which hits the value error:    

```python
raise ValueError(f" [!] Language {language} is not supported for phonemization.")
```

Here it looks like only zh-CN language is being accepted:

https://github.com/coqui-ai/TTS/blob/5482a0f62d3da9821b4689f4e9268580904a081f/TTS/tts/utils/text/__init__.py#L28

I have the synthesis working swapping out for the old `text2phone` function in the mozilla project: 

https://github.com/mozilla/TTS/blob/e9e07844b77a43fb0864354791fb4cf72ffded11/TTS/tts/utils/text/__init__.py#L28

**Comment by erogol** [comment]
> v0.0.14 does not support phonemes
