### ISSUE TITLE
[Bug] `CalledProcessError` thrown in `CheckDatasetSNR`

### ISSUE THREAD

**Issue by david-eom** [coqui-ai/TTS#525]
**Description of the Bug**
When running `CheckDatasetSNR.ipynb` under `dataset_analysis` directory, `CalledProcessError` was thrown in cell 4.
Please kindly refer to #516 for the original issue. Apologies for the replication.

**To Reproduce**
1. Open the `CheckDatasetSNR` notebook file
2. Change `DATA_PATH` in cell 2 to correct path
3. Run the first 4 cells, in cell 4 line 2 `output = compute_file_snr(wav_file)`, error is thrown (see below)

**Expected Behaviour**
Error message is thrown:
```
CalledProcessErrorTraceback (most recent call last)
<ipython-input-4-a0b9d37794db> in <module>
      1 wav_file = "TTS/tts/datasets/LJSpeech-1.1/wavs/LJ001-0001.wav"
----> 2 output = compute_file_snr(wav_file)

<ipython-input-3-c1fb739bfc8e> in compute_file_snr(file_path)
      9     os.system(command)
     10     command = [f'"{CURRENT_PATH}/WadaSNR/Exe/WADASNR"', f'-i "{new_file}"', f'-t "{CURRENT_PATH}/WadaSNR/Exe/Alpha0.400000.txt"', '-ifmt mswav']
---> 11     output = subprocess.check_output(" ".join(command), shell=True)
     12     try:
     13         output = float(output.split()[-3].decode("utf-8"))

/usr/lib/python3.8/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    409         kwargs['input'] = '' if kwargs.get('universal_newlines', False) else b''
    410 
--> 411     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    412                **kwargs).stdout
    413 

/usr/lib/python3.8/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    510         retcode = process.poll()
    511         if check and retcode:
--> 512             raise CalledProcessError(retcode, process.args,
    513                                      output=stdout, stderr=stderr)
    514     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '"/home/david_yan/mozilla_tts/Mozilla_TTS/WadaSNR/Exe/WADASNR" -i "TTS/tts/datasets/LJSpeech-1.1/wavs/LJ001-0001_tmp.wav" -t "/home/david_yan/mozilla_tts/Mozilla_TTS/WadaSNR/Exe/Alpha0.400000.txt" -ifmt mswav' returned non-zero exit status 139.
```
Upon running the command `"/home/david_yan/mozilla_tts/Mozilla_TTS/WadaSNR/Exe/WADASNR" -i "TTS/tts/datasets/LJSpeech-1.1/wavs/LJ001-0001_tmp.wav" -t "/home/david_yan/mozilla_tts/Mozilla_TTS/WadaSNR/Exe/Alpha0.400000.txt" -ifmt mswav` in shell, another error message was thrown:
```
INFO: ../Source/Config.cpp(76): Logfile will not be used.Segmentation fault (core dumped)
```

**Environment**
- **OS Platform and Distribution**: Linux Ubuntu 20.04.2
- **PyTorch or TensorFlow version**: PyTorch 1.8.1, TensorFlow 2.3.1
- **Python version**: Python 3.8.5

**Comment by skol101** [comment]
Same here. For me WadaSNR didn't compile after running make on Macos.

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by robinhad** [comment]
@skol101, In case you are still looking for solution, WadaSNR is a 32 bit executable, so you need to install support for 32bit architecture.
On Ubuntu:
`sudo apt-get install lib32stdc++6`
After that run WADASNR from archive.

**Comment by skol101** [comment]
> @skol101, In case you are still looking for solution, WadaSNR is a 32 bit executable, so you need to install support for 32bit architecture.
> On Ubuntu:
> `sudo apt-get install lib32stdc++6`
> After that run WADASNR from archive.

Cheers, though that was macOs Intel x86 . Now I've got ubuntu and mac arm. The way I 'fixed' it was to substitue WadaSNR executive with local python function that I found in a gist here on github.
