### ISSUE TITLE
[Bug] RuntimeError:  [!] Use 🐸TTS <= v0.0.13 for this model. Current version does not support phoneme based models.

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#528]
When I am running the command I get the error give below
`tts --text "This is a test message written using text to speech" --model_name "tts_models/en/ljspeech/glow-tts"  --out_path wav/glow-tts.wav`

```
RuntimeError:  [!] Use 🐸TTS <= v0.0.13 for this model. Current version does not support phoneme based models.
```

**To Reproduce**
After installation as given in the readme
1. Run the following command `tts --text "This is a test message written using text to speech" --model_name "tts_models/en/ljspeech/glow-tts"  --out_path wav/glow-tts.wav`

3. See error

**Expected behavior**
A wav output file should be generated

**Environment (please complete the following information):**
- Linux Ubuntu 18.04
- TensorFlow 2.3.1:
- Python version 3.6

**Comment by SanjaESC** [comment]
For the model you want to use, you need TTS with version 0.0.13 or lower, as the error message states.

Try this `python -m pip install TTS==0.0.13.2`

Tested it myself and it works fine.

**Comment by zubairahmed-ai** [comment]
Thanks. I installed it and will be trying it
Did you try training any of these models @SanjaESC ?
