### ISSUE TITLE
[Bug] hidden_channels=c["hidden_channels"], KeyError: 'hidden_channels'

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#533]
**Describe the bug**
When I am trying to train `speedy_speech` on LJSpeech dataset like this `~/work/TTS-0.0.13$ CUDA_VISIBLE_DEVICES="0" python TTS/bin/train_speedy_speech.py --config_path config.json | tee training.log` I get the following error

```
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "TTS/bin/train_speedy_speech.py", line 570, in <module>
    main(args)
  File "TTS/bin/train_speedy_speech.py", line 481, in main
    model = setup_model(num_chars, num_speakers, c, speaker_embedding_dim=speaker_embedding_dim)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/utils/generic_utils.py", line 140, in setup_model
    hidden_channels=c["hidden_channels"],
KeyError: 'hidden_channels'
 > Using CUDA:  True
 > Number of GPUs:  1
   >  Mixed precision mode is ON
 > Git Hash: 0000000
 > Experiment folder: /home/ubuntu/work/TTS-0.0.13/output/ljspeech-speedy-speech-June-04-2021_10+42AM-0000000
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /home/ubuntu/work/TTS-0.0.13/LJSpeech-1.1
 > Using model: speedy_speech
 ! Run is removed from /home/ubuntu/work/TTS-0.0.13/output/ljspeech-speedy-speech-June-04-2021_10+42AM-0000000

```

**To Reproduce**
1. Run the following command `CUDA_VISIBLE_DEVICES="0" python TTS/bin/train_speedy_speech.py --config_path config.json | tee training.log`

**Expected behavior**
Must start training

**Environment (please complete the following information):**
- **Ubuntu 18.04**:
- **TensorFlow**:
- **Python 3.6**:

**Comment by zubairahmed-ai** [comment]
[training.log](https://github.com/coqui-ai/TTS/files/6597917/training.log)

[config.json.txt](https://github.com/coqui-ai/TTS/files/6597918/config.json.txt)

Here's the `training.log` and `config.json`

**Comment by SanjaESC** [comment]
Your config seems like its for tacotron, which doesn't have the parameter `hidden_channels`.
See error message `KeyError: 'hidden_channels'`
 
There should also be an example config for speedyspeech.

**Comment by zubairahmed-ai** [comment]
It is for tacotron, where to find the example config for speedy speech?

**Comment by zubairahmed-ai** [comment]
Found the config. trying now

**Comment by zubairahmed-ai** [comment]
What to set for the `external_speaker_embedding_file: /home/ubuntu/work/TTS-0.0.13/Data/libritts/speakers.json` in config?
I dont have a `speakers.json` but there is a `dummy_speakers.json` under `tests\data`

**Comment by zubairahmed-ai** [comment]
deleted my earlier comment
I am getting the missing wav file error, I downloaded the dataset and there are over 13k files in it but not this one

```
Traceback (most recent call last):
  File "TTS/bin/train_speedy_speech.py", line 570, in <module>
    main(args)
  File "TTS/bin/train_speedy_speech.py", line 469, in main
    meta_data_train, meta_data_eval = load_meta_data(c.datasets, eval_split=True)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/datasets/preprocess.py", line 43, in load_meta_data
    attn_file = meta_data[ins[1]].strip()
KeyError: 'LJSpeech-1.1/wavs/LJ023-0005.wav'
 > Using CUDA:  True
 > Number of GPUs:  1
 > Git Hash: 0000000
 > Experiment folder: /home/ubuntu/work/TTS-0.0.13/output/speedy-speech-ljspeech-June-04-2021_02+15PM-0000000
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /home/ubuntu/work/TTS-0.0.13/LJSpeech-1.1
 ! Run is removed from /home/ubuntu/work/TTS-0.0.13/output/speedy-speech-ljspeech-June-04-2021_02+15PM-0000000

```

**Comment by zubairahmed-ai** [comment]
Note that it prompted for a path of `metadata_attn_mask.txt` so I gave it to `tests/data/ljspeech/metadata_attn_mask.txt` which I suppose is wrong so not sure what to put there?

**Comment by SanjaESC** [comment]
Sorry I haven't trained speedy speech myself, so not quite sure what is needed here. 

But from my understanding, you can compute the attention mask with this script here:
https://github.com/coqui-ai/TTS/blob/main/TTS/bin/compute_attention_masks.py

But this will require a functional tacotron model first I guess?
