### ISSUE TITLE
Server not work[Bug] 

### ISSUE THREAD

**Issue by tranquangchung** [coqui-ai/TTS#554]
I have just trained SC-GlowTTS. However, when I run the server with a custom models, server not respond. It only prints the following logs "Loading speakers ..."
![image](https://user-images.githubusercontent.com/19748790/121116930-84b7ce80-c841-11eb-8001-78c63d9bcc79.png)

**Comment by tranquangchung** [comment]
How to make speakers.json with the following content 
![image](https://user-images.githubusercontent.com/19748790/121120516-e8dd9100-c847-11eb-8629-bdeeb4098377.png)

**Comment by erogol** [comment]
you need to use `TTS/bin/compute_embeddings.py` with a functional speaker encoder.

And please use the issue template for us to help.
