### ISSUE TITLE
[Feature request] Supporting The Latest Version Of Python.

### ISSUE THREAD

**Issue by Karim-Fadi** [coqui-ai/TTS#570]
Hi, i want state of the art Text To Speech solution for a project, and i wanted it to be human like, high quality, etc... And after some research, it was obvious to me that Coqui was the best "free" option. But i have a problem with that, i am on Arch Linux, and as you know, Arch is a rolling release distro, so i have the latest version for everything including python. So i can't fallback to an older version. So what happens is that when i try to install via pip, i simply get an error:
 ```
ERROR: Could not find a version that satisfies the requirement TTS
ERROR: No matching distribution found for TTS 
```
So one thing i considered of course is virtual environments, but the project is really big and everything already works perfect without a virtual environment, so i really don't want to make a virtual environment just for one thing. But for now i will just use it as a workaround.

So my feature request is really simple: Just Supporting the Latest version of Python. Also Python 3.9 is not that new or alpha anyway. It has been around for quite a while now. Also in the Docs, you say you tested it on Ubuntu 18.04 which is really weird to me. Ubuntu 20.04 is released for over a year now (14 months). So i would be really grateful if you supported the latest version of Python.

Thanks.

**Comment by serg06** [comment]
Looks like this was completed in #602 (release v0.1.0)

> Enable support for Python 3.9

**Comment by erogol** [comment]
Python 3.9 sup is there with v0.1.0... closing this
