### ISSUE TITLE
`do_trim_silence` must be forced false in `extract_tts_spectrograms.py` [Bug] 

### ISSUE THREAD

**Issue by a-froghyar** [coqui-ai/TTS#571]
**Describe the bug**
We're forcing `do_trim_silence` to `False` in the notebook but not in the script and it's a very important setting.

In the notebook:

```
C = load_config(CONFIG_PATH)
C.audio['do_trim_silence'] = False  # IMPORTANT!!!!!!!!!!!!!!! disable to align mel 
```

**To Reproduce**
Run `python extract_tts_spectrograms.py` with a config where `do_trim_silence=True`

**Comment by erogol** [comment]
Nice catch! :)
