### ISSUE TITLE
[Bug] ParameterError: Audio buffer is not finite everywhere when running CheckSpectogram.ipynb

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#573]
When I am trying the first step to run the CheckSpectogram.ipynb as given [here](https://github.com/coqui-ai/TTS/wiki/FAQ#how-can-i-train-my-own-model) it fails with the below error

![image](https://user-images.githubusercontent.com/1317442/121899176-9adff600-cd3d-11eb-96d1-de4ef7459103.png)

Independently when I am running the below code I am getting `True` output

```
import scipy.io.wavfile as sc, numpy as np, librosa as lb
sample_rate, X = sc.read(r'TTS-0.0.13\dataset\wav48\p001\p001_096.wav')
print(np.isfinite(X).all())
filepath = r'TTS-0.0.13\dataset\wav48\p001\p001_096.wav'
y_mono, sr = lb.load(filepath, mono=True)
y_stereo, sr = lb.load(filepath, mono=False)

print(lb.util.valid_audio(y_mono), lb.util.valid_audio(y_stereo))
```

```
True True
```

1. Run [this notebook ](https://github.com/coqui-ai/TTS/blob/master/notebooks/dataset_analysis/CheckSpectrograms.ipynb)

**Expected behavior**
I should get a valid output

**Environment (please complete the following information):**
- **Linux Ubuntu 18.04**:
- **Python 3.6**:

**Comment by erogol** [comment]
Can you put a colab notebook with all the configs and wav files to replicate the error?

**Comment by zubairahmed-ai** [comment]
Thanks @erogol I proceeded training for now by commenting this line in librosa utils.py

**Comment by zubairahmed-ai** [comment]
But I will put it on Colab and share

**Comment by zubairahmed-ai** [comment]
closing this for now because I commented that line to kill this weird error
