### ISSUE TITLE
[Bug] size mismatch for emb.weight: copying a param with shape torch.Size([130, 256]) from checkpoint, the shape in current model is torch.Size([182, 256])

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#593]
Hi
I am trying to run `synthesize.py` on [my trained model](https://github.com/coqui-ai/TTS/discussions/580) but when I am loading my model I get the following error, [that's also reported here](https://github.com/coqui-ai/TTS/issues/382) but the suggested fix didn't work for me in 0.0.15.1 nor 0.0.13 versions

```
RuntimeError: Error(s) in loading state_dict for AlignTTS:
        size mismatch for emb.weight: copying a param with shape torch.Size([130, 256]) from checkpoint, the shape in current model is torch.Size([182, 256]).
```
**To Reproduce**

1. Run the following command 
```
python synthesize.py --text "Hi, this is me trying to test my voice and I am checking if longer text is supported" --model_path ../../output/best_model.pth.tar --config_path ../../output/config.json --out_path ../../output/speech.wav
```
2. See error

![image](https://user-images.githubusercontent.com/1317442/123209036-7cb28c80-d4d9-11eb-9166-0f4334f0172f.png)

**Environment (please complete the following information):**
- **Windows 10**:
- **PyTorch**:
- **Python 3.6**:

**Comment by erogol** [comment]
your config.json ?

**Comment by zubairahmed-ai** [comment]
Oh yes, here it is
[config_json.txt](https://github.com/coqui-ai/TTS/files/6707957/config_json.txt)

**Comment by lexkoro** [comment]
> Oh yes, here it is
> [config_json.txt](https://github.com/coqui-ai/TTS/files/6707957/config_json.txt)

Is this the config you trained the model with?

**Comment by zubairahmed-ai** [comment]
> > Oh yes, here it is
> > [config_json.txt](https://github.com/coqui-ai/TTS/files/6707957/config_json.txt)
> 
> Is this the config you trained the model with?

No, its from the output folder but it must be the same right?
My AWS instance isn't starting due to insufficient capacity as soon as it does I will send it

**Comment by lexkoro** [comment]
But you trained with use_phonemes: true??

**Comment by zubairahmed-ai** [comment]
Yes I did

**Comment by lexkoro** [comment]
If you train with `use_phonemes: true` then you can't switch it to false when synthesizing

**Comment by zubairahmed-ai** [comment]
I trained my model with 0.0.13 and if I set `use_phonemes:true` when synthesizing I got another error

`ValueError:  [!] Language en-us is not supported for phonemization.`

![image](https://user-images.githubusercontent.com/1317442/123240175-84822900-d4f9-11eb-97b5-88bcd281934f.png)

**Comment by lexkoro** [comment]
And why are you not using 0.0.13 for synthesizing?

**Comment by zubairahmed-ai** [comment]
I was, same error then I decided to try 0.0.15 basically no change in the error

**Comment by lexkoro** [comment]
The language or size mismatch error?

**Comment by zubairahmed-ai** [comment]
both

**Comment by zubairahmed-ai** [comment]
> You shouldn't get the language error with 0.0.13.

That's the first error I got, not sure what's causing this, train and tried with this same version, any ideas?

**Comment by lexkoro** [comment]
Try a clean env with 0.0.13

**Comment by zubairahmed-ai** [comment]
@lexkoro Here's my config file [aligntts_transformers.json](https://github.com/coqui-ai/TTS/files/6719410/aligntts_transformers_2.txt)
