### ISSUE TITLE
Training stuck using new trainer API

### ISSUE THREAD

**Issue by loganhart420** [coqui-ai/TTS#610]
If you've found a bug, please provide the following information:

**Describe the bug**
I just locally installed the new 0.1.0 version of coqui-tts and I was trying to run one of the training recipes to see if I set up everything correctly. When I start the script it seems to hang/get stuck on the model loading. Completely new to the whole Trainer API so any help on trying to fix this would be great.

to reproduce this all I ran was 
python train_hifigan.py

I'm using python 3.8
and followed the steps in the docs to install locally

Here is where the script seems to get stuck 

 > Git Hash: c25a2184
 > Experiment folder: /home/logan/...t/TTS/recipes/ljspeech/hifigan/-July-03-2021_10+45PM-c25a2184
 > Using CUDA:  True
 > Number of GPUs:  2
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Using model: hifigan
 > Vocoder Model: hifigan
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator

**Comment by erogol** [comment]
You need to define the GPU you want to use by CUDA_VISIBLE_DEVICES and if you want to use two gpus, you need to run TTS/bin/distribute.py

Docs can help tts.readthedocs.io
