### ISSUE TITLE
[Bug] requirements.txt missing in the 0.1.0 distribution

### ISSUE THREAD

**Issue by gizmo84** [coqui-ai/TTS#614]
**Describe the bug**
I'm unable to install TTS 0.1.0 as requirements.txt is missing in the 0.1.0 distribution

**To Reproduce**
1. Run the following command 'pip install tts'
2. FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-9bbidghs/tts/requirements.txt'
3. TTS-0.1.0.tar.gz on PyPi is missing requirements.txt

**Expected behavior**
Be able to install TTS 0.1.0

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker Python 3.8 / Debian 10
- **PyTorch or TensorFlow version (use command below)**: N/A
- **Python version**: 3.8
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: pip install tts

**Comment by erogol** [comment]
fixed in v0.1.1.

**Comment by gizmo84** [comment]
Thanks you! Do you know wen v0.1.1 will be released?

**Comment by erogol** [comment]
already released
