### ISSUE TITLE
[Bug] requirements.txt Missing From Pip Install

### ISSUE THREAD

**Issue by ZingBlue** [coqui-ai/TTS#615]
**Describe the bug**
When installing TTS 0.1.0 via Pip, you will encounter an error refers to a missing requirements.txt file. Installing the requirements manually does not solve the issue, as pip will still fail to find a missing file.

**To Reproduce**
1. Open your CLI, type `pip install tts`
2. TTS will start downloading but fail to install.
3. See error: `FileNotFoundError: [Errno 2] No such file or directory: (a directory to a missing requirements.txt file)`

**Expected behavior**
Pip should install TTS successfully.

**Environment:**
- **Windows 10**:
- **Tensorflow 2.5.0**:
- **Python 3.9**:
- **GTX 1070**:

**Comment by serg06** [comment]
Fixed in #611 I think, new version just needs to be pushed to pypi.

**Comment by erogol** [comment]
I forgot to release the version. Now it should be there.
