### ISSUE TITLE
[Bug] Baker changed their ProsodyLabeling rule

### ISSUE THREAD

**Issue by Aloento** [coqui-ai/TTS#623]
The current Coqui Baker formatter is no longer suitable for the new version of the Baker dataset.
The newer ProsodyLabeling seems like

```
000001	卡尔普#2陪外孙#1玩滑梯#4。
	ka2 er2 pu3 pei2 wai4 sun1 wan2 hua2 ti1
000002	假语村言#2别再#1拥抱我#4。
	jia2 yu3 cun1 yan2 bie2 zai4 yong1 bao4 wo3
000003	宝马#1配挂#1跛骡鞍#3，貂蝉#1怨枕#2董翁榻#4。
	bao2 ma3 pei4 gua4 bo3 luo2 an1 diao1 chan2 yuan4 zhen3 dong3 weng1 ta4
000004	邓小平#2与#1撒切尔#2会晤#4。
	deng4 xiao3 ping2 yu3 sa4 qie4 er3 hui4 wu4
000005	老虎#1幼崽#2与#1宠物犬#1玩耍#4。
	lao2 hu3 you4 zai3 yu2 chong3 wu4 quan3 wan2 shua3
```

`000001` map to ` 000001.wav`
`#1 #2 `is Prosody
`卡尔普#2陪外孙#1玩滑梯#4。` is a Chinese sentence.
`ka2 er2 pu3 pei2 wai4 sun1 wan2 hua2 ti1` is Pinyin with the tune (number) for this Chinese sentence.

**Comment by erogol** [comment]
I leave this issue to someone who works on this dataset until I've some time for it

**Comment by Aloento** [comment]
It's my first time to write Python and I think it should works, please review it:
```
def baker(root_path: str, meta_file: str) -> List[List[str]]:
    """Normalizes the Baker meta data file to TTS format

    Args:
        root_path (str): path to the baker dataset
        meta_file (str): name of the meta dataset containing names of wav to select and the transcript of the sentence
    Returns:
        List[List[str]]: List of (text, wav_path, speaker_name) associated with each sentences
    """
    txt_file = os.path.join(root_path, meta_file)
    items = []
    speaker_name = "baker"
    with open(txt_file, "r") as ttf:
        i = 1
        texts = []
        for line in ttf:
            if (i % 2 == 0):
                text = line.strip()
                items.append([text, texts[1], speaker_name])
                texts.clear()
            else:
                texts.append(line.split("	")[0])
                texts.append(os.path.join(root_path, "Wave", texts[0] + ".wav"))
            i += 1
            
    return items
```

**Comment by Aloento** [comment]
If you use Pinyin (like my code above), you should not use `chinese_mandarin_cleaners `and `replace_numbers_to_characters_in_text`.

**Comment by erogol** [comment]
Can you send a PR, if you are interested ?

**Comment by Aloento** [comment]
>  #1234“”、。一万丈三上下不与业东丝两中串为主之乌九也买乱乳了二于云五亚亦产亨亩亲人亿仑他代以仿伊会伟传位低住体余你供侧保信修候假做健儿元兄光入全公兰共关养内再军冠冲几凯出刁分切列别到刺前劈努勇勾勿北千华卓单卖南博卡卧卫卯印即却厂压原去县又及友反发受叟口另叮可台右吃合后吕君否吴吻员呢周味命和咛咸品哟哥哲哺哼商啊喉喳喷嘛嘣嘴回团园围国图圈在地场垄垚埋城堂塔墙壤壮声处复外多大天太夫夸奈奎奏契套女奶好如妙妮妹姆姊委姜娃娇婉婴嫂子孔孙学孩安宋宛宝宠客宣宴家宽寅富寸对寿将小少尔尝尺尼尾局居屋展山屿岐岛峦峰崽左巧巫差已巴布带帽干平幼广庄应度康庸廖异引弟张弯强形影往得微德必志忘快怀怂怕思怡性怨恩息患情惹感戏成我或戴房所才扑打托找抠护报抱押拉拍拥拴挂挑捂捐损掌接控掩揄揶搂搜搞搭摇摊摘撒收改效敏散敬数文斐料斜斤新方施旋无日时旺昆明易昔映春是晒晤晨普暴曲曹曼替月有本杀村条来杨杰杷板枇枕枯某柯柴样根案梯棉棍棚榻檩欢歌止正此殒殡毁毋母毒民气水永汪沉沙沟没油泳洒派浚浦海涧涨淤港渴游溜溶滑满演火灭炊炖炸点烟烤照熊燕爱牌牙物特犬狂猛玉王玩环现班理琼瑟璃瓣瓦瓮生用由电略疯病瘦癌百的皎皖盆益盐盘盛省看真眶眼着瞎瞒矬短矮石砂砖硅硝碧磋祖秀秋科秦称穷空穿窃窑窝窟竟童笑第等筛筹管篮类粉粗粮约级纹线织经绕给维缺网罪羊羞翁老者而耍耳耶肉股肯育肾肿背胎胖胶能脆脸腐腺腾腿自舀舍舒舛舞节花苏苗若英荫药荻莉莜菲营萨落董葵蔡蔺薄薛藏虎虽蚁蛮蝉蝼行衣表袅袜被西要观觅言詹计记讳许诊语说请谁谆谋谓豆豫豹貂贫购贴贼资赏赤赫走赵起越跑跛蹦身躲转轻辉达过迎运还进远违选道遛遮邀邓邦郎都鄂配酸醋采釉里重金针钓钙铁销镇镜长门闭问闯间阔防阳阿陈院除陪隐难雁雄雅雌雨雪雾霍霞露青面鞍须颓风食餐饮饵馓香马驴骐骡高鬼鱼鲁鸟鸡鸩鸭麟麻黄黑鼻，：？

Baker's charset for someone needed.

**Comment by erogol** [comment]
for keeping it up
