### ISSUE TITLE
[Bug] Failed running pretrained Models

### ISSUE THREAD

**Issue by Karim-Fadi** [coqui-ai/TTS#624]
Hi, i am on Arch Linux, with latest versions of Python and pip. I installed  the TTS package with this command:
`pip install TTS`. And by default it made a user installation in the .local folder. So i left it installing everything 
And everything was installed successfully.

So now, i ran this command just like in the demo video of the docs in order to test things out: 
`tts —text “This is a Demo” —model_name tts_models/en/ljspeech/glow-tts —out_path test.wav`

So as expected it downloaded both the model and the vocoder. However at the end of the install there was this error:
`zipfile.BadZipFile(“File is not a zip file”)`

So i tried running it again and now it showed a different error:
`FileNotFoundError: no such file or directory: ‘/home/user/.local/share/tts/vocoder_models—en—ljspeech—multiband-melgan/config.json’`

Now every time i try it gives the same error. It is also worth mentioning that if i list the models, the models shows as downloaded.

So any help ?

**Comment by erogol** [comment]
Can't replicate the error.

- Try the latest version of 🐸 TTS v0.1.2
- Try removing the downloaded models and re-run the commands.
