### ISSUE TITLE
TTS Module Missing Attributes

### ISSUE THREAD

**Issue by ZingBlue** [coqui-ai/TTS#633]
**Describe the bug**
When importing TTS in Python, you should be able to access attributes via call (e.g: `TTS.model`). However, most attributes are inaccessible. A few attributes are still accessible such as `f`, `version`, and `__name__`, which all return expected results.

**To Reproduce**

1. Open your CLI and install TTS via Pip or install manually via the instructions in the Readme (doesn't matter in this case, I tested both).
2. After installation, open a Python environment and import TTS.
3. Try accessing any of the core classes (e.g: `TTS.utils`)
4. See result: `AttributeError: module 'TTS' has no attribute 'utils'`

**Expected behavior**
You should be able to access all of TTS' attributes.

**Environment:**
- **OS Platform and Distribution**: Windows 10, 21H1
- **PyTorch or TensorFlow version**: PyTorch 1.9.0
- **Python version**: Python 3.9.6
- **CUDA/cuDNN version**: N / A
- **GPU model and memory**: N / A
- **Exact command to reproduce**: N / A

**Additional context**

1. I tried this on two similar Windows machines and had the same issue.
2. It is also worth noting that TTS functions in the CLI. I can use commands such as `TTS --text "The meaning of life is 42."` without issue.
3. As of now, Gruut and Gruut-IPA do not install on Windows via Pip. This is because of a single line error in setup.py, I've sent over PRs for both repos and as of now 1/2 have been merged. You will need to manually install Gruut and Gruut-IPA until these changes are merged and released. This is an unrelated issue however, only mentioned here to ensure this does not stall testing.

**Comment by erogol** [comment]
It is not a bug since `PyPI`release is only for inference. If you want to use `TTS`for development, you need to install it from GitHub. 

If you want to install it from `PyPI`even for development, you can post a feature request.

**Comment by ZingBlue** [comment]
> It is not a bug since `PyPI`release is only for inference. If you want to use `TTS`for development, you need to install it from GitHub.
> 
> If you want to install it from `PyPI`even for development, you can post a feature request.

No, I installed by cloning the repo.

**Comment by ZingBlue** [comment]
As I said in the post, if you do the commands
`git clone https://github.com/coqui-ai/TTS`
`pip install -e .[all,dev,notebooks,tf]  # Select the relevant extras`
It will install and have the same issue regardless.

**Comment by ZingBlue** [comment]
Even `pip install -e .\` in the TTS top directory does not allow access to all attributes.

**Comment by ZingBlue** [comment]
I just went on Mac and installed using the same instructions. Still, no attribute access.

**Comment by erogol** [comment]
I can't replicate the issue since all works on my side. 

What is your system? Do you use conda or something else?

**Comment by ZingBlue** [comment]
I feel like I must be missing something, to install TTS with access to attributes on a UNIX/Linux system (Mac in this case), all I have to do is clone the repo, and go into the TTS dir and install via `pip install -e .[all,dev,notebooks,tf]` right? That's all I'm doing yet I still can't access any attributes.

**Comment by erogol** [comment]
Exactly. To help you in that I should be able to replicate the issue but I cannot. 

Try using conda and create a new env and install TTS from scratch by `pip install -e .`
