### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow2.5.0

### ISSUE THREAD

**Issue by borissprat** [coqui-ai/TTS#704]
AMD 64 installation seems to have no way to install tensorflow2.5.0 (version unavailable)

**Comment by borissprat** [comment]
Ubuntu 18.04

**Comment by thorstenMueller** [comment]
According to https://github.com/coqui-ai/TTS/blob/main/requirements.txt there's no dependency for tensorflow 2.5.0. Where's the dependency coming from?

**Comment by erogol** [comment]
TF 2.6 is even available so I believe it is about your platform
