### ISSUE TITLE
[Feature Request ] non-zero exit code on max_decoder_steps

### ISSUE THREAD

**Issue by Dmole** [coqui-ai/TTS#709]
**Describe the bug**
max_decoder_steps error is a known issue that causes output to be missing parts.
🐸 should use a non-zero exit code when that happens.
EG: double the first of the examples linked from README.md;
"Bill got in the habit of asking himself Is that thought true? and if he wasnt absolutely certain it was, he just let it go, Bill got in the habit of asking himself Is that thought true? and if he wasnt absolutely certain it was, he just let it go."

**To Reproduce**
- **Exact command to reproduce**:
1. ~/.local/bin/tts --text "Bill got in the habit of asking himself  Is that thought true?  and if he wasnt absolutely certain it was, he just let it go, Bill got in the habit of asking himself  Is that thought true?  and if he wasnt absolutely certain it was, he just let it go."  --model_name tts_models/en/ljspeech/tacotron2-DDC --vocoder_name vocoder_models/en/ljspeech/hifigan_v2 --out_path /tmp/tmp.E9grqIFNx8.wav ; echo $?

**Expected behavior**
exit code should be 1 or any non-zero value

**Environment (please complete the following information):**
pip3 show TTS | grep Version
Version: 0.1.3

**Comment by Dmole** [comment]
There are 2 workarounds;

Increasing the max_decoder_steps https://github.com/thorstenMueller/deep-learning-german-tts/issues/22

grepping the output for the error and returning non-zero from a wrapper script.

**Comment by erogol** [comment]
I don't understand why you need non-zero error return. What is the use-case? Is it when you pipe the output to another command?

**Comment by Dmole** [comment]
The practical reason for exit codes is to know if a command completed successfully.
It is the only reliable way to know if the output is correct/usable.
For coqui-ai specifically exit codes should be used to indicate the input was not handled properly and should be split up or further filtered.


Misusing exit status likely breaks compliance with specifications like posix.
https://en.wikipedia.org/wiki/Exit_status

**Comment by Sadam1195** [comment]
Do you think it would be wise to handle `max_decoder_steps` and `max_seq_len` dynamically when running inference according to length of `text`?

**Comment by Sadam1195** [comment]
> I don't understand why you need non-zero error return. What is the use-case? Is it when you pipe the output to another command?

Do you think it would be wise to handle `max_decoder_steps` and `max_seq_len` dynamically when running inference according to length of `text`?

**Comment by erogol** [comment]
alas, max_decoder_steps cannot be estimated from the text length

**Comment by Dmole** [comment]
Bad bot.

**Comment by Dmole** [comment]
Bad bot.
