### ISSUE TITLE
[Bug] Error importing load_config

### ISSUE THREAD

**Issue by LordApplesause** [coqui-ai/TTS#710]
I am trying to anayize my spectrograms for my dataset using the notebook CheckSpectrograms.ipynb on Google Colab. However, I receive the following error when importing the libraries: 

`
ImportError: cannot import name 'load_config' from 'TTS.utils.io' (/content/TTS/TTS/utils/io.py)`

_How to reproduce:_ start a google colab notebook, and download/setup rep using the following

`!git clone https://github.com/coqui-ai/TTS/`
`%cd TTS`
`!make system-deps  # only on Linux systems.`
`!make install`

and then run the code, copied from CheckSpectrograms.ipynb:

`%matplotlib inline`
`from TTS.utils.audio import AudioProcessor`
`from TTS.tts.utils.visual import plot_spectrogram`
`from TTS.utils.io import load_config`

`import IPython.display as ipd`
`import glob`

and you will receive the same error. It should run without error. This prohibits the rest of the notebook from working. Any help would be appreciated!

**Comment by Sadam1195** [comment]
Hey, try changing from `TTS.utils.io import load_config` to  `TTS.config import load_config`
@LordApplesause

**Comment by wanghaisheng** [comment]
```
 77, in <module>
    from TTS.config  import load_config
ModuleNotFoundError: No module named 'TTS.config'
```
@Sadam1195

**Comment by Sadam1195** [comment]
> ```
>  77, in <module>
>     from TTS.config  import load_config
> ModuleNotFoundError: No module named 'TTS.config'
> ```
> 


are you running the notebook/script on colab?

**Comment by erogol** [comment]
Fixed here #725

**Comment by wanghaisheng** [comment]
> 
> 
> > ```
> >  77, in <module>
> >     from TTS.config  import load_config
> > ModuleNotFoundError: No module named 'TTS.config'
> > ```
> 
> are you running the notebook/script on colab?

no  just  save notebook as py locally

**Comment by madey83** [comment]
from TTS.tts.utils.generic_utils import setup_model
ModuleNotFoundError: No module named 'TTS.tts.utils.generic_utils'

> > > ```
> > >  77, in <module>
> > >     from TTS.config  import load_config
> > > ModuleNotFoundError: No module named 'TTS.config'
> > > ```
> > 
> > 
> > are you running the notebook/script on colab?
> 
> no just save notebook as py locally

i think it works due to fact not showing any errors related to it, but i have got below

    from TTS.tts.utils.generic_utils import setup_model
ModuleNotFoundError: No module named 'TTS.tts.utils.generic_utils'

**Comment by eginhard** [comment]
@madey83 Use `from TTS.tts.models import setup_model`

**Comment by madey83** [comment]
now i have got this

    from TTS.tts.utils.text.symbols import symbols, phonemes
ModuleNotFoundError: No module named 'TTS.tts.utils.text.symbols'

    from TTS.tts.utils.io import load_checkpoint
ModuleNotFoundError: No module named 'TTS.tts.utils.io'

    from TTS.vocoder.utils.generic_utils import setup_generator
ImportError: cannot import name 'setup_generator' from 'TTS.vocoder.utils.generic_utils' (/mnt/c/Users/lukas/.venv/lib/python3.10/site-packages/TTS/vocoder/utils/generic_utils.py)


i have try to use code from google colab on my own PC:
 
https://colab.research.google.com/drive/1NC4eQJFvVEqD8L4Rd8CVK25_Z-ypaBHD#scrollTo=FuWxZ9Ey5Puj

can you help me ?

**Comment by eginhard** [comment]
Probably a bunch of other changes are needed, some of the notebook are very out of date. You'll need to do a bit of digging yourself, but PRs to fix it are welcome in our fork: https://github.com/idiap/coqui-ai-TTS
