### ISSUE TITLE
[Bug] using "tts_models/en/ljspeech/tacotron2-DDC" does not complete sentence in output file

### ISSUE THREAD

**Issue by kyutums** [coqui-ai/TTS#738]
**Describe the bug**
Running tts (compiled from source) via `./tts --text "Low salary and sheer physical exhaustion from a prolonged pandemic have pushed a big number of nurses to give up and leave hospitals, straining further a health care system that many feared could soon be on the brink of collapse." --model_name "tts_models/en/ljspeech/tacotron2-DDC" --out_path /home/my-user/sample-tts-output/output.wav` does not complete the sentence. The resulting .wav just covers ""Low salary and sheer physical exhaustion from a prolonged pandemic have pushed a big number of nurses"

**To Reproduce**
1. Installed  coqui-ai / TTS from source (including `make system-deps` and `make install`)
2. Enter resulting bin folder.
3. Run `./tts --text "Low salary and sheer physical exhaustion from a prolonged pandemic have pushed a big number of nurses to give up and leave hospitals, straining further a health care system that many feared could soon be on the brink of collapse." --model_name "tts_models/en/ljspeech/tacotron2-DDC" --out_path /home/my-user/sample-tts-output/output.wav`

**Expected behavior**
Using other models, such as tts_models/en/ljspeech/glow-tts, resulted in a .wav that had the complete sentence rendered. Using tts_models/en/ljspeech/tacotron2-DDC though left a partially rendered file.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.2 LTS
- **PyTorch or TensorFlow version (use command below)**: 1.9.0+cu102
- **Python version**: 3.8.10
- **CUDA/cuDNN version**: N/A (no Nvidia GPU)
- **GPU model and memory**: N/A (embedded GPU in motherboard)
- **Exact command to reproduce**: `./tts --text "Low salary and sheer physical exhaustion from a prolonged pandemic have pushed a big number of nurses to give up and leave hospitals, straining further a health care system that many feared could soon be on the brink of collapse." --model_name "tts_models/en/ljspeech/tacotron2-DDC" --out_path /home/my-user/sample-tts-output/output.wav`

**Additional context**
Other models rendered well. Attaching the output rendered (had to convert it to .mp4 as .wav files can't be attached in Github).

https://user-images.githubusercontent.com/7320150/129646910-3e08c303-2481-4166-91b2-0b08f96d1357.mp4

**Comment by Sadam1195** [comment]
I think this could be because of the default config settings, default loads model with ` "max_seq_len": 180,`  and ` "max_decoder_steps": 1000,`  Try adding a modified config with higher values mentioned.

```
./tts --text "Low salary and sheer physical exhaustion from a prolonged pandemic have pushed a big number of nurses to give up and leave hospitals, straining further a health care system that many feared could soon be on the brink of collapse." \ 
    --model_name "tts_models/en/ljspeech/tacotron2-DDC" \
    --config_path "modified_config_path_here_with_higher_values_mentioned"
    --out_path /home/my-user/sample-tts-output/output.wav
```
@kyutums

**Comment by kyutums** [comment]
Thanks @Sadam1195! It worked!

The command I placed to test again is now `./tts --text "Low salary and sheer physical exhaustion from a prolonged pandemic have pushed a big number of nurses to give up and leave hospitals, straining further a health care system that many feared could soon be on the brink of collapse." \ 
    --model_name "tts_models/en/ljspeech/tacotron2-DDC" \
    --config_path "/home/my-user/TTS/tts/configs/tacotron2_config.py"
    --out_path /home/my-user/sample-tts-output/output.wav`

tacotron2_config.py now, after the edit, is as follows:
from dataclasses import dataclass

from TTS.tts.configs.tacotron_config import TacotronConfig


@dataclass
class Tacotron2Config(TacotronConfig):
    """Defines parameters for Tacotron2 based models.

    Example:

        >>> from TTS.tts.configs import Tacotron2Config
        >>> config = Tacotron2Config()

    Check `TacotronConfig` for argument descriptions.
    """

    model: str = "tacotron2"
    out_channels: int = 80
    encoder_in_features: int = 512
    decoder_in_features: int = 512
    max_seq_len: int = 540
    max_decoder_steps: int = 3000



I have attached the now complete sentence.

Many thanks!
https://user-images.githubusercontent.com/7320150/129676061-87a9c23c-6ce2-4351-b67a-b9827a938fc4.mp4

**Comment by faredus** [comment]
@kyutums I have the exact same problem, but I don't quite understand how it works with this config and where you have put it. I copied your code and did the same thing, still same result. Isn't config supposed to be a json file?

**Comment by AlexTMjugador** [comment]
@faredus I think he just edited the `tacotron2_config.py` included with the TTS distribution, on the installed pip packages directory: https://github.com/coqui-ai/TTS/blob/main/TTS/tts/configs/tacotron2_config.py. Doing that is extremely ugly, but it worked for me.
