### ISSUE TITLE
Having troubles converting a tacotron DDC_GST model from torch to tflite

### ISSUE THREAD

**Issue by HaoZhang-umich** [coqui-ai/TTS#745]
Hello, I am trying to convert a Tacotron DDC-GST torch model to a tflite model. I tried `convert_tacotron2_torch_to_tf.py` as it is listed in the notebook, but it does not work and it throws the error   

```
File "/Users/haozhang/Voice/TTS/TTS/tts/tf/utils/convert_torch_to_tf_utils.py", line 77, in transfer_weights_torch_to_tf
    assert np.all(
AssertionError:  [!] weight shapes does not match: embedding/embeddings:0 vs embedding.weight --> (130, 512) vs (149, 512)
```
I think it is because the conversion is using Tacotron2 model which is not consistent with Tacotron DDC-GST. 
So, how should I do the conversion?

**Comment by erogol** [comment]
Tf lite model only supports vanilla Tacotron.
