### ISSUE TITLE
[Feature request] Allow tts to print version number in appropriate output on command line

### ISSUE THREAD

**Issue by wyattscarpenter** [coqui-ai/TTS#747]
It is difficult for me to be sure what version of tts I am currently interacting with, to make sure I am on the latest version. It would be useful if the version number were listed in the help message (probably near the top) or if `-v, --version` printed the version number.

**Comment by Sadam1195** [comment]
> It is difficult for me to be sure what version of tts I am currently interacting with, to make sure I am on the latest version. It would be useful if the version number were listed in the help message (probably near the top) or if `-v, --version` printed the version number.

It's already implemented, see the link for reference. https://github.com/coqui-ai/TTS/blob/main/TTS/VERSION
@wyattscarpenter

**Comment by wyattscarpenter** [comment]
@Sadam1195 can tts be made to print this number? That's what I'd like
