### ISSUE TITLE
load_fsspec leaves residue in GPU memory 

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#750]
https://github.com/coqui-ai/TTS/blob/3ab8cef99e295880e42393195734530023a741e7/TTS/trainer.py#L328

If you restore the model with `load_ffspec`, it leaves some residue in GPU RAM which causes OOM when you restore a model which barely fits in the GPU memory. 

Maybe you could check if there is anything we can do about it @agrinh 

For instance if I do  ``` checkpoint = torch.load(restore_path, map_location='cpu') ```, there is no OOM

**Comment by agrinh** [comment]
But if you run it with `map_location='cpu' then you're not loading it to the GPU right? Do you have the same issue if you replace this line with `checkpoint = torch.load(restore_path)`?

**Comment by erogol** [comment]
only `checkpoint = load_fsspec(restore_path, map_location='cpu') ` works in my case. This loads the checkpoint in CPU but when you `model.load_state_dict` it passes the weights to GPU
