### ISSUE TITLE
[Bug?] VITS recipe uses english_cleaners instead of phoneme_cleaners

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#754]
The VITS recipe has [phonemes enabled](https://github.com/coqui-ai/TTS/blob/01a2b0b5c086e94b6f14076763bd1abb5dc86968/recipes/ljspeech/vits_tts/train_vits.py#L35) but `text_cleaner` is set to [english_cleaners instead of phoneme_cleaners](https://github.com/coqui-ai/TTS/blob/01a2b0b5c086e94b6f14076763bd1abb5dc86968/recipes/ljspeech/vits_tts/train_vits.py#L38).

Isn't that a mistake?

**Comment by lexkoro** [comment]
They both do basically the same cleaning so it shouldn't really matter.

https://github.com/coqui-ai/TTS/blob/c3082267073ed45b69993aa83437958b1c42615f/TTS/tts/utils/text/cleaners.py#L90

https://github.com/coqui-ai/TTS/blob/c3082267073ed45b69993aa83437958b1c42615f/TTS/tts/utils/text/cleaners.py#L129
