### ISSUE TITLE
[Bug] VITS recipe - Detected NaN loss

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#755]
**Description**
I tried fine tuning the VITS model using the provided recipe, starting from the pretrained checkpoint, but a few hours in it broke with the following error:

```
  --> STEP: 183/270 -- GLOBAL_STEP: 1061700
     | > loss_gen: 2.44422  (2.17234)
     | > loss_kl: 2.52505  (2.60772)
     | > loss_feat: 0.00347  (0.00353)
     | > loss_mel: 16.64367  (16.56427)
     | > nll_duration: -1.13348  (-1.12440)
     | > loss_0: 20.48293  (20.22347)
     | > grad_norm_0: 459.31244  (378.85425)
     | > loss_disc: 3.21796  (3.63533)
     | > loss_1: 3.21796  (3.63533)
     | > grad_norm_1: 115.94435  (216.08353)
     | > step_time: 1.02200  (0.88802)
     | > loader_time: 0.04640  (0.03137)

Traceback (most recent call last):
  File "/home/fijipants/repo/coqui-0.2/TTS/trainer.py", line 855, in fit
    self._fit()
  File "/home/fijipants/repo/coqui-0.2/TTS/trainer.py", line 840, in _fit
    self.train_epoch()
  File "/home/fijipants/repo/coqui-0.2/TTS/trainer.py", line 686, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/fijipants/repo/coqui-0.2/TTS/trainer.py", line 577, in train_step
    batch, self.model, optimizer, scaler, criterion, scheduler, self.config, idx
  File "/home/fijipants/repo/coqui-0.2/TTS/trainer.py", line 466, in _optimize
    raise RuntimeError(f" > Detected NaN loss - {loss_dict}.")
RuntimeError:  > Detected NaN loss - {'loss_gen': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_kl': tensor(2.5773, device='cuda:0', grad_fn=<MulBackward0>), 'loss_feat': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_mel': tensor(16.4915, device='cuda:0', grad_fn=<MulBackward0>), 'loss': tensor(nan, device='cuda:0', grad_fn=<AddBackward0>), 'nll_duration': tensor(-1.1557, device='cuda:0', grad_fn=<SumBackward0>)}.
```

**To Reproduce**
1. Add LJSpeech-1.1 dataset to root directory of repo.
2. Run `CUDA_VISIBLE_DEVICES=0 python recipes/ljspeech/vits_tts/train_vits.py --restore_path /home/fijipants/.local/share/tts/tts_models--en--ljspeech--vits/model_file.pth.tar`
3. Wait a few hours and pray it breaks.

**Expected behavior**
It shouldn't break from this, no?

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **PyTorch or TensorFlow version (use command below)**: PyTorch 1.9.0 w/ CUDA 11.1
- **Python version**: 3.7.11
- **CUDA/cuDNN version**: 11.1
- **GPU model and memory**: RTX 3090 24GB
- **Exact command to reproduce**: See "To Reproduce" section.

**Additional context**
Here's how the sample audio sounded before crashing.

https://user-images.githubusercontent.com/88913682/130295077-d4db2aa1-51d2-456c-bb98-1ac0feab45e6.mp4

**Comment by erogol** [comment]
latest changes in `fix_distribute` branch fix this
