### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'TTS.vocoder.models.tacotron2'

### ISSUE THREAD

**Issue by Aaron2550** [coqui-ai/TTS#757]
**Describe the bug**
I installed TTS using `pip install TTS`, and ran TTS as below

**To Reproduce**
1. Run TTS with arguments as below
2. Wait for the Model Download
3. See error `ModuleNotFoundError: No module named 'TTS.vocoder.models.tacotron2'`

**Expected behavior**
Works and output the Audio File

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64 21H1 19043.1165
- **PyTorch or TensorFlow version (use command below)**: Torch 1.9.0
- **Python version**: Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
- **CUDA/cuDNN version**: None Installed (Not trying to train any Models)
- **GPU model and memory**: AMD RX5700XT 8GB
- **Exact command to reproduce**: `tts --text "Test" --model_name "tts_models/en/ek1/tacotron2" --vocoder_name "tts_models/en/ek1/tacotron2" --out_path "C:\Users\Aaron\Desktop\a.wav"`

**Additional context**

**Comment by Lizh-TW** [comment]
"tts_models/en/ek1/tacotron2" is TTS model
--vocoder_name is 
![image](https://user-images.githubusercontent.com/58511222/130403039-159bccc3-4453-49aa-b765-ac49addec137.png)

**Comment by Lizh-TW** [comment]
Try : tts --text "Test" --model_name "tts_models/en/ek1/tacotron2" --vocoder_name "vocoder_models/en/ek1/wavegrad"

**Comment by erogol** [comment]
you should call one of the vocoders with `--vocoder_name` as @Lizh-TW  rightly pointed.
