### ISSUE TITLE
[Bug] ProjectsMac path bug in vctk/vits model

### ISSUE THREAD

**Issue by nitinthewiz** [coqui-ai/TTS#767]
When trying to use the tts/en/vctk/vits model, I see the following error - 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/ProjectsMac/TTS/tts_models--en--vctk--vits/speaker_ids.json'
```

OS: Windows 10
Python: 3.8
TTS version: 0.2.0 (latest released version)

I believe I've found the issue here -
https://github.com/coqui-ai/TTS/blob/c3082267073ed45b69993aa83437958b1c42615f/TTS/.models.json#L81

The referenced file - https://github.com/coqui-ai/TTS/releases/download/v0.2.0/tts_models--en--vctk--vits.zip

has the following in the config.json file on line 170 - 
```
"speakers_file": "/home/ubuntu/ProjectsMac/TTS/tts_models--en--vctk--vits/speaker_ids.json",
```

I also noticed a few more absolute paths in other models. 

In tts_models--en--vctk--sc-glow-tts - 
```
"d_vector_file": "/home/erogol/.local/share/tts/tts_models--en--vctk--sc-glow-tts/speakers.json",
```

In ljspeech-dcattn-April-05-2021_01+52PM-0947822 - 
```
"output_path": "/home/ubuntu/MyDrive/Trainings/sam/",
"phoneme_cache_path": "/home/ubuntu/en-us-phonemes/",
"datasets": [
        {
            "meta_file_train": "recording_script.xml",
            "meta_file_val": null,
            "name": "sam_accenture",
            "path": "/home/ubuntu/MyDrive/Datasets/non-binary-voice-files/"
        }
    ]
```

The output_path gets overridden easily, but speakers_file does not and I haven't tested it but possibly neither does the d_vector_file, so the first two models would fail. The third model might fail if the datasets->path is referenced, but I don't know if it is.

I think these are being trained locally and uploaded manually to the release. So I don't see how I can help in fixing these. Could the devs or release lead please look into fixing these absolute paths? 

Workaround: My current solution is to give it the model_path folder for vctk-vits and that seems to work. However, I'm also working on a production environment, where I would not have knowledge of where the models are downloaded, so I can't use the model_path argument. Is there a way for me to specify where TTS downloads the models?

Thanks!

p.s. I also noted these observations [here](https://github.com/coqui-ai/TTS/issues/730#issuecomment-905038920) but I later noticed that that bug is closed so you might not be looking at my notes there, hence I opened a new bug.

**Comment by erogol** [comment]
if you now use the `fix_distribute` branch it should work.

**Comment by nitinthewiz** [comment]
Awesome, thanks!
