### ISSUE TITLE
[Bug] VITS recipe breaks with "local variable 'outputs' referenced before assignment"

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#786]
**Describe the bug**
When I try to train VITS in any way, e.g. with the recipe, it crashes with `local variable 'outputs' referenced before assignment`.

**To Reproduce**
- Make a directory `runs2`
- Copy the VITS recipe `recipes/ljspeech/vits_tts/train_vits.py` into there
- Place LJSpeech dataset into there
- Run it: `CUDA_VISIBLE_DEVICES=0 python runs2/train_vits.py`
- Wait for the first `> EVALUATION`
- It immediately crashes

**Expected behavior**
It doesn't crash.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **PyTorch or TensorFlow version (use command below)**: PyTorch 1.9.0 w/ CUDA 11.1
- **Python version**: 3.7.11
- **CUDA/cuDNN version**: 11.1
- **GPU model and memory**: RTX 3090 24GB
- **Exact command to reproduce**: See "To Reproduce" section.

**Additional context**

Here's the last part of the output:

```
 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 131
 | > Computing phonemes ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 131/131 [00:06<00:00, 19.03it/s] | > Max length sequence: 445286
 | > Min length sequence: 69478
 | > Avg length sequence: 288066.8244274809
 | > Num. instances discarded by max-min (max=5000, min=0) seq limits: 131
 | > Batch group size: 0.

 > EVALUATION

Traceback (most recent call last):
  File "/home/fijipants/repo/coqui-0.2.1/TTS/trainer.py", line 911, in fit
    self._fit()
  File "/home/fijipants/repo/coqui-0.2.1/TTS/trainer.py", line 898, in _fit
    self.eval_epoch()
  File "/home/fijipants/repo/coqui-0.2.1/TTS/trainer.py", line 839, in eval_epoch
    figures, audios = self.model.eval_log(self.ap, batch, outputs)
UnboundLocalError: local variable 'outputs' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runs2/train_vits.py", line 52, in <module>
    trainer.fit()
  File "/home/fijipants/repo/coqui-0.2.1/TTS/trainer.py", line 930, in fit
    remove_experiment_folder(self.output_path)
  File "/home/fijipants/repo/coqui-0.2.1/TTS/utils/generic_utils.py", line 74, in remove_experiment_folder
    print(" ! Run is removed from {}".format(experiment_path))
  File "/home/fijipants/repo/coqui-0.2.1/TTS/trainer.py", line 986, in write
    with open(self.log_file, "a", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/fijipants/repo/coqui-0.2.1/runs2/vits_ljspeech-August-31-2021_11+23PM-5793dca7/trainer_0_log.txt'
```

**Comment by erogol** [comment]
I couldn't replicate the issue on my local system.

**Comment by fijipants** [comment]
@erogol Oh no, I'll try again from scratch and see if I can.

**Comment by lexkoro** [comment]
you filtered out all of your data with the seq_limits.

```
 | > Number of instances : 131
 | > Min length sequence: 69478
 | > Avg length sequence: 288066.8244274809
 | > Num. instances discarded by max-min (max=5000, min=0) seq limits: 131
```

**Comment by fijipants** [comment]
@lexkoro Oh damn, nice catch. Turns out I was using an old `train_vits.py` that I'd copied earlier. Thanks!

**Comment by fijipants** [comment]
Update: Retried and got the "file does not exist" issue again, I'll just modify it on my side if you guys aren't experiencing it.

**Comment by fijipants** [comment]
Update: Now it broke with the `FileNotFound` error, and you'll never guess what the fix was: Uninstalling PyTorch and reinstalling it with Conda. Nice. Weird CUDA issue I guess.

**Comment by Ca-ressemble-a-du-fake** [comment]
I am still facing this issue with all data filtered out although I used the config.json coming along with the model (see fine tuning). I am using `train_tts.py`. Then I get the same error with outputs not defined :

`
> DataLoader initialization
 | > Use phonemes: False
 | > Number of instances : 1442
 | > Max length sequence: 533320.0
 | > Min length sequence: 8200.0
 | > Avg length sequence: 102100.2080443828
 | > Num. instances discarded by max-min (max=250, min=30) seq limits: 1442
 | > Batch group size: 0.

 > EVALUATION 

Traceback (most recent call last):
  File "/content/TTS/TTS/trainer.py", line 1007, in fit
    self._fit()
  File "/content/TTS/TTS/trainer.py", line 994, in _fit
    self.eval_epoch()
  File "/content/TTS/TTS/trainer.py", line 934, in eval_epoch
    self.model.eval_log(batch, outputs, self.dashboard_logger, self.training_assets, self.total_steps_done)
UnboundLocalError: local variable 'outputs' referenced before assignment
`

How did you solve that ?

**Comment by lexkoro** [comment]
You filtered out all your data

**Comment by Ca-ressemble-a-du-fake** [comment]
@lexkoro I took the config.json as it was and as it was designed for the dataset... Oh well, you mean I should use min = 8200 and max = 533320. But how do I map the original min map value in this new "space". What is the unit of min and max ?

**Comment by souvikg544** [comment]
Facing the same error in yourtts - https://github.com/coqui-ai/TTS/issues/2631 
Kindly look into this
