### ISSUE TITLE
Tacotron2-DDC error

### ISSUE THREAD

**Issue by terry-ess** [coqui-ai/TTS#806]
Attempting to create a new Synthesizer with the TTS model Tacotron2 DDC results in the following message:

Error(s) in loading state_dict for Tacotron2: size mismatch for embedding.weight: copying a param with shape torch.Size([129, 512]) from checkpoint

The model data (checkpoint_130000.pth.tar, config.jason and scale_stats.npy) was downloaded from your released model table.  I am using Python 3.8 on a Windows 10  PC

**Comment by terry-ess** [comment]
Okay I found the appropriate zip file with the model and it works.

**Comment by eslam69** [comment]
> Okay I found the appropriate zip file with the model and it works.

I have the same issue, could you refer to the appropriate zip file that worked with you, please?

**Comment by terry-ess** [comment]
You can download it at: https://github.com/coqui-ai/TTS/releases/download/v0.0.12/tts_models--en--ljspeech--tacotron2-DDC.zip

The .models.json file in the TTS folder lists all the TTS and vocoder models.
