### ISSUE TITLE
[Feature request] Web user interface

### ISSUE THREAD

**Issue by ghost** [coqui-ai/TTS#829]
This is the output when I am running on my local machine .(current version = v0.3.1)
![image](https://user-images.githubusercontent.com/88183889/134165962-f8e972ac-9f6b-422e-b2cc-bb3521199d57.png)

 but In actual documentation, they provide drop-down menu to choose models there 
so the actual output look like this below image:
![image](https://user-images.githubusercontent.com/88183889/134166294-cedbe7da-1d54-4ad1-876d-b29782aa8ab1.png)

I would like to fix  this bug in your current released version and for my local machine. Can anyone guide me which file is responsible for the WEB-UI.. Kindly provide the file name and which directory the file is present...
I have tried in server directory but it's not working.

**Comment by erogol** [comment]
The dropdown menu is not for choosing models it is for choosing speakers in a multi-speaker model.

**Comment by ManoBharathi93** [comment]
> The dropdown menu is not for choosing models it is for choosing speakers in a multi-speaker model.

As you said, If we could able to choose models in web interface it will be the nice features in coqui..

**Comment by BillyBobQuebec** [comment]
@ManoBharathi93 
I agree that would be convenient and useful to also be able to have a dropdown for selecting model.
