### ISSUE TITLE
[Feature request] Inference on Windows using .Net C#

### ISSUE THREAD

**Issue by BitBarrel** [coqui-ai/TTS#860]
It would be very helpful if a c# API implementation is available so TTS can run on Windows. Coqui STT already supports this but unfortunately this is not yet the case with TTS.

**Comment by erogol** [comment]
I don't use windows but if someone is willing to do it, it is definitely open for a ✨PR✨

**Comment by BitBarrel** [comment]
I will have a look, but first there needs to be a native library like libstt.so for coqui STT, probably written in C++ to make it cross platform compatible. Once that is done, a wrapper for C# can be made. That is the way they done it for STT I believe. 

Is there anything you can point me to to get me started? How to make library which can be called with C++?

**Comment by erogol** [comment]
Pytorch has a C++ interface. That might be a starter https://pytorch.org/cppdocs/

**Comment by Darth-Carrotpie** [comment]
So did anyone have a poke at this? In the meantime ONNX became a really popular format. Most frameworks tend to have their most advanced models available for ONNX export, i.e. [huggingface transformers](https://huggingface.co/docs/transformers/serialization) have most of their pre-trained models ready for export.

**Comment by BitBarrel** [comment]
> So did anyone have a poke at this?
I didn't unfortunately.  It's way over my head.
