### ISSUE TITLE
[Bug] Use Spawn Instead of Fork on Windows

### ISSUE THREAD

**Issue by Sniper296** [coqui-ai/TTS#867]
**Describe the bug**
Attempting to train a tacotron model on Windows (Anaconda) fails immediately due to `multiprocessing` configured to use `fork`. [Multiprocessing#Contexts and start methods](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)

**To Reproduce**
1. `conda env create -f  environment.yml` [environment.yml](https://github.com/coqui-ai/TTS/files/7296093/environment.yml.txt)
2. `conda activate tts`
3. `python tacotron_train.py` [tacotron_train.py](https://github.com/coqui-ai/TTS/files/7296100/tacotron_train.py.txt)
```
Traceback (most recent call last):
  File "tacotron_train.py", line 5, in <module>
    from TTS.trainer import init_training, Trainer, TrainingArgs
  File "C:\Users\Adam\.conda\envs\tts\lib\site-packages\TTS\trainer.py", line 46, in <module>
    multiprocessing.set_start_method("fork")
  File "C:\Users\Adam\.conda\envs\tts\lib\multiprocessing\context.py", line 247, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\Users\Adam\.conda\envs\tts\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Users\Adam\.conda\envs\tts\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**Expected behavior**
Training to start.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64-bit 19043.1237
- **PyTorch or TensorFlow version (use command below)**: 1.9.1
- **Python version**: 3.8.12
- **CUDA/cuDNN version**: CUDA 10.2 cuDNN 7.0
- **GPU model and memory**: GeForce GTX 1070 Ti 8GiB driver 471.96
- **Exact command to reproduce**: See steps

**Comment by bitnom** [comment]
Temporary fix until PR is accepted:

1. Clone TTS repo.
2. In requirements.txt replace `trainer` with `trainer4win`
3. Build TTS package and install via pip.
