### ISSUE TITLE
[Feature request] Lightweight inference

### ISSUE THREAD

**Issue by robinhad** [coqui-ai/TTS#883]
**Is your feature request related to a problem? Please describe.**
I would like to run TTS in a serverless way/constrained environments, but currently in order to run TTS you need to pull ~10GB worth of dependencies + model (330 MB approx).
**Describe the solution you'd like**
Is there any built-in way to export to ONNX and run inference using ONNX-runtime?
Or maybe some kind of lightweight package used only for inference?

**Comment by synesthesiam** [comment]
Onnx export isn't easy; it's something you have to do for each individual model (same with TorchScript).

Here are some straightforward tips to get the size of your TTS installation down:

1. If you don't need CUDA, install a CPU-only PyTorch from [here](https://download.pytorch.org/whl/cpu/torch_stable.html)
    * `pip3 install -f 'https://download.pytorch.org/whl/cpu/torch_stable.html' ...`
2. Remove the optimizer state from your model checkpoints
    * `state = torch.load(...); state.pop("optimizer", None); torch.save(state, ...)`
3. Remove references to `matplotlib` in the code and `requirements.txt`
    * Delete all `import matplotlib` statements and replace the body of all visualization functions with `raise NotImplementedError()`
4. Only include support for the languages you need (may require editing `import` statements in `TTS/tts/utils/text`)
    * Remove `gruut` languages you're not using (just use `gruut` if English only)
    * Remove `mecab-python3` and `unidic-lite` if you don't need Japanese
    * Remove `pypinyin` and `jieba` if you don't need Chinese

These steps should shave a few gigs off of your installation. Hope this helps!
