### ISSUE TITLE
[Bug] trim_silence() function values should be set in the config

### ISSUE THREAD

**Issue by george-roussos** [coqui-ai/TTS#892]
Right now, it only takes in the produced waveform as an argument (see [here](https://github.com/coqui-ai/TTS/blob/40c17b220512fa8ccbc20930b9649a978254903d/TTS/utils/synthesizer.py#L268)), which is then passed to `find_endpoint()` (see [here](https://github.com/coqui-ai/TTS/blob/40c17b220512fa8ccbc20930b9649a978254903d/TTS/utils/audio.py#L677)). There, these values are set to `-40dB` and a minimum silence of `0.8`, since other values are not passed along with the waveform. For models trained on samples that contain long silences and the dB threshold should be different, this creates problems (cutting parts of the speech). I think it would be better if we were able to somehow set these in the config file, based on the model individually.

Another good option (methinks), would be to check the config during synthesis, specifically whether `do_trim_silence` is `True` or `False` and only then passing the waveform to `trim_silence()`. That is assuming those default values must stay.

If it sounds like a nice idea, I can try and send a PR to `dev`.

**Comment by erogol** [comment]
This is fixed by @george-roussos
