### ISSUE TITLE
Error in magma_getdevice_arch: MAGMA not initialized (call magma_init() first) or bad device

### ISSUE THREAD

**Issue by harveenchadha** [coqui-ai/TTS#906]
**Describe the bug**
Error in magma_getdevice_arch: MAGMA not initialized (call magma_init() first) or bad device

The dataset loader does not loads all the files instead throws the this error.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux, PopOS
- **PyTorch or TensorFlow version (use command below)**: 1.10 Pytorch
- **Python version**: 3.8
- **CUDA/cuDNN version**: 11.3
- **GPU model and memory**: NVIDIA Quadro RTX 3000, 6 GB
- **Exact command to reproduce**:

**Comment by erogol** [comment]
It is about PyTorch initialisation. You can either use a newer version or refer back to Pytorch repo for a solution.
