### ISSUE TITLE
[Bug] VCTK Fast Pitch model is not compatible with the vocoder

### ISSUE THREAD

**Issue by erogol** [coqui-ai/TTS#907]
The vocoder model designated for the VCTK FastPitch model is not compatible and it produces pure noise. 

We need to train a new compatible vocoder or update the FastPitch model.

Until then recommended to use Griffin-Lim vocoder by passing empty vocoder name or setting the field in `.models.json` to None

**Comment by skol101** [comment]
Even though they mention only WaveGlow in their paper, from here https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/tts_en_fastpitch it's evident that HifiGan can be used as a vocoder. 

I'm sorry I could be stupid but here https://github.com/coqui-ai/TTS/blob/0c2150a6c10060c9427d7940bf845d61b88a7c09/TTS/vocoder/README.md I don't see instruction of how a vocoder is tied anyhow to a TTS model. 
How can one train a 'designated' vocoder model for a TTS model?

**Comment by skol101** [comment]
Btw, hifigan_v2 vocoder that's used in the project is just 3,5 MB. Is this ok @Edresson 
```
  "vctk": {
                "hifigan_v2": {
                    "description": "Finetuned and intended to be used with tts_models/en/vctk/sc-glow-tts",
                    "github_rls_url": "https://coqui.gateway.scarf.sh/v0.0.12/vocoder_model--en--vctk--hifigan_v2.zip",
                    "commit": "2f07160",
                    "author": "Edresson Casanova",
                    "license": "",
                    "contact": ""
                }
            },
```

**Comment by erogol** [comment]
It has only the generator network.

**Comment by erogol** [comment]
> Even though they mention only WaveGlow in their paper, from here https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/tts_en_fastpitch it's evident that HifiGan can be used as a vocoder.
> 
> I'm sorry I could be stupid but here https://github.com/coqui-ai/TTS/blob/0c2150a6c10060c9427d7940bf845d61b88a7c09/TTS/vocoder/README.md I don't see instruction of how a vocoder is tied anyhow to a TTS model. How can one train a 'designated' vocoder model for a TTS model?

train the vocoder on the same dataset using the same audio parameters

**Comment by skol101** [comment]
Yep, started doing that but only on a single GPU bacause I couldn't find distributed training for training_vocoder.py. Is there one?

**Comment by skol101** [comment]
@erogol  HiFiGan model in CoquiTTS doesn't support SpeakerManager, so multispeaker HifiGan cannot be trained using vctk dataset.

**Comment by skol101** [comment]
I'll roll-back to CoquiTTS 3.x to see if it makes any changes in HiFiGan training.

**Comment by skol101** [comment]
No improvement.

![Uploading Screenshot from 2021-12-03 13-05-18.png…]()

**Comment by skol101** [comment]
@erogol no help here?

**Comment by erogol** [comment]
how should I help you just by looking at your tensorboard? 

It is also not relevant to the issue. Please create a new thread.
