### ISSUE TITLE
Wrong d_vector shape in testing.

### ISSUE THREAD

**Issue by maxfrenzel** [coqui-ai/TTS#911]
I think there's a little typo here, there shouldn't be any brackets around this. It crashes during testing. Removing the brackets and comma resolves the issue.

https://github.com/coqui-ai/TTS/blob/d227aaebcc7e4b0df7b3bd0714807748e8164e14/TTS/tts/models/base_tts.py#L291

**Comment by WeberJulian** [comment]
Hey there, thanks for the report. I pushed a PR here that fixes that https://github.com/coqui-ai/TTS/pull/943.
I have to make a few changes and then the fix will be merged.

**Comment by maxfrenzel** [comment]
Thanks, your PR did fix the issue, as well as several others I was having. Looks like I tried to fix things too far down the line, which then broke other things, but your change solved the problem at its root.
