### ISSUE TITLE
[Bug] Impossible to download models 

### ISSUE THREAD

**Issue by Vxs14** [coqui-ai/TTS#927]
Thank a lot for this project, it's very great ! but i'm facing to a problem with download models, i tried for 2 days and i think it's a bug ... (not sure,excuse me if I made a mistake) 

**To Reproduce**

Fresh install Ubuntu 18.04, with python 3.6.9.
Install TTS with the following instructions : 

git clone https://github.com/coqui-ai/TTS/
cd TTS
make system-deps  
make install

Try to Synthesizing Speech with 

tts --text "this is a test" --out_path /home/user/test1.wav

The result : 

/home/user/.local/lib/python3.6/site-packages/numba/core/errors.py:154: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
 > Downloading model to /home/user/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/home/user/TTS/TTS/bin/synthesize.py", line 205, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "/home/user/TTS/TTS/utils/manage.py", line 109, in download_model
    self._download_zip_file(model_item["github_rls_url"], output_path)
  File "/home/user/TTS/TTS/utils/manage.py", line 162, in _download_zip_file
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Same with all other models, like tts_models/en/ljspeech/glow-tts .

Could you help me ?

**Comment by thorstenMueller** [comment]
If you just want to synthesize voice with a pretrained model you can skip these steps:
```
git clone https://github.com/coqui-ai/TTS/
cd TTS
make system-deps
make install
```

Just run
```
pip install tts
tts --text "this is a test" --out_path /home/user/test1.wav
```

**Comment by Vxs14** [comment]
Thank you for your answer but i'll need to training my own voice, Nevertheless this morning i tried with a new install of ubuntu 20.4, python 3.8, pip 21.3.1.

pip install tts -> all the install did without any problem.

try : 
tts --text "this is a test" --out_path /home/user/test1.wav

same result : 

Downloading model to /home/user/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/TTS/bin/synthesize.py", line 205, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "/usr/local/lib/python3.8/dist-packages/TTS/utils/manage.py", line 117, in download_model
    self._download_zip_file(model_item["github_rls_url"], output_path)
  File "/usr/local/lib/python3.8/dist-packages/TTS/utils/manage.py", line 181, in _download_zip_file
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

I know that the best python version for TTS is the 3.6, but i don't think that the raison of a bad zip file.

**Comment by Vxs14** [comment]
Thank you for your help !

Same error : zipfile.BadZipFile: File is not a zip file

the both folders have been created :  /tts/tts_models--en--ljspeech--tacotron2-DDC/ 
but empty,
it's really strange .

**Comment by Vxs14** [comment]
anybody have an idea for this issue ?

**Comment by erogol** [comment]
You can maybe download the model directly from the URL manually.

**Comment by meliksahturker** [comment]
> remove this folder `/home/user/.local/share/tts/` and try again

Cleaning the content of tts resolved this issue for me.

**Comment by erogol** [comment]
Yes sometimes due to some connection issue, the file is downloaded broken. So removing it and downloading it again filxes the issue

**Comment by iprovalo** [comment]
I just had a similar issue for the 

```
    "es": {
      "mai": {
        "tacotron2-DDC": {
          "github_rls_url": "https://coqui.gateway.scarf.sh/v0.0.9/tts_models--es--mai--tacotron2-DDC.zip",
          "default_vocoder": "vocoder_models/universal/libri-tts/fullband-melgan",
          "commit": "",
          "author": "Eren Gölge @erogol",
          "license": "MPL",
          "contact": "egolge@coqui.com"
        }
      }
    },
```

Manual download worked, but I had to change a hardcoded path to home dir in the config.json
