### ISSUE TITLE
ModuleNotFoundError: No module named 'gruut' On Windows

### ISSUE THREAD

**Issue by Areopagitics** [coqui-ai/TTS#933]
Even after installing TTS according to guy paddock according to this [post](https://stackoverflow.com/questions/66726331/how-can-i-run-mozilla-tts-coqui-tts-training-with-cuda-on-a-windows-system) I am still getting this error when running the _tts_ command.

**ModuleNotFoundError: No module named 'gruut'** 

It goes away when installing a higher version of gruut (not gruut 1.2.3), but then a whole sequence of errors follows due to incompatibility of modules. 

The Windows platform definitely needs some help.

**Comment by erogol** [comment]
Alas, we don't support Windows yet as nobody in the dev team uses it. 

If someone is willing to take the initiative, I can be the help.

**Comment by Areopagitics** [comment]
Thanks for getting back! I'd be willing to help as well, but not take the lead from my limited experience
