### ISSUE TITLE
[Feature request] Raw Stream output for long texts on CLI

### ISSUE THREAD

**Issue by framilano** [coqui-ai/TTS#936]
I'm trying to TTS large texts, even splitting in different sentences takes too much time (I need a response in 2/3 seconds max), is there a way to stream the output before finishing the process? So without saving the audio in a WAV file essentially.

Something like:
```
tts --text "Hello sir, what is your name?" --raw_stream | aplay -r 22050 -c 1 -f S16_LE
```

**Comment by erogol** [comment]
There is no streaming currently.

**Comment by lawrence-laz** [comment]
How complex would such feature be? Is this something that realistically could be expected to be available in the foreseeable future?

**Comment by jnak** [comment]
+1 That seems like a very compelling feature to build conversational agent. Breaking texts into smaller sentences increases a bit the latency but it's not ideal and it removes context from the engine that can useful for intonations and punctuations.
