### ISSUE TITLE
[Feature request] make model download directory configurable at command line

### ISSUE THREAD

**Issue by jreus** [coqui-ai/TTS#948]
It would be really handy to be able to specify the models directory as a command line argument to `tts`
I usually keep all my models in one place, including self-trained models. And I like these to be in a directory within my current working project rather than in a hidden directory inside user home.

The only alternative I know is to hack a solution together by modifying `synthesize.py` 

btw. I would be happy to implement this myself and submit a PR. I'm not an expert on the coqui codebase, but this seems like a simple enough thing to add even for me. :-)

**Comment by erogol** [comment]
Another hack is to use symbolic linking the 🐸 TTS folder to your target folder.
