### ISSUE TITLE
[Bug] 0.4.2 (dev) Fail to finetune VITS VCTK model on a single voice

### ISSUE THREAD

**Issue by skol101** [coqui-ai/TTS#951]
**Describe the bug**
When trying to finetune VITS VCTK model on a new single voice, training stops on Epoch 0. Works fine on >1 voices.

**To Reproduce**
0. Create a folder structure similar to VCTK dataset but only with one voice.
1. Run the following command : CUDA_VISIBLE_DEVICES=0,1 python ../TTS/TTS/bin/distribute.py --script train_vits_newone.py --restore_path /home/sk/.local/share/tts/tts_models--en--vctk--vits/model_file.pth.tar
2. > Using CUDA:  True
 > Number of GPUs:  2
 > `speakers.json` is saved to /home/sk/work/newone/vits_vctk_newone-November-22-2021_02+23PM-0000000/speakers.json.
 > `speakers_file` is updated in the config.json.
 > Restoring from model_file.pth.tar ...
 > Restoring Model...
 > Partial model initialization...
 | > 856 / 969 layers are restored.
 > Model restored from step 1000000

 > Model has 86422380 parameters
 > Restoring best loss from  ...
 > Starting with loaded last best loss inf.

3. > TRAINING (2021-11-22 14:23:43) 
Traceback (most recent call last):
  File "/home/sk/work/TTS/TTS/trainer.py", line 1007, in fit
    self._fit()
  File "/home/sk/work/TTS/TTS/trainer.py", line 992, in _fit
    self.train_epoch()
  File "/home/sk/work/TTS/TTS/trainer.py", line 820, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/sk/work/TTS/TTS/trainer.py", line 703, in train_step
    outputs, loss_dict_new, step_time = self._optimize(
  File "/home/sk/work/TTS/TTS/trainer.py", line 599, in _optimize
    outputs, loss_dict = self._model_train_step(batch, model, criterion, optimizer_idx=optimizer_idx)
  File "/home/sk/work/TTS/TTS/trainer.py", line 559, in _model_train_step
    return model.module.train_step(*input_args)
  File "/home/sk/work/TTS/TTS/tts/models/vits.py", line 538, in train_step
    outputs = self.forward(
  File "/home/sk/work/TTS/TTS/tts/models/vits.py", line 449, in forward
    o = self.waveform_decoder(z_slice, g=g)
  File "/home/sk/anaconda3/envs/tts_one/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sk/work/TTS/TTS/vocoder/models/hifigan_generator.py", line 250, in forward
    o = o + self.cond_layer(g)
  File "/home/sk/anaconda3/envs/tts_one/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sk/anaconda3/envs/tts_one/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sk/anaconda3/envs/tts_one/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
TypeError: conv1d() received an invalid combination of arguments - got (NoneType, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple, tuple, tuple, int)

**Expected behavior**
Training continue as normal

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **PyTorch or TensorFlow version (use command below)**: pytorch                   1.10.0         
- **Python version**: 3.9.7
- **CUDA/cuDNN version**:  py3.9_cuda11.3_cudnn8.2.0_0
- **GPU model and memory**: 2xRTX 3090
- **Exact command to reproduce**: CUDA_VISIBLE_DEVICES=0,1 python ../TTS/TTS/bin/distribute.py --script train_vits_newone.py --restore_path /home/sk/.local/share/tts/tts_models--en--vctk--vits/model_file.pth.tar

**Additional context**
Training works fine if the dataset contains at least two voices.
Similar setup works in v.0.3.0.

**Comment by erogol** [comment]
it doesn't make sense to finetune multi-speaker VITS on a single speaker since you need to avoid the speaker embedding layer and then the model needs to learn to adapt to this change. Or you need some manual surgery to change the model architecture before you fine-tune the model. 

It is better to fine-tune the LJSpecch VITS model.

**Comment by skol101** [comment]
Ok, understood. But strange thing is when I fine-tuned to two voices, after about 50k steps synthesized voices started sound similar in prosody.
