### ISSUE TITLE
[Bug] tts_models/en/vctk/fast_pitch does not generate speech properly

### ISSUE THREAD

**Issue by wangtiance** [coqui-ai/TTS#981]
**Describe the bug**
I installed TTS 0.4.1 and ran 
tts --model_name tts_models/en/vctk/fast_pitch --text "hello world." --speaker_idx VCTK_p225
It uses vocoder_models/en/vctk/hifigan_v2 by default, but the wav file generated contains pure noise. I tried a bunch of different speaker_idx and the results are the same. I also tried other vocoders like vocoder_models/universal/libri-tts/fullband-melgan, and the output is barely intelligible.

Other models like tts_models/en/ljspeech/tacotron2-DDC worked fine for me, but I wanted to try multi speaker models.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.1
- **Python version**: 3.8.12
- **CUDA/cuDNN version**: 11.0
- **Exact command to reproduce**: tts --model_name tts_models/en/vctk/fast_pitch --text "hello world." --speaker_idx VCTK_p225

[tts_output.zip](https://github.com/coqui-ai/TTS/files/7622746/tts_output.zip)

**Comment by skol101** [comment]
Yep, that's a known issue.  https://github.com/coqui-ai/TTS/issues/907
