### ISSUE TITLE
[Bug] multi-gpu broken in dev?

### ISSUE THREAD

**Issue by mittimithai** [coqui-ai/TTS#993]
**Describe the bug**
Something is wrong with multi-gpu training in dev branch? Training on ljspeech with standard config. You can see both gpus are being use with nvidia-smu) multiple copies of lines  but number of GPUs being used reported as 1.

TTS$ git branch
* dev
  main

TTS$ CUDA_VISIBLE_DEVICES="0,1" python TTS/bin/distribute.py --config_path ../test_models/tts/ljspeech_baseline/config.json --script train_tts.py
['/home/users/myadav/venvs/sri_tts/ci-tts4/TTS/TTS/bin/train_tts.py', '--continue_path=', '--restore_path=', '--config_path=../test_models/tts/ljspeech_baseline/config.json', '--group_id=group_2021_12_02-114307', '--use_ddp=true', '--rank=0']
['/home/users/myadav/venvs/sri_tts/ci-tts4/TTS/TTS/bin/train_tts.py', '--continue_path=', '--restore_path=', '--config_path=../test_models/tts/ljspeech_baseline/config.json', '--group_id=group_2021_12_02-114307', '--use_ddp=true', '--rank=1']
 | > Found 12000 files in /nobackup/myadav1/TTS/datasets/LJSpeech-1.1
 | > Found 12000 files in /nobackup/myadav1/TTS/datasets/LJSpeech-1.1
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Using model: tacotron2
 > Using model: tacotron2
 > Using CUDA:  True
 > Number of GPUs:  1

 > Model has 28888978 parameters

**To Reproduce**
Should be reproducible with any training using dev branch.

**Expected behavior**

**Comment by mittimithai** [comment]
I suppose it might be working, but (I'm not sure when this was put in) it is difficult to verify multi-gpu training is working.  Right now, num_gpus is being printed from the subprocess (=1), the you see only the subprocess step count i.e. single gpu and multi-gpu look the same right now from the perspective of running the job.  I'm going through the code now and trying to understand how output is collated.

**Comment by mittimithai** [comment]
I think we don't want:
my_env["CUDA_VISIBLE_DEVICES"] = "{}".format(value)
in distribute.py? With that, num_gpus in trainer.py is always=1 and all the "if num_gpus>1" code never runs.

**Comment by Edresson** [comment]
Thanks, @mittimithai   Looks like it was an old bug. Currently, it is fixed in the current dev branch. So for now I will close this issue.
