### ISSUE TITLE
[Bug] Link to Universal WaveGrad model missing!

### ISSUE THREAD

**Issue by vatsalaggarwal** [coqui-ai/TTS#994]
Welcome to the 🐸TTS project! We are excited to see your interest, and appreciate your support!

This repository is governed by the Contributor Covenant Code of Conduct. For more details, see the [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md) file.

If you've found a bug, please provide the following information:

**Describe the bug**
https://github.com/coqui-ai/TTS/wiki/Experimental-Released-Models doesn't contain the link for the Universal WaveGrad model.

**To Reproduce**
N/A
**Expected behavior**
Link points to a trained model

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by erogol** [comment]
models are linked under .models.json now and you can use them by `tts` and `tts-server` commands.

**Comment by vatsalaggarwal** [comment]
Thank you!
